"""Architecture-owned Python reference models (RTL-independent golden).

Ownership: architecture (Xia), see docs/TEAM.md. Verification scoreboards
call these modules; they must not import cocotb, uvm, or anything under rtl/.

``model.regs`` is generated by the REGMAP YAML PR and is **not** authored
here. Do not add ``model/regs.py`` in this tree.

Section-by-section citations live in each module docstring (SPEC.md /
UB-PHY / UB-DL section numbers only).
"""

from model.config import PENDING, PendingParams
from model.ub_dll_bcrc import UbDllBcrc, UbDllBcrcCheck, UbDllBcrcConfig, pack_bcrc_word
from model.ub_pcs_lane_dist import UbPcsLaneDedist, UbPcsLaneDist, UbPcsLaneDistConfig
from model.ub_pcs_scrambler import (
    SymbolKind,
    UbPcsDescrambler,
    UbPcsScrambler,
    UbPcsScramblerConfig,
)

__all__ = [
    "PENDING",
    "PendingParams",
    "SymbolKind",
    "UbDllBcrc",
    "UbDllBcrcCheck",
    "UbDllBcrcConfig",
    "UbPcsDescrambler",
    "UbPcsLaneDedist",
    "UbPcsLaneDist",
    "UbPcsLaneDistConfig",
    "UbPcsScrambler",
    "UbPcsScramblerConfig",
    "pack_bcrc_word",
]
