"""Architecture-owned Python reference models (RTL-independent golden).

Ownership: architecture (Xia), see docs/TEAM.md. Scoreboards import from
here. Do not import cocotb, uvm, ``rtl/``, or ``pycircuit/``.

``model.regs`` is generated by the REGMAP YAML PR and is not authored here.
"""

from model.ub_cmn_mem_1r1w import (
    UbCmnMem1r1w,
    UbCmnMem1r1wSimpleRef,
    UbCmnMemAddrError,
    UbCmnMemUnwrittenError,
    clog2,
    variant_name,
)

__all__ = [
    "UbCmnMem1r1w",
    "UbCmnMem1r1wSimpleRef",
    "UbCmnMemAddrError",
    "UbCmnMemUnwrittenError",
    "clog2",
    "variant_name",
]
