"""UB M1 CSR constants. GENERATED — edit docs/regmap/regmap.yaml"""

from __future__ import annotations

WORD_BITS = 32
ADDR_BITS = 16
ALIGN_BYTES = 4
READ_LATENCY_CYCLES = 1
PORT_RST_PULSE_CYCLES = 16

ACCESS_RW = "RW"
ACCESS_RO = "RO"
ACCESS_WO = "WO"
ACCESS_W1C = "W1C"
ACCESS_MIX = "MIX"

WINDOWS = {
    'CTRL_STATUS': {'name': 'CTRL/STATUS', 'start': 0x0000, 'end': 0x00ff},
    'PARAM': {'name': 'PARAM', 'start': 0x0100, 'end': 0x01ff},
    'ERR': {'name': 'ERR', 'start': 0x0200, 'end': 0x02ff},
    'TEST': {'name': 'TEST', 'start': 0x0300, 'end': 0x03ff},
    'APPD_PORT': {'name': 'APPD_PORT', 'start': 0x1000, 'end': 0x1fff},
}

WIN_CTRL_STATUS_START = 0x0000
WIN_CTRL_STATUS_END = 0x00ff
WIN_PARAM_START = 0x0100
WIN_PARAM_END = 0x01ff
WIN_ERR_START = 0x0200
WIN_ERR_END = 0x02ff
WIN_TEST_START = 0x0300
WIN_TEST_END = 0x03ff
WIN_APPD_PORT_START = 0x1000
WIN_APPD_PORT_END = 0x1fff

CTRL = 0x0000
CTRL_OFFSET = 0x0000
CTRL_PORT_RST_LSB = 0
CTRL_PORT_RST_MSB = 0
CTRL_PORT_RST_WIDTH = 1
CTRL_PORT_RST_MASK = 0x00000001
CTRL_PORT_RST_SHIFT = 0
CTRL_PORT_RST_ACCESS = 'WO'
CTRL_PORT_RST_RESET = 0x0
CTRL_PORT_RST_SELF_CLEARING = True
CTRL_PORT_RST_PULSE_CYCLES = 16
CTRL_LMSM_START_LSB = 1
CTRL_LMSM_START_MSB = 1
CTRL_LMSM_START_WIDTH = 1
CTRL_LMSM_START_MASK = 0x00000002
CTRL_LMSM_START_SHIFT = 1
CTRL_LMSM_START_ACCESS = 'RW'
CTRL_LMSM_START_RESET = 0x0
CTRL_IRQ_EN_LSB = 2
CTRL_IRQ_EN_MSB = 2
CTRL_IRQ_EN_WIDTH = 1
CTRL_IRQ_EN_MASK = 0x00000004
CTRL_IRQ_EN_SHIFT = 2
CTRL_IRQ_EN_ACCESS = 'RW'
CTRL_IRQ_EN_RESET = 0x0
CTRL_RSVD_LSB = 3
CTRL_RSVD_MSB = 31
CTRL_RSVD_WIDTH = 29
CTRL_RSVD_MASK = 0xfffffff8
CTRL_RSVD_SHIFT = 3
CTRL_RSVD_ACCESS = 'RO'
CTRL_RSVD_RESET = 0x0

STATUS = 0x0004
STATUS_OFFSET = 0x0004
STATUS_LINK_UP_LSB = 0
STATUS_LINK_UP_MSB = 0
STATUS_LINK_UP_WIDTH = 1
STATUS_LINK_UP_MASK = 0x00000001
STATUS_LINK_UP_SHIFT = 0
STATUS_LINK_UP_ACCESS = 'RO'
STATUS_LINK_UP_RESET = 0x0
STATUS_LINK_READY_LSB = 1
STATUS_LINK_READY_MSB = 1
STATUS_LINK_READY_WIDTH = 1
STATUS_LINK_READY_MASK = 0x00000002
STATUS_LINK_READY_SHIFT = 1
STATUS_LINK_READY_ACCESS = 'RO'
STATUS_LINK_READY_RESET = 0x0
STATUS_DLL_STATUS_UP_LSB = 2
STATUS_DLL_STATUS_UP_MSB = 2
STATUS_DLL_STATUS_UP_WIDTH = 1
STATUS_DLL_STATUS_UP_MASK = 0x00000004
STATUS_DLL_STATUS_UP_SHIFT = 2
STATUS_DLL_STATUS_UP_ACCESS = 'RO'
STATUS_DLL_STATUS_UP_RESET = 0x0
STATUS_LMSM_ST_LSB = 3
STATUS_LMSM_ST_MSB = 7
STATUS_LMSM_ST_WIDTH = 5
STATUS_LMSM_ST_MASK = 0x000000f8
STATUS_LMSM_ST_SHIFT = 3
STATUS_LMSM_ST_ACCESS = 'RO'
STATUS_LMSM_ST_RESET = 0x0
STATUS_DLL_SM_ST_LSB = 8
STATUS_DLL_SM_ST_MSB = 9
STATUS_DLL_SM_ST_WIDTH = 2
STATUS_DLL_SM_ST_MASK = 0x00000300
STATUS_DLL_SM_ST_SHIFT = 8
STATUS_DLL_SM_ST_ACCESS = 'RO'
STATUS_DLL_SM_ST_RESET = 0x0
STATUS_RETRY_REQ_ST_LSB = 10
STATUS_RETRY_REQ_ST_MSB = 12
STATUS_RETRY_REQ_ST_WIDTH = 3
STATUS_RETRY_REQ_ST_MASK = 0x00001c00
STATUS_RETRY_REQ_ST_SHIFT = 10
STATUS_RETRY_REQ_ST_ACCESS = 'RO'
STATUS_RETRY_REQ_ST_RESET = 0x0
STATUS_RETRY_REQ_ST_NORMAL = 0
STATUS_RETRY_REQ_ST_REQ = 1
STATUS_RETRY_REQ_ST_WAIT = 2
STATUS_RETRY_REQ_ST_RETRAIN = 3
STATUS_RETRY_REQ_ST_ERROR = 4
STATUS_RETRY_REQ_ST_RSVD5 = 5
STATUS_RETRY_REQ_ST_RSVD6 = 6
STATUS_RETRY_REQ_ST_RSVD7 = 7
STATUS_RETRY_REQ_ST_RESERVED = (5, 6, 7,)
STATUS_RETRY_ACK_ST_LSB = 13
STATUS_RETRY_ACK_ST_MSB = 14
STATUS_RETRY_ACK_ST_WIDTH = 2
STATUS_RETRY_ACK_ST_MASK = 0x00006000
STATUS_RETRY_ACK_ST_SHIFT = 13
STATUS_RETRY_ACK_ST_ACCESS = 'RO'
STATUS_RETRY_ACK_ST_RESET = 0x0
STATUS_RETRY_ACK_ST_NORMAL = 0
STATUS_RETRY_ACK_ST_ACK = 1
STATUS_RETRY_ACK_ST_RSVD2 = 2
STATUS_RETRY_ACK_ST_RSVD3 = 3
STATUS_RETRY_ACK_ST_RESERVED = (2, 3,)
STATUS_RSVD_LSB = 15
STATUS_RSVD_MSB = 31
STATUS_RSVD_WIDTH = 17
STATUS_RSVD_MASK = 0xffff8000
STATUS_RSVD_SHIFT = 15
STATUS_RSVD_ACCESS = 'RO'
STATUS_RSVD_RESET = 0x0

IRQ_STATUS = 0x0008
IRQ_STATUS_OFFSET = 0x0008
IRQ_STATUS_FEC_UNCORR_LSB = 0
IRQ_STATUS_FEC_UNCORR_MSB = 0
IRQ_STATUS_FEC_UNCORR_WIDTH = 1
IRQ_STATUS_FEC_UNCORR_MASK = 0x00000001
IRQ_STATUS_FEC_UNCORR_SHIFT = 0
IRQ_STATUS_FEC_UNCORR_ACCESS = 'W1C'
IRQ_STATUS_FEC_UNCORR_RESET = 0x0
IRQ_STATUS_CRC_FAIL_LSB = 1
IRQ_STATUS_CRC_FAIL_MSB = 1
IRQ_STATUS_CRC_FAIL_WIDTH = 1
IRQ_STATUS_CRC_FAIL_MASK = 0x00000002
IRQ_STATUS_CRC_FAIL_SHIFT = 1
IRQ_STATUS_CRC_FAIL_ACCESS = 'W1C'
IRQ_STATUS_CRC_FAIL_RESET = 0x0
IRQ_STATUS_RETRY_ERR_LSB = 2
IRQ_STATUS_RETRY_ERR_MSB = 2
IRQ_STATUS_RETRY_ERR_WIDTH = 1
IRQ_STATUS_RETRY_ERR_MASK = 0x00000004
IRQ_STATUS_RETRY_ERR_SHIFT = 2
IRQ_STATUS_RETRY_ERR_ACCESS = 'W1C'
IRQ_STATUS_RETRY_ERR_RESET = 0x0
IRQ_STATUS_CRD_PROTO_LSB = 3
IRQ_STATUS_CRD_PROTO_MSB = 3
IRQ_STATUS_CRD_PROTO_WIDTH = 1
IRQ_STATUS_CRD_PROTO_MASK = 0x00000008
IRQ_STATUS_CRD_PROTO_SHIFT = 3
IRQ_STATUS_CRD_PROTO_ACCESS = 'W1C'
IRQ_STATUS_CRD_PROTO_RESET = 0x0
IRQ_STATUS_TRAIN_FAIL_LSB = 4
IRQ_STATUS_TRAIN_FAIL_MSB = 4
IRQ_STATUS_TRAIN_FAIL_WIDTH = 1
IRQ_STATUS_TRAIN_FAIL_MASK = 0x00000010
IRQ_STATUS_TRAIN_FAIL_SHIFT = 4
IRQ_STATUS_TRAIN_FAIL_ACCESS = 'W1C'
IRQ_STATUS_TRAIN_FAIL_RESET = 0x0
IRQ_STATUS_BAD_VL_LSB = 5
IRQ_STATUS_BAD_VL_MSB = 5
IRQ_STATUS_BAD_VL_WIDTH = 1
IRQ_STATUS_BAD_VL_MASK = 0x00000020
IRQ_STATUS_BAD_VL_SHIFT = 5
IRQ_STATUS_BAD_VL_ACCESS = 'W1C'
IRQ_STATUS_BAD_VL_RESET = 0x0
IRQ_STATUS_CRD_UF_LSB = 6
IRQ_STATUS_CRD_UF_MSB = 6
IRQ_STATUS_CRD_UF_WIDTH = 1
IRQ_STATUS_CRD_UF_MASK = 0x00000040
IRQ_STATUS_CRD_UF_SHIFT = 6
IRQ_STATUS_CRD_UF_ACCESS = 'W1C'
IRQ_STATUS_CRD_UF_RESET = 0x0
IRQ_STATUS_RSVD_LSB = 7
IRQ_STATUS_RSVD_MSB = 31
IRQ_STATUS_RSVD_WIDTH = 25
IRQ_STATUS_RSVD_MASK = 0xffffff80
IRQ_STATUS_RSVD_SHIFT = 7
IRQ_STATUS_RSVD_ACCESS = 'RO'
IRQ_STATUS_RSVD_RESET = 0x0

IRQ_MASK = 0x000c
IRQ_MASK_OFFSET = 0x000c
IRQ_MASK_MASK_LSB = 0
IRQ_MASK_MASK_MSB = 6
IRQ_MASK_MASK_WIDTH = 7
IRQ_MASK_MASK_MASK = 0x0000007f
IRQ_MASK_MASK_SHIFT = 0
IRQ_MASK_MASK_ACCESS = 'RW'
IRQ_MASK_MASK_RESET = 0x7f
IRQ_MASK_RSVD_LSB = 7
IRQ_MASK_RSVD_MSB = 31
IRQ_MASK_RSVD_WIDTH = 25
IRQ_MASK_RSVD_MASK = 0xffffff80
IRQ_MASK_RSVD_SHIFT = 7
IRQ_MASK_RSVD_ACCESS = 'RO'
IRQ_MASK_RSVD_RESET = 0x0

PORT_CNA = 0x0010
PORT_CNA_OFFSET = 0x0010
PORT_CNA_CNA_LSB = 0
PORT_CNA_CNA_MSB = 31
PORT_CNA_CNA_WIDTH = 32
PORT_CNA_CNA_MASK = 0xffffffff
PORT_CNA_CNA_SHIFT = 0
PORT_CNA_CNA_ACCESS = 'RW'
PORT_CNA_CNA_RESET = 0x0

PARAM_PHY = 0x0100
PARAM_PHY_OFFSET = 0x0100
PARAM_PHY_PHY_MODE_LSB = 0
PARAM_PHY_PHY_MODE_MSB = 1
PARAM_PHY_PHY_MODE_WIDTH = 2
PARAM_PHY_PHY_MODE_MASK = 0x00000003
PARAM_PHY_PHY_MODE_SHIFT = 0
PARAM_PHY_PHY_MODE_ACCESS = 'RO'
PARAM_PHY_PHY_MODE_RESET = 0x2
PARAM_PHY_PHY_MODE_MODE_1 = 1
PARAM_PHY_PHY_MODE_MODE_2 = 2
PARAM_PHY_DATA_RATE_LSB = 2
PARAM_PHY_DATA_RATE_MSB = 5
PARAM_PHY_DATA_RATE_WIDTH = 4
PARAM_PHY_DATA_RATE_MASK = 0x0000003c
PARAM_PHY_DATA_RATE_SHIFT = 2
PARAM_PHY_DATA_RATE_ACCESS = 'RO'
PARAM_PHY_DATA_RATE_RESET = 0x0
PARAM_PHY_NUM_LANES_TX_LSB = 6
PARAM_PHY_NUM_LANES_TX_MSB = 9
PARAM_PHY_NUM_LANES_TX_WIDTH = 4
PARAM_PHY_NUM_LANES_TX_MASK = 0x000003c0
PARAM_PHY_NUM_LANES_TX_SHIFT = 6
PARAM_PHY_NUM_LANES_TX_ACCESS = 'RO'
PARAM_PHY_NUM_LANES_TX_RESET = 0x1
PARAM_PHY_NUM_LANES_TX_LEGAL = (1, 2, 4, 8,)
PARAM_PHY_NUM_LANES_TX_RESERVED = (0, 3, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15,)
PARAM_PHY_NUM_LANES_RX_LSB = 10
PARAM_PHY_NUM_LANES_RX_MSB = 13
PARAM_PHY_NUM_LANES_RX_WIDTH = 4
PARAM_PHY_NUM_LANES_RX_MASK = 0x00003c00
PARAM_PHY_NUM_LANES_RX_SHIFT = 10
PARAM_PHY_NUM_LANES_RX_ACCESS = 'RO'
PARAM_PHY_NUM_LANES_RX_RESET = 0x1
PARAM_PHY_NUM_LANES_RX_LEGAL = (1, 2, 4, 8,)
PARAM_PHY_NUM_LANES_RX_RESERVED = (0, 3, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15,)
PARAM_PHY_PMA_W_LSB = 14
PARAM_PHY_PMA_W_MSB = 21
PARAM_PHY_PMA_W_WIDTH = 8
PARAM_PHY_PMA_W_MASK = 0x003fc000
PARAM_PHY_PMA_W_SHIFT = 14
PARAM_PHY_PMA_W_ACCESS = 'RO'
PARAM_PHY_PMA_W_RESET = 0x20
PARAM_PHY_ALLOW_ASYM_LSB = 22
PARAM_PHY_ALLOW_ASYM_MSB = 22
PARAM_PHY_ALLOW_ASYM_WIDTH = 1
PARAM_PHY_ALLOW_ASYM_MASK = 0x00400000
PARAM_PHY_ALLOW_ASYM_SHIFT = 22
PARAM_PHY_ALLOW_ASYM_ACCESS = 'RO'
PARAM_PHY_ALLOW_ASYM_RESET = 0x0
PARAM_PHY_RSVD_LSB = 23
PARAM_PHY_RSVD_MSB = 31
PARAM_PHY_RSVD_WIDTH = 9
PARAM_PHY_RSVD_MASK = 0xff800000
PARAM_PHY_RSVD_SHIFT = 23
PARAM_PHY_RSVD_ACCESS = 'RO'
PARAM_PHY_RSVD_RESET = 0x0

PARAM_FEC = 0x0104
PARAM_FEC_OFFSET = 0x0104
PARAM_FEC_FEC_MODE_LSB = 0
PARAM_FEC_FEC_MODE_MSB = 2
PARAM_FEC_FEC_MODE_WIDTH = 3
PARAM_FEC_FEC_MODE_MASK = 0x00000007
PARAM_FEC_FEC_MODE_SHIFT = 0
PARAM_FEC_FEC_MODE_ACCESS = 'RO'
PARAM_FEC_FEC_MODE_RESET = 0x2
PARAM_FEC_CODEC_NUM_LSB = 3
PARAM_FEC_CODEC_NUM_MSB = 4
PARAM_FEC_CODEC_NUM_WIDTH = 2
PARAM_FEC_CODEC_NUM_MASK = 0x00000018
PARAM_FEC_CODEC_NUM_SHIFT = 3
PARAM_FEC_CODEC_NUM_ACCESS = 'RO'
PARAM_FEC_CODEC_NUM_RESET = 0x1
PARAM_FEC_RSVD_LSB = 5
PARAM_FEC_RSVD_MSB = 31
PARAM_FEC_RSVD_WIDTH = 27
PARAM_FEC_RSVD_MASK = 0xffffffe0
PARAM_FEC_RSVD_SHIFT = 5
PARAM_FEC_RSVD_ACCESS = 'RO'
PARAM_FEC_RSVD_RESET = 0x0

PARAM_DLL = 0x0108
PARAM_DLL_OFFSET = 0x0108
PARAM_DLL_NUM_VL_LSB = 0
PARAM_DLL_NUM_VL_MSB = 4
PARAM_DLL_NUM_VL_WIDTH = 5
PARAM_DLL_NUM_VL_MASK = 0x0000001f
PARAM_DLL_NUM_VL_SHIFT = 0
PARAM_DLL_NUM_VL_ACCESS = 'RO'
PARAM_DLL_NUM_VL_RESET = 0x2
PARAM_DLL_FLOW_CTRL_SIZE_LSB = 5
PARAM_DLL_FLOW_CTRL_SIZE_MSB = 12
PARAM_DLL_FLOW_CTRL_SIZE_WIDTH = 8
PARAM_DLL_FLOW_CTRL_SIZE_MASK = 0x00001fe0
PARAM_DLL_FLOW_CTRL_SIZE_SHIFT = 5
PARAM_DLL_FLOW_CTRL_SIZE_ACCESS = 'RO'
PARAM_DLL_FLOW_CTRL_SIZE_RESET = 0x1
PARAM_DLL_ACK_GRAIN_LSB = 13
PARAM_DLL_ACK_GRAIN_MSB = 20
PARAM_DLL_ACK_GRAIN_WIDTH = 8
PARAM_DLL_ACK_GRAIN_MASK = 0x001fe000
PARAM_DLL_ACK_GRAIN_SHIFT = 13
PARAM_DLL_ACK_GRAIN_ACCESS = 'RO'
PARAM_DLL_ACK_GRAIN_RESET = 0x20
PARAM_DLL_CREDIT_EXCL_LSB = 21
PARAM_DLL_CREDIT_EXCL_MSB = 21
PARAM_DLL_CREDIT_EXCL_WIDTH = 1
PARAM_DLL_CREDIT_EXCL_MASK = 0x00200000
PARAM_DLL_CREDIT_EXCL_SHIFT = 21
PARAM_DLL_CREDIT_EXCL_ACCESS = 'RO'
PARAM_DLL_CREDIT_EXCL_RESET = 0x1
PARAM_DLL_RSVD_LSB = 22
PARAM_DLL_RSVD_MSB = 31
PARAM_DLL_RSVD_WIDTH = 10
PARAM_DLL_RSVD_MASK = 0xffc00000
PARAM_DLL_RSVD_SHIFT = 22
PARAM_DLL_RSVD_ACCESS = 'RO'
PARAM_DLL_RSVD_RESET = 0x0

PARAM_RETRY = 0x010c
PARAM_RETRY_OFFSET = 0x010c
PARAM_RETRY_RETRY_BUF_DEPTH_LSB = 0
PARAM_RETRY_RETRY_BUF_DEPTH_MSB = 15
PARAM_RETRY_RETRY_BUF_DEPTH_WIDTH = 16
PARAM_RETRY_RETRY_BUF_DEPTH_MASK = 0x0000ffff
PARAM_RETRY_RETRY_BUF_DEPTH_SHIFT = 0
PARAM_RETRY_RETRY_BUF_DEPTH_ACCESS = 'RO'
PARAM_RETRY_RETRY_BUF_DEPTH_RESET = 0x100
PARAM_RETRY_NUM_RETRY_TH_LSB = 16
PARAM_RETRY_NUM_RETRY_TH_MSB = 23
PARAM_RETRY_NUM_RETRY_TH_WIDTH = 8
PARAM_RETRY_NUM_RETRY_TH_MASK = 0x00ff0000
PARAM_RETRY_NUM_RETRY_TH_SHIFT = 16
PARAM_RETRY_NUM_RETRY_TH_ACCESS = 'RO'
PARAM_RETRY_NUM_RETRY_TH_RESET = 0xf
PARAM_RETRY_NUM_PHY_REINIT_TH_LSB = 24
PARAM_RETRY_NUM_PHY_REINIT_TH_MSB = 31
PARAM_RETRY_NUM_PHY_REINIT_TH_WIDTH = 8
PARAM_RETRY_NUM_PHY_REINIT_TH_MASK = 0xff000000
PARAM_RETRY_NUM_PHY_REINIT_TH_SHIFT = 24
PARAM_RETRY_NUM_PHY_REINIT_TH_ACCESS = 'RO'
PARAM_RETRY_NUM_PHY_REINIT_TH_RESET = 0x4

PARAM_CRD = 0x0110
PARAM_CRD_OFFSET = 0x0110
PARAM_CRD_INIT_CRD_LSB = 0
PARAM_CRD_INIT_CRD_MSB = 15
PARAM_CRD_INIT_CRD_WIDTH = 16
PARAM_CRD_INIT_CRD_MASK = 0x0000ffff
PARAM_CRD_INIT_CRD_SHIFT = 0
PARAM_CRD_INIT_CRD_ACCESS = 'RO'
PARAM_CRD_INIT_CRD_RESET = 0x280
PARAM_CRD_CRD_BP_TH_LSB = 16
PARAM_CRD_CRD_BP_TH_MSB = 31
PARAM_CRD_CRD_BP_TH_WIDTH = 16
PARAM_CRD_CRD_BP_TH_MASK = 0xffff0000
PARAM_CRD_CRD_BP_TH_SHIFT = 16
PARAM_CRD_CRD_BP_TH_ACCESS = 'RO'
PARAM_CRD_CRD_BP_TH_RESET = 0x400

PARAM_INIT_FEATURE = 0x0114
PARAM_INIT_FEATURE_OFFSET = 0x0114
PARAM_INIT_FEATURE_FEATURE_ID_LSB = 0
PARAM_INIT_FEATURE_FEATURE_ID_MSB = 15
PARAM_INIT_FEATURE_FEATURE_ID_WIDTH = 16
PARAM_INIT_FEATURE_FEATURE_ID_MASK = 0x0000ffff
PARAM_INIT_FEATURE_FEATURE_ID_SHIFT = 0
PARAM_INIT_FEATURE_FEATURE_ID_ACCESS = 'RO'
PARAM_INIT_FEATURE_FEATURE_ID_RESET = 0x1
PARAM_INIT_FEATURE_RXBUF_VL_SHARE_LSB = 16
PARAM_INIT_FEATURE_RXBUF_VL_SHARE_MSB = 16
PARAM_INIT_FEATURE_RXBUF_VL_SHARE_WIDTH = 1
PARAM_INIT_FEATURE_RXBUF_VL_SHARE_MASK = 0x00010000
PARAM_INIT_FEATURE_RXBUF_VL_SHARE_SHIFT = 16
PARAM_INIT_FEATURE_RXBUF_VL_SHARE_ACCESS = 'RO'
PARAM_INIT_FEATURE_RXBUF_VL_SHARE_RESET = 0x0
PARAM_INIT_FEATURE_VL_ENABLE_LSB = 17
PARAM_INIT_FEATURE_VL_ENABLE_MSB = 31
PARAM_INIT_FEATURE_VL_ENABLE_WIDTH = 15
PARAM_INIT_FEATURE_VL_ENABLE_MASK = 0xfffe0000
PARAM_INIT_FEATURE_VL_ENABLE_SHIFT = 17
PARAM_INIT_FEATURE_VL_ENABLE_ACCESS = 'RO'
PARAM_INIT_FEATURE_VL_ENABLE_RESET = 0x3

PARAM_INIT_VL = 0x0118
PARAM_INIT_VL_OFFSET = 0x0118
PARAM_INIT_VL_VL_ENABLE_LSB = 0
PARAM_INIT_VL_VL_ENABLE_MSB = 15
PARAM_INIT_VL_VL_ENABLE_WIDTH = 16
PARAM_INIT_VL_VL_ENABLE_MASK = 0x0000ffff
PARAM_INIT_VL_VL_ENABLE_SHIFT = 0
PARAM_INIT_VL_VL_ENABLE_ACCESS = 'RO'
PARAM_INIT_VL_VL_ENABLE_RESET = 0x3
PARAM_INIT_VL_RSVD_LSB = 16
PARAM_INIT_VL_RSVD_MSB = 31
PARAM_INIT_VL_RSVD_WIDTH = 16
PARAM_INIT_VL_RSVD_MASK = 0xffff0000
PARAM_INIT_VL_RSVD_SHIFT = 16
PARAM_INIT_VL_RSVD_ACCESS = 'RO'
PARAM_INIT_VL_RSVD_RESET = 0x0

CNT_FEC_UNCORR = 0x0200
CNT_FEC_UNCORR_OFFSET = 0x0200
CNT_FEC_UNCORR_COUNT_LSB = 0
CNT_FEC_UNCORR_COUNT_MSB = 31
CNT_FEC_UNCORR_COUNT_WIDTH = 32
CNT_FEC_UNCORR_COUNT_MASK = 0xffffffff
CNT_FEC_UNCORR_COUNT_SHIFT = 0
CNT_FEC_UNCORR_COUNT_ACCESS = 'RO'
CNT_FEC_UNCORR_COUNT_RESET = 0x0
CNT_FEC_UNCORR_COUNT_SATURATING = True

CNT_CRC_FAIL = 0x0204
CNT_CRC_FAIL_OFFSET = 0x0204
CNT_CRC_FAIL_COUNT_LSB = 0
CNT_CRC_FAIL_COUNT_MSB = 31
CNT_CRC_FAIL_COUNT_WIDTH = 32
CNT_CRC_FAIL_COUNT_MASK = 0xffffffff
CNT_CRC_FAIL_COUNT_SHIFT = 0
CNT_CRC_FAIL_COUNT_ACCESS = 'RO'
CNT_CRC_FAIL_COUNT_RESET = 0x0
CNT_CRC_FAIL_COUNT_SATURATING = True

CNT_RETRY_REQ = 0x0208
CNT_RETRY_REQ_OFFSET = 0x0208
CNT_RETRY_REQ_COUNT_LSB = 0
CNT_RETRY_REQ_COUNT_MSB = 31
CNT_RETRY_REQ_COUNT_WIDTH = 32
CNT_RETRY_REQ_COUNT_MASK = 0xffffffff
CNT_RETRY_REQ_COUNT_SHIFT = 0
CNT_RETRY_REQ_COUNT_ACCESS = 'RO'
CNT_RETRY_REQ_COUNT_RESET = 0x0
CNT_RETRY_REQ_COUNT_SATURATING = True

CNT_RETRY_TO = 0x020c
CNT_RETRY_TO_OFFSET = 0x020c
CNT_RETRY_TO_COUNT_LSB = 0
CNT_RETRY_TO_COUNT_MSB = 31
CNT_RETRY_TO_COUNT_WIDTH = 32
CNT_RETRY_TO_COUNT_MASK = 0xffffffff
CNT_RETRY_TO_COUNT_SHIFT = 0
CNT_RETRY_TO_COUNT_ACCESS = 'RO'
CNT_RETRY_TO_COUNT_RESET = 0x0
CNT_RETRY_TO_COUNT_SATURATING = True

CNT_CRD_OF = 0x0210
CNT_CRD_OF_OFFSET = 0x0210
CNT_CRD_OF_COUNT_LSB = 0
CNT_CRD_OF_COUNT_MSB = 31
CNT_CRD_OF_COUNT_WIDTH = 32
CNT_CRD_OF_COUNT_MASK = 0xffffffff
CNT_CRD_OF_COUNT_SHIFT = 0
CNT_CRD_OF_COUNT_ACCESS = 'RO'
CNT_CRD_OF_COUNT_RESET = 0x0
CNT_CRD_OF_COUNT_SATURATING = True

CNT_CRD_TO = 0x0214
CNT_CRD_TO_OFFSET = 0x0214
CNT_CRD_TO_COUNT_LSB = 0
CNT_CRD_TO_COUNT_MSB = 31
CNT_CRD_TO_COUNT_WIDTH = 32
CNT_CRD_TO_COUNT_MASK = 0xffffffff
CNT_CRD_TO_COUNT_SHIFT = 0
CNT_CRD_TO_COUNT_ACCESS = 'RO'
CNT_CRD_TO_COUNT_RESET = 0x0
CNT_CRD_TO_COUNT_SATURATING = True

CNT_TRAIN_TO = 0x0218
CNT_TRAIN_TO_OFFSET = 0x0218
CNT_TRAIN_TO_COUNT_LSB = 0
CNT_TRAIN_TO_COUNT_MSB = 31
CNT_TRAIN_TO_COUNT_WIDTH = 32
CNT_TRAIN_TO_COUNT_MASK = 0xffffffff
CNT_TRAIN_TO_COUNT_SHIFT = 0
CNT_TRAIN_TO_COUNT_ACCESS = 'RO'
CNT_TRAIN_TO_COUNT_RESET = 0x0
CNT_TRAIN_TO_COUNT_SATURATING = True

CNT_BAD_VL = 0x021c
CNT_BAD_VL_OFFSET = 0x021c
CNT_BAD_VL_COUNT_LSB = 0
CNT_BAD_VL_COUNT_MSB = 31
CNT_BAD_VL_COUNT_WIDTH = 32
CNT_BAD_VL_COUNT_MASK = 0xffffffff
CNT_BAD_VL_COUNT_SHIFT = 0
CNT_BAD_VL_COUNT_ACCESS = 'RO'
CNT_BAD_VL_COUNT_RESET = 0x0
CNT_BAD_VL_COUNT_SATURATING = True

CNT_CRD_UF = 0x0220
CNT_CRD_UF_OFFSET = 0x0220
CNT_CRD_UF_COUNT_LSB = 0
CNT_CRD_UF_COUNT_MSB = 31
CNT_CRD_UF_COUNT_WIDTH = 32
CNT_CRD_UF_COUNT_MASK = 0xffffffff
CNT_CRD_UF_COUNT_SHIFT = 0
CNT_CRD_UF_COUNT_ACCESS = 'RO'
CNT_CRD_UF_COUNT_RESET = 0x0
CNT_CRD_UF_COUNT_SATURATING = True

CNT_CLR = 0x0224
CNT_CLR_OFFSET = 0x0224
CNT_CLR_FEC_UNCORR_LSB = 0
CNT_CLR_FEC_UNCORR_MSB = 0
CNT_CLR_FEC_UNCORR_WIDTH = 1
CNT_CLR_FEC_UNCORR_MASK = 0x00000001
CNT_CLR_FEC_UNCORR_SHIFT = 0
CNT_CLR_FEC_UNCORR_ACCESS = 'WO'
CNT_CLR_FEC_UNCORR_RESET = 0x0
CNT_CLR_FEC_UNCORR_SELF_CLEARING = True
CNT_CLR_CRC_FAIL_LSB = 1
CNT_CLR_CRC_FAIL_MSB = 1
CNT_CLR_CRC_FAIL_WIDTH = 1
CNT_CLR_CRC_FAIL_MASK = 0x00000002
CNT_CLR_CRC_FAIL_SHIFT = 1
CNT_CLR_CRC_FAIL_ACCESS = 'WO'
CNT_CLR_CRC_FAIL_RESET = 0x0
CNT_CLR_CRC_FAIL_SELF_CLEARING = True
CNT_CLR_RETRY_REQ_LSB = 2
CNT_CLR_RETRY_REQ_MSB = 2
CNT_CLR_RETRY_REQ_WIDTH = 1
CNT_CLR_RETRY_REQ_MASK = 0x00000004
CNT_CLR_RETRY_REQ_SHIFT = 2
CNT_CLR_RETRY_REQ_ACCESS = 'WO'
CNT_CLR_RETRY_REQ_RESET = 0x0
CNT_CLR_RETRY_REQ_SELF_CLEARING = True
CNT_CLR_RETRY_TO_LSB = 3
CNT_CLR_RETRY_TO_MSB = 3
CNT_CLR_RETRY_TO_WIDTH = 1
CNT_CLR_RETRY_TO_MASK = 0x00000008
CNT_CLR_RETRY_TO_SHIFT = 3
CNT_CLR_RETRY_TO_ACCESS = 'WO'
CNT_CLR_RETRY_TO_RESET = 0x0
CNT_CLR_RETRY_TO_SELF_CLEARING = True
CNT_CLR_CRD_OF_LSB = 4
CNT_CLR_CRD_OF_MSB = 4
CNT_CLR_CRD_OF_WIDTH = 1
CNT_CLR_CRD_OF_MASK = 0x00000010
CNT_CLR_CRD_OF_SHIFT = 4
CNT_CLR_CRD_OF_ACCESS = 'WO'
CNT_CLR_CRD_OF_RESET = 0x0
CNT_CLR_CRD_OF_SELF_CLEARING = True
CNT_CLR_CRD_TO_LSB = 5
CNT_CLR_CRD_TO_MSB = 5
CNT_CLR_CRD_TO_WIDTH = 1
CNT_CLR_CRD_TO_MASK = 0x00000020
CNT_CLR_CRD_TO_SHIFT = 5
CNT_CLR_CRD_TO_ACCESS = 'WO'
CNT_CLR_CRD_TO_RESET = 0x0
CNT_CLR_CRD_TO_SELF_CLEARING = True
CNT_CLR_TRAIN_TO_LSB = 6
CNT_CLR_TRAIN_TO_MSB = 6
CNT_CLR_TRAIN_TO_WIDTH = 1
CNT_CLR_TRAIN_TO_MASK = 0x00000040
CNT_CLR_TRAIN_TO_SHIFT = 6
CNT_CLR_TRAIN_TO_ACCESS = 'WO'
CNT_CLR_TRAIN_TO_RESET = 0x0
CNT_CLR_TRAIN_TO_SELF_CLEARING = True
CNT_CLR_BAD_VL_LSB = 7
CNT_CLR_BAD_VL_MSB = 7
CNT_CLR_BAD_VL_WIDTH = 1
CNT_CLR_BAD_VL_MASK = 0x00000080
CNT_CLR_BAD_VL_SHIFT = 7
CNT_CLR_BAD_VL_ACCESS = 'WO'
CNT_CLR_BAD_VL_RESET = 0x0
CNT_CLR_BAD_VL_SELF_CLEARING = True
CNT_CLR_CRD_UF_LSB = 8
CNT_CLR_CRD_UF_MSB = 8
CNT_CLR_CRD_UF_WIDTH = 1
CNT_CLR_CRD_UF_MASK = 0x00000100
CNT_CLR_CRD_UF_SHIFT = 8
CNT_CLR_CRD_UF_ACCESS = 'WO'
CNT_CLR_CRD_UF_RESET = 0x0
CNT_CLR_CRD_UF_SELF_CLEARING = True
CNT_CLR_RSVD_LSB = 9
CNT_CLR_RSVD_MSB = 31
CNT_CLR_RSVD_WIDTH = 23
CNT_CLR_RSVD_MASK = 0xfffffe00
CNT_CLR_RSVD_SHIFT = 9
CNT_CLR_RSVD_ACCESS = 'RO'
CNT_CLR_RSVD_RESET = 0x0

LMSM_TMR_SCALE = 0x0300
LMSM_TMR_SCALE_OFFSET = 0x0300
LMSM_TMR_SCALE_SCALE_LSB = 0
LMSM_TMR_SCALE_SCALE_MSB = 7
LMSM_TMR_SCALE_SCALE_WIDTH = 8
LMSM_TMR_SCALE_SCALE_MASK = 0x000000ff
LMSM_TMR_SCALE_SCALE_SHIFT = 0
LMSM_TMR_SCALE_SCALE_ACCESS = 'RW'
LMSM_TMR_SCALE_SCALE_RESET = 0x0
LMSM_TMR_SCALE_RSVD_LSB = 8
LMSM_TMR_SCALE_RSVD_MSB = 31
LMSM_TMR_SCALE_RSVD_WIDTH = 24
LMSM_TMR_SCALE_RSVD_MASK = 0xffffff00
LMSM_TMR_SCALE_RSVD_SHIFT = 8
LMSM_TMR_SCALE_RSVD_ACCESS = 'RO'
LMSM_TMR_SCALE_RSVD_RESET = 0x0

CRD_TO_DIS = 0x0304
CRD_TO_DIS_OFFSET = 0x0304
CRD_TO_DIS_DIS_LSB = 0
CRD_TO_DIS_DIS_MSB = 0
CRD_TO_DIS_DIS_WIDTH = 1
CRD_TO_DIS_DIS_MASK = 0x00000001
CRD_TO_DIS_DIS_SHIFT = 0
CRD_TO_DIS_DIS_ACCESS = 'RW'
CRD_TO_DIS_DIS_RESET = 0x0
CRD_TO_DIS_RSVD_LSB = 1
CRD_TO_DIS_RSVD_MSB = 31
CRD_TO_DIS_RSVD_WIDTH = 31
CRD_TO_DIS_RSVD_MASK = 0xfffffffe
CRD_TO_DIS_RSVD_SHIFT = 1
CRD_TO_DIS_RSVD_ACCESS = 'RO'
CRD_TO_DIS_RSVD_RESET = 0x0

PCS_TX_TEST = 0x0308
PCS_TX_TEST_OFFSET = 0x0308
PCS_TX_TEST_AM_IVL_SCALE_LSB = 0
PCS_TX_TEST_AM_IVL_SCALE_MSB = 7
PCS_TX_TEST_AM_IVL_SCALE_WIDTH = 8
PCS_TX_TEST_AM_IVL_SCALE_MASK = 0x000000ff
PCS_TX_TEST_AM_IVL_SCALE_SHIFT = 0
PCS_TX_TEST_AM_IVL_SCALE_ACCESS = 'RW'
PCS_TX_TEST_AM_IVL_SCALE_RESET = 0x0
PCS_TX_TEST_RSVD_LSB = 8
PCS_TX_TEST_RSVD_MSB = 31
PCS_TX_TEST_RSVD_WIDTH = 24
PCS_TX_TEST_RSVD_MASK = 0xffffff00
PCS_TX_TEST_RSVD_SHIFT = 8
PCS_TX_TEST_RSVD_ACCESS = 'RO'
PCS_TX_TEST_RSVD_RESET = 0x0

APPD_PORT_BASIC = 0x1000
APPD_PORT_BASIC_OFFSET = 0x1000
APPD_PORT_BASIC_WINDOW_LSB = 0
APPD_PORT_BASIC_WINDOW_MSB = 31
APPD_PORT_BASIC_WINDOW_WIDTH = 32
APPD_PORT_BASIC_WINDOW_MASK = 0xffffffff
APPD_PORT_BASIC_WINDOW_SHIFT = 0
APPD_PORT_BASIC_WINDOW_ACCESS = 'MIX'
APPD_PORT_BASIC_WINDOW_RESET = None  # NA; see App. D.5、D.5.1–D.5.6

APPD_LINK_CAP = 0x1100
APPD_LINK_CAP_OFFSET = 0x1100
APPD_LINK_CAP_WINDOW_LSB = 0
APPD_LINK_CAP_WINDOW_MSB = 31
APPD_LINK_CAP_WINDOW_WIDTH = 32
APPD_LINK_CAP_WINDOW_MASK = 0xffffffff
APPD_LINK_CAP_WINDOW_SHIFT = 0
APPD_LINK_CAP_WINDOW_ACCESS = 'MIX'
APPD_LINK_CAP_WINDOW_RESET = None  # NA; see App. D.6.2、D.6.2.1–D.6.2.3

APPD_LINK_LOG = 0x1200
APPD_LINK_LOG_OFFSET = 0x1200
APPD_LINK_LOG_WINDOW_LSB = 0
APPD_LINK_LOG_WINDOW_MSB = 31
APPD_LINK_LOG_WINDOW_WIDTH = 32
APPD_LINK_LOG_WINDOW_MASK = 0xffffffff
APPD_LINK_LOG_WINDOW_SHIFT = 0
APPD_LINK_LOG_WINDOW_ACCESS = 'MIX'
APPD_LINK_LOG_WINDOW_RESET = None  # NA; see App. D.6.3

APPD_LMSM_ST = 0x1e00
APPD_LMSM_ST_OFFSET = 0x1e00
APPD_LMSM_ST_WINDOW_LSB = 0
APPD_LMSM_ST_WINDOW_MSB = 31
APPD_LMSM_ST_WINDOW_WIDTH = 32
APPD_LMSM_ST_WINDOW_MASK = 0xffffffff
APPD_LMSM_ST_WINDOW_SHIFT = 0
APPD_LMSM_ST_WINDOW_ACCESS = 'MIX'
APPD_LMSM_ST_WINDOW_RESET = None  # NA; see App. D.6.21

APPD_PORT_ERR = 0x1f00
APPD_PORT_ERR_OFFSET = 0x1f00
APPD_PORT_ERR_WINDOW_LSB = 0
APPD_PORT_ERR_WINDOW_MSB = 31
APPD_PORT_ERR_WINDOW_WIDTH = 32
APPD_PORT_ERR_WINDOW_MASK = 0xffffffff
APPD_PORT_ERR_WINDOW_SHIFT = 0
APPD_PORT_ERR_WINDOW_ACCESS = 'MIX'
APPD_PORT_ERR_WINDOW_RESET = None  # NA; see App. D.6.22

REGISTERS = (
    {'name': 'CTRL', 'offset': 0x0000, 'window': 'CTRL_STATUS', 'kind': 'register'},
    {'name': 'STATUS', 'offset': 0x0004, 'window': 'CTRL_STATUS', 'kind': 'register'},
    {'name': 'IRQ_STATUS', 'offset': 0x0008, 'window': 'CTRL_STATUS', 'kind': 'register'},
    {'name': 'IRQ_MASK', 'offset': 0x000c, 'window': 'CTRL_STATUS', 'kind': 'register'},
    {'name': 'PORT_CNA', 'offset': 0x0010, 'window': 'CTRL_STATUS', 'kind': 'register'},
    {'name': 'PARAM_PHY', 'offset': 0x0100, 'window': 'PARAM', 'kind': 'register'},
    {'name': 'PARAM_FEC', 'offset': 0x0104, 'window': 'PARAM', 'kind': 'register'},
    {'name': 'PARAM_DLL', 'offset': 0x0108, 'window': 'PARAM', 'kind': 'register'},
    {'name': 'PARAM_RETRY', 'offset': 0x010c, 'window': 'PARAM', 'kind': 'register'},
    {'name': 'PARAM_CRD', 'offset': 0x0110, 'window': 'PARAM', 'kind': 'register'},
    {'name': 'PARAM_INIT_FEATURE', 'offset': 0x0114, 'window': 'PARAM', 'kind': 'register'},
    {'name': 'PARAM_INIT_VL', 'offset': 0x0118, 'window': 'PARAM', 'kind': 'register'},
    {'name': 'CNT_FEC_UNCORR', 'offset': 0x0200, 'window': 'ERR', 'kind': 'register'},
    {'name': 'CNT_CRC_FAIL', 'offset': 0x0204, 'window': 'ERR', 'kind': 'register'},
    {'name': 'CNT_RETRY_REQ', 'offset': 0x0208, 'window': 'ERR', 'kind': 'register'},
    {'name': 'CNT_RETRY_TO', 'offset': 0x020c, 'window': 'ERR', 'kind': 'register'},
    {'name': 'CNT_CRD_OF', 'offset': 0x0210, 'window': 'ERR', 'kind': 'register'},
    {'name': 'CNT_CRD_TO', 'offset': 0x0214, 'window': 'ERR', 'kind': 'register'},
    {'name': 'CNT_TRAIN_TO', 'offset': 0x0218, 'window': 'ERR', 'kind': 'register'},
    {'name': 'CNT_BAD_VL', 'offset': 0x021c, 'window': 'ERR', 'kind': 'register'},
    {'name': 'CNT_CRD_UF', 'offset': 0x0220, 'window': 'ERR', 'kind': 'register'},
    {'name': 'CNT_CLR', 'offset': 0x0224, 'window': 'ERR', 'kind': 'register'},
    {'name': 'LMSM_TMR_SCALE', 'offset': 0x0300, 'window': 'TEST', 'kind': 'register'},
    {'name': 'CRD_TO_DIS', 'offset': 0x0304, 'window': 'TEST', 'kind': 'register'},
    {'name': 'PCS_TX_TEST', 'offset': 0x0308, 'window': 'TEST', 'kind': 'register'},
    {'name': 'APPD_PORT_BASIC', 'offset': 0x1000, 'window': 'APPD_PORT', 'kind': 'window'},
    {'name': 'APPD_LINK_CAP', 'offset': 0x1100, 'window': 'APPD_PORT', 'kind': 'window'},
    {'name': 'APPD_LINK_LOG', 'offset': 0x1200, 'window': 'APPD_PORT', 'kind': 'window'},
    {'name': 'APPD_LMSM_ST', 'offset': 0x1e00, 'window': 'APPD_PORT', 'kind': 'window'},
    {'name': 'APPD_PORT_ERR', 'offset': 0x1f00, 'window': 'APPD_PORT', 'kind': 'window'},
)


def field_get(word: int, mask: int, shift: int) -> int:
    return (int(word) & int(mask)) >> int(shift)


def field_insert(word: int, mask: int, shift: int, value: int) -> int:
    return (int(word) & ~int(mask)) | ((int(value) << int(shift)) & int(mask))
