// Generated by pycc (pyCircuit) from pycircuit/mem/ub_mem_inv.py — do not edit.
// Regenerate: python3 scripts/emit_rtl.py
// PRODUCT (TEST_HOOKS=0). SPEC §2.2 default parameter set (no Verilog parameter).

`include "pyc_reg.v"

// Generated by pycc (pyCircuit)
// Module: ub_mem_inv

module ub_mem_inv (
  input core_clk,
  input rst_pyc,
  input cmd_valid,
  input [1:0] cmd_op,
  input [3:0] cmd_ent_idx,
  input [19:0] cmd_token_id,
  input cmd_match_ent,
  input cmd_match_tok,
  input done_ready,
  input miss_pend,
  input inv2tlb_all_ready,
  input inv2tlb_scan_ready,
  input tlb2inv_scan_done,
  output cmd_ready,
  output done_valid,
  output inv2tlb_all_valid,
  output inv2tlb_scan_valid,
  output [5:0] inv2tlb_scan_set,
  output [3:0] inv2tlb_scan_ent_idx,
  output [19:0] inv2tlb_scan_token_id,
  output inv2tlb_scan_match_ent,
  output inv2tlb_scan_match_tok,
  output busy
);

wire [6:0] dones; // pyc.name="dones"
wire [6:0] dones__next; // pyc.name="dones__next"
wire [3:0] ent_q; // pyc.name="ent_q"
wire [3:0] ent_q__next; // pyc.name="ent_q__next"
wire [6:0] issued; // pyc.name="issued"
wire [6:0] issued__next; // pyc.name="issued__next"
wire me_q; // pyc.name="me_q"
wire me_q__next; // pyc.name="me_q__next"
wire mt_q; // pyc.name="mt_q"
wire mt_q__next; // pyc.name="mt_q__next"
wire [6:0] pyc_add_86; // op=pyc.add
wire [6:0] pyc_add_92; // op=pyc.add
wire pyc_and_41; // op=pyc.and
wire pyc_and_45; // op=pyc.and
wire pyc_and_46; // op=pyc.and
wire pyc_and_47; // op=pyc.and
wire pyc_and_48; // op=pyc.and
wire pyc_and_50; // op=pyc.and
wire pyc_and_52; // op=pyc.and
wire pyc_and_53; // op=pyc.and
wire pyc_and_84; // op=pyc.and
wire pyc_and_85; // op=pyc.and
wire pyc_and_91; // op=pyc.and
wire pyc_comb_16; // op=pyc.comb
wire [2:0] pyc_comb_17; // op=pyc.comb
wire [6:0] pyc_comb_18; // op=pyc.comb
wire [3:0] pyc_comb_19; // op=pyc.comb
wire [19:0] pyc_comb_20; // op=pyc.comb
wire pyc_comb_21; // op=pyc.comb
wire [2:0] pyc_comb_22; // op=pyc.comb
wire [2:0] pyc_comb_23; // op=pyc.comb
wire [2:0] pyc_comb_24; // op=pyc.comb
wire [2:0] pyc_comb_25; // op=pyc.comb
wire [1:0] pyc_comb_26; // op=pyc.comb
wire [1:0] pyc_comb_27; // op=pyc.comb
wire [1:0] pyc_comb_28; // op=pyc.comb
wire [6:0] pyc_comb_29; // op=pyc.comb
wire [6:0] pyc_comb_30; // op=pyc.comb
wire pyc_comb_61; // op=pyc.comb
wire pyc_comb_62; // op=pyc.comb
wire pyc_comb_63; // op=pyc.comb
wire pyc_comb_64; // op=pyc.comb
wire pyc_comb_65; // op=pyc.comb
wire pyc_comb_66; // op=pyc.comb
wire [2:0] pyc_comb_67; // op=pyc.comb
wire [1:0] pyc_comb_72; // op=pyc.comb
wire [1:0] pyc_comb_73; // op=pyc.comb
wire pyc_comb_78; // op=pyc.comb
wire pyc_comb_79; // op=pyc.comb
wire pyc_comb_80; // op=pyc.comb
wire pyc_comb_89; // op=pyc.comb
wire [6:0] pyc_comb_90; // op=pyc.comb
wire [6:0] pyc_comb_95; // op=pyc.comb
wire [5:0] pyc_comb_98; // op=pyc.comb
wire pyc_comb_99; // op=pyc.comb
wire [1:0] pyc_concat_70; // op=pyc.concat
wire [1:0] pyc_concat_71; // op=pyc.concat
wire pyc_constant_1; // op=pyc.constant
wire [2:0] pyc_constant_10; // op=pyc.constant
wire [1:0] pyc_constant_11; // op=pyc.constant
wire [1:0] pyc_constant_12; // op=pyc.constant
wire [1:0] pyc_constant_13; // op=pyc.constant
wire [6:0] pyc_constant_14; // op=pyc.constant
wire [6:0] pyc_constant_15; // op=pyc.constant
wire [2:0] pyc_constant_2; // op=pyc.constant
wire [6:0] pyc_constant_3; // op=pyc.constant
wire [3:0] pyc_constant_4; // op=pyc.constant
wire [19:0] pyc_constant_5; // op=pyc.constant
wire pyc_constant_6; // op=pyc.constant
wire [2:0] pyc_constant_7; // op=pyc.constant
wire [2:0] pyc_constant_8; // op=pyc.constant
wire [2:0] pyc_constant_9; // op=pyc.constant
wire pyc_eq_36; // op=pyc.eq
wire pyc_eq_37; // op=pyc.eq
wire pyc_eq_38; // op=pyc.eq
wire pyc_eq_39; // op=pyc.eq
wire pyc_eq_40; // op=pyc.eq
wire pyc_eq_42; // op=pyc.eq
wire pyc_eq_43; // op=pyc.eq
wire pyc_eq_44; // op=pyc.eq
wire pyc_eq_49; // op=pyc.eq
wire pyc_eq_82; // op=pyc.eq
wire pyc_extract_75; // op=pyc.extract
wire pyc_extract_76; // op=pyc.extract
wire [5:0] pyc_extract_96; // op=pyc.extract
wire [2:0] pyc_mux_54; // op=pyc.mux
wire [2:0] pyc_mux_55; // op=pyc.mux
wire [2:0] pyc_mux_56; // op=pyc.mux
wire [2:0] pyc_mux_57; // op=pyc.mux
wire [2:0] pyc_mux_58; // op=pyc.mux
wire [2:0] pyc_mux_59; // op=pyc.mux
wire [2:0] pyc_mux_60; // op=pyc.mux
wire [3:0] pyc_mux_68; // op=pyc.mux
wire [19:0] pyc_mux_69; // op=pyc.mux
wire pyc_mux_77; // op=pyc.mux
wire pyc_mux_81; // op=pyc.mux
wire [6:0] pyc_mux_87; // op=pyc.mux
wire [6:0] pyc_mux_88; // op=pyc.mux
wire [6:0] pyc_mux_93; // op=pyc.mux
wire [6:0] pyc_mux_94; // op=pyc.mux
wire pyc_not_51; // op=pyc.not
wire pyc_not_83; // op=pyc.not
wire pyc_not_97; // op=pyc.not
wire [2:0] pyc_reg_31; // op=pyc.reg
wire [6:0] pyc_reg_32; // op=pyc.reg
wire [6:0] pyc_reg_33; // op=pyc.reg
wire [3:0] pyc_reg_34; // op=pyc.reg
wire [19:0] pyc_reg_35; // op=pyc.reg
wire [1:0] pyc_reg_74; // op=pyc.reg
wire [2:0] st; // pyc.name="st"
wire [2:0] st__next; // pyc.name="st__next"
wire [19:0] tok_q; // pyc.name="tok_q"
wire [19:0] tok_q__next; // pyc.name="tok_q__next"

// --- Combinational (netlist)
assign dones = pyc_reg_33;
assign ent_q = pyc_reg_34;
assign issued = pyc_reg_32;
assign pyc_constant_1 = 1'd1;
assign pyc_constant_2 = 3'd0;
assign pyc_constant_3 = 7'd0;
assign pyc_constant_4 = 4'd0;
assign pyc_constant_5 = 20'd0;
assign pyc_constant_6 = 1'd0;
assign pyc_constant_7 = 3'd1;
assign pyc_constant_8 = 3'd2;
assign pyc_constant_9 = 3'd3;
assign pyc_constant_10 = 3'd4;
assign pyc_constant_11 = 2'd0;
assign pyc_constant_12 = 2'd1;
assign pyc_constant_13 = 2'd2;
assign pyc_constant_14 = 7'd64;
assign pyc_constant_15 = 7'd1;
assign pyc_comb_16 = pyc_constant_1;
assign pyc_comb_17 = pyc_constant_2;
assign pyc_comb_18 = pyc_constant_3;
assign pyc_comb_19 = pyc_constant_4;
assign pyc_comb_20 = pyc_constant_5;
assign pyc_comb_21 = pyc_constant_6;
assign pyc_comb_22 = pyc_constant_7;
assign pyc_comb_23 = pyc_constant_8;
assign pyc_comb_24 = pyc_constant_9;
assign pyc_comb_25 = pyc_constant_10;
assign pyc_comb_26 = pyc_constant_11;
assign pyc_comb_27 = pyc_constant_12;
assign pyc_comb_28 = pyc_constant_13;
assign pyc_comb_29 = pyc_constant_14;
assign pyc_comb_30 = pyc_constant_15;
assign st = pyc_reg_31;
assign pyc_eq_36 = (st == pyc_comb_17);
assign pyc_eq_37 = (st == pyc_comb_22);
assign pyc_eq_38 = (st == pyc_comb_23);
assign pyc_eq_39 = (st == pyc_comb_24);
assign pyc_eq_40 = (st == pyc_comb_25);
assign pyc_and_41 = (pyc_eq_36 & cmd_valid);
assign pyc_eq_42 = (cmd_op == pyc_comb_26);
assign pyc_eq_43 = (cmd_op == pyc_comb_27);
assign pyc_eq_44 = (cmd_op == pyc_comb_28);
assign pyc_and_45 = (pyc_and_41 & pyc_eq_42);
assign pyc_and_46 = (pyc_and_41 & pyc_eq_43);
assign pyc_and_47 = (pyc_and_41 & pyc_eq_44);
assign pyc_and_48 = (pyc_eq_37 & inv2tlb_all_ready);
assign pyc_eq_49 = (dones == pyc_comb_29);
assign pyc_and_50 = (pyc_eq_38 & pyc_eq_49);
assign pyc_not_51 = (~miss_pend);
assign pyc_and_52 = (pyc_eq_39 & pyc_not_51);
assign pyc_and_53 = (pyc_eq_40 & done_ready);
assign pyc_mux_54 = (pyc_and_53 ? pyc_comb_17 : st);
assign pyc_mux_55 = (pyc_and_52 ? pyc_comb_25 : pyc_mux_54);
assign pyc_mux_56 = (pyc_and_50 ? pyc_comb_25 : pyc_mux_55);
assign pyc_mux_57 = (pyc_and_48 ? pyc_comb_25 : pyc_mux_56);
assign pyc_mux_58 = (pyc_and_47 ? pyc_comb_24 : pyc_mux_57);
assign pyc_mux_59 = (pyc_and_46 ? pyc_comb_23 : pyc_mux_58);
assign pyc_mux_60 = (pyc_and_45 ? pyc_comb_22 : pyc_mux_59);
assign pyc_comb_61 = pyc_eq_36;
assign pyc_comb_62 = pyc_eq_37;
assign pyc_comb_63 = pyc_eq_38;
assign pyc_comb_64 = pyc_eq_40;
assign pyc_comb_65 = pyc_and_41;
assign pyc_comb_66 = pyc_and_46;
assign pyc_comb_67 = pyc_mux_60;
assign pyc_extract_75 = pyc_reg_74[0];
assign pyc_extract_76 = pyc_reg_74[1];
assign me_q = pyc_extract_75;
assign mt_q = pyc_extract_76;
assign pyc_mux_77 = (pyc_comb_65 ? cmd_match_ent : me_q);
assign pyc_comb_78 = me_q;
assign pyc_comb_79 = mt_q;
assign pyc_comb_80 = pyc_mux_77;
assign me_q__next = pyc_comb_80;
assign pyc_eq_82 = (issued == pyc_comb_29);
assign pyc_not_83 = (~pyc_eq_82);
assign pyc_and_84 = (pyc_comb_63 & pyc_not_83);
assign pyc_and_85 = (pyc_and_84 & inv2tlb_scan_ready);
assign pyc_add_86 = (issued + pyc_comb_30);
assign pyc_mux_87 = (pyc_and_85 ? pyc_add_86 : issued);
assign pyc_mux_88 = (pyc_comb_66 ? pyc_comb_18 : pyc_mux_87);
assign pyc_comb_89 = pyc_and_84;
assign pyc_comb_90 = pyc_mux_88;
assign issued__next = pyc_comb_90;
assign pyc_and_91 = (pyc_comb_63 & tlb2inv_scan_done);
assign pyc_add_92 = (dones + pyc_comb_30);
assign pyc_mux_93 = (pyc_and_91 ? pyc_add_92 : dones);
assign pyc_mux_94 = (pyc_comb_66 ? pyc_comb_18 : pyc_mux_93);
assign pyc_comb_95 = pyc_mux_94;
assign dones__next = pyc_comb_95;
assign pyc_extract_96 = issued[5:0];
assign pyc_not_97 = (~pyc_comb_61);
assign pyc_comb_98 = pyc_extract_96;
assign pyc_comb_99 = pyc_not_97;
assign pyc_mux_68 = (pyc_comb_65 ? cmd_ent_idx : ent_q);
assign ent_q__next = pyc_mux_68;
assign pyc_mux_81 = (pyc_comb_65 ? cmd_match_tok : pyc_comb_79);
assign mt_q__next = pyc_mux_81;
assign pyc_concat_70 = {mt_q__next, me_q__next};
assign pyc_concat_71 = {pyc_comb_21, pyc_comb_21};
assign pyc_comb_72 = pyc_concat_70;
assign pyc_comb_73 = pyc_concat_71;
assign st__next = pyc_comb_67;
assign tok_q = pyc_reg_35;
assign pyc_mux_69 = (pyc_comb_65 ? cmd_token_id : tok_q);
assign tok_q__next = pyc_mux_69;

// --- Sequential primitives
pyc_reg #(.WIDTH(3)) pyc_reg_31_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_16),
  .d(st__next),
  .init(pyc_comb_17),
  .q(pyc_reg_31)
);
pyc_reg #(.WIDTH(7)) pyc_reg_32_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_16),
  .d(issued__next),
  .init(pyc_comb_18),
  .q(pyc_reg_32)
);
pyc_reg #(.WIDTH(7)) pyc_reg_33_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_16),
  .d(dones__next),
  .init(pyc_comb_18),
  .q(pyc_reg_33)
);
pyc_reg #(.WIDTH(4)) pyc_reg_34_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_16),
  .d(ent_q__next),
  .init(pyc_comb_19),
  .q(pyc_reg_34)
);
pyc_reg #(.WIDTH(20)) pyc_reg_35_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_16),
  .d(tok_q__next),
  .init(pyc_comb_20),
  .q(pyc_reg_35)
);
pyc_reg #(.WIDTH(2)) pyc_reg_74_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_16),
  .d(pyc_comb_72),
  .init(pyc_comb_73),
  .q(pyc_reg_74)
);

assign cmd_ready = pyc_comb_61;
assign done_valid = pyc_comb_64;
assign inv2tlb_all_valid = pyc_comb_62;
assign inv2tlb_scan_valid = pyc_comb_89;
assign inv2tlb_scan_set = pyc_comb_98;
assign inv2tlb_scan_ent_idx = ent_q;
assign inv2tlb_scan_token_id = tok_q;
assign inv2tlb_scan_match_ent = pyc_comb_78;
assign inv2tlb_scan_match_tok = pyc_comb_79;
assign busy = pyc_comb_99;

endmodule

