"""Compile a @module leaf through pycircuit + pycc (byte-stable).

Same invocation as PR #11 CSR: compile() + pycc --emit=verilog --logic-depth=64.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from pathlib import Path

from lib.variants import variant_name

REPO = Path(__file__).resolve().parents[2]

# Keep in lockstep with pycircuit/csr/ub_csr_regs.py PYCC_EMIT + --logic-depth=64.
PYCC_EMIT = ["--emit=verilog"]
PYCC_LOGIC_DEPTH = "64"

_PRIMITIVES = (
    "pyc_reg",
    "pyc_add",
    "pyc_and",
    "pyc_or",
    "pyc_not",
    "pyc_xor",
    "pyc_mux",
    "pyc_fifo",
    "pyc_byte_mem",
    "pyc_sync_mem",
    "pyc_sync_mem_dp",
    "pyc_async_fifo",
    "pyc_cdc_sync",
)


def toolchain_root() -> Path:
    env = os.environ.get("PYC_TOOLCHAIN_ROOT")
    if env:
        return Path(env)
    return Path("/tmp/pyCircuit/.pycircuit_out/toolchain/install")


def pycc_bin() -> Path:
    root = toolchain_root()
    cand = root / "bin" / "pycc"
    if cand.is_file():
        return cand
    found = shutil.which("pycc")
    if found:
        return Path(found)
    raise FileNotFoundError(
        "pycc not found. Run scripts/setup_pycircuit.sh "
        f"(expected {root / 'bin' / 'pycc'})"
    )


def keep_used_primitive_includes(verilog: str) -> str:
    """Drop unused `include of fifo/mem/cdc primitives (PR #11 same filter)."""
    used: set[str] = set()
    for name in _PRIMITIVES:
        if f"{name} #" in verilog or f"{name} " in verilog.replace(
            f'`include "{name}.v"', ""
        ):
            used.add(name)
    kept: list[str] = []
    for line in verilog.splitlines(keepends=True):
        stripped = line.strip()
        if stripped.startswith("`include"):
            if not any(f'"{name}.v"' in stripped for name in used):
                continue
        kept.append(line)
    return "".join(kept)


def compile_to_verilog(
    build,
    *,
    name: str,
    params: dict,
    test_hooks: bool,
) -> str:
    from pycircuit import compile as pyc_compile

    kw = dict(params)
    kw["test_hooks"] = 1 if test_hooks else 0
    design = pyc_compile(build, name=name, **kw)
    mlir = design.emit_mlir()
    pycc = pycc_bin()
    env = os.environ.copy()
    env.setdefault("PYC_TOOLCHAIN_ROOT", str(toolchain_root()))
    env["PATH"] = f"{toolchain_root() / 'bin'}:{env.get('PATH', '')}"
    with tempfile.TemporaryDirectory(prefix="ub-pycc-") as td:
        mlir_path = Path(td) / f"{name}.pyc"
        v_path = Path(td) / f"{name}.v"
        mlir_path.write_text(mlir, encoding="utf-8")
        cmd = [
            str(pycc),
            str(mlir_path),
            *PYCC_EMIT,
            f"--logic-depth={PYCC_LOGIC_DEPTH}",
            "-o",
            str(v_path),
        ]
        subprocess.check_call(cmd, env=env)
        body = keep_used_primitive_includes(v_path.read_text(encoding="utf-8"))
    th = 1 if test_hooks else 0
    header = (
        f"// GENERATED by pycc from pycircuit — do not edit.\n"
        f"// Reproduce: python3 scripts/emit_rtl.py\n"
        f"// compile() + pycc --emit=verilog --logic-depth=64\n"
        f"// TEST_HOOKS={th}\n"
    )
    return header + body


def emit_variant(
    build,
    *,
    leaf: str,
    tag: str,
    params: dict,
    test_hooks: bool,
    sequential: bool,
) -> tuple[str, str]:
    del sequential
    name = variant_name(leaf, tag)
    text = compile_to_verilog(
        build,
        name=name,
        params=params,
        test_hooks=test_hooks,
    )
    return name, text
