"""Compile a @module leaf through pycircuit + pycc (byte-stable)."""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from pathlib import Path

from lib.variants import variant_name

REPO = Path(__file__).resolve().parents[2]


def toolchain_root() -> Path:
    env = os.environ.get("PYC_TOOLCHAIN_ROOT")
    if env:
        return Path(env)
    return Path("/tmp/pyCircuit/.pycircuit_out/toolchain/install")


def pycc_bin() -> Path:
    root = toolchain_root()
    cand = root / "bin" / "pycc"
    if cand.is_file():
        return cand
    found = shutil.which("pycc")
    if found:
        return Path(found)
    raise FileNotFoundError(
        "pycc not found. Run scripts/setup_pycircuit.sh "
        f"(expected {root / 'bin' / 'pycc'})"
    )


def compile_to_verilog(
    build,
    *,
    name: str,
    params: dict,
    test_hooks: bool,
    include_primitives: bool,
) -> str:
    from pycircuit import compile as pyc_compile

    kw = dict(params)
    kw["test_hooks"] = 1 if test_hooks else 0
    design = pyc_compile(build, name=name, **kw)
    mlir = design.emit_mlir()
    pycc = pycc_bin()
    env = os.environ.copy()
    env.setdefault("PYC_TOOLCHAIN_ROOT", str(toolchain_root()))
    env["PATH"] = f"{toolchain_root() / 'bin'}:{env.get('PATH', '')}"
    with tempfile.TemporaryDirectory(prefix="ub-pycc-") as td:
        mlir_path = Path(td) / f"{name}.mlir"
        v_path = Path(td) / f"{name}.v"
        mlir_path.write_text(mlir, encoding="utf-8")
        cmd = [str(pycc), str(mlir_path), "--emit=verilog", "-o", str(v_path)]
        if not include_primitives:
            cmd.append("--include-primitives=0")
        subprocess.check_call(cmd, env=env)
        body = v_path.read_text(encoding="utf-8")
    th = 1 if test_hooks else 0
    header = (
        f"// GENERATED by pycc from pycircuit — do not edit.\n"
        f"// Reproduce: python3 scripts/emit_rtl.py\n"
        f"// TEST_HOOKS={th}\n"
    )
    return header + body


def emit_variant(
    build,
    *,
    leaf: str,
    tag: str,
    params: dict,
    test_hooks: bool,
    sequential: bool,
) -> tuple[str, str]:
    name = variant_name(leaf, tag)
    text = compile_to_verilog(
        build,
        name=name,
        params=params,
        test_hooks=test_hooks,
        include_primitives=False,
    )
    return name, text
