"""ub_dll_retry_ack_sm — DLL RETRY_ACK_SM (pyc4.0 leaf).

Source of truth for this leaf. Business registers are ``pyc_reg``
(synchronous, active-high ``rst_pyc``; sensitive to ``core_clk`` only).
``TEST_HOOKS`` is expanded here at Python generation-time (SPEC §11);
the generated Verilog has no ``ifdef TEST_HOOKS``.

Source lives under ``pycircuit/dll/`` (PR #5 layout: pyCircuit in
``pycircuit/<layer>/``, generated ``.v`` only under ``rtl/<layer>/``).
Temporary emit until ``scripts/emit_rtl.py`` lands via PR #5:

    python3 pycircuit/dll/emit.py

SPEC §2.2 / CODING_STYLE §5:

    PRODUCT (TEST_HOOKS=0) → ``rtl/dll/ub_dll_retry_ack_sm.v``
    HOOKS   (TEST_HOOKS=1) → ``rtl/dll/hooks/ub_dll_retry_ack_sm.v``

SPEC §10 lists **no** hooks for this leaf. Xia: HOOKS has the same
ports as PRODUCT — no ``tb_test_mode`` (that port is only on modules
§10 lists hooks for).

Module name ``ub_dll_retry_ack_sm`` = ``ub_<层>_<功能>``
(CODING_STYLE §5). SPEC §2.6 names the parent ``ub_dll_retry``
(buffer + both SMs) and the block ``RETRY_ACK_SM``; this leaf is
that SM only (buffer / replay datapath is out of scope).

Mapped to SPEC §6.4 / UB-DL §4.7.3.4 (transfers closed in docs PR #9
@ 1277cce0), REGMAP ``STATUS.RETRY_ACK_ST[14:13]``, SPEC §4.2 /
§3.2.3 ``PORT_RST``.

Does not generate the 16-cycle PORT_RST pulse (``ub_csr`` does);
``port_rst`` is a sync clear to NORMAL. Does not own Retry_Ack_Set
serialization or the retry-buffer replay stream (parent pulses
``retry_ack_set_done`` / ``replay_done``).
"""

from __future__ import annotations

from pathlib import Path

# STATUS.RETRY_ACK_ST[14:13] (SPEC §6.4 / REGMAP). 2–3 reserved; never produced.
ST_NORMAL = 0
ST_ACK = 1

# Internal only — not visible on retry_ack_st (SPEC has two CSR states).
SUB_SET = 0
SUB_REPLAY = 1

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
PRODUCT_V = REPO / "rtl" / "dll" / "ub_dll_retry_ack_sm.v"
HOOKS_V = REPO / "rtl" / "dll" / "hooks" / "ub_dll_retry_ack_sm.v"


def _header(test_hooks: int) -> str:
    return f"""\
// Generated by pycircuit/dll/ub_dll_retry_ack_sm.py — do not hand-edit.
// pyc4.0 leaf ub_dll_retry_ack_sm. TEST_HOOKS={test_hooks} (Python generation-time).
// Registers: pyc_reg semantics (sync, rst_pyc active-high, core_clk).
// SPEC: §2.6, §3.2.3, §4.2, §6.4, §9, §10, §11.
// PORT_RST 16-cycle pulse: ub_csr; this leaf sees port_rst as sync clear.
// SPEC §10 lists no hooks — HOOKS ports == PRODUCT (no tb_test_mode).
"""


def emit_verilog(test_hooks: bool) -> str:
    """Emit one netlist. ``test_hooks`` is the Python-level TEST_HOOKS flag."""
    th = 1 if test_hooks else 0
    lines: list[str] = [_header(th)]

    def w(s: str = "") -> None:
        lines.append(s)

    w("module ub_dll_retry_ack_sm (")
    w("  input  wire                    core_clk,")
    w("  input  wire                    rst_pyc,")
    w("  input  wire                    port_rst,")
    w()
    w("  // OPEN leaf events: SPEC §6.4 names the condition, not a pin.")
    w("  // Level; sampled each core_clk. Parent owns 1 Idle + 32 Ack and replay.")
    w("  input  wire                    retry_req_set_rx,")
    w("  input  wire                    retry_ack_set_done,")
    w("  input  wire                    replay_done,")
    w()
    w("  // REGMAP STATUS.RETRY_ACK_ST[14:13] (SPEC §6.4). Never 2–3.")
    w("  output wire [1:0]              retry_ack_st")
    w(");")
    w()
    w("  // ------------------------------------------------------------------")
    w("  // STATUS.RETRY_ACK_ST encoding (SPEC §6.4). 2–3 reserved — never driven.")
    w("  // ------------------------------------------------------------------")
    w(f"  localparam [1:0] ST_NORMAL = 2'd{ST_NORMAL};")
    w(f"  localparam [1:0] ST_ACK    = 2'd{ST_ACK};")
    w()
    w("  // Internal substate of ACK. Not exported (SPEC has two CSR states).")
    w(f"  localparam        SUB_SET    = 1'b{SUB_SET};")
    w(f"  localparam        SUB_REPLAY = 1'b{SUB_REPLAY};")
    w()
    w("  // Combined sync reset: rst_pyc (entity) or port_rst (CSR PORT_RST).")
    w("  // SPEC §6.4: reset → NORMAL.")
    w("  // Xia: no tb_test_mode — SPEC §10 lists no hooks for this leaf.")
    w("  wire rst_eff = rst_pyc | port_rst;")
    w()
    w("  // pyc_reg: st, sub.")
    w("  reg [1:0] st;")
    w("  reg       sub;")
    w()
    w("  // ------------------------------------------------------------------")
    w("  // Next-state (SPEC §6.4 table).")
    w("  //   NORMAL → ACK : received peer Retry_Req_Set")
    w("  //   ACK → NORMAL : Retry_Ack_Set done AND this-round replay done")
    w("  //   ACK stay ACK : Retry_Req_Set while sending marked replay (restart)")
    w("  // WAIVER_RETRY_ACK_FSM_DEFAULT: illegal st (2–3) → NORMAL.")
    w("  // ------------------------------------------------------------------")
    w("  reg [1:0] st_n;")
    w("  reg       sub_n;")
    w()
    w("  always @* begin")
    w("    st_n  = st;")
    w("    sub_n = sub;")
    w("    case (st)")
    w("      ST_NORMAL: begin")
    w("        sub_n = SUB_SET;")
    w("        if (retry_req_set_rx)")
    w("          st_n = ST_ACK;")
    w("      end")
    w()
    w("      ST_ACK: begin")
    w("        // SPEC §6.4: while sending replay, a new Retry_Req_Set restarts.")
    w("        if ((sub == SUB_REPLAY) && retry_req_set_rx) begin")
    w("          sub_n = SUB_SET;")
    w("        end else if ((sub == SUB_SET) && retry_ack_set_done && replay_done) begin")
    w("          st_n  = ST_NORMAL;")
    w("          sub_n = SUB_SET;")
    w("        end else if ((sub == SUB_SET) && retry_ack_set_done) begin")
    w("          sub_n = SUB_REPLAY;")
    w("        end else if ((sub == SUB_REPLAY) && replay_done) begin")
    w("          st_n  = ST_NORMAL;")
    w("          sub_n = SUB_SET;")
    w("        end")
    w("      end")
    w()
    w("      default: begin")
    w("        st_n  = ST_NORMAL; // WAIVER_RETRY_ACK_FSM_DEFAULT")
    w("        sub_n = SUB_SET;")
    w("      end")
    w("    endcase")
    w("  end")
    w()
    w("  // pyc_reg bank (sync; rst_eff = rst_pyc | port_rst).")
    w("  always @(posedge core_clk) begin")
    w("    if (rst_eff) begin")
    w("      st  <= ST_NORMAL;")
    w("      sub <= SUB_SET;")
    w("    end else begin")
    w("      st  <= st_n;")
    w("      sub <= sub_n;")
    w("    end")
    w("  end")
    w()
    w("  assign retry_ack_st = st;")
    w()
    w("endmodule")
    w()
    return "\n".join(lines) + "\n"


def generate() -> tuple[Path, Path]:
    product = emit_verilog(False)
    hooks = emit_verilog(True)
    if "`ifdef" in product or "`ifdef" in hooks:
        raise RuntimeError("generated Verilog must not use ifdef TEST_HOOKS")
    def _port_lines(text: str) -> list[str]:
        return [
            line
            for line in text.splitlines()
            if line.lstrip().startswith(("input", "output", "assign", "wire"))
        ]

    prod_ports = _port_lines(product)
    hooks_ports = _port_lines(hooks)
    if prod_ports != hooks_ports:
        raise RuntimeError("HOOKS ports must equal PRODUCT ports (no §10 hooks)")
    for token in ("tb_test_mode", "tb_inj_", "tb_obs_"):
        if any(token in line for line in prod_ports + hooks_ports):
            raise RuntimeError(f"no-§10 leaf must not contain {token}")
    for text in (product, hooks):
        for line in text.splitlines():
            if "st_n" in line and ("2'd2" in line or "2'd3" in line
                                   or "2'b10" in line or "2'b11" in line):
                raise RuntimeError(f"RETRY_ACK_ST reserved encoding: {line}")
    PRODUCT_V.parent.mkdir(parents=True, exist_ok=True)
    HOOKS_V.parent.mkdir(parents=True, exist_ok=True)
    PRODUCT_V.write_text(product)
    HOOKS_V.write_text(hooks)
    return PRODUCT_V, HOOKS_V


# Optional pyc4.0 frontend entry (port/clock/reset declaration).
try:
    from pycircuit import Circuit, module, u  # type: ignore

    @module(name="ub_dll_retry_ack_sm")
    def build(m: Circuit) -> None:
        """pyc4.0 module boundary for ub_dll_retry_ack_sm."""
        clk = m.clock("core_clk")
        rst = m.reset("rst")
        _ = (clk, rst)
        st = m.out("st", clk=clk, rst=rst, width=2, init=u(2, ST_NORMAL))
        st.set(st.out())
        m.output("retry_ack_st", st.out())

    build.__pycircuit_name__ = "ub_dll_retry_ack_sm"
except ImportError:
    build = None  # type: ignore


if __name__ == "__main__":
    product, hooks = generate()
    print(f"wrote {product}")
    print(f"wrote {hooks}")
