#!/usr/bin/env python3
"""Emit PRODUCT Verilog for registered pyCircuit leaves via pycc.

CODING_STYLE §1 / SPEC §11: TEST_HOOKS expands at Python generation time.
This registry currently holds ``ub_cmn_mem_1r1w`` only. SPEC §10 lists no
``tb_*`` hooks for that leaf, so only PRODUCT netlists are written
(``rtl/cmn/<leaf>_<tag>.v``). No ``rtl/cmn/hooks/`` copies.

Do not put the repo root on PYTHONPATH (the toolchain package is also
named ``pycircuit``). ``scripts/emit_rtl.py`` inserts this directory.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
RTL = REPO / "rtl"

# LEAVES table — one row per source module. Variants follow SPEC §2.2
# ``<leaf>_<tag>``. hooks=False means PRODUCT only.
LEAVES: list[dict] = [
    {
        "name": "ub_cmn_mem_1r1w",
        "layer": "cmn",
        "source": "cmn/ub_cmn_mem_1r1w.py",
        "hooks": False,
        "variants": [
            {"label": "d5w8", "depth": 5, "width": 8, "wmask_w": 8},
            {"label": "d8w16", "depth": 8, "width": 16, "wmask_w": 16},
            {"label": "d64w64m16", "depth": 64, "width": 64, "wmask_w": 16},
            {"label": "d512w512m64", "depth": 512, "width": 512, "wmask_w": 64},
        ],
    },
]


def clog2(n: int) -> int:
    if n < 1:
        raise ValueError("DEPTH must be >= 1")
    return (n - 1).bit_length()


def _find_pycc() -> Path:
    root = os.environ.get("PYC_TOOLCHAIN_ROOT")
    if root:
        cand = Path(root) / "bin" / "pycc"
        if cand.is_file():
            return cand
    which = shutil.which("pycc")
    if which:
        return Path(which)
    for cand in (
        Path("/tmp/pyCircuit/.pycircuit_out/toolchain/install/bin/pycc"),
        Path("/tmp/spike/pyCircuit/.pycircuit_out/toolchain/install/bin/pycc"),
    ):
        if cand.is_file():
            return cand
    raise SystemExit(
        "pycc not found. Build lukebest/pyCircuit @ 43cc5918 and set "
        "PYC_TOOLCHAIN_ROOT to <clone>/.pycircuit_out/toolchain/install "
        "(or put pycc on PATH)."
    )


def _find_pyc_reg(pycc: Path) -> Path:
    install = pycc.resolve().parent.parent
    cand = install / "include" / "verilog" / "pyc_reg.v"
    if cand.is_file():
        return cand
    raise SystemExit(f"pyc_reg.v not found next to pycc ({cand})")


def _ensure_pycircuit() -> None:
    try:
        import pycircuit  # noqa: F401
    except ImportError as exc:
        raise SystemExit(
            "Python package pycircuit is not importable. "
            "Use the venv that has `pip install -e <pyCircuit>`."
        ) from exc


def _tie_off_rst(verilog: str, module: str) -> str:
    """Drop the leaf rst port and tie the internal net to 0.

    ``m.out`` / pyc_reg require ``!pyc.reset``. PRODUCT has no reset
    (CODING_STYLE §10): array and rdata stay undefined until a defined
    write/read. Business-leaf name is ``rst_pyc``; this primitive does
    not bring it out.
    """
    needle = f"module {module} ("
    start = verilog.find(needle)
    if start < 0:
        raise SystemExit(f"generated Verilog missing {module!r}")
    ports_end = verilog.find(");", start)
    if ports_end < 0:
        raise SystemExit(f"generated Verilog: no port-list end for {module}")
    ports = verilog[start:ports_end]
    if "\n  input rst,\n" not in ports:
        raise SystemExit(f"generated Verilog: expected `input rst` on {module}")
    ports = ports.replace("\n  input rst,", "")
    insert = (
        "\n"
        "  // pyc_reg requires !pyc.reset; PRODUCT ties it off.\n"
        "  // Array and rdata are not reset (undefined until a defined read).\n"
        "  wire rst = 1'b0;\n"
    )
    return verilog[:start] + ports + verilog[ports_end : ports_end + 2] + insert + verilog[
        ports_end + 2 :
    ]


def _header(leaf: str, label: str, depth: int, width: int, wmask_w: int) -> str:
    aw = clog2(depth)
    nseg = width // wmask_w
    ports = (
        f"core_clk, we, waddr[{aw}-1:0], wdata[{width}-1:0], "
        f"re, raddr[{aw}-1:0], rdata[{width}-1:0]"
    )
    if nseg > 1:
        ports = (
            f"core_clk, we, waddr[{aw}-1:0], wdata[{width}-1:0], "
            f"wmask[{nseg}-1:0], re, raddr[{aw}-1:0], rdata[{width}-1:0]"
        )
    return (
        f"// Generated by pycc (pyCircuit) from pycircuit/cmn/{leaf}.py — do not edit.\n"
        f"// Regenerate: python3 scripts/emit_rtl.py\n"
        f"// PRODUCT (TEST_HOOKS=0). SPEC §10 lists no tb_* hooks — no HOOKS netlist.\n"
        f"// Variant {label}: DEPTH={depth} WIDTH={width} WMASK_W={wmask_w} "
        f"N={nseg} AW={aw}\n"
        f"// Ports: {ports}\n"
        f"// 1R1W, registered rdata (1-cycle), same-address same-cycle read-old.\n"
        f"// No rst_pyc port; array and rdata are not reset.\n"
        f"// OOR addresses are not truncated.\n"
        f"\n"
    )


def _write_pyc_reg(out_root: Path, pyc_reg: Path) -> Path:
    dest = out_root / "cmn" / "pyc_reg.v"
    dest.parent.mkdir(parents=True, exist_ok=True)
    text = pyc_reg.read_text(encoding="utf-8")
    if not text.endswith("\n"):
        text += "\n"
    dest.write_text(text, encoding="utf-8")
    return dest


def emit_variant(
    *,
    source: Path,
    module: str,
    depth: int,
    width: int,
    wmask_w: int,
    dest: Path,
    pycc: Path,
) -> Path:
    from pycircuit.jit import compile

    # Import the @module entry from the leaf file (not as pycircuit.*).
    import importlib.util

    spec = importlib.util.spec_from_file_location(source.stem, source)
    if spec is None or spec.loader is None:
        raise SystemExit(f"cannot load {source}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    build = getattr(mod, "build", None)
    if build is None:
        raise SystemExit(f"{source} has no build()")

    design = compile(
        build,
        name=module,
        depth=int(depth),
        width=int(width),
        wmask_w=int(wmask_w),
        test_hooks=0,
    )
    mlir = design.emit_mlir()

    dest.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="ub_cmn_emit_") as tmp:
        mlir_path = Path(tmp) / f"{module}.mlir"
        raw_v = Path(tmp) / f"{module}.raw.v"
        mlir_path.write_text(mlir, encoding="utf-8")
        env = os.environ.copy()
        env.setdefault("PYC_TOOLCHAIN_ROOT", str(pycc.resolve().parent.parent))
        subprocess.run(
            [str(pycc), str(mlir_path), "--emit=verilog", "--include-primitives=0", "-o", str(raw_v)],
            check=True,
            env=env,
        )
        raw = raw_v.read_text(encoding="utf-8")

    raw = _tie_off_rst(raw, module)
    label = module[len("ub_cmn_mem_1r1w_") :] if module.startswith("ub_cmn_mem_1r1w_") else module
    include = '`include "pyc_reg.v"\n\n'
    text = _header("ub_cmn_mem_1r1w", label, depth, width, wmask_w) + include + raw
    dest.write_text(text, encoding="utf-8")
    return dest


def emit_all(out_root: Path = RTL) -> list[Path]:
    _ensure_pycircuit()
    pycc = _find_pycc()
    pyc_reg = _find_pyc_reg(pycc)
    written: list[Path] = [_write_pyc_reg(out_root, pyc_reg)]
    for leaf in LEAVES:
        source = HERE / leaf["source"]
        for var in leaf["variants"]:
            module = f"{leaf['name']}_{var['label']}"
            dest = out_root / leaf["layer"] / f"{module}.v"
            width = int(var["width"])
            wmask_w = int(var.get("wmask_w") or width)
            if wmask_w < 1 or width % wmask_w != 0:
                raise SystemExit(
                    f"{module}: WIDTH={width} must be a multiple of WMASK_W={wmask_w}"
                )
            written.append(
                emit_variant(
                    source=source,
                    module=module,
                    depth=int(var["depth"]),
                    width=width,
                    wmask_w=wmask_w,
                    dest=dest,
                    pycc=pycc,
                )
            )
            if leaf.get("hooks"):
                hooks = out_root / leaf["layer"] / "hooks" / f"{module}.v"
                # No hooks defined for the current leaf; kept for later rows.
                hooks.parent.mkdir(parents=True, exist_ok=True)
                hooks.write_text(dest.read_text(encoding="utf-8"), encoding="utf-8")
                written.append(hooks)
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=RTL)
    args = parser.parse_args()
    paths = emit_all(args.out)
    for p in paths:
        try:
            rel = p.relative_to(REPO)
        except ValueError:
            rel = p
        print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
