#!/usr/bin/env python3
"""Emit PRODUCT / HOOKS Verilog for C-line mem leaves via pycc.

    python3 scripts/emit_rtl.py

Do not put the repo root on PYTHONPATH (the toolchain package is also
named pycircuit). ``scripts/emit_rtl.py`` inserts this directory.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
RTL = REPO / "rtl"

STUB_MOD = "ub_cmn_mem_1r1w_d64w109"

LEAVES: list[dict] = [
    {
        "name": "ub_mem_tlb",
        "layer": "mem",
        "source": "mem/ub_mem_tlb.py",
        "hooks": True,
        "variants": [{"label": "", "tlb_sets": 64, "tlb_ways": 4}],
    },
    {
        "name": "ub_mem_inv",
        "layer": "mem",
        "source": "mem/ub_mem_inv.py",
        "hooks": True,  # gate: every leaf has PRODUCT + HOOKS (no tb_* here)
        "variants": [{"label": ""}],
    },
]


def _find_pycc() -> Path:
    root = os.environ.get("PYC_TOOLCHAIN_ROOT")
    if root:
        cand = Path(root) / "bin" / "pycc"
        if cand.is_file():
            return cand
    which = shutil.which("pycc")
    if which:
        return Path(which)
    for cand in (
        Path("/tmp/pyCircuit/.pycircuit_out/toolchain/install/bin/pycc"),
        Path("/tmp/spike/pyCircuit/.pycircuit_out/toolchain/install/bin/pycc"),
    ):
        if cand.is_file():
            return cand
    raise SystemExit(
        "pycc not found. Build lukebest/pyCircuit @ 43cc5918 and set "
        "PYC_TOOLCHAIN_ROOT to <clone>/.pycircuit_out/toolchain/install."
    )


def _find_pyc_reg(pycc: Path) -> Path:
    install = pycc.resolve().parent.parent
    cand = install / "include" / "verilog" / "pyc_reg.v"
    if cand.is_file():
        return cand
    raise SystemExit(f"pyc_reg.v not found next to pycc ({cand})")


def _ensure_pycircuit() -> None:
    try:
        import pycircuit  # noqa: F401
    except ImportError as exc:
        raise SystemExit(
            "Python package pycircuit is not importable. "
            "Use the venv that has `pip install -e <pyCircuit>`."
        ) from exc


def _load_build(source: Path):
    import importlib.util

    spec = importlib.util.spec_from_file_location(source.stem, source)
    if spec is None or spec.loader is None:
        raise SystemExit(f"cannot load {source}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    build = getattr(mod, "build", None)
    if build is None:
        raise SystemExit(f"{source} has no build()")
    return build


def _strip_stub_module(verilog: str, name: str) -> str:
    """Drop the black-box stub body; keep named instances in the parent."""
    needle = f"module {name} ("
    start = verilog.find(needle)
    if start < 0:
        needle = f"module {name}("
        start = verilog.find(needle)
    if start < 0:
        return verilog
    comm = verilog.rfind("// Generated by pycc", 0, start)
    prev_end = verilog.rfind("endmodule", 0, start)
    if comm >= 0 and comm > prev_end:
        start = comm
    end = verilog.find("endmodule", start)
    if end < 0:
        raise SystemExit(f"no endmodule for stub {name}")
    end = end + len("endmodule")
    while end < len(verilog) and verilog[end] in "\r\n":
        end += 1
    return verilog[:start] + verilog[end:]


def _header(leaf: str, hooks: int) -> str:
    kind = "HOOKS (TEST_HOOKS=1)" if hooks else "PRODUCT (TEST_HOOKS=0)"
    extra = ""
    if leaf == "ub_mem_tlb":
        extra = f"// Instantiates {STUB_MOD} by name (design-B PR #21).\n"
    return (
        f"// Generated by pycc (pyCircuit) from pycircuit/mem/{leaf}.py — do not edit.\n"
        f"// Regenerate: python3 scripts/emit_rtl.py\n"
        f"// {kind}. SPEC §2.2 default parameter set (no Verilog parameter).\n"
        + extra
        + "\n"
    )


def _write_pyc_reg(out_root: Path, pyc_reg: Path) -> Path | None:
    # PR #21 owns rtl/pyc_lib/pyc_reg.v. Do not write it into the repo tree
    # from this PR (identical bytes would still collide on merge). Regen
    # checks pass --out <tmpdir> and get a local copy there.
    if out_root.resolve() == RTL.resolve():
        return None
    dest = out_root / "pyc_lib" / "pyc_reg.v"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(pyc_reg.read_bytes())
    return dest


def emit_one(
    *,
    source: Path,
    module: str,
    dest: Path,
    pycc: Path,
    test_hooks: int,
    extra: dict,
) -> Path:
    from pycircuit.jit import compile

    if str(HERE) not in os.sys.path:
        os.sys.path.insert(0, str(HERE))
    build = _load_build(source)
    kwargs = {"test_hooks": int(test_hooks)}
    kwargs.update(extra)
    design = compile(build, name=module, **kwargs)
    mlir = design.emit_mlir()

    dest.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="ub_mem_emit_") as tmp:
        mlir_path = Path(tmp) / f"{module}.mlir"
        raw_v = Path(tmp) / f"{module}.raw.v"
        mlir_path.write_text(mlir, encoding="utf-8")
        env = os.environ.copy()
        env.setdefault("PYC_TOOLCHAIN_ROOT", str(pycc.resolve().parent.parent))
        subprocess.run(
            [
                str(pycc),
                str(mlir_path),
                "--emit=verilog",
                "--include-primitives=0",
                # 64-set valid/PLRU mux trees + 60b tag compare exceed the
                # default 32; UARCH §6.1 budgets this on the 80.57 MHz P1 path.
                "--logic-depth=128",
                "-o",
                str(raw_v),
            ],
            check=True,
            env=env,
        )
        raw = raw_v.read_text(encoding="utf-8")

    raw = _strip_stub_module(raw, STUB_MOD)
    include = '`include "pyc_reg.v"\n\n'
    text = _header(source.stem, test_hooks) + include + raw
    dest.write_text(text, encoding="utf-8")
    return dest


def emit_all(out_root: Path = RTL) -> list[Path]:
    _ensure_pycircuit()
    if str(HERE) not in os.sys.path:
        os.sys.path.insert(0, str(HERE))
    pycc = _find_pycc()
    pyc_reg = _find_pyc_reg(pycc)
    written: list[Path] = []
    pyc_copy = _write_pyc_reg(out_root, pyc_reg)
    if pyc_copy is not None:
        written.append(pyc_copy)
    for leaf in LEAVES:
        source = HERE / leaf["source"]
        for var in leaf["variants"]:
            extra = {k: v for k, v in var.items() if k != "label"}
            module = leaf["name"]
            dest = out_root / leaf["layer"] / f"{module}.v"
            written.append(
                emit_one(
                    source=source,
                    module=module,
                    dest=dest,
                    pycc=pycc,
                    test_hooks=0,
                    extra=extra,
                )
            )
            if leaf.get("hooks"):
                hooks = out_root / leaf["layer"] / "hooks" / f"{module}.v"
                written.append(
                    emit_one(
                        source=source,
                        module=module,
                        dest=hooks,
                        pycc=pycc,
                        test_hooks=1,
                        extra=extra,
                    )
                )
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=RTL)
    args = parser.parse_args()
    paths = emit_all(args.out)
    for p in paths:
        try:
            rel = p.relative_to(REPO)
        except ValueError:
            rel = p
        print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
