// GENERATED by pycc from pycircuit — do not edit.
// Reproduce: python3 scripts/emit_rtl.py
// TEST_HOOKS=0
// Generated by pycc (pyCircuit)
// Module: ub_pcs_lane_dedist_x4

module ub_pcs_lane_dedist_x4 (
  input [127:0] data_in,
  output [127:0] data_out
);

wire [127:0] data_in__ub_pcs_lane_dedist__L46; // pyc.name="data_in__ub_pcs_lane_dedist__L46"
wire [127:0] pyc_comb_18; // op=pyc.comb
wire [127:0] pyc_concat_17; // op=pyc.concat
wire [7:0] pyc_extract_1; // op=pyc.extract
wire [7:0] pyc_extract_10; // op=pyc.extract
wire [7:0] pyc_extract_11; // op=pyc.extract
wire [7:0] pyc_extract_12; // op=pyc.extract
wire [7:0] pyc_extract_13; // op=pyc.extract
wire [7:0] pyc_extract_14; // op=pyc.extract
wire [7:0] pyc_extract_15; // op=pyc.extract
wire [7:0] pyc_extract_16; // op=pyc.extract
wire [7:0] pyc_extract_2; // op=pyc.extract
wire [7:0] pyc_extract_3; // op=pyc.extract
wire [7:0] pyc_extract_4; // op=pyc.extract
wire [7:0] pyc_extract_5; // op=pyc.extract
wire [7:0] pyc_extract_6; // op=pyc.extract
wire [7:0] pyc_extract_7; // op=pyc.extract
wire [7:0] pyc_extract_8; // op=pyc.extract
wire [7:0] pyc_extract_9; // op=pyc.extract

// --- Combinational (netlist)
assign data_in__ub_pcs_lane_dedist__L46 = data_in;
assign pyc_extract_1 = data_in__ub_pcs_lane_dedist__L46[7:0];
assign pyc_extract_2 = data_in__ub_pcs_lane_dedist__L46[39:32];
assign pyc_extract_3 = data_in__ub_pcs_lane_dedist__L46[71:64];
assign pyc_extract_4 = data_in__ub_pcs_lane_dedist__L46[103:96];
assign pyc_extract_5 = data_in__ub_pcs_lane_dedist__L46[15:8];
assign pyc_extract_6 = data_in__ub_pcs_lane_dedist__L46[47:40];
assign pyc_extract_7 = data_in__ub_pcs_lane_dedist__L46[79:72];
assign pyc_extract_8 = data_in__ub_pcs_lane_dedist__L46[111:104];
assign pyc_extract_9 = data_in__ub_pcs_lane_dedist__L46[23:16];
assign pyc_extract_10 = data_in__ub_pcs_lane_dedist__L46[55:48];
assign pyc_extract_11 = data_in__ub_pcs_lane_dedist__L46[87:80];
assign pyc_extract_12 = data_in__ub_pcs_lane_dedist__L46[119:112];
assign pyc_extract_13 = data_in__ub_pcs_lane_dedist__L46[31:24];
assign pyc_extract_14 = data_in__ub_pcs_lane_dedist__L46[63:56];
assign pyc_extract_15 = data_in__ub_pcs_lane_dedist__L46[95:88];
assign pyc_extract_16 = data_in__ub_pcs_lane_dedist__L46[127:120];
assign pyc_concat_17 = {pyc_extract_1, pyc_extract_2, pyc_extract_3, pyc_extract_4, pyc_extract_5, pyc_extract_6, pyc_extract_7, pyc_extract_8, pyc_extract_9, pyc_extract_10, pyc_extract_11, pyc_extract_12, pyc_extract_13, pyc_extract_14, pyc_extract_15, pyc_extract_16};
assign pyc_comb_18 = pyc_concat_17;

assign data_out = pyc_comb_18;

endmodule

