// GENERATED by pycc from pycircuit — do not edit.
// Reproduce: python3 scripts/emit_rtl.py
// TEST_HOOKS=0
// Generated by pycc (pyCircuit)
// Module: ub_pcs_lane_dist_x8

module ub_pcs_lane_dist_x8 (
  input [255:0] data_in,
  output [255:0] data_out
);

wire [255:0] data_in__ub_pcs_lane_dist__L50; // pyc.name="data_in__ub_pcs_lane_dist__L50"
wire [255:0] pyc_comb_34; // op=pyc.comb
wire [255:0] pyc_concat_33; // op=pyc.concat
wire [7:0] pyc_extract_1; // op=pyc.extract
wire [7:0] pyc_extract_10; // op=pyc.extract
wire [7:0] pyc_extract_11; // op=pyc.extract
wire [7:0] pyc_extract_12; // op=pyc.extract
wire [7:0] pyc_extract_13; // op=pyc.extract
wire [7:0] pyc_extract_14; // op=pyc.extract
wire [7:0] pyc_extract_15; // op=pyc.extract
wire [7:0] pyc_extract_16; // op=pyc.extract
wire [7:0] pyc_extract_17; // op=pyc.extract
wire [7:0] pyc_extract_18; // op=pyc.extract
wire [7:0] pyc_extract_19; // op=pyc.extract
wire [7:0] pyc_extract_2; // op=pyc.extract
wire [7:0] pyc_extract_20; // op=pyc.extract
wire [7:0] pyc_extract_21; // op=pyc.extract
wire [7:0] pyc_extract_22; // op=pyc.extract
wire [7:0] pyc_extract_23; // op=pyc.extract
wire [7:0] pyc_extract_24; // op=pyc.extract
wire [7:0] pyc_extract_25; // op=pyc.extract
wire [7:0] pyc_extract_26; // op=pyc.extract
wire [7:0] pyc_extract_27; // op=pyc.extract
wire [7:0] pyc_extract_28; // op=pyc.extract
wire [7:0] pyc_extract_29; // op=pyc.extract
wire [7:0] pyc_extract_3; // op=pyc.extract
wire [7:0] pyc_extract_30; // op=pyc.extract
wire [7:0] pyc_extract_31; // op=pyc.extract
wire [7:0] pyc_extract_32; // op=pyc.extract
wire [7:0] pyc_extract_4; // op=pyc.extract
wire [7:0] pyc_extract_5; // op=pyc.extract
wire [7:0] pyc_extract_6; // op=pyc.extract
wire [7:0] pyc_extract_7; // op=pyc.extract
wire [7:0] pyc_extract_8; // op=pyc.extract
wire [7:0] pyc_extract_9; // op=pyc.extract

// --- Combinational (netlist)
assign data_in__ub_pcs_lane_dist__L50 = data_in;
assign pyc_extract_1 = data_in__ub_pcs_lane_dist__L50[7:0];
assign pyc_extract_2 = data_in__ub_pcs_lane_dist__L50[71:64];
assign pyc_extract_3 = data_in__ub_pcs_lane_dist__L50[135:128];
assign pyc_extract_4 = data_in__ub_pcs_lane_dist__L50[199:192];
assign pyc_extract_5 = data_in__ub_pcs_lane_dist__L50[15:8];
assign pyc_extract_6 = data_in__ub_pcs_lane_dist__L50[79:72];
assign pyc_extract_7 = data_in__ub_pcs_lane_dist__L50[143:136];
assign pyc_extract_8 = data_in__ub_pcs_lane_dist__L50[207:200];
assign pyc_extract_9 = data_in__ub_pcs_lane_dist__L50[23:16];
assign pyc_extract_10 = data_in__ub_pcs_lane_dist__L50[87:80];
assign pyc_extract_11 = data_in__ub_pcs_lane_dist__L50[151:144];
assign pyc_extract_12 = data_in__ub_pcs_lane_dist__L50[215:208];
assign pyc_extract_13 = data_in__ub_pcs_lane_dist__L50[31:24];
assign pyc_extract_14 = data_in__ub_pcs_lane_dist__L50[95:88];
assign pyc_extract_15 = data_in__ub_pcs_lane_dist__L50[159:152];
assign pyc_extract_16 = data_in__ub_pcs_lane_dist__L50[223:216];
assign pyc_extract_17 = data_in__ub_pcs_lane_dist__L50[39:32];
assign pyc_extract_18 = data_in__ub_pcs_lane_dist__L50[103:96];
assign pyc_extract_19 = data_in__ub_pcs_lane_dist__L50[167:160];
assign pyc_extract_20 = data_in__ub_pcs_lane_dist__L50[231:224];
assign pyc_extract_21 = data_in__ub_pcs_lane_dist__L50[47:40];
assign pyc_extract_22 = data_in__ub_pcs_lane_dist__L50[111:104];
assign pyc_extract_23 = data_in__ub_pcs_lane_dist__L50[175:168];
assign pyc_extract_24 = data_in__ub_pcs_lane_dist__L50[239:232];
assign pyc_extract_25 = data_in__ub_pcs_lane_dist__L50[55:48];
assign pyc_extract_26 = data_in__ub_pcs_lane_dist__L50[119:112];
assign pyc_extract_27 = data_in__ub_pcs_lane_dist__L50[183:176];
assign pyc_extract_28 = data_in__ub_pcs_lane_dist__L50[247:240];
assign pyc_extract_29 = data_in__ub_pcs_lane_dist__L50[63:56];
assign pyc_extract_30 = data_in__ub_pcs_lane_dist__L50[127:120];
assign pyc_extract_31 = data_in__ub_pcs_lane_dist__L50[191:184];
assign pyc_extract_32 = data_in__ub_pcs_lane_dist__L50[255:248];
assign pyc_concat_33 = {pyc_extract_1, pyc_extract_2, pyc_extract_3, pyc_extract_4, pyc_extract_5, pyc_extract_6, pyc_extract_7, pyc_extract_8, pyc_extract_9, pyc_extract_10, pyc_extract_11, pyc_extract_12, pyc_extract_13, pyc_extract_14, pyc_extract_15, pyc_extract_16, pyc_extract_17, pyc_extract_18, pyc_extract_19, pyc_extract_20, pyc_extract_21, pyc_extract_22, pyc_extract_23, pyc_extract_24, pyc_extract_25, pyc_extract_26, pyc_extract_27, pyc_extract_28, pyc_extract_29, pyc_extract_30, pyc_extract_31, pyc_extract_32};
assign pyc_comb_34 = pyc_concat_33;

assign data_out = pyc_comb_34;

endmodule

