// GENERATED by pycc from pycircuit — do not edit.
// Reproduce: python3 scripts/emit_rtl.py
// compile() + pycc --emit=verilog --logic-depth=64
// TEST_HOOKS=0



// Generated by pycc (pyCircuit)
// Module: ub_pyc_rst_adapt

module ub_pyc_rst_adapt (
  input rst_n_sync,
  output rst_pyc
);

wire pyc_comb_2; // op=pyc.comb
wire pyc_not_1; // op=pyc.not
wire rst_n_sync__ub_pyc_rst_adapt__L31; // pyc.name="rst_n_sync__ub_pyc_rst_adapt__L31"

// --- Combinational (netlist)
assign rst_n_sync__ub_pyc_rst_adapt__L31 = rst_n_sync;
assign pyc_not_1 = (~rst_n_sync__ub_pyc_rst_adapt__L31);
assign pyc_comb_2 = pyc_not_1;

assign rst_pyc = pyc_comb_2;

endmodule

