// Generated by pycircuit/dll/ub_dll_retry_req_sm.py — do not hand-edit.
// pyc4.0 leaf ub_dll_retry_req_sm. TEST_HOOKS=1 (Python generation-time).
// Registers: pyc_reg semantics (sync, rst_pyc active-high, core_clk).
// SPEC: §2.6, §3.2.3, §3.3.3, §4.2, §6.3, §7, §9, §10, §11, §13.
// PORT_RST 16-cycle pulse: ub_csr; this leaf sees port_rst as sync clear.
// SPEC §10 lists no tb_inj_*/tb_obs_* for this leaf.
// HOOKS adds only gated tb_test_mode (CODING_STYLE); never intervenes.

module ub_dll_retry_req_sm #(
  parameter integer NUM_RETRY_THRESHOLD       = 15,   // SPEC §9 / §4.7.3.3 rec.; draft §13
  parameter integer NUM_PHY_REINIT_THRESHOLD  = 4,    // SPEC §9 / §4.7.3.3 rec.; draft §13
  parameter integer RETRY_WAIT_CYC            = 323,  // OPEN stub cycles; SPEC §13 / §6.3 WAIT timeout
  parameter integer CNT_W                     = 8,    // NUM_RETRY / NUM_PHY_REINIT width
  parameter integer TMR_W                     = 32     // WAIT timer width; F_CORE SPEC §4.1 / §9
) (
  input  wire                    core_clk,
  input  wire                    rst_pyc,
  input  wire                    port_rst,

  // SPEC §3.3.3 LMSM↔DLL. lmsm_retrain_ack = PHY started retrain (level).
  input  wire                    lmsm_retrain_ack,
  output wire                    dll_retrain_req,

  // OPEN leaf events: SPEC §6.3 names the condition, not a pin.
  // Parent forms start_retry = CRC-mode BCRC fail OR non-CRC FEC uncorr
  // (SPEC §6.3 / §3.3.2 / UB-DL §4.7.1). Level; sampled each core_clk.
  input  wire                    start_retry,
  input  wire                    retry_req_set_done,
  input  wire                    retry_ack_set_rx,
  input  wire                    phy_retrain_ok,

  // REGMAP STATUS.RETRY_REQ_ST[12:10] (SPEC §6.3). Never 5–7.
  output wire [2:0]              retry_req_st,

  // REGMAP / SPEC §7 sideband to ub_csr (1-cycle pulses / ERROR level).
  output wire                    retry_req_inc,
  output wire                    retry_to_inc,
  output wire                    retry_err,

  // TEST_HOOKS=1 only. SPEC §10 lists no inj/obs for RETRY_REQ_SM.
  // CODING_STYLE: gated tb_test_mode port. PRODUCT has no tb_* ports.
  input  wire                    tb_test_mode
);

  // ------------------------------------------------------------------
  // STATUS.RETRY_REQ_ST encoding (SPEC §6.3). 5–7 reserved — never driven.
  // ------------------------------------------------------------------
  localparam [2:0] ST_NORMAL  = 3'd0;
  localparam [2:0] ST_REQ     = 3'd1;
  localparam [2:0] ST_WAIT    = 3'd2;
  localparam [2:0] ST_RETRAIN = 3'd3;
  localparam [2:0] ST_ERROR   = 3'd4;

  // Combined sync reset: rst_pyc (entity) or port_rst (CSR PORT_RST).
  // SPEC §6.3: reset → NORMAL; clear NUM_RETRY and NUM_PHY_REINIT.
  // tb_test_mode is gated (CODING_STYLE) and folded & 1'b0 so it never
  // intervenes — no §10 inj/obs on this leaf; eqy vs PRODUCT holds.
  wire rst_eff = rst_pyc | port_rst | (tb_test_mode & 1'b0);

  // pyc_reg: st, num_retry, num_phy, tmr, inc pulses.
  reg [2:0]        st;
  reg [CNT_W-1:0]  num_retry;
  reg [CNT_W-1:0]  num_phy;
  reg [TMR_W-1:0]  tmr;
  reg              retry_req_inc_q;
  reg              retry_to_inc_q;

  wire [CNT_W-1:0] num_retry_inc =
      (&num_retry) ? num_retry : (num_retry + {{(CNT_W-1){1'b0}}, 1'b1});
  wire [CNT_W-1:0] num_phy_inc =
      (&num_phy) ? num_phy : (num_phy + {{(CNT_W-1){1'b0}}, 1'b1});
  wire             retry_hits_th =
      (num_retry_inc == NUM_RETRY_THRESHOLD[CNT_W-1:0]);
  wire             phy_hits_th =
      (num_phy_inc == NUM_PHY_REINIT_THRESHOLD[CNT_W-1:0]);
  wire             tmr_sat = &tmr;
  wire [TMR_W-1:0] tmr_inc = tmr_sat ? tmr : (tmr + {{(TMR_W-1){1'b0}}, 1'b1});
  wire             tmr_to  = (tmr >= RETRY_WAIT_CYC[TMR_W-1:0]);

  // ------------------------------------------------------------------
  // Next-state (SPEC §6.3 table). Priority when several fire (OPEN §6.3):
  //   rst_eff > ERROR hold > PHY retrain (lmsm_retrain_ack)
  //   > start_retry / set_done / ack / timeout / phy_retrain_ok.
  // REQ entry increments NUM_RETRY; if == TH, redirect to RETRAIN and
  // clear NUM_RETRY (SPEC §6.3 REQ→RETRAIN).
  // RETRAIN entry increments NUM_PHY_REINIT; if == TH, redirect to
  // ERROR and clear NUM_PHY_REINIT (SPEC §6.3 RETRAIN→ERROR).
  // WAIVER_RETRY_REQ_FSM_DEFAULT: illegal st → NORMAL.
  // ------------------------------------------------------------------
  reg [2:0]       st_n;
  reg [CNT_W-1:0] num_retry_n;
  reg [CNT_W-1:0] num_phy_n;
  reg [TMR_W-1:0] tmr_n;
  reg             try_enter_req;
  reg             enter_retrain;
  reg             wait_timeout;

  always @* begin
    st_n          = st;
    num_retry_n   = num_retry;
    num_phy_n     = num_phy;
    tmr_n         = tmr;
    try_enter_req = 1'b0;
    enter_retrain = 1'b0;
    wait_timeout  = 1'b0;
    case (st)
      ST_NORMAL: begin
        tmr_n = {TMR_W{1'b0}};
        if (lmsm_retrain_ack)
          enter_retrain = 1'b1;
        else if (start_retry)
          try_enter_req = 1'b1;
      end

      ST_REQ: begin
        tmr_n = {TMR_W{1'b0}};
        if (lmsm_retrain_ack) begin
          enter_retrain = 1'b1;
          num_retry_n   = {CNT_W{1'b0}}; // SPEC §6.3: REQ→RETRAIN clears NUM_RETRY
        end else if (retry_req_set_done) begin
          st_n  = ST_WAIT;
          tmr_n = {TMR_W{1'b0}};
        end
      end

      ST_WAIT: begin
        tmr_n = tmr_inc;
        if (lmsm_retrain_ack) begin
          enter_retrain = 1'b1;
        end else if (retry_ack_set_rx) begin
          st_n = ST_NORMAL;
        end else if (tmr_to) begin
          wait_timeout  = 1'b1;
          try_enter_req = 1'b1;
        end
      end

      ST_RETRAIN: begin
        tmr_n = {TMR_W{1'b0}};
        // SPEC §6.3 RETRAIN→REQ: PHY retrain succeeded.
        // Do not leave while lmsm_retrain_ack is still high.
        if (phy_retrain_ok && !lmsm_retrain_ack)
          try_enter_req = 1'b1;
      end

      ST_ERROR: begin
        tmr_n = {TMR_W{1'b0}};
        st_n  = ST_ERROR; // SPEC §6.3: only PORT_RST / entity rst → NORMAL
      end

      default: begin
        st_n        = ST_NORMAL; // WAIVER_RETRY_REQ_FSM_DEFAULT
        num_retry_n = {CNT_W{1'b0}};
        num_phy_n   = {CNT_W{1'b0}};
        tmr_n       = {TMR_W{1'b0}};
      end
    endcase

    // SPEC §6.3: increment NUM_RETRY on entry to REQ; if == TH → RETRAIN.
    if (try_enter_req) begin
      if (retry_hits_th) begin
        num_retry_n   = {CNT_W{1'b0}};
        enter_retrain = 1'b1;
      end else begin
        st_n        = ST_REQ;
        num_retry_n = num_retry_inc;
      end
    end

    // SPEC §6.3: increment NUM_PHY_REINIT on entry to RETRAIN; if == TH → ERROR.
    if (enter_retrain) begin
      if (phy_hits_th) begin
        st_n      = ST_ERROR;
        num_phy_n = {CNT_W{1'b0}};
      end else begin
        st_n      = ST_RETRAIN;
        num_phy_n = num_phy_inc;
      end
    end
  end

  wire enter_req = (st_n == ST_REQ) && (st != ST_REQ);

  // pyc_reg bank (sync; rst_eff = rst_pyc | port_rst).
  always @(posedge core_clk) begin
    if (rst_eff) begin
      st              <= ST_NORMAL;
      num_retry       <= {CNT_W{1'b0}};
      num_phy         <= {CNT_W{1'b0}};
      tmr             <= {TMR_W{1'b0}};
      retry_req_inc_q <= 1'b0;
      retry_to_inc_q  <= 1'b0;
    end else begin
      st              <= st_n;
      num_retry       <= num_retry_n;
      num_phy         <= num_phy_n;
      tmr             <= tmr_n;
      retry_req_inc_q <= enter_req;
      retry_to_inc_q  <= wait_timeout;
    end
  end

  assign retry_req_st   = st;
  assign dll_retrain_req = (st == ST_RETRAIN); // SPEC §3.3.3; level, not a pulse
  assign retry_req_inc  = retry_req_inc_q;     // REGMAP CNT_RETRY_REQ
  assign retry_to_inc   = retry_to_inc_q;      // REGMAP CNT_RETRY_TO
  assign retry_err      = (st == ST_ERROR);    // REGMAP IRQ_STATUS.RETRY_ERR

endmodule

