// Generated by pycircuit/csr/ub_csr_regs.py via pycircuit.compile() + pycc --emit=verilog
// GENERATED — edit docs/regmap/regmap.yaml
// pyc4.0 leaf ub_csr_x8_vl2_placeholder. TEST_HOOKS=0 variant=x8_vl2_placeholder.
// lukebest/pyCircuit @43cc5918e3d09ecc0c814cabef6c1384cb9980ae; backend pycc / LLVM 19.
// Attribute-driven Circuit API: W1C / saturating / WO pulse / TEST gate / csr_err.
// SPEC §2.2 / §3.2.3 / §11. Not string-templated Verilog.
`include "pyc_reg.v"



// Generated by pycc (pyCircuit)
// Module: ub_csr_x8_vl2_placeholder

module ub_csr_x8_vl2_placeholder (
  input core_clk,
  input rst_pyc,
  input csr_req,
  input csr_wr,
  input [15:0] csr_addr,
  input [31:0] csr_wdata,
  input hw_link_up,
  input hw_link_ready,
  input hw_dll_status_up,
  input [4:0] hw_lmsm_st,
  input [1:0] hw_dll_sm_st,
  input [2:0] hw_retry_req_st,
  input [1:0] hw_retry_ack_st,
  input ev_fec_uncorr,
  input ev_crc_fail,
  input ev_retry_err,
  input ev_crd_proto,
  input ev_train_fail,
  input ev_bad_vl,
  input ev_crd_uf,
  input inc_fec_uncorr,
  input inc_crc_fail,
  input inc_retry_req,
  input inc_retry_to,
  input inc_crd_of,
  input inc_crd_to,
  input inc_train_to,
  input inc_bad_vl,
  input inc_crd_uf,
  output csr_ready,
  output port_rst_pulse,
  output csr_lmsm_start,
  output csr_irq_en,
  output [6:0] csr_irq_mask,
  output [31:0] csr_port_cna,
  output [7:0] csr_tmr_scale,
  output csr_crd_to_dis,
  output [7:0] csr_am_ivl_scale,
  output irq,
  output csr_rvalid,
  output [31:0] csr_rdata,
  output csr_err
);

wire [4:0] cnt_ctrl_port_rst; // pyc.name="cnt_ctrl_port_rst"
wire [4:0] cnt_ctrl_port_rst__next; // pyc.name="cnt_ctrl_port_rst__next"
wire csr_err_q; // pyc.name="csr_err_q"
wire csr_err_q__next; // pyc.name="csr_err_q__next"
wire [31:0] csr_rdata_q; // pyc.name="csr_rdata_q"
wire [31:0] csr_rdata_q__next; // pyc.name="csr_rdata_q__next"
wire csr_rvalid_q; // pyc.name="csr_rvalid_q"
wire csr_rvalid_q__next; // pyc.name="csr_rvalid_q__next"
wire [31:0] pyc_add_328; // op=pyc.add
wire [31:0] pyc_add_335; // op=pyc.add
wire [31:0] pyc_add_342; // op=pyc.add
wire [31:0] pyc_add_349; // op=pyc.add
wire [31:0] pyc_add_356; // op=pyc.add
wire [31:0] pyc_add_363; // op=pyc.add
wire [31:0] pyc_add_370; // op=pyc.add
wire [31:0] pyc_add_377; // op=pyc.add
wire [31:0] pyc_add_384; // op=pyc.add
wire pyc_and_100; // op=pyc.and
wire pyc_and_102; // op=pyc.and
wire pyc_and_104; // op=pyc.and
wire pyc_and_106; // op=pyc.and
wire pyc_and_108; // op=pyc.and
wire pyc_and_110; // op=pyc.and
wire pyc_and_112; // op=pyc.and
wire pyc_and_114; // op=pyc.and
wire pyc_and_116; // op=pyc.and
wire pyc_and_118; // op=pyc.and
wire pyc_and_146; // op=pyc.and
wire pyc_and_239; // op=pyc.and
wire pyc_and_240; // op=pyc.and
wire pyc_and_241; // op=pyc.and
wire pyc_and_242; // op=pyc.and
wire pyc_and_243; // op=pyc.and
wire pyc_and_245; // op=pyc.and
wire pyc_and_247; // op=pyc.and
wire pyc_and_249; // op=pyc.and
wire pyc_and_251; // op=pyc.and
wire pyc_and_253; // op=pyc.and
wire pyc_and_255; // op=pyc.and
wire pyc_and_257; // op=pyc.and
wire pyc_and_259; // op=pyc.and
wire pyc_and_261; // op=pyc.and
wire pyc_and_290; // op=pyc.and
wire pyc_and_293; // op=pyc.and
wire pyc_and_295; // op=pyc.and
wire pyc_and_298; // op=pyc.and
wire pyc_and_300; // op=pyc.and
wire pyc_and_303; // op=pyc.and
wire pyc_and_305; // op=pyc.and
wire pyc_and_308; // op=pyc.and
wire pyc_and_310; // op=pyc.and
wire pyc_and_313; // op=pyc.and
wire pyc_and_315; // op=pyc.and
wire pyc_and_318; // op=pyc.and
wire pyc_and_320; // op=pyc.and
wire pyc_and_323; // op=pyc.and
wire pyc_and_327; // op=pyc.and
wire pyc_and_334; // op=pyc.and
wire pyc_and_341; // op=pyc.and
wire pyc_and_348; // op=pyc.and
wire pyc_and_355; // op=pyc.and
wire pyc_and_362; // op=pyc.and
wire pyc_and_369; // op=pyc.and
wire pyc_and_376; // op=pyc.and
wire pyc_and_383; // op=pyc.and
wire pyc_and_388; // op=pyc.and
wire [6:0] pyc_and_398; // op=pyc.and
wire pyc_and_401; // op=pyc.and
wire pyc_and_452; // op=pyc.and
wire pyc_and_459; // op=pyc.and
wire pyc_and_464; // op=pyc.and
wire pyc_and_56; // op=pyc.and
wire pyc_and_61; // op=pyc.and
wire pyc_and_62; // op=pyc.and
wire pyc_and_64; // op=pyc.and
wire pyc_and_66; // op=pyc.and
wire pyc_and_68; // op=pyc.and
wire pyc_and_70; // op=pyc.and
wire pyc_and_72; // op=pyc.and
wire pyc_and_74; // op=pyc.and
wire pyc_and_76; // op=pyc.and
wire pyc_and_78; // op=pyc.and
wire pyc_and_80; // op=pyc.and
wire pyc_and_82; // op=pyc.and
wire pyc_and_84; // op=pyc.and
wire pyc_and_86; // op=pyc.and
wire pyc_and_88; // op=pyc.and
wire pyc_and_90; // op=pyc.and
wire pyc_and_92; // op=pyc.and
wire pyc_and_94; // op=pyc.and
wire pyc_and_96; // op=pyc.and
wire pyc_and_98; // op=pyc.and
wire pyc_comb_147; // op=pyc.comb
wire pyc_comb_148; // op=pyc.comb
wire [6:0] pyc_comb_149; // op=pyc.comb
wire [31:0] pyc_comb_150; // op=pyc.comb
wire [7:0] pyc_comb_151; // op=pyc.comb
wire [4:0] pyc_comb_152; // op=pyc.comb
wire [31:0] pyc_comb_153; // op=pyc.comb
wire [31:0] pyc_comb_154; // op=pyc.comb
wire [4:0] pyc_comb_155; // op=pyc.comb
wire [4:0] pyc_comb_156; // op=pyc.comb
wire [6:0] pyc_comb_157; // op=pyc.comb
wire [28:0] pyc_comb_158; // op=pyc.comb
wire [16:0] pyc_comb_159; // op=pyc.comb
wire [24:0] pyc_comb_160; // op=pyc.comb
wire [31:0] pyc_comb_161; // op=pyc.comb
wire [31:0] pyc_comb_162; // op=pyc.comb
wire [31:0] pyc_comb_163; // op=pyc.comb
wire [31:0] pyc_comb_164; // op=pyc.comb
wire [31:0] pyc_comb_165; // op=pyc.comb
wire [31:0] pyc_comb_166; // op=pyc.comb
wire [31:0] pyc_comb_167; // op=pyc.comb
wire [31:0] pyc_comb_168; // op=pyc.comb
wire pyc_comb_169; // op=pyc.comb
wire pyc_comb_170; // op=pyc.comb
wire pyc_comb_171; // op=pyc.comb
wire pyc_comb_172; // op=pyc.comb
wire pyc_comb_173; // op=pyc.comb
wire pyc_comb_174; // op=pyc.comb
wire pyc_comb_175; // op=pyc.comb
wire pyc_comb_176; // op=pyc.comb
wire pyc_comb_177; // op=pyc.comb
wire pyc_comb_178; // op=pyc.comb
wire pyc_comb_179; // op=pyc.comb
wire pyc_comb_180; // op=pyc.comb
wire pyc_comb_181; // op=pyc.comb
wire pyc_comb_182; // op=pyc.comb
wire pyc_comb_183; // op=pyc.comb
wire pyc_comb_184; // op=pyc.comb
wire pyc_comb_185; // op=pyc.comb
wire pyc_comb_186; // op=pyc.comb
wire pyc_comb_187; // op=pyc.comb
wire pyc_comb_188; // op=pyc.comb
wire pyc_comb_189; // op=pyc.comb
wire pyc_comb_190; // op=pyc.comb
wire pyc_comb_191; // op=pyc.comb
wire pyc_comb_192; // op=pyc.comb
wire pyc_comb_193; // op=pyc.comb
wire pyc_comb_194; // op=pyc.comb
wire pyc_comb_195; // op=pyc.comb
wire [1:0] pyc_comb_198; // op=pyc.comb
wire [1:0] pyc_comb_199; // op=pyc.comb
wire pyc_comb_203; // op=pyc.comb
wire pyc_comb_204; // op=pyc.comb
wire [6:0] pyc_comb_212; // op=pyc.comb
wire [6:0] pyc_comb_213; // op=pyc.comb
wire pyc_comb_222; // op=pyc.comb
wire pyc_comb_223; // op=pyc.comb
wire pyc_comb_224; // op=pyc.comb
wire pyc_comb_225; // op=pyc.comb
wire pyc_comb_226; // op=pyc.comb
wire pyc_comb_227; // op=pyc.comb
wire pyc_comb_228; // op=pyc.comb
wire [4:0] pyc_comb_263; // op=pyc.comb
wire pyc_comb_264; // op=pyc.comb
wire pyc_comb_265; // op=pyc.comb
wire pyc_comb_266; // op=pyc.comb
wire pyc_comb_267; // op=pyc.comb
wire pyc_comb_268; // op=pyc.comb
wire pyc_comb_269; // op=pyc.comb
wire pyc_comb_270; // op=pyc.comb
wire pyc_comb_271; // op=pyc.comb
wire pyc_comb_272; // op=pyc.comb
wire pyc_comb_273; // op=pyc.comb
wire pyc_comb_274; // op=pyc.comb
wire pyc_comb_275; // op=pyc.comb
wire pyc_comb_276; // op=pyc.comb
wire pyc_comb_277; // op=pyc.comb
wire pyc_comb_278; // op=pyc.comb
wire pyc_comb_279; // op=pyc.comb
wire pyc_comb_280; // op=pyc.comb
wire pyc_comb_281; // op=pyc.comb
wire pyc_comb_282; // op=pyc.comb
wire pyc_comb_283; // op=pyc.comb
wire pyc_comb_284; // op=pyc.comb
wire [6:0] pyc_comb_288; // op=pyc.comb
wire pyc_comb_294; // op=pyc.comb
wire pyc_comb_299; // op=pyc.comb
wire pyc_comb_304; // op=pyc.comb
wire pyc_comb_309; // op=pyc.comb
wire pyc_comb_314; // op=pyc.comb
wire pyc_comb_319; // op=pyc.comb
wire pyc_comb_324; // op=pyc.comb
wire [31:0] pyc_comb_331; // op=pyc.comb
wire [31:0] pyc_comb_338; // op=pyc.comb
wire [31:0] pyc_comb_345; // op=pyc.comb
wire [31:0] pyc_comb_352; // op=pyc.comb
wire [31:0] pyc_comb_359; // op=pyc.comb
wire [31:0] pyc_comb_366; // op=pyc.comb
wire [31:0] pyc_comb_373; // op=pyc.comb
wire [31:0] pyc_comb_380; // op=pyc.comb
wire [31:0] pyc_comb_387; // op=pyc.comb
wire pyc_comb_394; // op=pyc.comb
wire [4:0] pyc_comb_395; // op=pyc.comb
wire pyc_comb_454; // op=pyc.comb
wire [31:0] pyc_comb_455; // op=pyc.comb
wire pyc_comb_456; // op=pyc.comb
wire pyc_comb_460; // op=pyc.comb
wire pyc_comb_461; // op=pyc.comb
wire pyc_comb_465; // op=pyc.comb
wire pyc_comb_466; // op=pyc.comb
wire [1:0] pyc_concat_196; // op=pyc.concat
wire [1:0] pyc_concat_197; // op=pyc.concat
wire [6:0] pyc_concat_210; // op=pyc.concat
wire [6:0] pyc_concat_211; // op=pyc.concat
wire [6:0] pyc_concat_396; // op=pyc.concat
wire [31:0] pyc_concat_402; // op=pyc.concat
wire [31:0] pyc_concat_403; // op=pyc.concat
wire [31:0] pyc_concat_404; // op=pyc.concat
wire [31:0] pyc_concat_405; // op=pyc.concat
wire pyc_constant_1; // op=pyc.constant
wire [15:0] pyc_constant_10; // op=pyc.constant
wire [15:0] pyc_constant_11; // op=pyc.constant
wire [15:0] pyc_constant_12; // op=pyc.constant
wire [15:0] pyc_constant_13; // op=pyc.constant
wire [15:0] pyc_constant_14; // op=pyc.constant
wire [15:0] pyc_constant_15; // op=pyc.constant
wire [15:0] pyc_constant_16; // op=pyc.constant
wire [15:0] pyc_constant_17; // op=pyc.constant
wire [15:0] pyc_constant_18; // op=pyc.constant
wire [15:0] pyc_constant_19; // op=pyc.constant
wire [1:0] pyc_constant_2; // op=pyc.constant
wire [15:0] pyc_constant_20; // op=pyc.constant
wire [15:0] pyc_constant_21; // op=pyc.constant
wire [15:0] pyc_constant_22; // op=pyc.constant
wire [15:0] pyc_constant_23; // op=pyc.constant
wire [15:0] pyc_constant_24; // op=pyc.constant
wire [15:0] pyc_constant_25; // op=pyc.constant
wire [15:0] pyc_constant_26; // op=pyc.constant
wire [15:0] pyc_constant_27; // op=pyc.constant
wire [15:0] pyc_constant_28; // op=pyc.constant
wire [15:0] pyc_constant_29; // op=pyc.constant
wire [15:0] pyc_constant_3; // op=pyc.constant
wire [15:0] pyc_constant_30; // op=pyc.constant
wire [15:0] pyc_constant_31; // op=pyc.constant
wire [15:0] pyc_constant_32; // op=pyc.constant
wire pyc_constant_33; // op=pyc.constant
wire [6:0] pyc_constant_34; // op=pyc.constant
wire [31:0] pyc_constant_35; // op=pyc.constant
wire [7:0] pyc_constant_36; // op=pyc.constant
wire [4:0] pyc_constant_37; // op=pyc.constant
wire [31:0] pyc_constant_38; // op=pyc.constant
wire [31:0] pyc_constant_39; // op=pyc.constant
wire [15:0] pyc_constant_4; // op=pyc.constant
wire [4:0] pyc_constant_40; // op=pyc.constant
wire [4:0] pyc_constant_41; // op=pyc.constant
wire [6:0] pyc_constant_42; // op=pyc.constant
wire [28:0] pyc_constant_43; // op=pyc.constant
wire [16:0] pyc_constant_44; // op=pyc.constant
wire [24:0] pyc_constant_45; // op=pyc.constant
wire [31:0] pyc_constant_46; // op=pyc.constant
wire [31:0] pyc_constant_47; // op=pyc.constant
wire [31:0] pyc_constant_48; // op=pyc.constant
wire [31:0] pyc_constant_49; // op=pyc.constant
wire [15:0] pyc_constant_5; // op=pyc.constant
wire [31:0] pyc_constant_50; // op=pyc.constant
wire [31:0] pyc_constant_51; // op=pyc.constant
wire [31:0] pyc_constant_52; // op=pyc.constant
wire [31:0] pyc_constant_53; // op=pyc.constant
wire [15:0] pyc_constant_6; // op=pyc.constant
wire [15:0] pyc_constant_7; // op=pyc.constant
wire [15:0] pyc_constant_8; // op=pyc.constant
wire [15:0] pyc_constant_9; // op=pyc.constant
wire pyc_eq_101; // op=pyc.eq
wire pyc_eq_103; // op=pyc.eq
wire pyc_eq_105; // op=pyc.eq
wire pyc_eq_107; // op=pyc.eq
wire pyc_eq_109; // op=pyc.eq
wire pyc_eq_111; // op=pyc.eq
wire pyc_eq_113; // op=pyc.eq
wire pyc_eq_115; // op=pyc.eq
wire pyc_eq_117; // op=pyc.eq
wire pyc_eq_325; // op=pyc.eq
wire pyc_eq_332; // op=pyc.eq
wire pyc_eq_339; // op=pyc.eq
wire pyc_eq_346; // op=pyc.eq
wire pyc_eq_353; // op=pyc.eq
wire pyc_eq_360; // op=pyc.eq
wire pyc_eq_367; // op=pyc.eq
wire pyc_eq_374; // op=pyc.eq
wire pyc_eq_381; // op=pyc.eq
wire pyc_eq_389; // op=pyc.eq
wire pyc_eq_399; // op=pyc.eq
wire pyc_eq_55; // op=pyc.eq
wire pyc_eq_63; // op=pyc.eq
wire pyc_eq_65; // op=pyc.eq
wire pyc_eq_67; // op=pyc.eq
wire pyc_eq_69; // op=pyc.eq
wire pyc_eq_71; // op=pyc.eq
wire pyc_eq_73; // op=pyc.eq
wire pyc_eq_75; // op=pyc.eq
wire pyc_eq_77; // op=pyc.eq
wire pyc_eq_79; // op=pyc.eq
wire pyc_eq_81; // op=pyc.eq
wire pyc_eq_83; // op=pyc.eq
wire pyc_eq_85; // op=pyc.eq
wire pyc_eq_87; // op=pyc.eq
wire pyc_eq_89; // op=pyc.eq
wire pyc_eq_91; // op=pyc.eq
wire pyc_eq_93; // op=pyc.eq
wire pyc_eq_95; // op=pyc.eq
wire pyc_eq_97; // op=pyc.eq
wire pyc_eq_99; // op=pyc.eq
wire pyc_extract_201; // op=pyc.extract
wire pyc_extract_202; // op=pyc.extract
wire pyc_extract_215; // op=pyc.extract
wire pyc_extract_216; // op=pyc.extract
wire pyc_extract_217; // op=pyc.extract
wire pyc_extract_218; // op=pyc.extract
wire pyc_extract_219; // op=pyc.extract
wire pyc_extract_220; // op=pyc.extract
wire pyc_extract_221; // op=pyc.extract
wire pyc_extract_244; // op=pyc.extract
wire pyc_extract_246; // op=pyc.extract
wire pyc_extract_248; // op=pyc.extract
wire pyc_extract_250; // op=pyc.extract
wire pyc_extract_252; // op=pyc.extract
wire pyc_extract_254; // op=pyc.extract
wire pyc_extract_256; // op=pyc.extract
wire pyc_extract_258; // op=pyc.extract
wire pyc_extract_260; // op=pyc.extract
wire [6:0] pyc_extract_286; // op=pyc.extract
wire [1:0] pyc_extract_54; // op=pyc.extract
wire pyc_mux_262; // op=pyc.mux
wire pyc_mux_285; // op=pyc.mux
wire [6:0] pyc_mux_287; // op=pyc.mux
wire [31:0] pyc_mux_289; // op=pyc.mux
wire [31:0] pyc_mux_329; // op=pyc.mux
wire [31:0] pyc_mux_330; // op=pyc.mux
wire [31:0] pyc_mux_336; // op=pyc.mux
wire [31:0] pyc_mux_337; // op=pyc.mux
wire [31:0] pyc_mux_343; // op=pyc.mux
wire [31:0] pyc_mux_344; // op=pyc.mux
wire [31:0] pyc_mux_350; // op=pyc.mux
wire [31:0] pyc_mux_351; // op=pyc.mux
wire [31:0] pyc_mux_357; // op=pyc.mux
wire [31:0] pyc_mux_358; // op=pyc.mux
wire [31:0] pyc_mux_364; // op=pyc.mux
wire [31:0] pyc_mux_365; // op=pyc.mux
wire [31:0] pyc_mux_371; // op=pyc.mux
wire [31:0] pyc_mux_372; // op=pyc.mux
wire [31:0] pyc_mux_378; // op=pyc.mux
wire [31:0] pyc_mux_379; // op=pyc.mux
wire [31:0] pyc_mux_385; // op=pyc.mux
wire [31:0] pyc_mux_386; // op=pyc.mux
wire [4:0] pyc_mux_392; // op=pyc.mux
wire [4:0] pyc_mux_393; // op=pyc.mux
wire [31:0] pyc_mux_406; // op=pyc.mux
wire [31:0] pyc_mux_407; // op=pyc.mux
wire [31:0] pyc_mux_408; // op=pyc.mux
wire [31:0] pyc_mux_409; // op=pyc.mux
wire [31:0] pyc_mux_410; // op=pyc.mux
wire [31:0] pyc_mux_411; // op=pyc.mux
wire [31:0] pyc_mux_412; // op=pyc.mux
wire [31:0] pyc_mux_413; // op=pyc.mux
wire [31:0] pyc_mux_414; // op=pyc.mux
wire [31:0] pyc_mux_415; // op=pyc.mux
wire [31:0] pyc_mux_416; // op=pyc.mux
wire [31:0] pyc_mux_417; // op=pyc.mux
wire [31:0] pyc_mux_418; // op=pyc.mux
wire [31:0] pyc_mux_419; // op=pyc.mux
wire [31:0] pyc_mux_420; // op=pyc.mux
wire [31:0] pyc_mux_421; // op=pyc.mux
wire [31:0] pyc_mux_422; // op=pyc.mux
wire [31:0] pyc_mux_423; // op=pyc.mux
wire [31:0] pyc_mux_424; // op=pyc.mux
wire [31:0] pyc_mux_425; // op=pyc.mux
wire [31:0] pyc_mux_426; // op=pyc.mux
wire [31:0] pyc_mux_427; // op=pyc.mux
wire pyc_not_292; // op=pyc.not
wire pyc_not_297; // op=pyc.not
wire pyc_not_302; // op=pyc.not
wire pyc_not_307; // op=pyc.not
wire pyc_not_312; // op=pyc.not
wire pyc_not_317; // op=pyc.not
wire pyc_not_322; // op=pyc.not
wire pyc_not_326; // op=pyc.not
wire pyc_not_333; // op=pyc.not
wire pyc_not_340; // op=pyc.not
wire pyc_not_347; // op=pyc.not
wire pyc_not_354; // op=pyc.not
wire pyc_not_361; // op=pyc.not
wire pyc_not_368; // op=pyc.not
wire pyc_not_375; // op=pyc.not
wire pyc_not_382; // op=pyc.not
wire pyc_not_390; // op=pyc.not
wire [6:0] pyc_not_397; // op=pyc.not
wire pyc_not_400; // op=pyc.not
wire pyc_not_449; // op=pyc.not
wire pyc_not_450; // op=pyc.not
wire pyc_not_451; // op=pyc.not
wire pyc_not_458; // op=pyc.not
wire pyc_not_58; // op=pyc.not
wire pyc_not_60; // op=pyc.not
wire pyc_or_119; // op=pyc.or
wire pyc_or_120; // op=pyc.or
wire pyc_or_121; // op=pyc.or
wire pyc_or_122; // op=pyc.or
wire pyc_or_123; // op=pyc.or
wire pyc_or_124; // op=pyc.or
wire pyc_or_125; // op=pyc.or
wire pyc_or_126; // op=pyc.or
wire pyc_or_127; // op=pyc.or
wire pyc_or_128; // op=pyc.or
wire pyc_or_129; // op=pyc.or
wire pyc_or_130; // op=pyc.or
wire pyc_or_131; // op=pyc.or
wire pyc_or_132; // op=pyc.or
wire pyc_or_133; // op=pyc.or
wire pyc_or_134; // op=pyc.or
wire pyc_or_135; // op=pyc.or
wire pyc_or_136; // op=pyc.or
wire pyc_or_137; // op=pyc.or
wire pyc_or_138; // op=pyc.or
wire pyc_or_139; // op=pyc.or
wire pyc_or_140; // op=pyc.or
wire pyc_or_141; // op=pyc.or
wire pyc_or_142; // op=pyc.or
wire pyc_or_143; // op=pyc.or
wire pyc_or_144; // op=pyc.or
wire pyc_or_145; // op=pyc.or
wire pyc_or_291; // op=pyc.or
wire pyc_or_296; // op=pyc.or
wire pyc_or_301; // op=pyc.or
wire pyc_or_306; // op=pyc.or
wire pyc_or_311; // op=pyc.or
wire pyc_or_316; // op=pyc.or
wire pyc_or_321; // op=pyc.or
wire [31:0] pyc_or_428; // op=pyc.or
wire [31:0] pyc_or_429; // op=pyc.or
wire [31:0] pyc_or_430; // op=pyc.or
wire [31:0] pyc_or_431; // op=pyc.or
wire [31:0] pyc_or_432; // op=pyc.or
wire [31:0] pyc_or_433; // op=pyc.or
wire [31:0] pyc_or_434; // op=pyc.or
wire [31:0] pyc_or_435; // op=pyc.or
wire [31:0] pyc_or_436; // op=pyc.or
wire [31:0] pyc_or_437; // op=pyc.or
wire [31:0] pyc_or_438; // op=pyc.or
wire [31:0] pyc_or_439; // op=pyc.or
wire [31:0] pyc_or_440; // op=pyc.or
wire [31:0] pyc_or_441; // op=pyc.or
wire [31:0] pyc_or_442; // op=pyc.or
wire [31:0] pyc_or_443; // op=pyc.or
wire [31:0] pyc_or_444; // op=pyc.or
wire [31:0] pyc_or_445; // op=pyc.or
wire [31:0] pyc_or_446; // op=pyc.or
wire [31:0] pyc_or_447; // op=pyc.or
wire [31:0] pyc_or_448; // op=pyc.or
wire pyc_or_453; // op=pyc.or
wire [1:0] pyc_reg_200; // op=pyc.reg
wire [6:0] pyc_reg_205; // op=pyc.reg
wire [31:0] pyc_reg_206; // op=pyc.reg
wire [7:0] pyc_reg_207; // op=pyc.reg
wire pyc_reg_208; // op=pyc.reg
wire [7:0] pyc_reg_209; // op=pyc.reg
wire [6:0] pyc_reg_214; // op=pyc.reg
wire [31:0] pyc_reg_229; // op=pyc.reg
wire [31:0] pyc_reg_230; // op=pyc.reg
wire [31:0] pyc_reg_231; // op=pyc.reg
wire [31:0] pyc_reg_232; // op=pyc.reg
wire [31:0] pyc_reg_233; // op=pyc.reg
wire [31:0] pyc_reg_234; // op=pyc.reg
wire [31:0] pyc_reg_235; // op=pyc.reg
wire [31:0] pyc_reg_236; // op=pyc.reg
wire [31:0] pyc_reg_237; // op=pyc.reg
wire [4:0] pyc_reg_238; // op=pyc.reg
wire pyc_reg_457; // op=pyc.reg
wire [31:0] pyc_reg_462; // op=pyc.reg
wire pyc_reg_463; // op=pyc.reg
wire [4:0] pyc_sub_391; // op=pyc.sub
wire pyc_ult_57; // op=pyc.ult
wire pyc_ult_59; // op=pyc.ult
wire [31:0] q_cnt_bad_vl_count; // pyc.name="q_cnt_bad_vl_count"
wire [31:0] q_cnt_bad_vl_count__next; // pyc.name="q_cnt_bad_vl_count__next"
wire [31:0] q_cnt_crc_fail_count; // pyc.name="q_cnt_crc_fail_count"
wire [31:0] q_cnt_crc_fail_count__next; // pyc.name="q_cnt_crc_fail_count__next"
wire [31:0] q_cnt_crd_of_count; // pyc.name="q_cnt_crd_of_count"
wire [31:0] q_cnt_crd_of_count__next; // pyc.name="q_cnt_crd_of_count__next"
wire [31:0] q_cnt_crd_to_count; // pyc.name="q_cnt_crd_to_count"
wire [31:0] q_cnt_crd_to_count__next; // pyc.name="q_cnt_crd_to_count__next"
wire [31:0] q_cnt_crd_uf_count; // pyc.name="q_cnt_crd_uf_count"
wire [31:0] q_cnt_crd_uf_count__next; // pyc.name="q_cnt_crd_uf_count__next"
wire [31:0] q_cnt_fec_uncorr_count; // pyc.name="q_cnt_fec_uncorr_count"
wire [31:0] q_cnt_fec_uncorr_count__next; // pyc.name="q_cnt_fec_uncorr_count__next"
wire [31:0] q_cnt_retry_req_count; // pyc.name="q_cnt_retry_req_count"
wire [31:0] q_cnt_retry_req_count__next; // pyc.name="q_cnt_retry_req_count__next"
wire [31:0] q_cnt_retry_to_count; // pyc.name="q_cnt_retry_to_count"
wire [31:0] q_cnt_retry_to_count__next; // pyc.name="q_cnt_retry_to_count__next"
wire [31:0] q_cnt_train_to_count; // pyc.name="q_cnt_train_to_count"
wire [31:0] q_cnt_train_to_count__next; // pyc.name="q_cnt_train_to_count__next"
wire q_crd_to_dis_dis; // pyc.name="q_crd_to_dis_dis"
wire q_crd_to_dis_dis__next; // pyc.name="q_crd_to_dis_dis__next"
wire q_ctrl_irq_en; // pyc.name="q_ctrl_irq_en"
wire q_ctrl_irq_en__next; // pyc.name="q_ctrl_irq_en__next"
wire q_ctrl_lmsm_start; // pyc.name="q_ctrl_lmsm_start"
wire q_ctrl_lmsm_start__next; // pyc.name="q_ctrl_lmsm_start__next"
wire [6:0] q_irq_mask_mask; // pyc.name="q_irq_mask_mask"
wire [6:0] q_irq_mask_mask__next; // pyc.name="q_irq_mask_mask__next"
wire q_irq_status_bad_vl; // pyc.name="q_irq_status_bad_vl"
wire q_irq_status_bad_vl__next; // pyc.name="q_irq_status_bad_vl__next"
wire q_irq_status_crc_fail; // pyc.name="q_irq_status_crc_fail"
wire q_irq_status_crc_fail__next; // pyc.name="q_irq_status_crc_fail__next"
wire q_irq_status_crd_proto; // pyc.name="q_irq_status_crd_proto"
wire q_irq_status_crd_proto__next; // pyc.name="q_irq_status_crd_proto__next"
wire q_irq_status_crd_uf; // pyc.name="q_irq_status_crd_uf"
wire q_irq_status_crd_uf__next; // pyc.name="q_irq_status_crd_uf__next"
wire q_irq_status_fec_uncorr; // pyc.name="q_irq_status_fec_uncorr"
wire q_irq_status_fec_uncorr__next; // pyc.name="q_irq_status_fec_uncorr__next"
wire q_irq_status_retry_err; // pyc.name="q_irq_status_retry_err"
wire q_irq_status_retry_err__next; // pyc.name="q_irq_status_retry_err__next"
wire q_irq_status_train_fail; // pyc.name="q_irq_status_train_fail"
wire q_irq_status_train_fail__next; // pyc.name="q_irq_status_train_fail__next"
wire [7:0] q_lmsm_tmr_scale_scale; // pyc.name="q_lmsm_tmr_scale_scale"
wire [7:0] q_lmsm_tmr_scale_scale__next; // pyc.name="q_lmsm_tmr_scale_scale__next"
wire [7:0] q_pcs_tx_test_am_ivl_scale; // pyc.name="q_pcs_tx_test_am_ivl_scale"
wire [7:0] q_pcs_tx_test_am_ivl_scale__next; // pyc.name="q_pcs_tx_test_am_ivl_scale__next"
wire [31:0] q_port_cna_cna; // pyc.name="q_port_cna_cna"
wire [31:0] q_port_cna_cna__next; // pyc.name="q_port_cna_cna__next"

// --- Combinational (netlist)
assign csr_rdata_q = pyc_reg_462;
assign pyc_constant_1 = 1'd0;
assign pyc_constant_2 = 2'd0;
assign pyc_constant_3 = 16'd768;
assign pyc_constant_4 = 16'd1023;
assign pyc_constant_5 = 16'd0;
assign pyc_constant_6 = 16'd4;
assign pyc_constant_7 = 16'd8;
assign pyc_constant_8 = 16'd12;
assign pyc_constant_9 = 16'd16;
assign pyc_constant_10 = 16'd256;
assign pyc_constant_11 = 16'd260;
assign pyc_constant_12 = 16'd264;
assign pyc_constant_13 = 16'd268;
assign pyc_constant_14 = 16'd272;
assign pyc_constant_15 = 16'd276;
assign pyc_constant_16 = 16'd280;
assign pyc_constant_17 = 16'd284;
assign pyc_constant_18 = 16'd512;
assign pyc_constant_19 = 16'd516;
assign pyc_constant_20 = 16'd520;
assign pyc_constant_21 = 16'd524;
assign pyc_constant_22 = 16'd528;
assign pyc_constant_23 = 16'd532;
assign pyc_constant_24 = 16'd536;
assign pyc_constant_25 = 16'd540;
assign pyc_constant_26 = 16'd544;
assign pyc_constant_27 = 16'd548;
assign pyc_constant_28 = 16'd4096;
assign pyc_constant_29 = 16'd4352;
assign pyc_constant_30 = 16'd4608;
assign pyc_constant_31 = 16'd7680;
assign pyc_constant_32 = 16'd7936;
assign pyc_constant_33 = 1'd1;
assign pyc_constant_34 = 7'd127;
assign pyc_constant_35 = 32'd0;
assign pyc_constant_36 = 8'd0;
assign pyc_constant_37 = 5'd0;
assign pyc_constant_38 = 32'd4294967295;
assign pyc_constant_39 = 32'd1;
assign pyc_constant_40 = 5'd16;
assign pyc_constant_41 = 5'd1;
assign pyc_constant_42 = 7'd0;
assign pyc_constant_43 = 29'd0;
assign pyc_constant_44 = 17'd0;
assign pyc_constant_45 = 25'd0;
assign pyc_constant_46 = 32'd532994;
assign pyc_constant_47 = 32'd10;
assign pyc_constant_48 = 32'd2359330;
assign pyc_constant_49 = 32'd68092160;
assign pyc_constant_50 = 32'd67109504;
assign pyc_constant_51 = 32'd393217;
assign pyc_constant_52 = 32'd3;
assign pyc_constant_53 = 32'd18;
assign pyc_extract_54 = csr_addr[1:0];
assign pyc_eq_55 = (pyc_extract_54 == pyc_constant_2);
assign pyc_and_56 = (csr_req & csr_wr);
assign pyc_ult_57 = (csr_addr < pyc_constant_3);
assign pyc_not_58 = (~pyc_ult_57);
assign pyc_ult_59 = (pyc_constant_4 < csr_addr);
assign pyc_not_60 = (~pyc_ult_59);
assign pyc_and_61 = (pyc_not_58 & pyc_not_60);
assign pyc_and_62 = (pyc_and_61 & pyc_eq_55);
assign pyc_eq_63 = (csr_addr == pyc_constant_5);
assign pyc_and_64 = (pyc_eq_55 & pyc_eq_63);
assign pyc_eq_65 = (csr_addr == pyc_constant_6);
assign pyc_and_66 = (pyc_eq_55 & pyc_eq_65);
assign pyc_eq_67 = (csr_addr == pyc_constant_7);
assign pyc_and_68 = (pyc_eq_55 & pyc_eq_67);
assign pyc_eq_69 = (csr_addr == pyc_constant_8);
assign pyc_and_70 = (pyc_eq_55 & pyc_eq_69);
assign pyc_eq_71 = (csr_addr == pyc_constant_9);
assign pyc_and_72 = (pyc_eq_55 & pyc_eq_71);
assign pyc_eq_73 = (csr_addr == pyc_constant_10);
assign pyc_and_74 = (pyc_eq_55 & pyc_eq_73);
assign pyc_eq_75 = (csr_addr == pyc_constant_11);
assign pyc_and_76 = (pyc_eq_55 & pyc_eq_75);
assign pyc_eq_77 = (csr_addr == pyc_constant_12);
assign pyc_and_78 = (pyc_eq_55 & pyc_eq_77);
assign pyc_eq_79 = (csr_addr == pyc_constant_13);
assign pyc_and_80 = (pyc_eq_55 & pyc_eq_79);
assign pyc_eq_81 = (csr_addr == pyc_constant_14);
assign pyc_and_82 = (pyc_eq_55 & pyc_eq_81);
assign pyc_eq_83 = (csr_addr == pyc_constant_15);
assign pyc_and_84 = (pyc_eq_55 & pyc_eq_83);
assign pyc_eq_85 = (csr_addr == pyc_constant_16);
assign pyc_and_86 = (pyc_eq_55 & pyc_eq_85);
assign pyc_eq_87 = (csr_addr == pyc_constant_17);
assign pyc_and_88 = (pyc_eq_55 & pyc_eq_87);
assign pyc_eq_89 = (csr_addr == pyc_constant_18);
assign pyc_and_90 = (pyc_eq_55 & pyc_eq_89);
assign pyc_eq_91 = (csr_addr == pyc_constant_19);
assign pyc_and_92 = (pyc_eq_55 & pyc_eq_91);
assign pyc_eq_93 = (csr_addr == pyc_constant_20);
assign pyc_and_94 = (pyc_eq_55 & pyc_eq_93);
assign pyc_eq_95 = (csr_addr == pyc_constant_21);
assign pyc_and_96 = (pyc_eq_55 & pyc_eq_95);
assign pyc_eq_97 = (csr_addr == pyc_constant_22);
assign pyc_and_98 = (pyc_eq_55 & pyc_eq_97);
assign pyc_eq_99 = (csr_addr == pyc_constant_23);
assign pyc_and_100 = (pyc_eq_55 & pyc_eq_99);
assign pyc_eq_101 = (csr_addr == pyc_constant_24);
assign pyc_and_102 = (pyc_eq_55 & pyc_eq_101);
assign pyc_eq_103 = (csr_addr == pyc_constant_25);
assign pyc_and_104 = (pyc_eq_55 & pyc_eq_103);
assign pyc_eq_105 = (csr_addr == pyc_constant_26);
assign pyc_and_106 = (pyc_eq_55 & pyc_eq_105);
assign pyc_eq_107 = (csr_addr == pyc_constant_27);
assign pyc_and_108 = (pyc_eq_55 & pyc_eq_107);
assign pyc_eq_109 = (csr_addr == pyc_constant_28);
assign pyc_and_110 = (pyc_eq_55 & pyc_eq_109);
assign pyc_eq_111 = (csr_addr == pyc_constant_29);
assign pyc_and_112 = (pyc_eq_55 & pyc_eq_111);
assign pyc_eq_113 = (csr_addr == pyc_constant_30);
assign pyc_and_114 = (pyc_eq_55 & pyc_eq_113);
assign pyc_eq_115 = (csr_addr == pyc_constant_31);
assign pyc_and_116 = (pyc_eq_55 & pyc_eq_115);
assign pyc_eq_117 = (csr_addr == pyc_constant_32);
assign pyc_and_118 = (pyc_eq_55 & pyc_eq_117);
assign pyc_or_119 = (pyc_and_64 | pyc_and_66);
assign pyc_or_120 = (pyc_and_68 | pyc_and_70);
assign pyc_or_121 = (pyc_and_72 | pyc_and_74);
assign pyc_or_122 = (pyc_and_76 | pyc_and_78);
assign pyc_or_123 = (pyc_and_80 | pyc_and_82);
assign pyc_or_124 = (pyc_and_84 | pyc_and_86);
assign pyc_or_125 = (pyc_and_88 | pyc_and_90);
assign pyc_or_126 = (pyc_and_92 | pyc_and_94);
assign pyc_or_127 = (pyc_and_96 | pyc_and_98);
assign pyc_or_128 = (pyc_and_100 | pyc_and_102);
assign pyc_or_129 = (pyc_and_104 | pyc_and_106);
assign pyc_or_130 = (pyc_and_108 | pyc_and_110);
assign pyc_or_131 = (pyc_and_112 | pyc_and_114);
assign pyc_or_132 = (pyc_and_116 | pyc_and_118);
assign pyc_or_133 = (pyc_or_119 | pyc_or_120);
assign pyc_or_134 = (pyc_or_121 | pyc_or_122);
assign pyc_or_135 = (pyc_or_123 | pyc_or_124);
assign pyc_or_136 = (pyc_or_125 | pyc_or_126);
assign pyc_or_137 = (pyc_or_127 | pyc_or_128);
assign pyc_or_138 = (pyc_or_129 | pyc_or_130);
assign pyc_or_139 = (pyc_or_131 | pyc_or_132);
assign pyc_or_140 = (pyc_or_133 | pyc_or_134);
assign pyc_or_141 = (pyc_or_135 | pyc_or_136);
assign pyc_or_142 = (pyc_or_137 | pyc_or_138);
assign pyc_or_143 = (pyc_or_140 | pyc_or_141);
assign pyc_or_144 = (pyc_or_142 | pyc_or_139);
assign pyc_or_145 = (pyc_or_143 | pyc_or_144);
assign pyc_and_146 = (pyc_and_56 & pyc_or_145);
assign pyc_comb_147 = pyc_constant_1;
assign pyc_comb_148 = pyc_constant_33;
assign pyc_comb_149 = pyc_constant_34;
assign pyc_comb_150 = pyc_constant_35;
assign pyc_comb_151 = pyc_constant_36;
assign pyc_comb_152 = pyc_constant_37;
assign pyc_comb_153 = pyc_constant_38;
assign pyc_comb_154 = pyc_constant_39;
assign pyc_comb_155 = pyc_constant_40;
assign pyc_comb_156 = pyc_constant_41;
assign pyc_comb_157 = pyc_constant_42;
assign pyc_comb_158 = pyc_constant_43;
assign pyc_comb_159 = pyc_constant_44;
assign pyc_comb_160 = pyc_constant_45;
assign pyc_comb_161 = pyc_constant_46;
assign pyc_comb_162 = pyc_constant_47;
assign pyc_comb_163 = pyc_constant_48;
assign pyc_comb_164 = pyc_constant_49;
assign pyc_comb_165 = pyc_constant_50;
assign pyc_comb_166 = pyc_constant_51;
assign pyc_comb_167 = pyc_constant_52;
assign pyc_comb_168 = pyc_constant_53;
assign pyc_comb_169 = pyc_eq_55;
assign pyc_comb_170 = pyc_and_62;
assign pyc_comb_171 = pyc_and_64;
assign pyc_comb_172 = pyc_and_66;
assign pyc_comb_173 = pyc_and_68;
assign pyc_comb_174 = pyc_and_70;
assign pyc_comb_175 = pyc_and_72;
assign pyc_comb_176 = pyc_and_74;
assign pyc_comb_177 = pyc_and_76;
assign pyc_comb_178 = pyc_and_78;
assign pyc_comb_179 = pyc_and_80;
assign pyc_comb_180 = pyc_and_82;
assign pyc_comb_181 = pyc_and_84;
assign pyc_comb_182 = pyc_and_86;
assign pyc_comb_183 = pyc_and_88;
assign pyc_comb_184 = pyc_and_90;
assign pyc_comb_185 = pyc_and_92;
assign pyc_comb_186 = pyc_and_94;
assign pyc_comb_187 = pyc_and_96;
assign pyc_comb_188 = pyc_and_98;
assign pyc_comb_189 = pyc_and_100;
assign pyc_comb_190 = pyc_and_102;
assign pyc_comb_191 = pyc_and_104;
assign pyc_comb_192 = pyc_and_106;
assign pyc_comb_193 = pyc_and_108;
assign pyc_comb_194 = pyc_or_145;
assign pyc_comb_195 = pyc_and_146;
assign pyc_extract_201 = pyc_reg_200[0];
assign pyc_extract_202 = pyc_reg_200[1];
assign q_ctrl_lmsm_start = pyc_extract_201;
assign q_ctrl_irq_en = pyc_extract_202;
assign pyc_comb_203 = q_ctrl_lmsm_start;
assign pyc_comb_204 = q_ctrl_irq_en;
assign pyc_extract_215 = pyc_reg_214[0];
assign pyc_extract_216 = pyc_reg_214[1];
assign pyc_extract_217 = pyc_reg_214[2];
assign pyc_extract_218 = pyc_reg_214[3];
assign pyc_extract_219 = pyc_reg_214[4];
assign pyc_extract_220 = pyc_reg_214[5];
assign pyc_extract_221 = pyc_reg_214[6];
assign q_irq_status_fec_uncorr = pyc_extract_215;
assign q_irq_status_crc_fail = pyc_extract_216;
assign q_irq_status_retry_err = pyc_extract_217;
assign q_irq_status_crd_proto = pyc_extract_218;
assign q_irq_status_train_fail = pyc_extract_219;
assign q_irq_status_bad_vl = pyc_extract_220;
assign q_irq_status_crd_uf = pyc_extract_221;
assign pyc_comb_222 = q_irq_status_fec_uncorr;
assign pyc_comb_223 = q_irq_status_crc_fail;
assign pyc_comb_224 = q_irq_status_retry_err;
assign pyc_comb_225 = q_irq_status_crd_proto;
assign pyc_comb_226 = q_irq_status_train_fail;
assign pyc_comb_227 = q_irq_status_bad_vl;
assign pyc_comb_228 = q_irq_status_crd_uf;
assign cnt_ctrl_port_rst = pyc_reg_238;
assign pyc_and_239 = (pyc_comb_195 & pyc_comb_171);
assign pyc_and_240 = (pyc_comb_195 & pyc_comb_174);
assign pyc_and_241 = (pyc_comb_195 & pyc_comb_175);
assign pyc_and_242 = (pyc_comb_195 & pyc_comb_173);
assign pyc_and_243 = (pyc_comb_195 & pyc_comb_193);
assign pyc_extract_244 = csr_wdata[0];
assign pyc_and_245 = (pyc_and_243 & pyc_extract_244);
assign pyc_extract_246 = csr_wdata[1];
assign pyc_and_247 = (pyc_and_243 & pyc_extract_246);
assign pyc_extract_248 = csr_wdata[2];
assign pyc_and_249 = (pyc_and_243 & pyc_extract_248);
assign pyc_extract_250 = csr_wdata[3];
assign pyc_and_251 = (pyc_and_243 & pyc_extract_250);
assign pyc_extract_252 = csr_wdata[4];
assign pyc_and_253 = (pyc_and_243 & pyc_extract_252);
assign pyc_extract_254 = csr_wdata[5];
assign pyc_and_255 = (pyc_and_243 & pyc_extract_254);
assign pyc_extract_256 = csr_wdata[6];
assign pyc_and_257 = (pyc_and_243 & pyc_extract_256);
assign pyc_extract_258 = csr_wdata[7];
assign pyc_and_259 = (pyc_and_243 & pyc_extract_258);
assign pyc_extract_260 = csr_wdata[8];
assign pyc_and_261 = (pyc_and_243 & pyc_extract_260);
assign pyc_mux_262 = (pyc_and_239 ? pyc_extract_246 : pyc_comb_203);
assign pyc_comb_263 = cnt_ctrl_port_rst;
assign pyc_comb_264 = pyc_and_239;
assign pyc_comb_265 = pyc_and_240;
assign pyc_comb_266 = pyc_and_241;
assign pyc_comb_267 = pyc_and_242;
assign pyc_comb_268 = pyc_extract_244;
assign pyc_comb_269 = pyc_and_245;
assign pyc_comb_270 = pyc_extract_246;
assign pyc_comb_271 = pyc_and_247;
assign pyc_comb_272 = pyc_extract_248;
assign pyc_comb_273 = pyc_and_249;
assign pyc_comb_274 = pyc_extract_250;
assign pyc_comb_275 = pyc_and_251;
assign pyc_comb_276 = pyc_extract_252;
assign pyc_comb_277 = pyc_and_253;
assign pyc_comb_278 = pyc_extract_254;
assign pyc_comb_279 = pyc_and_255;
assign pyc_comb_280 = pyc_extract_256;
assign pyc_comb_281 = pyc_and_257;
assign pyc_comb_282 = pyc_and_259;
assign pyc_comb_283 = pyc_and_261;
assign pyc_comb_284 = pyc_mux_262;
assign pyc_and_290 = (pyc_comb_267 & pyc_comb_268);
assign pyc_or_291 = (pyc_comb_222 | ev_fec_uncorr);
assign pyc_not_292 = (~pyc_and_290);
assign pyc_and_293 = (pyc_or_291 & pyc_not_292);
assign pyc_comb_294 = pyc_and_293;
assign pyc_and_295 = (pyc_comb_267 & pyc_comb_270);
assign pyc_or_296 = (pyc_comb_223 | ev_crc_fail);
assign pyc_not_297 = (~pyc_and_295);
assign pyc_and_298 = (pyc_or_296 & pyc_not_297);
assign pyc_comb_299 = pyc_and_298;
assign pyc_and_300 = (pyc_comb_267 & pyc_comb_272);
assign pyc_or_301 = (pyc_comb_224 | ev_retry_err);
assign pyc_not_302 = (~pyc_and_300);
assign pyc_and_303 = (pyc_or_301 & pyc_not_302);
assign pyc_comb_304 = pyc_and_303;
assign pyc_and_305 = (pyc_comb_267 & pyc_comb_274);
assign pyc_or_306 = (pyc_comb_225 | ev_crd_proto);
assign pyc_not_307 = (~pyc_and_305);
assign pyc_and_308 = (pyc_or_306 & pyc_not_307);
assign pyc_comb_309 = pyc_and_308;
assign pyc_and_310 = (pyc_comb_267 & pyc_comb_276);
assign pyc_or_311 = (pyc_comb_226 | ev_train_fail);
assign pyc_not_312 = (~pyc_and_310);
assign pyc_and_313 = (pyc_or_311 & pyc_not_312);
assign pyc_comb_314 = pyc_and_313;
assign pyc_and_315 = (pyc_comb_267 & pyc_comb_278);
assign pyc_or_316 = (pyc_comb_227 | ev_bad_vl);
assign pyc_not_317 = (~pyc_and_315);
assign pyc_and_318 = (pyc_or_316 & pyc_not_317);
assign pyc_comb_319 = pyc_and_318;
assign pyc_and_320 = (pyc_comb_267 & pyc_comb_280);
assign pyc_or_321 = (pyc_comb_228 | ev_crd_uf);
assign pyc_not_322 = (~pyc_and_320);
assign pyc_and_323 = (pyc_or_321 & pyc_not_322);
assign pyc_comb_324 = pyc_and_323;
assign pyc_and_388 = (pyc_comb_264 & pyc_comb_268);
assign pyc_eq_389 = (pyc_comb_263 == pyc_comb_152);
assign pyc_not_390 = (~pyc_eq_389);
assign pyc_sub_391 = (pyc_comb_263 - pyc_comb_156);
assign pyc_mux_392 = (pyc_eq_389 ? pyc_comb_263 : pyc_sub_391);
assign pyc_mux_393 = (pyc_and_388 ? pyc_comb_155 : pyc_mux_392);
assign pyc_comb_394 = pyc_not_390;
assign pyc_comb_395 = pyc_mux_393;
assign cnt_ctrl_port_rst__next = pyc_comb_395;
assign csr_rvalid_q = pyc_reg_457;
assign pyc_not_458 = (~csr_wr);
assign pyc_and_459 = (csr_req & pyc_not_458);
assign pyc_comb_460 = csr_rvalid_q;
assign pyc_comb_461 = pyc_and_459;
assign csr_rvalid_q__next = pyc_comb_461;
assign pyc_mux_285 = (pyc_comb_264 ? pyc_comb_272 : pyc_comb_204);
assign q_cnt_bad_vl_count = pyc_reg_236;
assign pyc_eq_374 = (q_cnt_bad_vl_count == pyc_comb_153);
assign pyc_not_375 = (~pyc_eq_374);
assign pyc_and_376 = (inc_bad_vl & pyc_not_375);
assign pyc_add_377 = (q_cnt_bad_vl_count + pyc_comb_154);
assign pyc_mux_378 = (pyc_and_376 ? pyc_add_377 : q_cnt_bad_vl_count);
assign pyc_mux_379 = (pyc_comb_282 ? pyc_comb_150 : pyc_mux_378);
assign pyc_comb_380 = pyc_mux_379;
assign q_cnt_bad_vl_count__next = pyc_comb_380;
assign q_cnt_crc_fail_count = pyc_reg_230;
assign pyc_eq_332 = (q_cnt_crc_fail_count == pyc_comb_153);
assign pyc_not_333 = (~pyc_eq_332);
assign pyc_and_334 = (inc_crc_fail & pyc_not_333);
assign pyc_add_335 = (q_cnt_crc_fail_count + pyc_comb_154);
assign pyc_mux_336 = (pyc_and_334 ? pyc_add_335 : q_cnt_crc_fail_count);
assign pyc_mux_337 = (pyc_comb_271 ? pyc_comb_150 : pyc_mux_336);
assign pyc_comb_338 = pyc_mux_337;
assign q_cnt_crc_fail_count__next = pyc_comb_338;
assign q_cnt_crd_of_count = pyc_reg_233;
assign pyc_eq_353 = (q_cnt_crd_of_count == pyc_comb_153);
assign pyc_not_354 = (~pyc_eq_353);
assign pyc_and_355 = (inc_crd_of & pyc_not_354);
assign pyc_add_356 = (q_cnt_crd_of_count + pyc_comb_154);
assign pyc_mux_357 = (pyc_and_355 ? pyc_add_356 : q_cnt_crd_of_count);
assign pyc_mux_358 = (pyc_comb_277 ? pyc_comb_150 : pyc_mux_357);
assign pyc_comb_359 = pyc_mux_358;
assign q_cnt_crd_of_count__next = pyc_comb_359;
assign q_cnt_crd_to_count = pyc_reg_234;
assign pyc_eq_360 = (q_cnt_crd_to_count == pyc_comb_153);
assign pyc_not_361 = (~pyc_eq_360);
assign pyc_and_362 = (inc_crd_to & pyc_not_361);
assign pyc_add_363 = (q_cnt_crd_to_count + pyc_comb_154);
assign pyc_mux_364 = (pyc_and_362 ? pyc_add_363 : q_cnt_crd_to_count);
assign pyc_mux_365 = (pyc_comb_279 ? pyc_comb_150 : pyc_mux_364);
assign pyc_comb_366 = pyc_mux_365;
assign q_cnt_crd_to_count__next = pyc_comb_366;
assign q_cnt_crd_uf_count = pyc_reg_237;
assign pyc_eq_381 = (q_cnt_crd_uf_count == pyc_comb_153);
assign pyc_not_382 = (~pyc_eq_381);
assign pyc_and_383 = (inc_crd_uf & pyc_not_382);
assign pyc_add_384 = (q_cnt_crd_uf_count + pyc_comb_154);
assign pyc_mux_385 = (pyc_and_383 ? pyc_add_384 : q_cnt_crd_uf_count);
assign pyc_mux_386 = (pyc_comb_283 ? pyc_comb_150 : pyc_mux_385);
assign pyc_comb_387 = pyc_mux_386;
assign q_cnt_crd_uf_count__next = pyc_comb_387;
assign q_cnt_fec_uncorr_count = pyc_reg_229;
assign pyc_eq_325 = (q_cnt_fec_uncorr_count == pyc_comb_153);
assign pyc_not_326 = (~pyc_eq_325);
assign pyc_and_327 = (inc_fec_uncorr & pyc_not_326);
assign pyc_add_328 = (q_cnt_fec_uncorr_count + pyc_comb_154);
assign pyc_mux_329 = (pyc_and_327 ? pyc_add_328 : q_cnt_fec_uncorr_count);
assign pyc_mux_330 = (pyc_comb_269 ? pyc_comb_150 : pyc_mux_329);
assign pyc_comb_331 = pyc_mux_330;
assign q_cnt_fec_uncorr_count__next = pyc_comb_331;
assign q_cnt_retry_req_count = pyc_reg_231;
assign pyc_eq_339 = (q_cnt_retry_req_count == pyc_comb_153);
assign pyc_not_340 = (~pyc_eq_339);
assign pyc_and_341 = (inc_retry_req & pyc_not_340);
assign pyc_add_342 = (q_cnt_retry_req_count + pyc_comb_154);
assign pyc_mux_343 = (pyc_and_341 ? pyc_add_342 : q_cnt_retry_req_count);
assign pyc_mux_344 = (pyc_comb_273 ? pyc_comb_150 : pyc_mux_343);
assign pyc_comb_345 = pyc_mux_344;
assign q_cnt_retry_req_count__next = pyc_comb_345;
assign q_cnt_retry_to_count = pyc_reg_232;
assign pyc_eq_346 = (q_cnt_retry_to_count == pyc_comb_153);
assign pyc_not_347 = (~pyc_eq_346);
assign pyc_and_348 = (inc_retry_to & pyc_not_347);
assign pyc_add_349 = (q_cnt_retry_to_count + pyc_comb_154);
assign pyc_mux_350 = (pyc_and_348 ? pyc_add_349 : q_cnt_retry_to_count);
assign pyc_mux_351 = (pyc_comb_275 ? pyc_comb_150 : pyc_mux_350);
assign pyc_comb_352 = pyc_mux_351;
assign q_cnt_retry_to_count__next = pyc_comb_352;
assign q_cnt_train_to_count = pyc_reg_235;
assign pyc_eq_367 = (q_cnt_train_to_count == pyc_comb_153);
assign pyc_not_368 = (~pyc_eq_367);
assign pyc_and_369 = (inc_train_to & pyc_not_368);
assign pyc_add_370 = (q_cnt_train_to_count + pyc_comb_154);
assign pyc_mux_371 = (pyc_and_369 ? pyc_add_370 : q_cnt_train_to_count);
assign pyc_mux_372 = (pyc_comb_281 ? pyc_comb_150 : pyc_mux_371);
assign pyc_comb_373 = pyc_mux_372;
assign q_cnt_train_to_count__next = pyc_comb_373;
assign q_crd_to_dis_dis = pyc_reg_208;
assign q_crd_to_dis_dis__next = q_crd_to_dis_dis;
assign q_ctrl_irq_en__next = pyc_mux_285;
assign q_ctrl_lmsm_start__next = pyc_comb_284;
assign pyc_concat_196 = {q_ctrl_irq_en__next, q_ctrl_lmsm_start__next};
assign pyc_concat_197 = {pyc_comb_147, pyc_comb_147};
assign pyc_comb_198 = pyc_concat_196;
assign pyc_comb_199 = pyc_concat_197;
assign q_irq_mask_mask = pyc_reg_205;
assign pyc_extract_286 = csr_wdata[6:0];
assign pyc_mux_287 = (pyc_comb_265 ? pyc_extract_286 : q_irq_mask_mask);
assign pyc_comb_288 = pyc_mux_287;
assign q_irq_mask_mask__next = pyc_comb_288;
assign q_irq_status_bad_vl__next = pyc_comb_319;
assign q_irq_status_crc_fail__next = pyc_comb_299;
assign q_irq_status_crd_proto__next = pyc_comb_309;
assign q_irq_status_crd_uf__next = pyc_comb_324;
assign q_irq_status_fec_uncorr__next = pyc_comb_294;
assign q_irq_status_retry_err__next = pyc_comb_304;
assign q_irq_status_train_fail__next = pyc_comb_314;
assign pyc_concat_210 = {q_irq_status_crd_uf__next, q_irq_status_bad_vl__next, q_irq_status_train_fail__next, q_irq_status_crd_proto__next, q_irq_status_retry_err__next, q_irq_status_crc_fail__next, q_irq_status_fec_uncorr__next};
assign pyc_concat_211 = {pyc_comb_147, pyc_comb_147, pyc_comb_147, pyc_comb_147, pyc_comb_147, pyc_comb_147, pyc_comb_147};
assign pyc_comb_212 = pyc_concat_210;
assign pyc_comb_213 = pyc_concat_211;
assign q_lmsm_tmr_scale_scale = pyc_reg_207;
assign q_lmsm_tmr_scale_scale__next = q_lmsm_tmr_scale_scale;
assign q_pcs_tx_test_am_ivl_scale = pyc_reg_209;
assign q_pcs_tx_test_am_ivl_scale__next = q_pcs_tx_test_am_ivl_scale;
assign q_port_cna_cna = pyc_reg_206;
assign pyc_concat_396 = {pyc_comb_228, pyc_comb_227, pyc_comb_226, pyc_comb_225, pyc_comb_224, pyc_comb_223, pyc_comb_222};
assign pyc_not_397 = (~q_irq_mask_mask);
assign pyc_and_398 = (pyc_concat_396 & pyc_not_397);
assign pyc_eq_399 = (pyc_and_398 == pyc_comb_157);
assign pyc_not_400 = (~pyc_eq_399);
assign pyc_and_401 = (pyc_comb_204 & pyc_not_400);
assign pyc_concat_402 = {pyc_comb_158, pyc_comb_204, pyc_comb_203, pyc_comb_147};
assign pyc_concat_403 = {pyc_comb_159, hw_retry_ack_st, hw_retry_req_st, hw_dll_sm_st, hw_lmsm_st, hw_dll_status_up, hw_link_ready, hw_link_up};
assign pyc_concat_404 = {pyc_comb_160, pyc_comb_228, pyc_comb_227, pyc_comb_226, pyc_comb_225, pyc_comb_224, pyc_comb_223, pyc_comb_222};
assign pyc_concat_405 = {pyc_comb_160, q_irq_mask_mask};
assign pyc_mux_406 = (pyc_comb_171 ? pyc_concat_402 : pyc_comb_150);
assign pyc_mux_407 = (pyc_comb_172 ? pyc_concat_403 : pyc_comb_150);
assign pyc_mux_408 = (pyc_comb_173 ? pyc_concat_404 : pyc_comb_150);
assign pyc_mux_409 = (pyc_comb_174 ? pyc_concat_405 : pyc_comb_150);
assign pyc_mux_410 = (pyc_comb_175 ? q_port_cna_cna : pyc_comb_150);
assign pyc_mux_411 = (pyc_comb_176 ? pyc_comb_161 : pyc_comb_150);
assign pyc_mux_412 = (pyc_comb_177 ? pyc_comb_162 : pyc_comb_150);
assign pyc_mux_413 = (pyc_comb_178 ? pyc_comb_163 : pyc_comb_150);
assign pyc_mux_414 = (pyc_comb_179 ? pyc_comb_164 : pyc_comb_150);
assign pyc_mux_415 = (pyc_comb_180 ? pyc_comb_165 : pyc_comb_150);
assign pyc_mux_416 = (pyc_comb_181 ? pyc_comb_166 : pyc_comb_150);
assign pyc_mux_417 = (pyc_comb_182 ? pyc_comb_167 : pyc_comb_150);
assign pyc_mux_418 = (pyc_comb_183 ? pyc_comb_168 : pyc_comb_150);
assign pyc_mux_419 = (pyc_comb_184 ? q_cnt_fec_uncorr_count : pyc_comb_150);
assign pyc_mux_420 = (pyc_comb_185 ? q_cnt_crc_fail_count : pyc_comb_150);
assign pyc_mux_421 = (pyc_comb_186 ? q_cnt_retry_req_count : pyc_comb_150);
assign pyc_mux_422 = (pyc_comb_187 ? q_cnt_retry_to_count : pyc_comb_150);
assign pyc_mux_423 = (pyc_comb_188 ? q_cnt_crd_of_count : pyc_comb_150);
assign pyc_mux_424 = (pyc_comb_189 ? q_cnt_crd_to_count : pyc_comb_150);
assign pyc_mux_425 = (pyc_comb_190 ? q_cnt_train_to_count : pyc_comb_150);
assign pyc_mux_426 = (pyc_comb_191 ? q_cnt_bad_vl_count : pyc_comb_150);
assign pyc_mux_427 = (pyc_comb_192 ? q_cnt_crd_uf_count : pyc_comb_150);
assign pyc_or_428 = (pyc_mux_406 | pyc_mux_407);
assign pyc_or_429 = (pyc_mux_408 | pyc_mux_409);
assign pyc_or_430 = (pyc_mux_410 | pyc_mux_411);
assign pyc_or_431 = (pyc_mux_412 | pyc_mux_413);
assign pyc_or_432 = (pyc_mux_414 | pyc_mux_415);
assign pyc_or_433 = (pyc_mux_416 | pyc_mux_417);
assign pyc_or_434 = (pyc_mux_418 | pyc_mux_419);
assign pyc_or_435 = (pyc_mux_420 | pyc_mux_421);
assign pyc_or_436 = (pyc_mux_422 | pyc_mux_423);
assign pyc_or_437 = (pyc_mux_424 | pyc_mux_425);
assign pyc_or_438 = (pyc_mux_426 | pyc_mux_427);
assign pyc_or_439 = (pyc_or_428 | pyc_or_429);
assign pyc_or_440 = (pyc_or_430 | pyc_or_431);
assign pyc_or_441 = (pyc_or_432 | pyc_or_433);
assign pyc_or_442 = (pyc_or_434 | pyc_or_435);
assign pyc_or_443 = (pyc_or_436 | pyc_or_437);
assign pyc_or_444 = (pyc_or_439 | pyc_or_440);
assign pyc_or_445 = (pyc_or_441 | pyc_or_442);
assign pyc_or_446 = (pyc_or_443 | pyc_or_438);
assign pyc_or_447 = (pyc_or_444 | pyc_or_445);
assign pyc_or_448 = (pyc_or_447 | pyc_or_446);
assign csr_rdata_q__next = pyc_or_448;
assign pyc_not_449 = (~pyc_comb_169);
assign pyc_not_450 = (~pyc_comb_194);
assign pyc_not_451 = (~pyc_comb_170);
assign pyc_and_452 = (pyc_not_450 & pyc_not_451);
assign pyc_or_453 = (pyc_not_449 | pyc_and_452);
assign pyc_comb_454 = pyc_and_401;
assign pyc_comb_455 = csr_rdata_q__next;
assign pyc_comb_456 = pyc_or_453;
assign csr_err_q = pyc_reg_463;
assign pyc_and_464 = (csr_req & pyc_comb_456);
assign pyc_comb_465 = csr_err_q;
assign pyc_comb_466 = pyc_and_464;
assign csr_err_q__next = pyc_comb_466;
assign pyc_mux_289 = (pyc_comb_266 ? csr_wdata : q_port_cna_cna);
assign q_port_cna_cna__next = pyc_mux_289;

// --- Sequential primitives
pyc_reg #(.WIDTH(2)) pyc_reg_200_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(pyc_comb_198),
  .init(pyc_comb_199),
  .q(pyc_reg_200)
);
pyc_reg #(.WIDTH(7)) pyc_reg_205_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(q_irq_mask_mask__next),
  .init(pyc_comb_149),
  .q(pyc_reg_205)
);
pyc_reg #(.WIDTH(32)) pyc_reg_206_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(q_port_cna_cna__next),
  .init(pyc_comb_150),
  .q(pyc_reg_206)
);
pyc_reg #(.WIDTH(8)) pyc_reg_207_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(q_lmsm_tmr_scale_scale__next),
  .init(pyc_comb_151),
  .q(pyc_reg_207)
);
pyc_reg #(.WIDTH(1)) pyc_reg_208_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(q_crd_to_dis_dis__next),
  .init(pyc_comb_147),
  .q(pyc_reg_208)
);
pyc_reg #(.WIDTH(8)) pyc_reg_209_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(q_pcs_tx_test_am_ivl_scale__next),
  .init(pyc_comb_151),
  .q(pyc_reg_209)
);
pyc_reg #(.WIDTH(7)) pyc_reg_214_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(pyc_comb_212),
  .init(pyc_comb_213),
  .q(pyc_reg_214)
);
pyc_reg #(.WIDTH(32)) pyc_reg_229_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(q_cnt_fec_uncorr_count__next),
  .init(pyc_comb_150),
  .q(pyc_reg_229)
);
pyc_reg #(.WIDTH(32)) pyc_reg_230_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(q_cnt_crc_fail_count__next),
  .init(pyc_comb_150),
  .q(pyc_reg_230)
);
pyc_reg #(.WIDTH(32)) pyc_reg_231_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(q_cnt_retry_req_count__next),
  .init(pyc_comb_150),
  .q(pyc_reg_231)
);
pyc_reg #(.WIDTH(32)) pyc_reg_232_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(q_cnt_retry_to_count__next),
  .init(pyc_comb_150),
  .q(pyc_reg_232)
);
pyc_reg #(.WIDTH(32)) pyc_reg_233_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(q_cnt_crd_of_count__next),
  .init(pyc_comb_150),
  .q(pyc_reg_233)
);
pyc_reg #(.WIDTH(32)) pyc_reg_234_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(q_cnt_crd_to_count__next),
  .init(pyc_comb_150),
  .q(pyc_reg_234)
);
pyc_reg #(.WIDTH(32)) pyc_reg_235_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(q_cnt_train_to_count__next),
  .init(pyc_comb_150),
  .q(pyc_reg_235)
);
pyc_reg #(.WIDTH(32)) pyc_reg_236_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(q_cnt_bad_vl_count__next),
  .init(pyc_comb_150),
  .q(pyc_reg_236)
);
pyc_reg #(.WIDTH(32)) pyc_reg_237_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(q_cnt_crd_uf_count__next),
  .init(pyc_comb_150),
  .q(pyc_reg_237)
);
pyc_reg #(.WIDTH(5)) pyc_reg_238_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(cnt_ctrl_port_rst__next),
  .init(pyc_comb_152),
  .q(pyc_reg_238)
);
pyc_reg #(.WIDTH(1)) pyc_reg_457_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(csr_rvalid_q__next),
  .init(pyc_comb_147),
  .q(pyc_reg_457)
);
pyc_reg #(.WIDTH(32)) pyc_reg_462_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(pyc_comb_455),
  .init(pyc_comb_150),
  .q(pyc_reg_462)
);
pyc_reg #(.WIDTH(1)) pyc_reg_463_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_148),
  .d(csr_err_q__next),
  .init(pyc_comb_147),
  .q(pyc_reg_463)
);

assign csr_ready = pyc_comb_148;
assign port_rst_pulse = pyc_comb_394;
assign csr_lmsm_start = pyc_comb_203;
assign csr_irq_en = pyc_comb_204;
assign csr_irq_mask = q_irq_mask_mask;
assign csr_port_cna = q_port_cna_cna;
assign csr_tmr_scale = pyc_comb_151;
assign csr_crd_to_dis = pyc_comb_147;
assign csr_am_ivl_scale = pyc_comb_151;
assign irq = pyc_comb_454;
assign csr_rvalid = pyc_comb_460;
assign csr_rdata = csr_rdata_q;
assign csr_err = pyc_comb_465;

endmodule

