// Generated by rtl/lmsm/ub_lmsm.py — do not hand-edit.
// pyc4.0 leaf ub_lmsm. TEST_HOOKS=1 (Python generation-time).
// Registers: pyc_reg semantics (sync, rst_pyc active-high, core_clk).
// SPEC: §2.5, §3.2.5, §3.3.3, §3.3.4, §4.2, §6.1, §9, §10, §11.
// CRC / padding / per-lane Lane_ID fill: PCS, not this leaf.
// PORT_RST 16-cycle pulse: ub_csr; this leaf sees port_rst as sync clear.

module ub_lmsm #(
  parameter NUM_LANES_TX              = 1,      // SPEC §9 / REGMAP PARAM_PHY; binary 1/2/4/8
  parameter NUM_LANES_RX              = 1,      // SPEC §9; default equals TX
  parameter TMR_W                     = 32,     // core_clk counter width; F_CORE SPEC §4.1 / §9
  parameter P_TMR_PROBE_WAIT          = 806,    // stub cycles; SPEC §13.2
  parameter P_TMR_PROBE_CONFIRM       = 806,    // stub; SPEC §13.2
  parameter P_TMR_RXEQ                = 80570,  // stub; SPEC §6.1 / §13.2 EQ empty-spin
  parameter P_TMR_DISC_ACTIVE         = 1933680, // stub; SPEC §13.2
  parameter P_TMR_DISC_CONFIRM        = 3867360, // stub; SPEC §13.2
  parameter P_TMR_CFG                 = 161140,  // stub; SPEC §13.2
  parameter P_TMR_NULL                = 161140,  // stub; SPEC §6.1 Send_NullBlock / §13.2
  parameter P_TMR_RETRAIN_ACTIVE      = 1933680, // stub; SPEC §13.2
  parameter P_TMR_RETRAIN_CONFIRM     = 3867360, // stub; SPEC §13.2
  parameter P_TMR_CHG_SPD             = 80570,  // stub; SPEC §6.1 Change_Speed / §13.2
  parameter P_TMR_EQ                  = 5156480, // stub; SPEC §6.1 / §13.2
  parameter P_NULL_BLK_NEED           = 8,      // stub cycles; SPEC §6.1 「连续空块」
  parameter P_MAX_RETRAIN             = 4,      // SPEC §9 NUM_PHY_REINIT_THRESHOLD (draft §13.1)
  parameter P_PROBE_MAX_RETRY         = 8,      // stub; SPEC §13.2 / §13.3 Probe
  parameter P_LTB_TYPE_DLTB           = 1,      // stub; UB-PHY §3.4.1.1 / SPEC §3.3.4
  parameter P_LTB_TYPE_CLTB           = 2,      // stub; UB-PHY §3.4.1.1 / SPEC §3.3.4
  parameter P_LTB_TYPE_RLTB           = 3,      // stub; UB-PHY §3.4.1.1 / SPEC §3.3.4
  parameter P_LTB_TYPE_ELTB           = 4,      // stub; UB-PHY §3.4.1.1 / SPEC §3.3.4
  parameter P_LTB_TYPE_NULL           = 0,      // stub; UB-PHY §3.4.1.1 / SPEC §3.3.4
  parameter P_LANE_ID_NULL            = 255,   // stub; UB-PHY §3.4.1.1 NULL Lane_ID
  parameter P_CHG_SPD_BIT             = 0       // stub; SPEC §3.3.4 / UB-PHY §3.4.1.1
) (
  input  wire                    core_clk,
  input  wire                    rst_pyc,
  input  wire                    port_rst,

  // CSR / App. D advertisement (SPEC §3.3.5). Level, no handshake.
  // csr_lmsm_start = CTRL.LMSM_START (REGMAP 0x0000 bit1; SPEC §6.1).
  input  wire                    csr_lmsm_start,
  input  wire                    csr_bypass_probe,
  input  wire                    cfg_fixed_rate_rxeq,
  input  wire                    cfg_req_change_speed,
  input  wire                    cfg_req_equalization,
  input  wire                    cfg_null_need_rediscovery,
  input  wire                    cfg_lane_reverse_tx,
  input  wire                    cfg_lane_reverse_rx,
  input  wire [NUM_LANES_RX-1:0] cfg_polarity_inv,
  input  wire [7:0]              cfg_link_id,
  input  wire [5:0]              cfg_tlw,
  input  wire [5:0]              cfg_rlw,
  input  wire [7:0]              cfg_data_rate_support_1,
  input  wire [7:0]              cfg_data_rate_support_2,
  input  wire [7:0]              cfg_fec_mode_support,
  input  wire                    cfg_port_type,
  input  wire [6:0]              cfg_portnego_random_value,
  input  wire [3:0]              cfg_fec_interleave_support,
  input  wire [2:0]              cfg_rx_lane0_id,
  input  wire [2:0]              cfg_max_link_width,
  input  wire [1:0]              cfg_eq_mode,
  input  wire [2:0]              cfg_fec_mode_ctrl,
  input  wire                    cfg_fec_interleave_ctrl,
  input  wire [5:0]              cfg_eq_ctrl1,
  input  wire [7:0]              cfg_eq_ctrl2,
  input  wire [7:0]              cfg_eq_ctrl3,
  input  wire [7:0]              cfg_eq_ctrl4,
  input  wire                    cfg_fec_crc_mode_reject,
  input  wire [1:0]              cfg_pre_fec_ber_meas_st,
  input  wire                    cfg_fec_interleave_enable,
  input  wire                    cfg_fec_interleave_ctrl_reject,
  input  wire                    cfg_request_equalization,
  input  wire [2:0]              cfg_crc_mode_ctrl,
  input  wire [3:0]              cfg_local_tx_preset,
  input  wire [5:0]              cfg_first_pre_cursor,
  input  wire                    cfg_eq_reject,
  input  wire [1:0]              cfg_current_eq_phase,
  input  wire                    cfg_preset_mode_en,
  input  wire [3:0]              cfg_tx_preset,
  input  wire [7:0]              cfg_lane_id_base,
  input  wire [8-1:0]            cfg_lane_id_map,

  // LMSM ↔ PMA training sideband (SPEC §3.2.5)
  output wire [3:0]              pma_data_rate_sel,
  output wire [3:0]              pma_tx_width,
  output wire [3:0]              pma_rx_width,
  output wire                    pma_lane_reverse_tx,
  output wire                    pma_lane_reverse_rx,
  output wire [NUM_LANES_RX-1:0] pma_polarity_inv,
  output wire                    pma_probe_pulse_en,
  input  wire [NUM_LANES_TX-1:0] pma_term_detect,
  input  wire [NUM_LANES_RX-1:0] pma_rx_eidle_exit,
  input  wire                    pma_phy_ready,

  // LMSM ↔ DLL (SPEC §3.3.3)
  output wire                    link_up,
  output wire                    link_ready,
  input  wire                    dll_retrain_req,
  output wire                    lmsm_retrain_ack,

  // LMSM ↔ PCS pattern / Lane_ID controls (SPEC §3.3.4)
  output wire [1:0]              lmsm2pcs_pattern,
  output wire                    lmsm2pcs_ltb_valid,
  output wire [1:0]              lmsm2pcs_lane_id_mode,
  output wire [7:0]              lmsm2pcs_lane_id_base,
  output wire [8-1:0]            lmsm2pcs_lane_id_map,

  // LTB/CLTB TX field ports (SPEC §3.3.4). Unused-in-this-type = 0.
  output wire [7:0]              lmsm2pcs_ltb_type,
  output wire [7:0]              lmsm2pcs_link_id,
  output wire [5:0]              lmsm2pcs_tlw,
  output wire [5:0]              lmsm2pcs_rlw,
  output wire [7:0]              lmsm2pcs_data_rate_support_1,
  output wire [7:0]              lmsm2pcs_data_rate_support_2,
  output wire [7:0]              lmsm2pcs_fec_mode_support,
  output wire                    lmsm2pcs_port_type,
  output wire [6:0]              lmsm2pcs_portnego_random_value,
  output wire [3:0]              lmsm2pcs_fec_interleave_support,
  output wire [2:0]              lmsm2pcs_rx_lane0_id,
  output wire [2:0]              lmsm2pcs_max_link_width,
  output wire [1:0]              lmsm2pcs_eq_mode,
  output wire [2:0]              lmsm2pcs_fec_mode_ctrl,
  output wire                    lmsm2pcs_fec_interleave_ctrl,
  output wire [5:0]              lmsm2pcs_eq_ctrl1,
  output wire [7:0]              lmsm2pcs_eq_ctrl2,
  output wire [7:0]              lmsm2pcs_eq_ctrl3,
  output wire [7:0]              lmsm2pcs_eq_ctrl4,
  output wire                    lmsm2pcs_fec_crc_mode_reject,
  output wire [1:0]              lmsm2pcs_pre_fec_ber_meas_st,
  output wire                    lmsm2pcs_fec_interleave_enable,
  output wire                    lmsm2pcs_fec_interleave_ctrl_reject,
  output wire                    lmsm2pcs_request_equalization,
  output wire [2:0]              lmsm2pcs_crc_mode_ctrl,
  output wire [3:0]              lmsm2pcs_local_tx_preset,
  output wire [5:0]              lmsm2pcs_first_pre_cursor,
  output wire                    lmsm2pcs_eq_reject,
  output wire [1:0]              lmsm2pcs_current_eq_phase,
  output wire                    lmsm2pcs_preset_mode_en,
  output wire [3:0]              lmsm2pcs_tx_preset,

  // LTB/CLTB RX field ports (SPEC §3.3.4). Sampled on ltb_valid.
  input  wire                    pcs2lmsm_ltb_valid,
  input  wire [7:0]              pcs2lmsm_ltb_type,
  input  wire [7:0]              pcs2lmsm_link_id,
  input  wire [7:0]              pcs2lmsm_lane_id,
  input  wire [5:0]              pcs2lmsm_tlw,
  input  wire [5:0]              pcs2lmsm_rlw,
  input  wire [7:0]              pcs2lmsm_data_rate_support_1,
  input  wire [7:0]              pcs2lmsm_data_rate_support_2,
  input  wire [7:0]              pcs2lmsm_fec_mode_support,
  input  wire                    pcs2lmsm_port_type,
  input  wire [6:0]              pcs2lmsm_portnego_random_value,
  input  wire [3:0]              pcs2lmsm_fec_interleave_support,
  input  wire [2:0]              pcs2lmsm_rx_lane0_id,
  input  wire [2:0]              pcs2lmsm_max_link_width,
  input  wire [1:0]              pcs2lmsm_eq_mode,
  input  wire [2:0]              pcs2lmsm_fec_mode_ctrl,
  input  wire                    pcs2lmsm_fec_interleave_ctrl,
  input  wire [5:0]              pcs2lmsm_eq_ctrl1,
  input  wire [7:0]              pcs2lmsm_eq_ctrl2,
  input  wire [7:0]              pcs2lmsm_eq_ctrl3,
  input  wire [7:0]              pcs2lmsm_eq_ctrl4,
  input  wire                    pcs2lmsm_fec_crc_mode_reject,
  input  wire [1:0]              pcs2lmsm_pre_fec_ber_meas_st,
  input  wire                    pcs2lmsm_fec_interleave_enable,
  input  wire                    pcs2lmsm_fec_interleave_ctrl_reject,
  input  wire                    pcs2lmsm_request_equalization,
  input  wire [2:0]              pcs2lmsm_crc_mode_ctrl,
  input  wire [3:0]              pcs2lmsm_local_tx_preset,
  input  wire [5:0]              pcs2lmsm_first_pre_cursor,
  input  wire                    pcs2lmsm_eq_reject,
  input  wire [1:0]              pcs2lmsm_current_eq_phase,
  input  wire                    pcs2lmsm_preset_mode_en,
  input  wire [3:0]              pcs2lmsm_tx_preset,
  input  wire [NUM_LANES_RX-1:0] pcs_am_locked,
  input  wire                    pcs_lid_bad,
  input  wire                    pcs_deskew_ok,

  // Status / IRQ events to ub_csr (REGMAP STATUS / IRQ / CNT)
  output wire [4:0]              lmsm_st,
  output wire                    train_fail,
  output wire                    train_to_inc
,

  // TEST_HOOKS=1 only (SPEC §10.1 / §10.2). PRODUCT has no tb_* ports.
  input  wire                    tb_test_mode,
  input  wire [7:0]              csr_tmr_scale,
  input  wire [NUM_LANES_RX-1:0] tb_inj_am_lock,
  input  wire                    tb_inj_lid_bad,
  output wire                    tb_obs_link_ready,
  output wire                    tb_obs_link_up,
  output wire [4:0]              tb_obs_lmsm_st
);

  // ------------------------------------------------------------------
  // Top-level state encoding = SPEC §10.3 (STATUS.LMSM_ST / hook observe)
  // ------------------------------------------------------------------
  localparam [4:0] ST_LINK_IDLE      = 5'd0;
  localparam [4:0] ST_PROBE          = 5'd1;
  localparam [4:0] ST_RXEQ_OPTIMIZE  = 5'd2;
  localparam [4:0] ST_DISCOVERY      = 5'd3;
  localparam [4:0] ST_CONFIG         = 5'd4;
  localparam [4:0] ST_SEND_NULLBLOCK = 5'd5;
  localparam [4:0] ST_LINK_ACTIVE    = 5'd6;
  localparam [4:0] ST_RETRAIN        = 5'd7;
  localparam [4:0] ST_CHANGE_SPEED   = 5'd8;
  localparam [4:0] ST_EQUALIZATION   = 5'd9;

  localparam [1:0] SUB_0 = 2'd0;
  localparam [1:0] SUB_1 = 2'd1;
  localparam [1:0] SUB_2 = 2'd2;

  localparam [1:0] PAT_IDLE = 2'd0;
  localparam [1:0] PAT_EEIB = 2'd1;
  localparam [1:0] PAT_LTB  = 2'd2;
  localparam [1:0] PAT_DLL  = 2'd3;

  // Lane_ID mode: 0=PHYS, 1=ASCEND, 2=NULL. 3=RESERVED — never driven.
  localparam [1:0] LANE_ID_PHYS   = 2'd0;
  localparam [1:0] LANE_ID_ASCEND = 2'd1;
  localparam [1:0] LANE_ID_NULL   = 2'd2;

  // Combined sync reset: rst_pyc (entity) or port_rst (CSR PORT_RST).
  wire rst_eff = rst_pyc | port_rst;

  // ------------------------------------------------------------------
  // Hook mux (SPEC §10.1). Python if TEST_HOOKS — no ifdef in Verilog.
  // Inject muxes LMSM inputs only; does not write back into PCS.
  // ------------------------------------------------------------------
  wire                    hook_en     = tb_test_mode;
  wire [NUM_LANES_RX-1:0] am_locked_u = hook_en ? tb_inj_am_lock : pcs_am_locked;
  wire                    lid_bad_u   = hook_en ? tb_inj_lid_bad   : pcs_lid_bad;
  // LMSM_TMR_SCALE (§10.4 / REGMAP): 0 = real-time (+1).
  // Non-zero: add SCALE each beat (suggested encoding; SPEC §13.2 open).
  wire [7:0] tmr_step_u = (hook_en && (csr_tmr_scale != 8'd0))
                         ? csr_tmr_scale : 8'd1;

  wire am_all   = &am_locked_u;
  wire term_any = |pma_term_detect;
  wire eidle_any = |pma_rx_eidle_exit;

  // pyc_reg: st, sub, tmr, null_cnt, probe_try, retrain_left, rx holds,
  //          saw_rx_ltb, train pulses.
  reg [4:0]      st;
  reg [1:0]      sub;
  reg [TMR_W-1:0] tmr;
  reg [7:0]      null_cnt;
  reg [7:0]      probe_try;
  reg [7:0]      retrain_left;
  reg            saw_rx_ltb;
  reg            train_fail_q;
  reg            train_to_q;
  reg [7:0]      rx_type_q;
  reg [7:0]      rx_link_q;
  reg [7:0]      rx_lane_q;
  reg [5:0]      rx_tlw_q;
  reg [5:0]      rx_rlw_q;
  reg [2:0]      rx_fec_ctrl_q;
  reg            rx_req_eq_q;
  reg [7:0]      rx_drs2_q;

  // Keep remaining RX LTB field ports in the cone (SPEC §3.3.4 completeness)
  // without steering the M1 top-level SM. WAIVER_LMSM_RX_LTB_AUX.
  wire unused_rx_aux = ^{pcs2lmsm_data_rate_support_1,
                         pcs2lmsm_fec_mode_support,
                         pcs2lmsm_port_type,
                         pcs2lmsm_portnego_random_value,
                         pcs2lmsm_fec_interleave_support,
                         pcs2lmsm_rx_lane0_id,
                         pcs2lmsm_max_link_width,
                         pcs2lmsm_eq_mode,
                         pcs2lmsm_fec_interleave_ctrl,
                         pcs2lmsm_eq_ctrl1,
                         pcs2lmsm_eq_ctrl2,
                         pcs2lmsm_eq_ctrl3,
                         pcs2lmsm_eq_ctrl4,
                         pcs2lmsm_fec_crc_mode_reject,
                         pcs2lmsm_pre_fec_ber_meas_st,
                         pcs2lmsm_fec_interleave_enable,
                         pcs2lmsm_fec_interleave_ctrl_reject,
                         pcs2lmsm_crc_mode_ctrl,
                         pcs2lmsm_local_tx_preset,
                         pcs2lmsm_first_pre_cursor,
                         pcs2lmsm_eq_reject,
                         pcs2lmsm_current_eq_phase,
                         pcs2lmsm_preset_mode_en,
                         pcs2lmsm_tx_preset,
                         eidle_any};
  wire unused_tie = unused_rx_aux & 1'b0;

  // Handshake quality used by Discovery/Config/Retrain.
  wire rx_type_dltb = (rx_type_q == P_LTB_TYPE_DLTB[7:0]) || (P_LTB_TYPE_DLTB == 0);
  wire rx_type_cltb = (rx_type_q == P_LTB_TYPE_CLTB[7:0]) || (P_LTB_TYPE_CLTB == 0);
  wire rx_type_rltb = (rx_type_q == P_LTB_TYPE_RLTB[7:0]) || (P_LTB_TYPE_RLTB == 0);
  wire disc_ok = am_all & ~lid_bad_u & pcs_deskew_ok & saw_rx_ltb & rx_type_dltb;
  wire cfg_ok  = am_all & ~lid_bad_u & saw_rx_ltb & rx_type_cltb;
  wire rtr_ok  = am_all & ~lid_bad_u & (saw_rx_ltb ? rx_type_rltb : 1'b1);

  wire rx_chg_spd = rx_drs2_q[P_CHG_SPD_BIT] | cfg_req_change_speed;
  wire rx_want_eq = rx_req_eq_q | cfg_req_equalization | cfg_request_equalization;

  // Timer compare. Limits are parameters (implementation-defined, §13.2).
  reg [TMR_W-1:0] tmr_lim;
  always @* begin
    tmr_lim = {TMR_W{1'b1}};
    case (st)
      ST_PROBE: tmr_lim = (sub == SUB_0)
                         ? P_TMR_PROBE_WAIT[TMR_W-1:0]
                         : P_TMR_PROBE_CONFIRM[TMR_W-1:0];
      ST_RXEQ_OPTIMIZE: tmr_lim = P_TMR_RXEQ[TMR_W-1:0];
      ST_DISCOVERY: tmr_lim = (sub == SUB_0)
                            ? P_TMR_DISC_ACTIVE[TMR_W-1:0]
                            : P_TMR_DISC_CONFIRM[TMR_W-1:0];
      ST_CONFIG: tmr_lim = P_TMR_CFG[TMR_W-1:0];
      ST_SEND_NULLBLOCK: tmr_lim = P_TMR_NULL[TMR_W-1:0];
      ST_RETRAIN: tmr_lim = (sub == SUB_0)
                           ? P_TMR_RETRAIN_ACTIVE[TMR_W-1:0]
                           : P_TMR_RETRAIN_CONFIRM[TMR_W-1:0];
      ST_CHANGE_SPEED: tmr_lim = P_TMR_CHG_SPD[TMR_W-1:0];
      ST_EQUALIZATION: tmr_lim = P_TMR_EQ[TMR_W-1:0];
      ST_LINK_IDLE,
      ST_LINK_ACTIVE: tmr_lim = {TMR_W{1'b1}};
      default: tmr_lim = {TMR_W{1'b1}}; // WAIVER_LMSM_FSM_DEFAULT
    endcase
  end

  wire [TMR_W-1:0] tmr_step_ext = {{(TMR_W-8){1'b0}}, tmr_step_u};
  wire             tmr_to       = (tmr >= tmr_lim);
  wire             tmr_sat      = &tmr;
  wire [TMR_W-1:0] tmr_inc      = tmr_sat ? tmr : (tmr + tmr_step_ext);

  // ------------------------------------------------------------------
  // Next-state (SPEC §6.1 mermaid). Default → Link_Idle.
  // WAIVER_LMSM_FSM_DEFAULT: illegal/unreachable st/sub → Link_Idle.
  // Do not force illegal states from the TB (CODING_STYLE §4 / SPEC §10.5).
  // ------------------------------------------------------------------
  reg [4:0] st_n;
  reg [1:0] sub_n;
  reg       to_idle_fail;
  reg       to_idle_timeout;

  always @* begin
    st_n            = st;
    sub_n           = sub;
    to_idle_fail    = 1'b0;
    to_idle_timeout = 1'b0;
    case (st)
      ST_LINK_IDLE: begin
        // SPEC §6.1 mermaid + CTRL.LMSM_START (0x0000 bit1):
        //   !bypass & phy_ready & start → Probe
        //   bypass & fixed-rate & start → RXEQ_Optimize
        //   bypass & !fixed-rate & start → Discovery
        sub_n = SUB_0;
        if (csr_lmsm_start & pma_phy_ready) begin
          if (!csr_bypass_probe) begin
            st_n  = ST_PROBE;
            sub_n = SUB_0;
          end else if (cfg_fixed_rate_rxeq) begin
            st_n  = ST_RXEQ_OPTIMIZE;
            sub_n = SUB_0;
          end else begin
            st_n  = ST_DISCOVERY;
            sub_n = SUB_0;
          end
        end
      end

      ST_PROBE: begin
        if (sub == SUB_0) begin
          if (term_any | unused_tie | unused_hold_tie) begin
            sub_n = SUB_1;
          end else if (tmr_to) begin
            if (probe_try >= P_PROBE_MAX_RETRY[7:0]) begin
              st_n            = ST_LINK_IDLE;
              sub_n           = SUB_0;
              to_idle_fail    = 1'b1;
              to_idle_timeout = 1'b1;
            end else begin
              st_n  = ST_PROBE;
              sub_n = SUB_0;
            end
          end
        end else begin
          if (tmr_to) begin
            st_n  = ST_DISCOVERY;
            sub_n = SUB_0;
          end
        end
      end

      ST_RXEQ_OPTIMIZE: begin
        // M1 stub: empty-spin then Discovery (SPEC §6.1 / §13.2).
        if (tmr_to) begin
          st_n  = ST_DISCOVERY;
          sub_n = SUB_0;
        end
      end

      ST_DISCOVERY: begin
        if (lid_bad_u) begin
          st_n         = ST_LINK_IDLE;
          sub_n        = SUB_0;
          to_idle_fail = 1'b1;
        end else if (sub == SUB_0) begin
          if (am_all) begin
            sub_n = SUB_1;
          end else if (tmr_to) begin
            st_n            = ST_LINK_IDLE;
            sub_n           = SUB_0;
            to_idle_fail    = 1'b1;
            to_idle_timeout = 1'b1;
          end
        end else begin
          if (disc_ok) begin
            st_n  = ST_CONFIG;
            sub_n = SUB_0;
          end else if (tmr_to) begin
            st_n            = ST_LINK_IDLE;
            sub_n           = SUB_0;
            to_idle_fail    = 1'b1;
            to_idle_timeout = 1'b1;
          end
        end
      end

      ST_CONFIG: begin
        if (lid_bad_u) begin
          st_n         = ST_LINK_IDLE;
          sub_n        = SUB_0;
          to_idle_fail = 1'b1;
        end else if (sub == SUB_0) begin
          if (am_all) begin
            sub_n = SUB_1;
          end else if (tmr_to) begin
            st_n            = ST_LINK_IDLE;
            sub_n           = SUB_0;
            to_idle_fail    = 1'b1;
            to_idle_timeout = 1'b1;
          end
        end else if (sub == SUB_1) begin
          if (tmr_to || cfg_ok) begin
            sub_n = SUB_2;
          end
        end else begin
          if (cfg_ok) begin
            st_n  = ST_SEND_NULLBLOCK;
            sub_n = SUB_0;
          end else if (tmr_to) begin
            st_n            = ST_LINK_IDLE;
            sub_n           = SUB_0;
            to_idle_fail    = 1'b1;
            to_idle_timeout = 1'b1;
          end
        end
      end

      ST_SEND_NULLBLOCK: begin
        if (null_cnt >= P_NULL_BLK_NEED[7:0]) begin
          st_n  = ST_LINK_ACTIVE;
          sub_n = SUB_0;
        end else if (cfg_null_need_rediscovery) begin
          st_n  = ST_DISCOVERY;
          sub_n = SUB_0;
        end else if (tmr_to) begin
          if (retrain_left != 8'd0) begin
            st_n  = ST_RETRAIN;
            sub_n = SUB_0;
          end else begin
            st_n            = ST_LINK_IDLE;
            sub_n           = SUB_0;
            to_idle_fail    = 1'b1;
            to_idle_timeout = 1'b1;
          end
        end
      end

      ST_LINK_ACTIVE: begin
        if (dll_retrain_req | lid_bad_u) begin
          st_n  = ST_RETRAIN;
          sub_n = SUB_0;
        end
      end

      ST_RETRAIN: begin
        if (sub == SUB_0) begin
          if (am_all) begin
            sub_n = SUB_1;
          end else if (tmr_to) begin
            st_n            = ST_LINK_IDLE;
            sub_n           = SUB_0;
            to_idle_fail    = 1'b1;
            to_idle_timeout = 1'b1;
          end
        end else begin
          if (tmr_to && !rtr_ok) begin
            st_n            = ST_LINK_IDLE;
            sub_n           = SUB_0;
            to_idle_fail    = 1'b1;
            to_idle_timeout = 1'b1;
          end else if (rtr_ok || tmr_to) begin
            if (rx_chg_spd) begin
              st_n  = ST_CHANGE_SPEED;
              sub_n = SUB_0;
            end else if (rx_want_eq) begin
              st_n  = ST_EQUALIZATION;
              sub_n = SUB_0;
            end else if (cfg_null_need_rediscovery) begin
              st_n  = ST_DISCOVERY;
              sub_n = SUB_0;
            end else begin
              st_n  = ST_SEND_NULLBLOCK;
              sub_n = SUB_0;
            end
          end
        end
      end

      ST_CHANGE_SPEED: begin
        // M1: state exists; Data Rate stays 0 (SPEC §6.1).
        if (tmr_to) begin
          st_n  = ST_RETRAIN;
          sub_n = SUB_0;
        end
      end

      ST_EQUALIZATION: begin
        // M1 stub: empty-spin then Retrain (SPEC §6.1 / §13.2).
        if (tmr_to) begin
          st_n  = ST_RETRAIN;
          sub_n = SUB_0;
        end
      end

      default: begin
        st_n  = ST_LINK_IDLE;
        sub_n = SUB_0;
      end
    endcase
  end

  wire st_enter = (st_n != st) || (sub_n != sub);

  // pyc_reg bank (sync; rst_eff = rst_pyc | port_rst).
  always @(posedge core_clk) begin
    if (rst_eff) begin
      st            <= ST_LINK_IDLE;
      sub           <= SUB_0;
      tmr           <= {TMR_W{1'b0}};
      null_cnt      <= 8'd0;
      probe_try     <= 8'd0;
      retrain_left  <= P_MAX_RETRAIN[7:0];
      saw_rx_ltb    <= 1'b0;
      train_fail_q  <= 1'b0;
      train_to_q    <= 1'b0;
      rx_type_q     <= 8'd0;
      rx_link_q     <= 8'd0;
      rx_lane_q     <= 8'd0;
      rx_tlw_q      <= 6'd0;
      rx_rlw_q      <= 6'd0;
      rx_fec_ctrl_q <= 3'd0;
      rx_req_eq_q   <= 1'b0;
      rx_drs2_q     <= 8'd0;
    end else begin
      st           <= st_n;
      sub          <= sub_n;
      train_fail_q <= to_idle_fail;
      train_to_q   <= to_idle_timeout;

      if (st_enter) begin
        tmr        <= {TMR_W{1'b0}};
        saw_rx_ltb <= 1'b0;
        if (st_n == ST_SEND_NULLBLOCK)
          null_cnt <= 8'd0;
        if (st_n == ST_PROBE && sub_n == SUB_0 && st == ST_PROBE)
          probe_try <= (probe_try == 8'hFF) ? probe_try : (probe_try + 8'd1);
        if (st_n == ST_PROBE && st == ST_LINK_IDLE)
          probe_try <= 8'd0;
        if (st_n == ST_RETRAIN && st == ST_LINK_ACTIVE) begin
          if (retrain_left != 8'd0)
            retrain_left <= retrain_left - 8'd1;
        end
        if (st_n == ST_LINK_IDLE)
          retrain_left <= P_MAX_RETRAIN[7:0];
      end else begin
        tmr <= tmr_inc;
        if (st == ST_SEND_NULLBLOCK && null_cnt != 8'hFF)
          null_cnt <= null_cnt + 8'd1;
      end

      if (pcs2lmsm_ltb_valid) begin
        saw_rx_ltb    <= 1'b1;
        rx_type_q     <= pcs2lmsm_ltb_type;
        rx_link_q     <= pcs2lmsm_link_id;
        rx_lane_q     <= pcs2lmsm_lane_id;
        rx_tlw_q      <= pcs2lmsm_tlw;
        rx_rlw_q      <= pcs2lmsm_rlw;
        rx_fec_ctrl_q <= pcs2lmsm_fec_mode_ctrl;
        rx_req_eq_q   <= pcs2lmsm_request_equalization;
        rx_drs2_q     <= pcs2lmsm_data_rate_support_2;
      end
    end
  end

  // Keep latched RX fields that do not steer the SM in the cone.
  wire unused_rx_hold = ^{rx_link_q, rx_lane_q, rx_tlw_q, rx_rlw_q, rx_fec_ctrl_q};
  wire unused_hold_tie = unused_rx_hold & 1'b0;

  // ------------------------------------------------------------------
  // Outputs
  // ------------------------------------------------------------------
  assign lmsm_st   = st;
  assign link_up   = (st == ST_SEND_NULLBLOCK) | (st == ST_LINK_ACTIVE);
  assign link_ready = (st == ST_LINK_ACTIVE);
  assign lmsm_retrain_ack = (st == ST_RETRAIN);
  assign train_fail   = train_fail_q;
  assign train_to_inc = train_to_q;

  // PMA sideband. pma_*_width encoding table still 待定 (SPEC §3.2.5 / §13.2).
  // CSR PARAM_PHY.NUM_LANES_* is now binary 1/2/4/8 (SPEC §9 / REGMAP);
  // drive the same legal set here so reserved 0/3/5/6/7 are never produced.
  assign pma_data_rate_sel   = 4'd0; // SPEC §9 DATA_RATE = 0
  assign pma_tx_width =
      (NUM_LANES_TX == 8) ? 4'd8 :
      (NUM_LANES_TX == 4) ? 4'd4 :
      (NUM_LANES_TX == 2) ? 4'd2 : 4'd1;
  assign pma_rx_width =
      (NUM_LANES_RX == 8) ? 4'd8 :
      (NUM_LANES_RX == 4) ? 4'd4 :
      (NUM_LANES_RX == 2) ? 4'd2 : 4'd1;
  assign pma_lane_reverse_tx = cfg_lane_reverse_tx;
  assign pma_lane_reverse_rx = cfg_lane_reverse_rx;
  assign pma_polarity_inv    = cfg_polarity_inv;
  assign pma_probe_pulse_en  = (st == ST_PROBE) && (sub == SUB_0);

  // Pattern (SPEC §3.3.4). PCS latches at each LMB start.
  assign lmsm2pcs_pattern =
      (st == ST_LINK_IDLE)                        ? PAT_IDLE :
      ((st == ST_PROBE) || (st == ST_RXEQ_OPTIMIZE)) ? PAT_EEIB :
      (st == ST_LINK_ACTIVE)                      ? PAT_DLL  :
                                                    PAT_LTB;

  wire use_dltb = (st == ST_DISCOVERY);
  wire use_cltb = (st == ST_CONFIG);
  wire use_rltb = (st == ST_RETRAIN) || (st == ST_CHANGE_SPEED);
  wire use_eltb = (st == ST_EQUALIZATION);
  wire use_nltb = (st == ST_SEND_NULLBLOCK);
  assign lmsm2pcs_ltb_valid = use_dltb | use_cltb | use_rltb | use_eltb | use_nltb;

  // Structural 3-way mux: only PHYS / ASCEND / NULL. Default NULL (2).
  // Encoding 3 is RESERVED (SPEC §3.3.4). No path assigns 2'd3 / 2'b11.
  wire sel_phys   = (st == ST_DISCOVERY);
  wire sel_ascend = (st == ST_CONFIG) || (st == ST_LINK_ACTIVE);
  assign lmsm2pcs_lane_id_mode = sel_phys   ? LANE_ID_PHYS :
                                 sel_ascend ? LANE_ID_ASCEND :
                                              LANE_ID_NULL;

  assign lmsm2pcs_lane_id_base = cfg_lane_id_base;

  // ASCEND map: cfg_lane_id_map if non-zero, else base+i per physical lane.
  wire [8-1:0] auto_ascend;
  wire [8-1:0] null_map;
  genvar gi;
  generate
    for (gi = 0; gi < NUM_LANES_TX; gi = gi + 1) begin : g_ascend
      assign auto_ascend[8*gi+7:8*gi] = cfg_lane_id_base + gi[7:0];
      assign null_map[8*gi+7:8*gi]    = P_LANE_ID_NULL[7:0];
    end
  endgenerate
  wire map_is_zero = (cfg_lane_id_map == 8'd0);
  // PHYS/NULL: PCS ignores map (SPEC §3.3.4). Drive NULL sentinel so the
  // open §3.4.1.1 value is a named parameter, not a magic number.
  assign lmsm2pcs_lane_id_map = sel_ascend
      ? (map_is_zero ? auto_ascend : cfg_lane_id_map)
      : null_map;

  // TX LTB fields: live for the type this state sends; else 0 (§3.3.4).
  assign lmsm2pcs_ltb_type =
      use_dltb ? P_LTB_TYPE_DLTB[7:0] :
      use_cltb ? P_LTB_TYPE_CLTB[7:0] :
      use_rltb ? P_LTB_TYPE_RLTB[7:0] :
      use_eltb ? P_LTB_TYPE_ELTB[7:0] :
      use_nltb ? P_LTB_TYPE_NULL[7:0] : 8'd0;

  wire use_dltb_cltb = use_dltb | use_cltb;
  assign lmsm2pcs_link_id = use_dltb_cltb ? cfg_link_id : 8'd0;
  assign lmsm2pcs_tlw     = use_dltb_cltb ? cfg_tlw     : 6'd0;
  assign lmsm2pcs_rlw     = use_dltb_cltb ? cfg_rlw     : 6'd0;

  wire use_dltb_rltb = use_dltb | use_rltb;
  assign lmsm2pcs_data_rate_support_1 = use_dltb_rltb ? cfg_data_rate_support_1 : 8'd0;
  assign lmsm2pcs_data_rate_support_2 = use_dltb_rltb ? cfg_data_rate_support_2 : 8'd0;

  assign lmsm2pcs_fec_mode_support        = use_dltb ? cfg_fec_mode_support        : 8'd0;
  assign lmsm2pcs_port_type               = use_dltb ? cfg_port_type               : 1'b0;
  assign lmsm2pcs_portnego_random_value   = use_dltb ? cfg_portnego_random_value   : 7'd0;
  assign lmsm2pcs_fec_interleave_support  = use_dltb ? cfg_fec_interleave_support  : 4'd0;
  assign lmsm2pcs_rx_lane0_id             = use_dltb ? cfg_rx_lane0_id             : 3'd0;
  assign lmsm2pcs_max_link_width          = use_dltb ? cfg_max_link_width          : 3'd0;

  assign lmsm2pcs_eq_mode              = use_cltb ? cfg_eq_mode              : 2'd0;
  assign lmsm2pcs_fec_interleave_ctrl  = use_cltb ? cfg_fec_interleave_ctrl  : 1'b0;

  wire use_cltb_rltb = use_cltb | use_rltb;
  assign lmsm2pcs_fec_mode_ctrl = use_cltb_rltb ? cfg_fec_mode_ctrl : 3'd0;

  wire use_rltb_eltb = use_rltb | use_eltb;
  assign lmsm2pcs_eq_ctrl1          = use_rltb_eltb ? cfg_eq_ctrl1          : 6'd0;
  assign lmsm2pcs_eq_ctrl2          = use_rltb_eltb ? cfg_eq_ctrl2          : 8'd0;
  assign lmsm2pcs_eq_ctrl3          = use_rltb_eltb ? cfg_eq_ctrl3          : 8'd0;
  assign lmsm2pcs_first_pre_cursor  = use_rltb_eltb ? cfg_first_pre_cursor  : 6'd0;

  assign lmsm2pcs_eq_ctrl4          = use_eltb ? cfg_eq_ctrl4          : 8'd0;
  assign lmsm2pcs_eq_reject         = use_eltb ? cfg_eq_reject         : 1'b0;
  assign lmsm2pcs_current_eq_phase  = use_eltb ? cfg_current_eq_phase  : 2'd0;
  assign lmsm2pcs_preset_mode_en    = use_eltb ? cfg_preset_mode_en    : 1'b0;
  assign lmsm2pcs_tx_preset         = use_eltb ? cfg_tx_preset         : 4'd0;

  assign lmsm2pcs_fec_crc_mode_reject        = use_rltb ? cfg_fec_crc_mode_reject        : 1'b0;
  assign lmsm2pcs_pre_fec_ber_meas_st        = use_rltb ? cfg_pre_fec_ber_meas_st        : 2'd0;
  assign lmsm2pcs_fec_interleave_enable      = use_rltb ? cfg_fec_interleave_enable      : 1'b0;
  assign lmsm2pcs_fec_interleave_ctrl_reject = use_rltb ? cfg_fec_interleave_ctrl_reject : 1'b0;
  assign lmsm2pcs_request_equalization       = use_rltb ? cfg_request_equalization       : 1'b0;
  assign lmsm2pcs_crc_mode_ctrl              = use_rltb ? cfg_crc_mode_ctrl              : 3'd0;
  assign lmsm2pcs_local_tx_preset            = use_rltb ? cfg_local_tx_preset            : 4'd0;

  // SPEC §10.1: tb_test_mode=0 → observe ports hold 0; inject does not intervene.
  assign tb_obs_link_ready = hook_en ? link_ready : 1'b0;
  assign tb_obs_link_up    = hook_en ? link_up    : 1'b0;
  assign tb_obs_lmsm_st    = hook_en ? st         : 5'd0;

endmodule

