// Generated by pycc (pyCircuit) from pycircuit/cmn/ub_cmn_mem_1r1w.py — do not edit.
// Regenerate: python3 scripts/emit_rtl.py
// PRODUCT (TEST_HOOKS=0). SPEC §10 lists no tb_* hooks — no HOOKS netlist.
// Variant d8w16: DEPTH=8 WIDTH=16 WMASK_W=16 N=1 AW=3
// Ports: core_clk, we, waddr[3-1:0], wdata[16-1:0], re, raddr[3-1:0], rdata[16-1:0]
// 1R1W, registered rdata (1-cycle), same-address same-cycle read-old.
// No rst_pyc port; array and rdata are not reset.
// OOR addresses are not truncated.

`include "pyc_reg.v"

// Generated by pycc (pyCircuit)
// Module: ub_cmn_mem_1r1w_d8w16

module ub_cmn_mem_1r1w_d8w16 (
  input core_clk,
  input we,
  input [2:0] waddr,
  input [15:0] wdata,
  input re,
  input [2:0] raddr,
  output [15:0] rdata
);
  // pyc_reg requires !pyc.reset; PRODUCT ties it off.
  // Array and rdata are not reset (undefined until a defined read).
  wire rst = 1'b0;


wire [15:0] cell__ub_cmn_mem_1r1w__L123; // pyc.name="cell__ub_cmn_mem_1r1w__L123"
wire [15:0] cell__ub_cmn_mem_1r1w__L123_2; // pyc.name="cell__ub_cmn_mem_1r1w__L123"
wire [15:0] cell__ub_cmn_mem_1r1w__L123_3; // pyc.name="cell__ub_cmn_mem_1r1w__L123"
wire [15:0] cell__ub_cmn_mem_1r1w__L123_4; // pyc.name="cell__ub_cmn_mem_1r1w__L123"
wire [15:0] cell__ub_cmn_mem_1r1w__L123_5; // pyc.name="cell__ub_cmn_mem_1r1w__L123"
wire [15:0] cell__ub_cmn_mem_1r1w__L123_6; // pyc.name="cell__ub_cmn_mem_1r1w__L123"
wire [15:0] cell__ub_cmn_mem_1r1w__L123_7; // pyc.name="cell__ub_cmn_mem_1r1w__L123"
wire [15:0] cell__ub_cmn_mem_1r1w__L123_8; // pyc.name="cell__ub_cmn_mem_1r1w__L123"
wire [15:0] hi__ub_cmn_mem_1r1w__L161; // pyc.name="hi__ub_cmn_mem_1r1w__L161"
wire [15:0] hi__ub_cmn_mem_1r1w__L161_2; // pyc.name="hi__ub_cmn_mem_1r1w__L161"
wire [15:0] hi__ub_cmn_mem_1r1w__L161_3; // pyc.name="hi__ub_cmn_mem_1r1w__L161"
wire [15:0] hi__ub_cmn_mem_1r1w__L161_4; // pyc.name="hi__ub_cmn_mem_1r1w__L161"
wire [15:0] lo__ub_cmn_mem_1r1w__L160; // pyc.name="lo__ub_cmn_mem_1r1w__L160"
wire [15:0] lo__ub_cmn_mem_1r1w__L160_2; // pyc.name="lo__ub_cmn_mem_1r1w__L160"
wire [15:0] lo__ub_cmn_mem_1r1w__L160_3; // pyc.name="lo__ub_cmn_mem_1r1w__L160"
wire [15:0] lo__ub_cmn_mem_1r1w__L160_4; // pyc.name="lo__ub_cmn_mem_1r1w__L160"
wire [15:0] mem_0; // pyc.name="mem_0"
wire [15:0] mem_0__next; // pyc.name="mem_0__next"
wire [15:0] mem_1; // pyc.name="mem_1"
wire [15:0] mem_1__next; // pyc.name="mem_1__next"
wire [15:0] mem_2; // pyc.name="mem_2"
wire [15:0] mem_2__next; // pyc.name="mem_2__next"
wire [15:0] mem_3; // pyc.name="mem_3"
wire [15:0] mem_3__next; // pyc.name="mem_3__next"
wire [15:0] mem_4; // pyc.name="mem_4"
wire [15:0] mem_4__next; // pyc.name="mem_4__next"
wire [15:0] mem_5; // pyc.name="mem_5"
wire [15:0] mem_5__next; // pyc.name="mem_5__next"
wire [15:0] mem_6; // pyc.name="mem_6"
wire [15:0] mem_6__next; // pyc.name="mem_6__next"
wire [15:0] mem_7; // pyc.name="mem_7"
wire [15:0] mem_7__next; // pyc.name="mem_7__next"
wire pyc_and_11; // op=pyc.and
wire pyc_and_35; // op=pyc.and
wire pyc_and_40; // op=pyc.and
wire pyc_and_45; // op=pyc.and
wire pyc_and_50; // op=pyc.and
wire pyc_and_55; // op=pyc.and
wire pyc_and_60; // op=pyc.and
wire pyc_and_65; // op=pyc.and
wire [15:0] pyc_comb_12; // op=pyc.comb
wire [2:0] pyc_comb_13; // op=pyc.comb
wire [2:0] pyc_comb_14; // op=pyc.comb
wire [2:0] pyc_comb_15; // op=pyc.comb
wire [2:0] pyc_comb_16; // op=pyc.comb
wire [2:0] pyc_comb_17; // op=pyc.comb
wire [2:0] pyc_comb_18; // op=pyc.comb
wire [2:0] pyc_comb_19; // op=pyc.comb
wire pyc_comb_20; // op=pyc.comb
wire [2:0] pyc_comb_21; // op=pyc.comb
wire [15:0] pyc_comb_22; // op=pyc.comb
wire [15:0] pyc_comb_23; // op=pyc.comb
wire [15:0] pyc_comb_24; // op=pyc.comb
wire [15:0] pyc_comb_25; // op=pyc.comb
wire [15:0] pyc_comb_26; // op=pyc.comb
wire [15:0] pyc_comb_27; // op=pyc.comb
wire [15:0] pyc_comb_28; // op=pyc.comb
wire [15:0] pyc_comb_29; // op=pyc.comb
wire pyc_comb_30; // op=pyc.comb
wire [2:0] pyc_comb_31; // op=pyc.comb
wire pyc_comb_32; // op=pyc.comb
wire [15:0] pyc_comb_36; // op=pyc.comb
wire pyc_comb_37; // op=pyc.comb
wire [15:0] pyc_comb_41; // op=pyc.comb
wire pyc_comb_42; // op=pyc.comb
wire [15:0] pyc_comb_46; // op=pyc.comb
wire pyc_comb_47; // op=pyc.comb
wire [15:0] pyc_comb_51; // op=pyc.comb
wire pyc_comb_52; // op=pyc.comb
wire [15:0] pyc_comb_56; // op=pyc.comb
wire pyc_comb_57; // op=pyc.comb
wire [15:0] pyc_comb_61; // op=pyc.comb
wire pyc_comb_62; // op=pyc.comb
wire [15:0] pyc_comb_66; // op=pyc.comb
wire pyc_comb_67; // op=pyc.comb
wire [15:0] pyc_comb_79; // op=pyc.comb
wire [15:0] pyc_comb_81; // op=pyc.comb
wire [2:0] pyc_constant_1; // op=pyc.constant
wire [15:0] pyc_constant_2; // op=pyc.constant
wire [2:0] pyc_constant_3; // op=pyc.constant
wire [2:0] pyc_constant_4; // op=pyc.constant
wire [2:0] pyc_constant_5; // op=pyc.constant
wire [2:0] pyc_constant_6; // op=pyc.constant
wire [2:0] pyc_constant_7; // op=pyc.constant
wire [2:0] pyc_constant_8; // op=pyc.constant
wire [2:0] pyc_constant_9; // op=pyc.constant
wire pyc_eq_10; // op=pyc.eq
wire pyc_eq_34; // op=pyc.eq
wire pyc_eq_39; // op=pyc.eq
wire pyc_eq_44; // op=pyc.eq
wire pyc_eq_49; // op=pyc.eq
wire pyc_eq_54; // op=pyc.eq
wire pyc_eq_59; // op=pyc.eq
wire pyc_eq_64; // op=pyc.eq
wire pyc_extract_69; // op=pyc.extract
wire pyc_extract_74; // op=pyc.extract
wire pyc_extract_77; // op=pyc.extract
wire [15:0] pyc_mux_70; // op=pyc.mux
wire [15:0] pyc_mux_71; // op=pyc.mux
wire [15:0] pyc_mux_72; // op=pyc.mux
wire [15:0] pyc_mux_73; // op=pyc.mux
wire [15:0] pyc_mux_75; // op=pyc.mux
wire [15:0] pyc_mux_76; // op=pyc.mux
wire [15:0] pyc_mux_78; // op=pyc.mux
wire [15:0] pyc_reg_33; // op=pyc.reg
wire [15:0] pyc_reg_38; // op=pyc.reg
wire [15:0] pyc_reg_43; // op=pyc.reg
wire [15:0] pyc_reg_48; // op=pyc.reg
wire [15:0] pyc_reg_53; // op=pyc.reg
wire [15:0] pyc_reg_58; // op=pyc.reg
wire [15:0] pyc_reg_63; // op=pyc.reg
wire [15:0] pyc_reg_68; // op=pyc.reg
wire [15:0] pyc_reg_80; // op=pyc.reg
wire [2:0] raddr__ub_cmn_mem_1r1w__L115; // pyc.name="raddr__ub_cmn_mem_1r1w__L115"
wire [15:0] rdata_q; // pyc.name="rdata_q"
wire [15:0] rdata_q__next; // pyc.name="rdata_q__next"
wire [15:0] rdata_q__ub_cmn_mem_1r1w__L166; // pyc.name="rdata_q__ub_cmn_mem_1r1w__L166"
wire re__ub_cmn_mem_1r1w__L114; // pyc.name="re__ub_cmn_mem_1r1w__L114"
wire [2:0] waddr__ub_cmn_mem_1r1w__L111; // pyc.name="waddr__ub_cmn_mem_1r1w__L111"
wire [15:0] wdata__ub_cmn_mem_1r1w__L112; // pyc.name="wdata__ub_cmn_mem_1r1w__L112"
wire we__ub_cmn_mem_1r1w__L110; // pyc.name="we__ub_cmn_mem_1r1w__L110"
wire wr_hit__ub_cmn_mem_1r1w__L121; // pyc.name="wr_hit__ub_cmn_mem_1r1w__L121"
wire wr_hit__ub_cmn_mem_1r1w__L121_2; // pyc.name="wr_hit__ub_cmn_mem_1r1w__L121"
wire wr_hit__ub_cmn_mem_1r1w__L121_3; // pyc.name="wr_hit__ub_cmn_mem_1r1w__L121"
wire wr_hit__ub_cmn_mem_1r1w__L121_4; // pyc.name="wr_hit__ub_cmn_mem_1r1w__L121"
wire wr_hit__ub_cmn_mem_1r1w__L121_5; // pyc.name="wr_hit__ub_cmn_mem_1r1w__L121"
wire wr_hit__ub_cmn_mem_1r1w__L121_6; // pyc.name="wr_hit__ub_cmn_mem_1r1w__L121"
wire wr_hit__ub_cmn_mem_1r1w__L121_7; // pyc.name="wr_hit__ub_cmn_mem_1r1w__L121"
wire wr_hit__ub_cmn_mem_1r1w__L121_8; // pyc.name="wr_hit__ub_cmn_mem_1r1w__L121"

// --- Combinational (netlist)
assign pyc_constant_1 = 3'd0;
assign pyc_constant_2 = 16'd0;
assign pyc_constant_3 = 3'd1;
assign pyc_constant_4 = 3'd2;
assign pyc_constant_5 = 3'd3;
assign pyc_constant_6 = 3'd4;
assign pyc_constant_7 = 3'd5;
assign pyc_constant_8 = 3'd6;
assign pyc_constant_9 = 3'd7;
assign we__ub_cmn_mem_1r1w__L110 = we;
assign waddr__ub_cmn_mem_1r1w__L111 = waddr;
assign wdata__ub_cmn_mem_1r1w__L112 = wdata;
assign mem_7__next = wdata__ub_cmn_mem_1r1w__L112;
assign mem_6__next = wdata__ub_cmn_mem_1r1w__L112;
assign mem_5__next = wdata__ub_cmn_mem_1r1w__L112;
assign mem_4__next = wdata__ub_cmn_mem_1r1w__L112;
assign mem_3__next = wdata__ub_cmn_mem_1r1w__L112;
assign mem_2__next = wdata__ub_cmn_mem_1r1w__L112;
assign mem_1__next = wdata__ub_cmn_mem_1r1w__L112;
assign mem_0__next = wdata__ub_cmn_mem_1r1w__L112;
assign re__ub_cmn_mem_1r1w__L114 = re;
assign raddr__ub_cmn_mem_1r1w__L115 = raddr;
assign pyc_eq_10 = (waddr__ub_cmn_mem_1r1w__L111 == pyc_constant_1);
assign pyc_and_11 = (we__ub_cmn_mem_1r1w__L110 & pyc_eq_10);
assign wr_hit__ub_cmn_mem_1r1w__L121 = pyc_and_11;
assign pyc_comb_12 = pyc_constant_2;
assign pyc_comb_13 = pyc_constant_3;
assign pyc_comb_14 = pyc_constant_4;
assign pyc_comb_15 = pyc_constant_5;
assign pyc_comb_16 = pyc_constant_6;
assign pyc_comb_17 = pyc_constant_7;
assign pyc_comb_18 = pyc_constant_8;
assign pyc_comb_19 = pyc_constant_9;
assign pyc_comb_20 = we__ub_cmn_mem_1r1w__L110;
assign pyc_comb_21 = waddr__ub_cmn_mem_1r1w__L111;
assign pyc_comb_22 = mem_7__next;
assign pyc_comb_23 = mem_6__next;
assign pyc_comb_24 = mem_5__next;
assign pyc_comb_25 = mem_4__next;
assign pyc_comb_26 = mem_3__next;
assign pyc_comb_27 = mem_2__next;
assign pyc_comb_28 = mem_1__next;
assign pyc_comb_29 = mem_0__next;
assign pyc_comb_30 = re__ub_cmn_mem_1r1w__L114;
assign pyc_comb_31 = raddr__ub_cmn_mem_1r1w__L115;
assign pyc_comb_32 = wr_hit__ub_cmn_mem_1r1w__L121;
assign mem_0 = pyc_reg_33;
assign cell__ub_cmn_mem_1r1w__L123 = mem_0;
assign pyc_eq_34 = (pyc_comb_21 == pyc_comb_13);
assign pyc_and_35 = (pyc_comb_20 & pyc_eq_34);
assign wr_hit__ub_cmn_mem_1r1w__L121_2 = pyc_and_35;
assign pyc_comb_36 = cell__ub_cmn_mem_1r1w__L123;
assign pyc_comb_37 = wr_hit__ub_cmn_mem_1r1w__L121_2;
assign mem_1 = pyc_reg_38;
assign cell__ub_cmn_mem_1r1w__L123_2 = mem_1;
assign pyc_eq_39 = (pyc_comb_21 == pyc_comb_14);
assign pyc_and_40 = (pyc_comb_20 & pyc_eq_39);
assign wr_hit__ub_cmn_mem_1r1w__L121_3 = pyc_and_40;
assign pyc_comb_41 = cell__ub_cmn_mem_1r1w__L123_2;
assign pyc_comb_42 = wr_hit__ub_cmn_mem_1r1w__L121_3;
assign mem_2 = pyc_reg_43;
assign cell__ub_cmn_mem_1r1w__L123_3 = mem_2;
assign pyc_eq_44 = (pyc_comb_21 == pyc_comb_15);
assign pyc_and_45 = (pyc_comb_20 & pyc_eq_44);
assign wr_hit__ub_cmn_mem_1r1w__L121_4 = pyc_and_45;
assign pyc_comb_46 = cell__ub_cmn_mem_1r1w__L123_3;
assign pyc_comb_47 = wr_hit__ub_cmn_mem_1r1w__L121_4;
assign mem_3 = pyc_reg_48;
assign cell__ub_cmn_mem_1r1w__L123_4 = mem_3;
assign pyc_eq_49 = (pyc_comb_21 == pyc_comb_16);
assign pyc_and_50 = (pyc_comb_20 & pyc_eq_49);
assign wr_hit__ub_cmn_mem_1r1w__L121_5 = pyc_and_50;
assign pyc_comb_51 = cell__ub_cmn_mem_1r1w__L123_4;
assign pyc_comb_52 = wr_hit__ub_cmn_mem_1r1w__L121_5;
assign mem_4 = pyc_reg_53;
assign cell__ub_cmn_mem_1r1w__L123_5 = mem_4;
assign pyc_eq_54 = (pyc_comb_21 == pyc_comb_17);
assign pyc_and_55 = (pyc_comb_20 & pyc_eq_54);
assign wr_hit__ub_cmn_mem_1r1w__L121_6 = pyc_and_55;
assign pyc_comb_56 = cell__ub_cmn_mem_1r1w__L123_5;
assign pyc_comb_57 = wr_hit__ub_cmn_mem_1r1w__L121_6;
assign mem_5 = pyc_reg_58;
assign cell__ub_cmn_mem_1r1w__L123_6 = mem_5;
assign pyc_eq_59 = (pyc_comb_21 == pyc_comb_18);
assign pyc_and_60 = (pyc_comb_20 & pyc_eq_59);
assign wr_hit__ub_cmn_mem_1r1w__L121_7 = pyc_and_60;
assign pyc_comb_61 = cell__ub_cmn_mem_1r1w__L123_6;
assign pyc_comb_62 = wr_hit__ub_cmn_mem_1r1w__L121_7;
assign mem_6 = pyc_reg_63;
assign cell__ub_cmn_mem_1r1w__L123_7 = mem_6;
assign pyc_eq_64 = (pyc_comb_21 == pyc_comb_19);
assign pyc_and_65 = (pyc_comb_20 & pyc_eq_64);
assign wr_hit__ub_cmn_mem_1r1w__L121_8 = pyc_and_65;
assign pyc_comb_66 = cell__ub_cmn_mem_1r1w__L123_7;
assign pyc_comb_67 = wr_hit__ub_cmn_mem_1r1w__L121_8;
assign mem_7 = pyc_reg_68;
assign cell__ub_cmn_mem_1r1w__L123_8 = mem_7;
assign pyc_extract_69 = pyc_comb_31[0];
assign lo__ub_cmn_mem_1r1w__L160 = pyc_comb_36;
assign hi__ub_cmn_mem_1r1w__L161 = pyc_comb_41;
assign pyc_mux_70 = (pyc_extract_69 ? hi__ub_cmn_mem_1r1w__L161 : lo__ub_cmn_mem_1r1w__L160);
assign lo__ub_cmn_mem_1r1w__L160_2 = pyc_comb_46;
assign hi__ub_cmn_mem_1r1w__L161_2 = pyc_comb_51;
assign pyc_mux_71 = (pyc_extract_69 ? hi__ub_cmn_mem_1r1w__L161_2 : lo__ub_cmn_mem_1r1w__L160_2);
assign lo__ub_cmn_mem_1r1w__L160_3 = pyc_comb_56;
assign hi__ub_cmn_mem_1r1w__L161_3 = pyc_comb_61;
assign pyc_mux_72 = (pyc_extract_69 ? hi__ub_cmn_mem_1r1w__L161_3 : lo__ub_cmn_mem_1r1w__L160_3);
assign lo__ub_cmn_mem_1r1w__L160_4 = pyc_comb_66;
assign hi__ub_cmn_mem_1r1w__L161_4 = cell__ub_cmn_mem_1r1w__L123_8;
assign pyc_mux_73 = (pyc_extract_69 ? hi__ub_cmn_mem_1r1w__L161_4 : lo__ub_cmn_mem_1r1w__L160_4);
assign pyc_extract_74 = pyc_comb_31[1];
assign pyc_mux_75 = (pyc_extract_74 ? pyc_mux_71 : pyc_mux_70);
assign pyc_mux_76 = (pyc_extract_74 ? pyc_mux_73 : pyc_mux_72);
assign pyc_extract_77 = pyc_comb_31[2];
assign pyc_mux_78 = (pyc_extract_77 ? pyc_mux_76 : pyc_mux_75);
assign rdata_q__next = pyc_mux_78;
assign pyc_comb_79 = rdata_q__next;
assign rdata_q = pyc_reg_80;
assign rdata_q__ub_cmn_mem_1r1w__L166 = rdata_q;
assign pyc_comb_81 = rdata_q__ub_cmn_mem_1r1w__L166;

// --- Sequential primitives
pyc_reg #(.WIDTH(16)) pyc_reg_33_inst (
  .clk(core_clk),
  .rst(rst),
  .en(pyc_comb_32),
  .d(pyc_comb_29),
  .init(pyc_comb_12),
  .q(pyc_reg_33)
);
pyc_reg #(.WIDTH(16)) pyc_reg_38_inst (
  .clk(core_clk),
  .rst(rst),
  .en(pyc_comb_37),
  .d(pyc_comb_28),
  .init(pyc_comb_12),
  .q(pyc_reg_38)
);
pyc_reg #(.WIDTH(16)) pyc_reg_43_inst (
  .clk(core_clk),
  .rst(rst),
  .en(pyc_comb_42),
  .d(pyc_comb_27),
  .init(pyc_comb_12),
  .q(pyc_reg_43)
);
pyc_reg #(.WIDTH(16)) pyc_reg_48_inst (
  .clk(core_clk),
  .rst(rst),
  .en(pyc_comb_47),
  .d(pyc_comb_26),
  .init(pyc_comb_12),
  .q(pyc_reg_48)
);
pyc_reg #(.WIDTH(16)) pyc_reg_53_inst (
  .clk(core_clk),
  .rst(rst),
  .en(pyc_comb_52),
  .d(pyc_comb_25),
  .init(pyc_comb_12),
  .q(pyc_reg_53)
);
pyc_reg #(.WIDTH(16)) pyc_reg_58_inst (
  .clk(core_clk),
  .rst(rst),
  .en(pyc_comb_57),
  .d(pyc_comb_24),
  .init(pyc_comb_12),
  .q(pyc_reg_58)
);
pyc_reg #(.WIDTH(16)) pyc_reg_63_inst (
  .clk(core_clk),
  .rst(rst),
  .en(pyc_comb_62),
  .d(pyc_comb_23),
  .init(pyc_comb_12),
  .q(pyc_reg_63)
);
pyc_reg #(.WIDTH(16)) pyc_reg_68_inst (
  .clk(core_clk),
  .rst(rst),
  .en(pyc_comb_67),
  .d(pyc_comb_22),
  .init(pyc_comb_12),
  .q(pyc_reg_68)
);
pyc_reg #(.WIDTH(16)) pyc_reg_80_inst (
  .clk(core_clk),
  .rst(rst),
  .en(pyc_comb_30),
  .d(pyc_comb_79),
  .init(pyc_comb_12),
  .q(pyc_reg_80)
);

assign rdata = pyc_comb_81;

endmodule

