// Generated by rtl/csr/ub_csr_regs.py from docs/regmap/regmap.yaml.
// GENERATED — edit docs/regmap/regmap.yaml
// pyc4.0 leaf ub_csr. TEST_HOOKS=1 (Python generation-time).
// Attribute-driven: W1C / saturating / WO self-clear / pulse_cycles / TEST gate / csr_err.
// SPEC §2.2 / §3.2.3 / §11.

module ub_csr (
  input  wire        core_clk,
  input  wire        rst_pyc,
  input  wire        csr_req,
  input  wire        csr_wr,
  input  wire [15:0] csr_addr,
  input  wire [31:0] csr_wdata,
  output wire        csr_ready,
  output reg         csr_rvalid,
  output reg  [31:0] csr_rdata,
  output reg         csr_err,
  input  wire        hw_link_up,
  input  wire        hw_link_ready,
  input  wire        hw_dll_status_up,
  input  wire  [4:0] hw_lmsm_st,
  input  wire  [1:0] hw_dll_sm_st,
  input  wire  [2:0] hw_retry_req_st,
  input  wire  [1:0] hw_retry_ack_st,
  input  wire        ev_fec_uncorr,
  input  wire        ev_crc_fail,
  input  wire        ev_retry_err,
  input  wire        ev_crd_proto,
  input  wire        ev_train_fail,
  input  wire        ev_bad_vl,
  input  wire        ev_crd_uf,
  input  wire        inc_fec_uncorr,
  input  wire        inc_crc_fail,
  input  wire        inc_retry_req,
  input  wire        inc_retry_to,
  input  wire        inc_crd_of,
  input  wire        inc_crd_to,
  input  wire        inc_train_to,
  input  wire        inc_bad_vl,
  input  wire        inc_crd_uf,
  output wire        port_rst_pulse,
  output wire        csr_lmsm_start,
  output wire        csr_irq_en,
  output wire  [6:0] csr_irq_mask,
  output wire [31:0] csr_port_cna,
  output wire  [7:0] csr_tmr_scale,
  output wire        csr_crd_to_dis,
  output wire  [7:0] csr_am_ivl_scale,
  output wire        irq,
  input  wire        tb_test_mode
);

  assign csr_ready = 1'b1; // full-word, no wait (SPEC §3.2.3)
  wire addr_aligned = (csr_addr[1:0] == 2'b00);
  wire req_fire     = csr_req;
  wire wr_fire      = req_fire & csr_wr;
  wire in_test      = (csr_addr[15:0] >= 16'h0300) && (csr_addr[15:0] <= 16'h03FF);
  wire test_active  = tb_test_mode;
  wire test_hit     = in_test & addr_aligned;

  wire sel_ctrl = addr_aligned && (csr_addr[15:0] == 16'h0000);
  wire sel_status = addr_aligned && (csr_addr[15:0] == 16'h0004);
  wire sel_irq_status = addr_aligned && (csr_addr[15:0] == 16'h0008);
  wire sel_irq_mask = addr_aligned && (csr_addr[15:0] == 16'h000C);
  wire sel_port_cna = addr_aligned && (csr_addr[15:0] == 16'h0010);
  wire sel_param_phy = addr_aligned && (csr_addr[15:0] == 16'h0100);
  wire sel_param_fec = addr_aligned && (csr_addr[15:0] == 16'h0104);
  wire sel_param_dll = addr_aligned && (csr_addr[15:0] == 16'h0108);
  wire sel_param_retry = addr_aligned && (csr_addr[15:0] == 16'h010C);
  wire sel_param_crd = addr_aligned && (csr_addr[15:0] == 16'h0110);
  wire sel_param_init_feature = addr_aligned && (csr_addr[15:0] == 16'h0114);
  wire sel_param_init_vl = addr_aligned && (csr_addr[15:0] == 16'h0118);
  wire sel_cnt_fec_uncorr = addr_aligned && (csr_addr[15:0] == 16'h0200);
  wire sel_cnt_crc_fail = addr_aligned && (csr_addr[15:0] == 16'h0204);
  wire sel_cnt_retry_req = addr_aligned && (csr_addr[15:0] == 16'h0208);
  wire sel_cnt_retry_to = addr_aligned && (csr_addr[15:0] == 16'h020C);
  wire sel_cnt_crd_of = addr_aligned && (csr_addr[15:0] == 16'h0210);
  wire sel_cnt_crd_to = addr_aligned && (csr_addr[15:0] == 16'h0214);
  wire sel_cnt_train_to = addr_aligned && (csr_addr[15:0] == 16'h0218);
  wire sel_cnt_bad_vl = addr_aligned && (csr_addr[15:0] == 16'h021C);
  wire sel_cnt_crd_uf = addr_aligned && (csr_addr[15:0] == 16'h0220);
  wire sel_cnt_clr = addr_aligned && (csr_addr[15:0] == 16'h0224);
  wire sel_lmsm_tmr_scale = addr_aligned && (csr_addr[15:0] == 16'h0300);
  wire sel_crd_to_dis = addr_aligned && (csr_addr[15:0] == 16'h0304);
  wire sel_pcs_tx_test = addr_aligned && (csr_addr[15:0] == 16'h0308);
  wire sel_appd_port_basic = addr_aligned && (csr_addr[15:0] == 16'h1000);
  wire sel_appd_link_cap = addr_aligned && (csr_addr[15:0] == 16'h1100);
  wire sel_appd_link_log = addr_aligned && (csr_addr[15:0] == 16'h1200);
  wire sel_appd_lmsm_st = addr_aligned && (csr_addr[15:0] == 16'h1E00);
  wire sel_appd_port_err = addr_aligned && (csr_addr[15:0] == 16'h1F00);
  wire sel_fn   = sel_ctrl | sel_status | sel_irq_status | sel_irq_mask | sel_port_cna | sel_param_phy | sel_param_fec | sel_param_dll | sel_param_retry | sel_param_crd | sel_param_init_feature | sel_param_init_vl | sel_cnt_fec_uncorr | sel_cnt_crc_fail | sel_cnt_retry_req | sel_cnt_retry_to | sel_cnt_crd_of | sel_cnt_crd_to | sel_cnt_train_to | sel_cnt_bad_vl | sel_cnt_crd_uf | sel_cnt_clr | sel_appd_port_basic | sel_appd_link_cap | sel_appd_link_log | sel_appd_lmsm_st | sel_appd_port_err;
  wire sel_test = sel_lmsm_tmr_scale | sel_crd_to_dis | sel_pcs_tx_test;
  wire wr_ok_fn   = wr_fire & sel_fn;
  wire wr_ok_test = wr_fire & sel_test & test_active;

  reg        q_ctrl_lmsm_start;
  reg        q_ctrl_irq_en;
  reg  [6:0] q_irq_mask_mask;
  reg [31:0] q_port_cna_cna;
  reg  [7:0] q_lmsm_tmr_scale_scale;
  reg        q_crd_to_dis_dis;
  reg  [7:0] q_pcs_tx_test_am_ivl_scale;
  reg        q_irq_status_fec_uncorr;
  reg        q_irq_status_crc_fail;
  reg        q_irq_status_retry_err;
  reg        q_irq_status_crd_proto;
  reg        q_irq_status_train_fail;
  reg        q_irq_status_bad_vl;
  reg        q_irq_status_crd_uf;
  reg [31:0] q_cnt_fec_uncorr_count;
  reg [31:0] q_cnt_crc_fail_count;
  reg [31:0] q_cnt_retry_req_count;
  reg [31:0] q_cnt_retry_to_count;
  reg [31:0] q_cnt_crd_of_count;
  reg [31:0] q_cnt_crd_to_count;
  reg [31:0] q_cnt_train_to_count;
  reg [31:0] q_cnt_bad_vl_count;
  reg [31:0] q_cnt_crd_uf_count;
  reg [4:0] cnt_ctrl_port_rst;

  wire wr_ctrl_lmsm_start = wr_ok_fn & sel_ctrl;
  wire wr_ctrl_irq_en = wr_ok_fn & sel_ctrl;
  wire wr_irq_mask_mask = wr_ok_fn & sel_irq_mask;
  wire wr_port_cna_cna = wr_ok_fn & sel_port_cna;
  wire wr_lmsm_tmr_scale_scale = wr_ok_test & sel_lmsm_tmr_scale;
  wire wr_crd_to_dis_dis = wr_ok_test & sel_crd_to_dis;
  wire wr_pcs_tx_test_am_ivl_scale = wr_ok_test & sel_pcs_tx_test;
  wire wr_irq_status_fec_uncorr = wr_ok_fn & sel_irq_status;
  wire wr_irq_status_crc_fail = wr_ok_fn & sel_irq_status;
  wire wr_irq_status_retry_err = wr_ok_fn & sel_irq_status;
  wire wr_irq_status_crd_proto = wr_ok_fn & sel_irq_status;
  wire wr_irq_status_train_fail = wr_ok_fn & sel_irq_status;
  wire wr_irq_status_bad_vl = wr_ok_fn & sel_irq_status;
  wire wr_irq_status_crd_uf = wr_ok_fn & sel_irq_status;
  wire wr_ctrl_port_rst = wr_ok_fn & sel_ctrl;
  wire wr_cnt_clr_fec_uncorr = wr_ok_fn & sel_cnt_clr;
  wire wr_cnt_clr_crc_fail = wr_ok_fn & sel_cnt_clr;
  wire wr_cnt_clr_retry_req = wr_ok_fn & sel_cnt_clr;
  wire wr_cnt_clr_retry_to = wr_ok_fn & sel_cnt_clr;
  wire wr_cnt_clr_crd_of = wr_ok_fn & sel_cnt_clr;
  wire wr_cnt_clr_crd_to = wr_ok_fn & sel_cnt_clr;
  wire wr_cnt_clr_train_to = wr_ok_fn & sel_cnt_clr;
  wire wr_cnt_clr_bad_vl = wr_ok_fn & sel_cnt_clr;
  wire wr_cnt_clr_crd_uf = wr_ok_fn & sel_cnt_clr;

  wire clr_cnt_fec_uncorr = wr_cnt_clr_fec_uncorr & csr_wdata[0];
  wire clr_cnt_crc_fail = wr_cnt_clr_crc_fail & csr_wdata[1];
  wire clr_cnt_retry_req = wr_cnt_clr_retry_req & csr_wdata[2];
  wire clr_cnt_retry_to = wr_cnt_clr_retry_to & csr_wdata[3];
  wire clr_cnt_crd_of = wr_cnt_clr_crd_of & csr_wdata[4];
  wire clr_cnt_crd_to = wr_cnt_clr_crd_to & csr_wdata[5];
  wire clr_cnt_train_to = wr_cnt_clr_train_to & csr_wdata[6];
  wire clr_cnt_bad_vl = wr_cnt_clr_bad_vl & csr_wdata[7];
  wire clr_cnt_crd_uf = wr_cnt_clr_crd_uf & csr_wdata[8];

  wire inc_fec_uncorr_qual = inc_fec_uncorr;
  wire inc_crc_fail_qual = inc_crc_fail;
  wire inc_retry_req_qual = inc_retry_req;
  wire inc_retry_to_qual = inc_retry_to;
  wire inc_crd_of_qual = inc_crd_of;
  wire inc_crd_to_qual = inc_crd_to & ~csr_crd_to_dis;
  wire inc_train_to_qual = inc_train_to;
  wire inc_bad_vl_qual = inc_bad_vl;
  wire inc_crd_uf_qual = inc_crd_uf;

  always @(posedge core_clk) begin
    if (rst_pyc) begin
      q_ctrl_lmsm_start <= 1'h0;
      q_ctrl_irq_en <= 1'h0;
      q_irq_mask_mask <= 7'h7f;
      q_port_cna_cna <= 32'h0;
      q_lmsm_tmr_scale_scale <= 8'h0;
      q_crd_to_dis_dis <= 1'h0;
      q_pcs_tx_test_am_ivl_scale <= 8'h0;
      q_irq_status_fec_uncorr <= 1'h0;
      q_irq_status_crc_fail <= 1'h0;
      q_irq_status_retry_err <= 1'h0;
      q_irq_status_crd_proto <= 1'h0;
      q_irq_status_train_fail <= 1'h0;
      q_irq_status_bad_vl <= 1'h0;
      q_irq_status_crd_uf <= 1'h0;
      q_cnt_fec_uncorr_count <= 32'h0;
      q_cnt_crc_fail_count <= 32'h0;
      q_cnt_retry_req_count <= 32'h0;
      q_cnt_retry_to_count <= 32'h0;
      q_cnt_crd_of_count <= 32'h0;
      q_cnt_crd_to_count <= 32'h0;
      q_cnt_train_to_count <= 32'h0;
      q_cnt_bad_vl_count <= 32'h0;
      q_cnt_crd_uf_count <= 32'h0;
      cnt_ctrl_port_rst <= 5'd0;
    end else begin
      if (wr_ctrl_lmsm_start) q_ctrl_lmsm_start <= csr_wdata[1];
      if (wr_ctrl_irq_en) q_ctrl_irq_en <= csr_wdata[2];
      if (wr_irq_mask_mask) q_irq_mask_mask <= csr_wdata[6:0];
      if (wr_port_cna_cna) q_port_cna_cna <= csr_wdata[31:0];
      if (wr_lmsm_tmr_scale_scale) q_lmsm_tmr_scale_scale <= csr_wdata[7:0];
      if (wr_crd_to_dis_dis) q_crd_to_dis_dis <= csr_wdata[0];
      if (wr_pcs_tx_test_am_ivl_scale) q_pcs_tx_test_am_ivl_scale <= csr_wdata[7:0];
      q_irq_status_fec_uncorr <= (q_irq_status_fec_uncorr | ev_fec_uncorr) & ~(wr_irq_status_fec_uncorr & csr_wdata[0]);
      q_irq_status_crc_fail <= (q_irq_status_crc_fail | ev_crc_fail) & ~(wr_irq_status_crc_fail & csr_wdata[1]);
      q_irq_status_retry_err <= (q_irq_status_retry_err | ev_retry_err) & ~(wr_irq_status_retry_err & csr_wdata[2]);
      q_irq_status_crd_proto <= (q_irq_status_crd_proto | ev_crd_proto) & ~(wr_irq_status_crd_proto & csr_wdata[3]);
      q_irq_status_train_fail <= (q_irq_status_train_fail | ev_train_fail) & ~(wr_irq_status_train_fail & csr_wdata[4]);
      q_irq_status_bad_vl <= (q_irq_status_bad_vl | ev_bad_vl) & ~(wr_irq_status_bad_vl & csr_wdata[5]);
      q_irq_status_crd_uf <= (q_irq_status_crd_uf | ev_crd_uf) & ~(wr_irq_status_crd_uf & csr_wdata[6]);
      if (clr_cnt_fec_uncorr)
        q_cnt_fec_uncorr_count <= 32'h0;
      else if (inc_fec_uncorr_qual && q_cnt_fec_uncorr_count != 32'hffffffff)
        q_cnt_fec_uncorr_count <= q_cnt_fec_uncorr_count + 1'b1;
      if (clr_cnt_crc_fail)
        q_cnt_crc_fail_count <= 32'h0;
      else if (inc_crc_fail_qual && q_cnt_crc_fail_count != 32'hffffffff)
        q_cnt_crc_fail_count <= q_cnt_crc_fail_count + 1'b1;
      if (clr_cnt_retry_req)
        q_cnt_retry_req_count <= 32'h0;
      else if (inc_retry_req_qual && q_cnt_retry_req_count != 32'hffffffff)
        q_cnt_retry_req_count <= q_cnt_retry_req_count + 1'b1;
      if (clr_cnt_retry_to)
        q_cnt_retry_to_count <= 32'h0;
      else if (inc_retry_to_qual && q_cnt_retry_to_count != 32'hffffffff)
        q_cnt_retry_to_count <= q_cnt_retry_to_count + 1'b1;
      if (clr_cnt_crd_of)
        q_cnt_crd_of_count <= 32'h0;
      else if (inc_crd_of_qual && q_cnt_crd_of_count != 32'hffffffff)
        q_cnt_crd_of_count <= q_cnt_crd_of_count + 1'b1;
      if (clr_cnt_crd_to)
        q_cnt_crd_to_count <= 32'h0;
      else if (inc_crd_to_qual && q_cnt_crd_to_count != 32'hffffffff)
        q_cnt_crd_to_count <= q_cnt_crd_to_count + 1'b1;
      if (clr_cnt_train_to)
        q_cnt_train_to_count <= 32'h0;
      else if (inc_train_to_qual && q_cnt_train_to_count != 32'hffffffff)
        q_cnt_train_to_count <= q_cnt_train_to_count + 1'b1;
      if (clr_cnt_bad_vl)
        q_cnt_bad_vl_count <= 32'h0;
      else if (inc_bad_vl_qual && q_cnt_bad_vl_count != 32'hffffffff)
        q_cnt_bad_vl_count <= q_cnt_bad_vl_count + 1'b1;
      if (clr_cnt_crd_uf)
        q_cnt_crd_uf_count <= 32'h0;
      else if (inc_crd_uf_qual && q_cnt_crd_uf_count != 32'hffffffff)
        q_cnt_crd_uf_count <= q_cnt_crd_uf_count + 1'b1;
      if (wr_ctrl_port_rst & csr_wdata[0])
        cnt_ctrl_port_rst <= 5'd16;
      else if (cnt_ctrl_port_rst != 5'd0)
        cnt_ctrl_port_rst <= cnt_ctrl_port_rst - 1'b1;
    end
  end

  assign port_rst_pulse = (cnt_ctrl_port_rst != 5'd0);
  assign csr_lmsm_start = q_ctrl_lmsm_start;
  assign csr_irq_en = q_ctrl_irq_en;
  assign csr_irq_mask = q_irq_mask_mask;
  assign csr_port_cna = q_port_cna_cna;
  assign csr_tmr_scale = test_active ? q_lmsm_tmr_scale_scale : 8'h0;
  assign csr_crd_to_dis = test_active ? q_crd_to_dis_dis : 1'h0;
  assign csr_am_ivl_scale = test_active ? q_pcs_tx_test_am_ivl_scale : 8'h0;

  wire [6:0] irq_sticky = {q_irq_status_crd_uf, q_irq_status_bad_vl, q_irq_status_train_fail, q_irq_status_crd_proto, q_irq_status_retry_err, q_irq_status_crc_fail, q_irq_status_fec_uncorr};
  wire [6:0] irq_mask_w = q_irq_mask_mask;
  assign irq = q_ctrl_irq_en & |(irq_sticky & ~irq_mask_w);

  wire [31:0] rdata_ctrl = {29'h0, q_ctrl_irq_en, q_ctrl_lmsm_start, 1'h0};
  wire [31:0] rdata_status = {17'h0, hw_retry_ack_st, hw_retry_req_st, hw_dll_sm_st, hw_lmsm_st, hw_dll_status_up, hw_link_ready, hw_link_up};
  wire [31:0] rdata_irq_status = {25'h0, q_irq_status_crd_uf, q_irq_status_bad_vl, q_irq_status_train_fail, q_irq_status_crd_proto, q_irq_status_retry_err, q_irq_status_crc_fail, q_irq_status_fec_uncorr};
  wire [31:0] rdata_irq_mask = {25'h0, q_irq_mask_mask};
  wire [31:0] rdata_port_cna = {q_port_cna_cna};
  wire [31:0] rdata_param_phy = {9'h0, 1'h0, 8'h20, 4'h1, 4'h1, 4'h0, 2'h2};
  wire [31:0] rdata_param_fec = {27'h0, 2'h1, 3'h2};
  wire [31:0] rdata_param_dll = {10'h0, 1'h1, 8'h20, 8'h1, 5'h2};
  wire [31:0] rdata_param_retry = {8'h4, 8'hf, 16'h100};
  wire [31:0] rdata_param_crd = {16'h400, 16'h280};
  wire [31:0] rdata_param_init_feature = {15'h3, 1'h0, 16'h1};
  wire [31:0] rdata_param_init_vl = {16'h0, 16'h3};
  wire [31:0] rdata_cnt_fec_uncorr = {q_cnt_fec_uncorr_count};
  wire [31:0] rdata_cnt_crc_fail = {q_cnt_crc_fail_count};
  wire [31:0] rdata_cnt_retry_req = {q_cnt_retry_req_count};
  wire [31:0] rdata_cnt_retry_to = {q_cnt_retry_to_count};
  wire [31:0] rdata_cnt_crd_of = {q_cnt_crd_of_count};
  wire [31:0] rdata_cnt_crd_to = {q_cnt_crd_to_count};
  wire [31:0] rdata_cnt_train_to = {q_cnt_train_to_count};
  wire [31:0] rdata_cnt_bad_vl = {q_cnt_bad_vl_count};
  wire [31:0] rdata_cnt_crd_uf = {q_cnt_crd_uf_count};
  wire [31:0] rdata_cnt_clr = {23'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0, 1'h0};
  wire [31:0] rdata_lmsm_tmr_scale = {24'h0, q_lmsm_tmr_scale_scale};
  wire [31:0] rdata_crd_to_dis = {31'h0, q_crd_to_dis_dis};
  wire [31:0] rdata_pcs_tx_test = {24'h0, q_pcs_tx_test_am_ivl_scale};
  wire [31:0] rdata_appd_port_basic = {32'h0};
  wire [31:0] rdata_appd_link_cap = {32'h0};
  wire [31:0] rdata_appd_link_log = {32'h0};
  wire [31:0] rdata_appd_lmsm_st = {32'h0};
  wire [31:0] rdata_appd_port_err = {32'h0};

  reg [31:0] rdata_n;
  reg        err_n;
  always @* begin
    rdata_n = 32'h0;
    err_n   = 1'b0;
    if (req_fire) begin
      if (!addr_aligned) begin
        err_n = 1'b1;
      end else if (test_hit) begin
        err_n = 1'b0; // mapped; PRODUCT / tb_test_mode=0: rdata=0 write-ignore
        if (test_active) begin
          if (sel_lmsm_tmr_scale) rdata_n = rdata_lmsm_tmr_scale;
          if (sel_crd_to_dis) rdata_n = rdata_crd_to_dis;
          if (sel_pcs_tx_test) rdata_n = rdata_pcs_tx_test;
        end
      end else begin
        if (sel_ctrl) rdata_n = rdata_ctrl;
        else if (sel_status) rdata_n = rdata_status;
        else if (sel_irq_status) rdata_n = rdata_irq_status;
        else if (sel_irq_mask) rdata_n = rdata_irq_mask;
        else if (sel_port_cna) rdata_n = rdata_port_cna;
        else if (sel_param_phy) rdata_n = rdata_param_phy;
        else if (sel_param_fec) rdata_n = rdata_param_fec;
        else if (sel_param_dll) rdata_n = rdata_param_dll;
        else if (sel_param_retry) rdata_n = rdata_param_retry;
        else if (sel_param_crd) rdata_n = rdata_param_crd;
        else if (sel_param_init_feature) rdata_n = rdata_param_init_feature;
        else if (sel_param_init_vl) rdata_n = rdata_param_init_vl;
        else if (sel_cnt_fec_uncorr) rdata_n = rdata_cnt_fec_uncorr;
        else if (sel_cnt_crc_fail) rdata_n = rdata_cnt_crc_fail;
        else if (sel_cnt_retry_req) rdata_n = rdata_cnt_retry_req;
        else if (sel_cnt_retry_to) rdata_n = rdata_cnt_retry_to;
        else if (sel_cnt_crd_of) rdata_n = rdata_cnt_crd_of;
        else if (sel_cnt_crd_to) rdata_n = rdata_cnt_crd_to;
        else if (sel_cnt_train_to) rdata_n = rdata_cnt_train_to;
        else if (sel_cnt_bad_vl) rdata_n = rdata_cnt_bad_vl;
        else if (sel_cnt_crd_uf) rdata_n = rdata_cnt_crd_uf;
        else if (sel_cnt_clr) rdata_n = rdata_cnt_clr;
        else if (sel_appd_port_basic) rdata_n = rdata_appd_port_basic;
        else if (sel_appd_link_cap) rdata_n = rdata_appd_link_cap;
        else if (sel_appd_link_log) rdata_n = rdata_appd_link_log;
        else if (sel_appd_lmsm_st) rdata_n = rdata_appd_lmsm_st;
        else if (sel_appd_port_err) rdata_n = rdata_appd_port_err;
        else err_n = 1'b1; // unmapped
      end
    end
  end

  always @(posedge core_clk) begin
    if (rst_pyc) begin
      csr_rvalid <= 1'b0;
      csr_rdata  <= 32'h0;
      csr_err    <= 1'b0;
    end else begin
      csr_rvalid <= req_fire & ~csr_wr; // write cycle: next csr_rvalid=0 (SPEC §3.2.3)
      csr_rdata  <= rdata_n;
      csr_err    <= req_fire ? err_n : 1'b0;
    end
  end

endmodule

