// Generated by pycircuit/csr/ub_csr.py via pycircuit.compile() + pycc --emit=verilog
// GENERATED — edit docs/regmap/regmap.yaml
// pyc4.0 leaf ub_csr_product_x8_vl2. TEST_HOOKS=1 variant=product_x8_vl2.
// lukebest/pyCircuit @43cc5918e3d09ecc0c814cabef6c1384cb9980ae; backend pycc / LLVM 19.
// Attribute-driven Circuit API: W1C / saturating / WO pulse / TEST gate / csr_err.
// SPEC §2.2 / §3.2.3 / §11. Not string-templated Verilog.
`include "pyc_reg.v"



// Generated by pycc (pyCircuit)
// Module: ub_csr_product_x8_vl2

module ub_csr_product_x8_vl2 (
  input core_clk,
  input rst_pyc,
  input csr_req,
  input csr_wr,
  input [15:0] csr_addr,
  input [31:0] csr_wdata,
  input hw_link_up,
  input hw_link_ready,
  input hw_dll_status_up,
  input [4:0] hw_lmsm_st,
  input [1:0] hw_dll_sm_st,
  input [2:0] hw_retry_req_st,
  input [1:0] hw_retry_ack_st,
  input ev_fec_uncorr,
  input ev_crc_fail,
  input ev_retry_err,
  input ev_crd_proto,
  input ev_train_fail,
  input ev_bad_vl,
  input ev_crd_uf,
  input inc_fec_uncorr,
  input inc_crc_fail,
  input inc_retry_req,
  input inc_retry_to,
  input inc_crd_of,
  input inc_crd_to,
  input inc_train_to,
  input inc_bad_vl,
  input inc_crd_uf,
  input tb_test_mode,
  output csr_ready,
  output port_rst_pulse,
  output csr_lmsm_start,
  output csr_irq_en,
  output [6:0] csr_irq_mask,
  output [31:0] csr_port_cna,
  output [7:0] csr_tmr_scale,
  output csr_crd_to_dis,
  output [7:0] csr_am_ivl_scale,
  output irq,
  output csr_rvalid,
  output [31:0] csr_rdata,
  output csr_err
);

wire [4:0] cnt_ctrl_port_rst; // pyc.name="cnt_ctrl_port_rst"
wire [4:0] cnt_ctrl_port_rst__next; // pyc.name="cnt_ctrl_port_rst__next"
wire csr_err_q; // pyc.name="csr_err_q"
wire csr_err_q__next; // pyc.name="csr_err_q__next"
wire [31:0] csr_rdata_q; // pyc.name="csr_rdata_q"
wire [31:0] csr_rdata_q__next; // pyc.name="csr_rdata_q__next"
wire csr_rvalid_q; // pyc.name="csr_rvalid_q"
wire csr_rvalid_q__next; // pyc.name="csr_rvalid_q__next"
wire [31:0] pyc_add_366; // op=pyc.add
wire [31:0] pyc_add_373; // op=pyc.add
wire [31:0] pyc_add_380; // op=pyc.add
wire [31:0] pyc_add_387; // op=pyc.add
wire [31:0] pyc_add_394; // op=pyc.add
wire [31:0] pyc_add_403; // op=pyc.add
wire [31:0] pyc_add_410; // op=pyc.add
wire [31:0] pyc_add_417; // op=pyc.add
wire [31:0] pyc_add_424; // op=pyc.add
wire pyc_and_100; // op=pyc.and
wire pyc_and_102; // op=pyc.and
wire pyc_and_104; // op=pyc.and
wire pyc_and_106; // op=pyc.and
wire pyc_and_108; // op=pyc.and
wire pyc_and_110; // op=pyc.and
wire pyc_and_112; // op=pyc.and
wire pyc_and_114; // op=pyc.and
wire pyc_and_116; // op=pyc.and
wire pyc_and_118; // op=pyc.and
wire pyc_and_120; // op=pyc.and
wire pyc_and_122; // op=pyc.and
wire pyc_and_124; // op=pyc.and
wire pyc_and_126; // op=pyc.and
wire pyc_and_128; // op=pyc.and
wire pyc_and_158; // op=pyc.and
wire pyc_and_159; // op=pyc.and
wire pyc_and_160; // op=pyc.and
wire pyc_and_259; // op=pyc.and
wire pyc_and_260; // op=pyc.and
wire pyc_and_261; // op=pyc.and
wire pyc_and_262; // op=pyc.and
wire pyc_and_263; // op=pyc.and
wire pyc_and_264; // op=pyc.and
wire pyc_and_265; // op=pyc.and
wire pyc_and_266; // op=pyc.and
wire pyc_and_268; // op=pyc.and
wire pyc_and_270; // op=pyc.and
wire pyc_and_272; // op=pyc.and
wire pyc_and_274; // op=pyc.and
wire pyc_and_276; // op=pyc.and
wire pyc_and_278; // op=pyc.and
wire pyc_and_280; // op=pyc.and
wire pyc_and_282; // op=pyc.and
wire pyc_and_284; // op=pyc.and
wire pyc_and_286; // op=pyc.and
wire pyc_and_328; // op=pyc.and
wire pyc_and_331; // op=pyc.and
wire pyc_and_333; // op=pyc.and
wire pyc_and_336; // op=pyc.and
wire pyc_and_338; // op=pyc.and
wire pyc_and_341; // op=pyc.and
wire pyc_and_343; // op=pyc.and
wire pyc_and_346; // op=pyc.and
wire pyc_and_348; // op=pyc.and
wire pyc_and_351; // op=pyc.and
wire pyc_and_353; // op=pyc.and
wire pyc_and_356; // op=pyc.and
wire pyc_and_358; // op=pyc.and
wire pyc_and_361; // op=pyc.and
wire pyc_and_365; // op=pyc.and
wire pyc_and_372; // op=pyc.and
wire pyc_and_379; // op=pyc.and
wire pyc_and_386; // op=pyc.and
wire pyc_and_393; // op=pyc.and
wire pyc_and_399; // op=pyc.and
wire pyc_and_402; // op=pyc.and
wire pyc_and_409; // op=pyc.and
wire pyc_and_416; // op=pyc.and
wire pyc_and_423; // op=pyc.and
wire pyc_and_428; // op=pyc.and
wire [6:0] pyc_and_438; // op=pyc.and
wire pyc_and_441; // op=pyc.and
wire pyc_and_471; // op=pyc.and
wire pyc_and_473; // op=pyc.and
wire pyc_and_475; // op=pyc.and
wire pyc_and_504; // op=pyc.and
wire pyc_and_511; // op=pyc.and
wire pyc_and_516; // op=pyc.and
wire pyc_and_60; // op=pyc.and
wire pyc_and_65; // op=pyc.and
wire pyc_and_66; // op=pyc.and
wire pyc_and_68; // op=pyc.and
wire pyc_and_70; // op=pyc.and
wire pyc_and_72; // op=pyc.and
wire pyc_and_74; // op=pyc.and
wire pyc_and_76; // op=pyc.and
wire pyc_and_78; // op=pyc.and
wire pyc_and_80; // op=pyc.and
wire pyc_and_82; // op=pyc.and
wire pyc_and_84; // op=pyc.and
wire pyc_and_86; // op=pyc.and
wire pyc_and_88; // op=pyc.and
wire pyc_and_90; // op=pyc.and
wire pyc_and_92; // op=pyc.and
wire pyc_and_94; // op=pyc.and
wire pyc_and_96; // op=pyc.and
wire pyc_and_98; // op=pyc.and
wire pyc_comb_161; // op=pyc.comb
wire pyc_comb_162; // op=pyc.comb
wire [6:0] pyc_comb_163; // op=pyc.comb
wire [31:0] pyc_comb_164; // op=pyc.comb
wire [7:0] pyc_comb_165; // op=pyc.comb
wire [4:0] pyc_comb_166; // op=pyc.comb
wire [31:0] pyc_comb_167; // op=pyc.comb
wire [31:0] pyc_comb_168; // op=pyc.comb
wire [4:0] pyc_comb_169; // op=pyc.comb
wire [4:0] pyc_comb_170; // op=pyc.comb
wire [6:0] pyc_comb_171; // op=pyc.comb
wire [28:0] pyc_comb_172; // op=pyc.comb
wire [16:0] pyc_comb_173; // op=pyc.comb
wire [24:0] pyc_comb_174; // op=pyc.comb
wire [23:0] pyc_comb_175; // op=pyc.comb
wire [30:0] pyc_comb_176; // op=pyc.comb
wire [31:0] pyc_comb_177; // op=pyc.comb
wire [31:0] pyc_comb_178; // op=pyc.comb
wire [31:0] pyc_comb_179; // op=pyc.comb
wire [31:0] pyc_comb_180; // op=pyc.comb
wire [31:0] pyc_comb_181; // op=pyc.comb
wire [31:0] pyc_comb_182; // op=pyc.comb
wire [31:0] pyc_comb_183; // op=pyc.comb
wire [31:0] pyc_comb_184; // op=pyc.comb
wire pyc_comb_185; // op=pyc.comb
wire pyc_comb_186; // op=pyc.comb
wire pyc_comb_187; // op=pyc.comb
wire pyc_comb_188; // op=pyc.comb
wire pyc_comb_189; // op=pyc.comb
wire pyc_comb_190; // op=pyc.comb
wire pyc_comb_191; // op=pyc.comb
wire pyc_comb_192; // op=pyc.comb
wire pyc_comb_193; // op=pyc.comb
wire pyc_comb_194; // op=pyc.comb
wire pyc_comb_195; // op=pyc.comb
wire pyc_comb_196; // op=pyc.comb
wire pyc_comb_197; // op=pyc.comb
wire pyc_comb_198; // op=pyc.comb
wire pyc_comb_199; // op=pyc.comb
wire pyc_comb_200; // op=pyc.comb
wire pyc_comb_201; // op=pyc.comb
wire pyc_comb_202; // op=pyc.comb
wire pyc_comb_203; // op=pyc.comb
wire pyc_comb_204; // op=pyc.comb
wire pyc_comb_205; // op=pyc.comb
wire pyc_comb_206; // op=pyc.comb
wire pyc_comb_207; // op=pyc.comb
wire pyc_comb_208; // op=pyc.comb
wire pyc_comb_209; // op=pyc.comb
wire pyc_comb_210; // op=pyc.comb
wire pyc_comb_211; // op=pyc.comb
wire pyc_comb_212; // op=pyc.comb
wire pyc_comb_213; // op=pyc.comb
wire pyc_comb_214; // op=pyc.comb
wire pyc_comb_215; // op=pyc.comb
wire [1:0] pyc_comb_218; // op=pyc.comb
wire [1:0] pyc_comb_219; // op=pyc.comb
wire pyc_comb_223; // op=pyc.comb
wire pyc_comb_224; // op=pyc.comb
wire [6:0] pyc_comb_232; // op=pyc.comb
wire [6:0] pyc_comb_233; // op=pyc.comb
wire pyc_comb_242; // op=pyc.comb
wire pyc_comb_243; // op=pyc.comb
wire pyc_comb_244; // op=pyc.comb
wire pyc_comb_245; // op=pyc.comb
wire pyc_comb_246; // op=pyc.comb
wire pyc_comb_247; // op=pyc.comb
wire pyc_comb_248; // op=pyc.comb
wire [4:0] pyc_comb_289; // op=pyc.comb
wire pyc_comb_290; // op=pyc.comb
wire pyc_comb_291; // op=pyc.comb
wire pyc_comb_292; // op=pyc.comb
wire pyc_comb_293; // op=pyc.comb
wire pyc_comb_294; // op=pyc.comb
wire pyc_comb_295; // op=pyc.comb
wire pyc_comb_296; // op=pyc.comb
wire pyc_comb_297; // op=pyc.comb
wire pyc_comb_298; // op=pyc.comb
wire pyc_comb_299; // op=pyc.comb
wire pyc_comb_300; // op=pyc.comb
wire pyc_comb_301; // op=pyc.comb
wire pyc_comb_302; // op=pyc.comb
wire pyc_comb_303; // op=pyc.comb
wire pyc_comb_304; // op=pyc.comb
wire pyc_comb_305; // op=pyc.comb
wire pyc_comb_306; // op=pyc.comb
wire pyc_comb_307; // op=pyc.comb
wire pyc_comb_308; // op=pyc.comb
wire pyc_comb_309; // op=pyc.comb
wire pyc_comb_310; // op=pyc.comb
wire pyc_comb_311; // op=pyc.comb
wire pyc_comb_312; // op=pyc.comb
wire [7:0] pyc_comb_313; // op=pyc.comb
wire pyc_comb_314; // op=pyc.comb
wire [7:0] pyc_comb_315; // op=pyc.comb
wire pyc_comb_316; // op=pyc.comb
wire [6:0] pyc_comb_320; // op=pyc.comb
wire [7:0] pyc_comb_324; // op=pyc.comb
wire [7:0] pyc_comb_325; // op=pyc.comb
wire pyc_comb_332; // op=pyc.comb
wire pyc_comb_337; // op=pyc.comb
wire pyc_comb_342; // op=pyc.comb
wire pyc_comb_347; // op=pyc.comb
wire pyc_comb_352; // op=pyc.comb
wire pyc_comb_357; // op=pyc.comb
wire pyc_comb_362; // op=pyc.comb
wire [31:0] pyc_comb_369; // op=pyc.comb
wire [31:0] pyc_comb_376; // op=pyc.comb
wire [31:0] pyc_comb_383; // op=pyc.comb
wire [31:0] pyc_comb_390; // op=pyc.comb
wire [31:0] pyc_comb_397; // op=pyc.comb
wire [31:0] pyc_comb_406; // op=pyc.comb
wire [31:0] pyc_comb_413; // op=pyc.comb
wire [31:0] pyc_comb_420; // op=pyc.comb
wire [31:0] pyc_comb_427; // op=pyc.comb
wire pyc_comb_434; // op=pyc.comb
wire [4:0] pyc_comb_435; // op=pyc.comb
wire pyc_comb_506; // op=pyc.comb
wire [31:0] pyc_comb_507; // op=pyc.comb
wire pyc_comb_508; // op=pyc.comb
wire pyc_comb_512; // op=pyc.comb
wire pyc_comb_513; // op=pyc.comb
wire pyc_comb_517; // op=pyc.comb
wire pyc_comb_518; // op=pyc.comb
wire [1:0] pyc_concat_216; // op=pyc.concat
wire [1:0] pyc_concat_217; // op=pyc.concat
wire [6:0] pyc_concat_230; // op=pyc.concat
wire [6:0] pyc_concat_231; // op=pyc.concat
wire [6:0] pyc_concat_436; // op=pyc.concat
wire [31:0] pyc_concat_442; // op=pyc.concat
wire [31:0] pyc_concat_443; // op=pyc.concat
wire [31:0] pyc_concat_444; // op=pyc.concat
wire [31:0] pyc_concat_445; // op=pyc.concat
wire [31:0] pyc_concat_446; // op=pyc.concat
wire [31:0] pyc_concat_447; // op=pyc.concat
wire [31:0] pyc_concat_448; // op=pyc.concat
wire [1:0] pyc_constant_1; // op=pyc.constant
wire [15:0] pyc_constant_10; // op=pyc.constant
wire [15:0] pyc_constant_11; // op=pyc.constant
wire [15:0] pyc_constant_12; // op=pyc.constant
wire [15:0] pyc_constant_13; // op=pyc.constant
wire [15:0] pyc_constant_14; // op=pyc.constant
wire [15:0] pyc_constant_15; // op=pyc.constant
wire [15:0] pyc_constant_16; // op=pyc.constant
wire [15:0] pyc_constant_17; // op=pyc.constant
wire [15:0] pyc_constant_18; // op=pyc.constant
wire [15:0] pyc_constant_19; // op=pyc.constant
wire [15:0] pyc_constant_2; // op=pyc.constant
wire [15:0] pyc_constant_20; // op=pyc.constant
wire [15:0] pyc_constant_21; // op=pyc.constant
wire [15:0] pyc_constant_22; // op=pyc.constant
wire [15:0] pyc_constant_23; // op=pyc.constant
wire [15:0] pyc_constant_24; // op=pyc.constant
wire [15:0] pyc_constant_25; // op=pyc.constant
wire [15:0] pyc_constant_26; // op=pyc.constant
wire [15:0] pyc_constant_27; // op=pyc.constant
wire [15:0] pyc_constant_28; // op=pyc.constant
wire [15:0] pyc_constant_29; // op=pyc.constant
wire [15:0] pyc_constant_3; // op=pyc.constant
wire [15:0] pyc_constant_30; // op=pyc.constant
wire [15:0] pyc_constant_31; // op=pyc.constant
wire [15:0] pyc_constant_32; // op=pyc.constant
wire [15:0] pyc_constant_33; // op=pyc.constant
wire pyc_constant_34; // op=pyc.constant
wire pyc_constant_35; // op=pyc.constant
wire [6:0] pyc_constant_36; // op=pyc.constant
wire [31:0] pyc_constant_37; // op=pyc.constant
wire [7:0] pyc_constant_38; // op=pyc.constant
wire [4:0] pyc_constant_39; // op=pyc.constant
wire [15:0] pyc_constant_4; // op=pyc.constant
wire [31:0] pyc_constant_40; // op=pyc.constant
wire [31:0] pyc_constant_41; // op=pyc.constant
wire [4:0] pyc_constant_42; // op=pyc.constant
wire [4:0] pyc_constant_43; // op=pyc.constant
wire [6:0] pyc_constant_44; // op=pyc.constant
wire [28:0] pyc_constant_45; // op=pyc.constant
wire [16:0] pyc_constant_46; // op=pyc.constant
wire [24:0] pyc_constant_47; // op=pyc.constant
wire [23:0] pyc_constant_48; // op=pyc.constant
wire [30:0] pyc_constant_49; // op=pyc.constant
wire [15:0] pyc_constant_5; // op=pyc.constant
wire [31:0] pyc_constant_50; // op=pyc.constant
wire [31:0] pyc_constant_51; // op=pyc.constant
wire [31:0] pyc_constant_52; // op=pyc.constant
wire [31:0] pyc_constant_53; // op=pyc.constant
wire [31:0] pyc_constant_54; // op=pyc.constant
wire [31:0] pyc_constant_55; // op=pyc.constant
wire [31:0] pyc_constant_56; // op=pyc.constant
wire [31:0] pyc_constant_57; // op=pyc.constant
wire [15:0] pyc_constant_6; // op=pyc.constant
wire [15:0] pyc_constant_7; // op=pyc.constant
wire [15:0] pyc_constant_8; // op=pyc.constant
wire [15:0] pyc_constant_9; // op=pyc.constant
wire pyc_eq_101; // op=pyc.eq
wire pyc_eq_103; // op=pyc.eq
wire pyc_eq_105; // op=pyc.eq
wire pyc_eq_107; // op=pyc.eq
wire pyc_eq_109; // op=pyc.eq
wire pyc_eq_111; // op=pyc.eq
wire pyc_eq_113; // op=pyc.eq
wire pyc_eq_115; // op=pyc.eq
wire pyc_eq_117; // op=pyc.eq
wire pyc_eq_119; // op=pyc.eq
wire pyc_eq_121; // op=pyc.eq
wire pyc_eq_123; // op=pyc.eq
wire pyc_eq_125; // op=pyc.eq
wire pyc_eq_127; // op=pyc.eq
wire pyc_eq_363; // op=pyc.eq
wire pyc_eq_370; // op=pyc.eq
wire pyc_eq_377; // op=pyc.eq
wire pyc_eq_384; // op=pyc.eq
wire pyc_eq_391; // op=pyc.eq
wire pyc_eq_400; // op=pyc.eq
wire pyc_eq_407; // op=pyc.eq
wire pyc_eq_414; // op=pyc.eq
wire pyc_eq_421; // op=pyc.eq
wire pyc_eq_429; // op=pyc.eq
wire pyc_eq_439; // op=pyc.eq
wire pyc_eq_59; // op=pyc.eq
wire pyc_eq_67; // op=pyc.eq
wire pyc_eq_69; // op=pyc.eq
wire pyc_eq_71; // op=pyc.eq
wire pyc_eq_73; // op=pyc.eq
wire pyc_eq_75; // op=pyc.eq
wire pyc_eq_77; // op=pyc.eq
wire pyc_eq_79; // op=pyc.eq
wire pyc_eq_81; // op=pyc.eq
wire pyc_eq_83; // op=pyc.eq
wire pyc_eq_85; // op=pyc.eq
wire pyc_eq_87; // op=pyc.eq
wire pyc_eq_89; // op=pyc.eq
wire pyc_eq_91; // op=pyc.eq
wire pyc_eq_93; // op=pyc.eq
wire pyc_eq_95; // op=pyc.eq
wire pyc_eq_97; // op=pyc.eq
wire pyc_eq_99; // op=pyc.eq
wire pyc_extract_221; // op=pyc.extract
wire pyc_extract_222; // op=pyc.extract
wire pyc_extract_235; // op=pyc.extract
wire pyc_extract_236; // op=pyc.extract
wire pyc_extract_237; // op=pyc.extract
wire pyc_extract_238; // op=pyc.extract
wire pyc_extract_239; // op=pyc.extract
wire pyc_extract_240; // op=pyc.extract
wire pyc_extract_241; // op=pyc.extract
wire pyc_extract_267; // op=pyc.extract
wire pyc_extract_269; // op=pyc.extract
wire pyc_extract_271; // op=pyc.extract
wire pyc_extract_273; // op=pyc.extract
wire pyc_extract_275; // op=pyc.extract
wire pyc_extract_277; // op=pyc.extract
wire pyc_extract_279; // op=pyc.extract
wire pyc_extract_281; // op=pyc.extract
wire pyc_extract_283; // op=pyc.extract
wire [6:0] pyc_extract_318; // op=pyc.extract
wire [7:0] pyc_extract_322; // op=pyc.extract
wire [1:0] pyc_extract_58; // op=pyc.extract
wire [7:0] pyc_mux_285; // op=pyc.mux
wire [7:0] pyc_mux_287; // op=pyc.mux
wire pyc_mux_288; // op=pyc.mux
wire pyc_mux_317; // op=pyc.mux
wire [6:0] pyc_mux_319; // op=pyc.mux
wire [31:0] pyc_mux_321; // op=pyc.mux
wire [7:0] pyc_mux_323; // op=pyc.mux
wire pyc_mux_326; // op=pyc.mux
wire [7:0] pyc_mux_327; // op=pyc.mux
wire [31:0] pyc_mux_367; // op=pyc.mux
wire [31:0] pyc_mux_368; // op=pyc.mux
wire [31:0] pyc_mux_374; // op=pyc.mux
wire [31:0] pyc_mux_375; // op=pyc.mux
wire [31:0] pyc_mux_381; // op=pyc.mux
wire [31:0] pyc_mux_382; // op=pyc.mux
wire [31:0] pyc_mux_388; // op=pyc.mux
wire [31:0] pyc_mux_389; // op=pyc.mux
wire [31:0] pyc_mux_395; // op=pyc.mux
wire [31:0] pyc_mux_396; // op=pyc.mux
wire [31:0] pyc_mux_404; // op=pyc.mux
wire [31:0] pyc_mux_405; // op=pyc.mux
wire [31:0] pyc_mux_411; // op=pyc.mux
wire [31:0] pyc_mux_412; // op=pyc.mux
wire [31:0] pyc_mux_418; // op=pyc.mux
wire [31:0] pyc_mux_419; // op=pyc.mux
wire [31:0] pyc_mux_425; // op=pyc.mux
wire [31:0] pyc_mux_426; // op=pyc.mux
wire [4:0] pyc_mux_432; // op=pyc.mux
wire [4:0] pyc_mux_433; // op=pyc.mux
wire [31:0] pyc_mux_449; // op=pyc.mux
wire [31:0] pyc_mux_450; // op=pyc.mux
wire [31:0] pyc_mux_451; // op=pyc.mux
wire [31:0] pyc_mux_452; // op=pyc.mux
wire [31:0] pyc_mux_453; // op=pyc.mux
wire [31:0] pyc_mux_454; // op=pyc.mux
wire [31:0] pyc_mux_455; // op=pyc.mux
wire [31:0] pyc_mux_456; // op=pyc.mux
wire [31:0] pyc_mux_457; // op=pyc.mux
wire [31:0] pyc_mux_458; // op=pyc.mux
wire [31:0] pyc_mux_459; // op=pyc.mux
wire [31:0] pyc_mux_460; // op=pyc.mux
wire [31:0] pyc_mux_461; // op=pyc.mux
wire [31:0] pyc_mux_462; // op=pyc.mux
wire [31:0] pyc_mux_463; // op=pyc.mux
wire [31:0] pyc_mux_464; // op=pyc.mux
wire [31:0] pyc_mux_465; // op=pyc.mux
wire [31:0] pyc_mux_466; // op=pyc.mux
wire [31:0] pyc_mux_467; // op=pyc.mux
wire [31:0] pyc_mux_468; // op=pyc.mux
wire [31:0] pyc_mux_469; // op=pyc.mux
wire [31:0] pyc_mux_470; // op=pyc.mux
wire [31:0] pyc_mux_472; // op=pyc.mux
wire [31:0] pyc_mux_474; // op=pyc.mux
wire [31:0] pyc_mux_476; // op=pyc.mux
wire pyc_not_330; // op=pyc.not
wire pyc_not_335; // op=pyc.not
wire pyc_not_340; // op=pyc.not
wire pyc_not_345; // op=pyc.not
wire pyc_not_350; // op=pyc.not
wire pyc_not_355; // op=pyc.not
wire pyc_not_360; // op=pyc.not
wire pyc_not_364; // op=pyc.not
wire pyc_not_371; // op=pyc.not
wire pyc_not_378; // op=pyc.not
wire pyc_not_385; // op=pyc.not
wire pyc_not_392; // op=pyc.not
wire pyc_not_398; // op=pyc.not
wire pyc_not_401; // op=pyc.not
wire pyc_not_408; // op=pyc.not
wire pyc_not_415; // op=pyc.not
wire pyc_not_422; // op=pyc.not
wire pyc_not_430; // op=pyc.not
wire [6:0] pyc_not_437; // op=pyc.not
wire pyc_not_440; // op=pyc.not
wire pyc_not_501; // op=pyc.not
wire pyc_not_502; // op=pyc.not
wire pyc_not_503; // op=pyc.not
wire pyc_not_510; // op=pyc.not
wire pyc_not_62; // op=pyc.not
wire pyc_not_64; // op=pyc.not
wire pyc_or_129; // op=pyc.or
wire pyc_or_130; // op=pyc.or
wire pyc_or_131; // op=pyc.or
wire pyc_or_132; // op=pyc.or
wire pyc_or_133; // op=pyc.or
wire pyc_or_134; // op=pyc.or
wire pyc_or_135; // op=pyc.or
wire pyc_or_136; // op=pyc.or
wire pyc_or_137; // op=pyc.or
wire pyc_or_138; // op=pyc.or
wire pyc_or_139; // op=pyc.or
wire pyc_or_140; // op=pyc.or
wire pyc_or_141; // op=pyc.or
wire pyc_or_142; // op=pyc.or
wire pyc_or_143; // op=pyc.or
wire pyc_or_144; // op=pyc.or
wire pyc_or_145; // op=pyc.or
wire pyc_or_146; // op=pyc.or
wire pyc_or_147; // op=pyc.or
wire pyc_or_148; // op=pyc.or
wire pyc_or_149; // op=pyc.or
wire pyc_or_150; // op=pyc.or
wire pyc_or_151; // op=pyc.or
wire pyc_or_152; // op=pyc.or
wire pyc_or_153; // op=pyc.or
wire pyc_or_154; // op=pyc.or
wire pyc_or_155; // op=pyc.or
wire pyc_or_156; // op=pyc.or
wire pyc_or_157; // op=pyc.or
wire pyc_or_329; // op=pyc.or
wire pyc_or_334; // op=pyc.or
wire pyc_or_339; // op=pyc.or
wire pyc_or_344; // op=pyc.or
wire pyc_or_349; // op=pyc.or
wire pyc_or_354; // op=pyc.or
wire pyc_or_359; // op=pyc.or
wire [31:0] pyc_or_477; // op=pyc.or
wire [31:0] pyc_or_478; // op=pyc.or
wire [31:0] pyc_or_479; // op=pyc.or
wire [31:0] pyc_or_480; // op=pyc.or
wire [31:0] pyc_or_481; // op=pyc.or
wire [31:0] pyc_or_482; // op=pyc.or
wire [31:0] pyc_or_483; // op=pyc.or
wire [31:0] pyc_or_484; // op=pyc.or
wire [31:0] pyc_or_485; // op=pyc.or
wire [31:0] pyc_or_486; // op=pyc.or
wire [31:0] pyc_or_487; // op=pyc.or
wire [31:0] pyc_or_488; // op=pyc.or
wire [31:0] pyc_or_489; // op=pyc.or
wire [31:0] pyc_or_490; // op=pyc.or
wire [31:0] pyc_or_491; // op=pyc.or
wire [31:0] pyc_or_492; // op=pyc.or
wire [31:0] pyc_or_493; // op=pyc.or
wire [31:0] pyc_or_494; // op=pyc.or
wire [31:0] pyc_or_495; // op=pyc.or
wire [31:0] pyc_or_496; // op=pyc.or
wire [31:0] pyc_or_497; // op=pyc.or
wire [31:0] pyc_or_498; // op=pyc.or
wire [31:0] pyc_or_499; // op=pyc.or
wire [31:0] pyc_or_500; // op=pyc.or
wire pyc_or_505; // op=pyc.or
wire [1:0] pyc_reg_220; // op=pyc.reg
wire [6:0] pyc_reg_225; // op=pyc.reg
wire [31:0] pyc_reg_226; // op=pyc.reg
wire [7:0] pyc_reg_227; // op=pyc.reg
wire pyc_reg_228; // op=pyc.reg
wire [7:0] pyc_reg_229; // op=pyc.reg
wire [6:0] pyc_reg_234; // op=pyc.reg
wire [31:0] pyc_reg_249; // op=pyc.reg
wire [31:0] pyc_reg_250; // op=pyc.reg
wire [31:0] pyc_reg_251; // op=pyc.reg
wire [31:0] pyc_reg_252; // op=pyc.reg
wire [31:0] pyc_reg_253; // op=pyc.reg
wire [31:0] pyc_reg_254; // op=pyc.reg
wire [31:0] pyc_reg_255; // op=pyc.reg
wire [31:0] pyc_reg_256; // op=pyc.reg
wire [31:0] pyc_reg_257; // op=pyc.reg
wire [4:0] pyc_reg_258; // op=pyc.reg
wire pyc_reg_509; // op=pyc.reg
wire [31:0] pyc_reg_514; // op=pyc.reg
wire pyc_reg_515; // op=pyc.reg
wire [4:0] pyc_sub_431; // op=pyc.sub
wire pyc_ult_61; // op=pyc.ult
wire pyc_ult_63; // op=pyc.ult
wire [31:0] q_cnt_bad_vl_count; // pyc.name="q_cnt_bad_vl_count"
wire [31:0] q_cnt_bad_vl_count__next; // pyc.name="q_cnt_bad_vl_count__next"
wire [31:0] q_cnt_crc_fail_count; // pyc.name="q_cnt_crc_fail_count"
wire [31:0] q_cnt_crc_fail_count__next; // pyc.name="q_cnt_crc_fail_count__next"
wire [31:0] q_cnt_crd_of_count; // pyc.name="q_cnt_crd_of_count"
wire [31:0] q_cnt_crd_of_count__next; // pyc.name="q_cnt_crd_of_count__next"
wire [31:0] q_cnt_crd_to_count; // pyc.name="q_cnt_crd_to_count"
wire [31:0] q_cnt_crd_to_count__next; // pyc.name="q_cnt_crd_to_count__next"
wire [31:0] q_cnt_crd_uf_count; // pyc.name="q_cnt_crd_uf_count"
wire [31:0] q_cnt_crd_uf_count__next; // pyc.name="q_cnt_crd_uf_count__next"
wire [31:0] q_cnt_fec_uncorr_count; // pyc.name="q_cnt_fec_uncorr_count"
wire [31:0] q_cnt_fec_uncorr_count__next; // pyc.name="q_cnt_fec_uncorr_count__next"
wire [31:0] q_cnt_retry_req_count; // pyc.name="q_cnt_retry_req_count"
wire [31:0] q_cnt_retry_req_count__next; // pyc.name="q_cnt_retry_req_count__next"
wire [31:0] q_cnt_retry_to_count; // pyc.name="q_cnt_retry_to_count"
wire [31:0] q_cnt_retry_to_count__next; // pyc.name="q_cnt_retry_to_count__next"
wire [31:0] q_cnt_train_to_count; // pyc.name="q_cnt_train_to_count"
wire [31:0] q_cnt_train_to_count__next; // pyc.name="q_cnt_train_to_count__next"
wire q_crd_to_dis_dis; // pyc.name="q_crd_to_dis_dis"
wire q_crd_to_dis_dis__next; // pyc.name="q_crd_to_dis_dis__next"
wire q_ctrl_irq_en; // pyc.name="q_ctrl_irq_en"
wire q_ctrl_irq_en__next; // pyc.name="q_ctrl_irq_en__next"
wire q_ctrl_lmsm_start; // pyc.name="q_ctrl_lmsm_start"
wire q_ctrl_lmsm_start__next; // pyc.name="q_ctrl_lmsm_start__next"
wire [6:0] q_irq_mask_mask; // pyc.name="q_irq_mask_mask"
wire [6:0] q_irq_mask_mask__next; // pyc.name="q_irq_mask_mask__next"
wire q_irq_status_bad_vl; // pyc.name="q_irq_status_bad_vl"
wire q_irq_status_bad_vl__next; // pyc.name="q_irq_status_bad_vl__next"
wire q_irq_status_crc_fail; // pyc.name="q_irq_status_crc_fail"
wire q_irq_status_crc_fail__next; // pyc.name="q_irq_status_crc_fail__next"
wire q_irq_status_crd_proto; // pyc.name="q_irq_status_crd_proto"
wire q_irq_status_crd_proto__next; // pyc.name="q_irq_status_crd_proto__next"
wire q_irq_status_crd_uf; // pyc.name="q_irq_status_crd_uf"
wire q_irq_status_crd_uf__next; // pyc.name="q_irq_status_crd_uf__next"
wire q_irq_status_fec_uncorr; // pyc.name="q_irq_status_fec_uncorr"
wire q_irq_status_fec_uncorr__next; // pyc.name="q_irq_status_fec_uncorr__next"
wire q_irq_status_retry_err; // pyc.name="q_irq_status_retry_err"
wire q_irq_status_retry_err__next; // pyc.name="q_irq_status_retry_err__next"
wire q_irq_status_train_fail; // pyc.name="q_irq_status_train_fail"
wire q_irq_status_train_fail__next; // pyc.name="q_irq_status_train_fail__next"
wire [7:0] q_lmsm_tmr_scale_scale; // pyc.name="q_lmsm_tmr_scale_scale"
wire [7:0] q_lmsm_tmr_scale_scale__next; // pyc.name="q_lmsm_tmr_scale_scale__next"
wire [7:0] q_pcs_tx_test_am_ivl_scale; // pyc.name="q_pcs_tx_test_am_ivl_scale"
wire [7:0] q_pcs_tx_test_am_ivl_scale__next; // pyc.name="q_pcs_tx_test_am_ivl_scale__next"
wire [31:0] q_port_cna_cna; // pyc.name="q_port_cna_cna"
wire [31:0] q_port_cna_cna__next; // pyc.name="q_port_cna_cna__next"

// --- Combinational (netlist)
assign csr_rdata_q = pyc_reg_514;
assign pyc_constant_1 = 2'd0;
assign pyc_constant_2 = 16'd768;
assign pyc_constant_3 = 16'd1023;
assign pyc_constant_4 = 16'd0;
assign pyc_constant_5 = 16'd4;
assign pyc_constant_6 = 16'd8;
assign pyc_constant_7 = 16'd12;
assign pyc_constant_8 = 16'd16;
assign pyc_constant_9 = 16'd256;
assign pyc_constant_10 = 16'd260;
assign pyc_constant_11 = 16'd264;
assign pyc_constant_12 = 16'd268;
assign pyc_constant_13 = 16'd272;
assign pyc_constant_14 = 16'd276;
assign pyc_constant_15 = 16'd280;
assign pyc_constant_16 = 16'd284;
assign pyc_constant_17 = 16'd512;
assign pyc_constant_18 = 16'd516;
assign pyc_constant_19 = 16'd520;
assign pyc_constant_20 = 16'd524;
assign pyc_constant_21 = 16'd528;
assign pyc_constant_22 = 16'd532;
assign pyc_constant_23 = 16'd536;
assign pyc_constant_24 = 16'd540;
assign pyc_constant_25 = 16'd544;
assign pyc_constant_26 = 16'd548;
assign pyc_constant_27 = 16'd772;
assign pyc_constant_28 = 16'd776;
assign pyc_constant_29 = 16'd4096;
assign pyc_constant_30 = 16'd4352;
assign pyc_constant_31 = 16'd4608;
assign pyc_constant_32 = 16'd7680;
assign pyc_constant_33 = 16'd7936;
assign pyc_constant_34 = 1'd1;
assign pyc_constant_35 = 1'd0;
assign pyc_constant_36 = 7'd127;
assign pyc_constant_37 = 32'd0;
assign pyc_constant_38 = 8'd0;
assign pyc_constant_39 = 5'd0;
assign pyc_constant_40 = 32'd4294967295;
assign pyc_constant_41 = 32'd1;
assign pyc_constant_42 = 5'd16;
assign pyc_constant_43 = 5'd1;
assign pyc_constant_44 = 7'd0;
assign pyc_constant_45 = 29'd0;
assign pyc_constant_46 = 17'd0;
assign pyc_constant_47 = 25'd0;
assign pyc_constant_48 = 24'd0;
assign pyc_constant_49 = 31'd0;
assign pyc_constant_50 = 32'd532994;
assign pyc_constant_51 = 32'd10;
assign pyc_constant_52 = 32'd2359330;
assign pyc_constant_53 = 32'd68092160;
assign pyc_constant_54 = 32'd67109504;
assign pyc_constant_55 = 32'd393217;
assign pyc_constant_56 = 32'd3;
assign pyc_constant_57 = 32'd2;
assign pyc_extract_58 = csr_addr[1:0];
assign pyc_eq_59 = (pyc_extract_58 == pyc_constant_1);
assign pyc_and_60 = (csr_req & csr_wr);
assign pyc_ult_61 = (csr_addr < pyc_constant_2);
assign pyc_not_62 = (~pyc_ult_61);
assign pyc_ult_63 = (pyc_constant_3 < csr_addr);
assign pyc_not_64 = (~pyc_ult_63);
assign pyc_and_65 = (pyc_not_62 & pyc_not_64);
assign pyc_and_66 = (pyc_and_65 & pyc_eq_59);
assign pyc_eq_67 = (csr_addr == pyc_constant_4);
assign pyc_and_68 = (pyc_eq_59 & pyc_eq_67);
assign pyc_eq_69 = (csr_addr == pyc_constant_5);
assign pyc_and_70 = (pyc_eq_59 & pyc_eq_69);
assign pyc_eq_71 = (csr_addr == pyc_constant_6);
assign pyc_and_72 = (pyc_eq_59 & pyc_eq_71);
assign pyc_eq_73 = (csr_addr == pyc_constant_7);
assign pyc_and_74 = (pyc_eq_59 & pyc_eq_73);
assign pyc_eq_75 = (csr_addr == pyc_constant_8);
assign pyc_and_76 = (pyc_eq_59 & pyc_eq_75);
assign pyc_eq_77 = (csr_addr == pyc_constant_9);
assign pyc_and_78 = (pyc_eq_59 & pyc_eq_77);
assign pyc_eq_79 = (csr_addr == pyc_constant_10);
assign pyc_and_80 = (pyc_eq_59 & pyc_eq_79);
assign pyc_eq_81 = (csr_addr == pyc_constant_11);
assign pyc_and_82 = (pyc_eq_59 & pyc_eq_81);
assign pyc_eq_83 = (csr_addr == pyc_constant_12);
assign pyc_and_84 = (pyc_eq_59 & pyc_eq_83);
assign pyc_eq_85 = (csr_addr == pyc_constant_13);
assign pyc_and_86 = (pyc_eq_59 & pyc_eq_85);
assign pyc_eq_87 = (csr_addr == pyc_constant_14);
assign pyc_and_88 = (pyc_eq_59 & pyc_eq_87);
assign pyc_eq_89 = (csr_addr == pyc_constant_15);
assign pyc_and_90 = (pyc_eq_59 & pyc_eq_89);
assign pyc_eq_91 = (csr_addr == pyc_constant_16);
assign pyc_and_92 = (pyc_eq_59 & pyc_eq_91);
assign pyc_eq_93 = (csr_addr == pyc_constant_17);
assign pyc_and_94 = (pyc_eq_59 & pyc_eq_93);
assign pyc_eq_95 = (csr_addr == pyc_constant_18);
assign pyc_and_96 = (pyc_eq_59 & pyc_eq_95);
assign pyc_eq_97 = (csr_addr == pyc_constant_19);
assign pyc_and_98 = (pyc_eq_59 & pyc_eq_97);
assign pyc_eq_99 = (csr_addr == pyc_constant_20);
assign pyc_and_100 = (pyc_eq_59 & pyc_eq_99);
assign pyc_eq_101 = (csr_addr == pyc_constant_21);
assign pyc_and_102 = (pyc_eq_59 & pyc_eq_101);
assign pyc_eq_103 = (csr_addr == pyc_constant_22);
assign pyc_and_104 = (pyc_eq_59 & pyc_eq_103);
assign pyc_eq_105 = (csr_addr == pyc_constant_23);
assign pyc_and_106 = (pyc_eq_59 & pyc_eq_105);
assign pyc_eq_107 = (csr_addr == pyc_constant_24);
assign pyc_and_108 = (pyc_eq_59 & pyc_eq_107);
assign pyc_eq_109 = (csr_addr == pyc_constant_25);
assign pyc_and_110 = (pyc_eq_59 & pyc_eq_109);
assign pyc_eq_111 = (csr_addr == pyc_constant_26);
assign pyc_and_112 = (pyc_eq_59 & pyc_eq_111);
assign pyc_eq_113 = (csr_addr == pyc_constant_2);
assign pyc_and_114 = (pyc_eq_59 & pyc_eq_113);
assign pyc_eq_115 = (csr_addr == pyc_constant_27);
assign pyc_and_116 = (pyc_eq_59 & pyc_eq_115);
assign pyc_eq_117 = (csr_addr == pyc_constant_28);
assign pyc_and_118 = (pyc_eq_59 & pyc_eq_117);
assign pyc_eq_119 = (csr_addr == pyc_constant_29);
assign pyc_and_120 = (pyc_eq_59 & pyc_eq_119);
assign pyc_eq_121 = (csr_addr == pyc_constant_30);
assign pyc_and_122 = (pyc_eq_59 & pyc_eq_121);
assign pyc_eq_123 = (csr_addr == pyc_constant_31);
assign pyc_and_124 = (pyc_eq_59 & pyc_eq_123);
assign pyc_eq_125 = (csr_addr == pyc_constant_32);
assign pyc_and_126 = (pyc_eq_59 & pyc_eq_125);
assign pyc_eq_127 = (csr_addr == pyc_constant_33);
assign pyc_and_128 = (pyc_eq_59 & pyc_eq_127);
assign pyc_or_129 = (pyc_and_68 | pyc_and_70);
assign pyc_or_130 = (pyc_and_72 | pyc_and_74);
assign pyc_or_131 = (pyc_and_76 | pyc_and_78);
assign pyc_or_132 = (pyc_and_80 | pyc_and_82);
assign pyc_or_133 = (pyc_and_84 | pyc_and_86);
assign pyc_or_134 = (pyc_and_88 | pyc_and_90);
assign pyc_or_135 = (pyc_and_92 | pyc_and_94);
assign pyc_or_136 = (pyc_and_96 | pyc_and_98);
assign pyc_or_137 = (pyc_and_100 | pyc_and_102);
assign pyc_or_138 = (pyc_and_104 | pyc_and_106);
assign pyc_or_139 = (pyc_and_108 | pyc_and_110);
assign pyc_or_140 = (pyc_and_112 | pyc_and_120);
assign pyc_or_141 = (pyc_and_122 | pyc_and_124);
assign pyc_or_142 = (pyc_and_126 | pyc_and_128);
assign pyc_or_143 = (pyc_or_129 | pyc_or_130);
assign pyc_or_144 = (pyc_or_131 | pyc_or_132);
assign pyc_or_145 = (pyc_or_133 | pyc_or_134);
assign pyc_or_146 = (pyc_or_135 | pyc_or_136);
assign pyc_or_147 = (pyc_or_137 | pyc_or_138);
assign pyc_or_148 = (pyc_or_139 | pyc_or_140);
assign pyc_or_149 = (pyc_or_141 | pyc_or_142);
assign pyc_or_150 = (pyc_or_143 | pyc_or_144);
assign pyc_or_151 = (pyc_or_145 | pyc_or_146);
assign pyc_or_152 = (pyc_or_147 | pyc_or_148);
assign pyc_or_153 = (pyc_or_150 | pyc_or_151);
assign pyc_or_154 = (pyc_or_152 | pyc_or_149);
assign pyc_or_155 = (pyc_or_153 | pyc_or_154);
assign pyc_or_156 = (pyc_and_114 | pyc_and_116);
assign pyc_or_157 = (pyc_or_156 | pyc_and_118);
assign pyc_and_158 = (pyc_and_60 & pyc_or_155);
assign pyc_and_159 = (pyc_and_60 & pyc_or_157);
assign pyc_and_160 = (pyc_and_159 & tb_test_mode);
assign pyc_comb_161 = pyc_constant_34;
assign pyc_comb_162 = pyc_constant_35;
assign pyc_comb_163 = pyc_constant_36;
assign pyc_comb_164 = pyc_constant_37;
assign pyc_comb_165 = pyc_constant_38;
assign pyc_comb_166 = pyc_constant_39;
assign pyc_comb_167 = pyc_constant_40;
assign pyc_comb_168 = pyc_constant_41;
assign pyc_comb_169 = pyc_constant_42;
assign pyc_comb_170 = pyc_constant_43;
assign pyc_comb_171 = pyc_constant_44;
assign pyc_comb_172 = pyc_constant_45;
assign pyc_comb_173 = pyc_constant_46;
assign pyc_comb_174 = pyc_constant_47;
assign pyc_comb_175 = pyc_constant_48;
assign pyc_comb_176 = pyc_constant_49;
assign pyc_comb_177 = pyc_constant_50;
assign pyc_comb_178 = pyc_constant_51;
assign pyc_comb_179 = pyc_constant_52;
assign pyc_comb_180 = pyc_constant_53;
assign pyc_comb_181 = pyc_constant_54;
assign pyc_comb_182 = pyc_constant_55;
assign pyc_comb_183 = pyc_constant_56;
assign pyc_comb_184 = pyc_constant_57;
assign pyc_comb_185 = pyc_eq_59;
assign pyc_comb_186 = pyc_and_66;
assign pyc_comb_187 = pyc_and_68;
assign pyc_comb_188 = pyc_and_70;
assign pyc_comb_189 = pyc_and_72;
assign pyc_comb_190 = pyc_and_74;
assign pyc_comb_191 = pyc_and_76;
assign pyc_comb_192 = pyc_and_78;
assign pyc_comb_193 = pyc_and_80;
assign pyc_comb_194 = pyc_and_82;
assign pyc_comb_195 = pyc_and_84;
assign pyc_comb_196 = pyc_and_86;
assign pyc_comb_197 = pyc_and_88;
assign pyc_comb_198 = pyc_and_90;
assign pyc_comb_199 = pyc_and_92;
assign pyc_comb_200 = pyc_and_94;
assign pyc_comb_201 = pyc_and_96;
assign pyc_comb_202 = pyc_and_98;
assign pyc_comb_203 = pyc_and_100;
assign pyc_comb_204 = pyc_and_102;
assign pyc_comb_205 = pyc_and_104;
assign pyc_comb_206 = pyc_and_106;
assign pyc_comb_207 = pyc_and_108;
assign pyc_comb_208 = pyc_and_110;
assign pyc_comb_209 = pyc_and_112;
assign pyc_comb_210 = pyc_and_114;
assign pyc_comb_211 = pyc_and_116;
assign pyc_comb_212 = pyc_and_118;
assign pyc_comb_213 = pyc_or_155;
assign pyc_comb_214 = pyc_and_158;
assign pyc_comb_215 = pyc_and_160;
assign pyc_extract_221 = pyc_reg_220[0];
assign pyc_extract_222 = pyc_reg_220[1];
assign q_ctrl_lmsm_start = pyc_extract_221;
assign q_ctrl_irq_en = pyc_extract_222;
assign pyc_comb_223 = q_ctrl_lmsm_start;
assign pyc_comb_224 = q_ctrl_irq_en;
assign pyc_extract_235 = pyc_reg_234[0];
assign pyc_extract_236 = pyc_reg_234[1];
assign pyc_extract_237 = pyc_reg_234[2];
assign pyc_extract_238 = pyc_reg_234[3];
assign pyc_extract_239 = pyc_reg_234[4];
assign pyc_extract_240 = pyc_reg_234[5];
assign pyc_extract_241 = pyc_reg_234[6];
assign q_irq_status_fec_uncorr = pyc_extract_235;
assign q_irq_status_crc_fail = pyc_extract_236;
assign q_irq_status_retry_err = pyc_extract_237;
assign q_irq_status_crd_proto = pyc_extract_238;
assign q_irq_status_train_fail = pyc_extract_239;
assign q_irq_status_bad_vl = pyc_extract_240;
assign q_irq_status_crd_uf = pyc_extract_241;
assign pyc_comb_242 = q_irq_status_fec_uncorr;
assign pyc_comb_243 = q_irq_status_crc_fail;
assign pyc_comb_244 = q_irq_status_retry_err;
assign pyc_comb_245 = q_irq_status_crd_proto;
assign pyc_comb_246 = q_irq_status_train_fail;
assign pyc_comb_247 = q_irq_status_bad_vl;
assign pyc_comb_248 = q_irq_status_crd_uf;
assign csr_rvalid_q = pyc_reg_509;
assign pyc_not_510 = (~csr_wr);
assign pyc_and_511 = (csr_req & pyc_not_510);
assign pyc_comb_512 = csr_rvalid_q;
assign pyc_comb_513 = pyc_and_511;
assign csr_rvalid_q__next = pyc_comb_513;
assign q_cnt_bad_vl_count = pyc_reg_256;
assign q_cnt_crc_fail_count = pyc_reg_250;
assign q_cnt_crd_of_count = pyc_reg_253;
assign q_cnt_crd_to_count = pyc_reg_254;
assign q_cnt_crd_uf_count = pyc_reg_257;
assign q_cnt_fec_uncorr_count = pyc_reg_249;
assign q_cnt_retry_req_count = pyc_reg_251;
assign q_cnt_retry_to_count = pyc_reg_252;
assign q_cnt_train_to_count = pyc_reg_255;
assign q_crd_to_dis_dis = pyc_reg_228;
assign q_irq_mask_mask = pyc_reg_225;
assign q_lmsm_tmr_scale_scale = pyc_reg_227;
assign q_pcs_tx_test_am_ivl_scale = pyc_reg_229;
assign cnt_ctrl_port_rst = pyc_reg_258;
assign pyc_and_259 = (pyc_comb_214 & pyc_comb_187);
assign pyc_and_260 = (pyc_comb_214 & pyc_comb_190);
assign pyc_and_261 = (pyc_comb_214 & pyc_comb_191);
assign pyc_and_262 = (pyc_comb_215 & pyc_comb_210);
assign pyc_and_263 = (pyc_comb_215 & pyc_comb_211);
assign pyc_and_264 = (pyc_comb_215 & pyc_comb_212);
assign pyc_and_265 = (pyc_comb_214 & pyc_comb_189);
assign pyc_and_266 = (pyc_comb_214 & pyc_comb_209);
assign pyc_extract_267 = csr_wdata[0];
assign pyc_and_268 = (pyc_and_266 & pyc_extract_267);
assign pyc_extract_269 = csr_wdata[1];
assign pyc_and_270 = (pyc_and_266 & pyc_extract_269);
assign pyc_extract_271 = csr_wdata[2];
assign pyc_and_272 = (pyc_and_266 & pyc_extract_271);
assign pyc_extract_273 = csr_wdata[3];
assign pyc_and_274 = (pyc_and_266 & pyc_extract_273);
assign pyc_extract_275 = csr_wdata[4];
assign pyc_and_276 = (pyc_and_266 & pyc_extract_275);
assign pyc_extract_277 = csr_wdata[5];
assign pyc_and_278 = (pyc_and_266 & pyc_extract_277);
assign pyc_extract_279 = csr_wdata[6];
assign pyc_and_280 = (pyc_and_266 & pyc_extract_279);
assign pyc_extract_281 = csr_wdata[7];
assign pyc_and_282 = (pyc_and_266 & pyc_extract_281);
assign pyc_extract_283 = csr_wdata[8];
assign pyc_and_284 = (pyc_and_266 & pyc_extract_283);
assign pyc_mux_285 = (tb_test_mode ? q_lmsm_tmr_scale_scale : pyc_comb_165);
assign pyc_and_286 = (tb_test_mode & q_crd_to_dis_dis);
assign pyc_mux_287 = (tb_test_mode ? q_pcs_tx_test_am_ivl_scale : pyc_comb_165);
assign pyc_mux_288 = (pyc_and_259 ? pyc_extract_269 : pyc_comb_223);
assign pyc_comb_289 = cnt_ctrl_port_rst;
assign pyc_comb_290 = pyc_and_259;
assign pyc_comb_291 = pyc_and_260;
assign pyc_comb_292 = pyc_and_261;
assign pyc_comb_293 = pyc_and_262;
assign pyc_comb_294 = pyc_and_263;
assign pyc_comb_295 = pyc_and_264;
assign pyc_comb_296 = pyc_and_265;
assign pyc_comb_297 = pyc_extract_267;
assign pyc_comb_298 = pyc_and_268;
assign pyc_comb_299 = pyc_extract_269;
assign pyc_comb_300 = pyc_and_270;
assign pyc_comb_301 = pyc_extract_271;
assign pyc_comb_302 = pyc_and_272;
assign pyc_comb_303 = pyc_extract_273;
assign pyc_comb_304 = pyc_and_274;
assign pyc_comb_305 = pyc_extract_275;
assign pyc_comb_306 = pyc_and_276;
assign pyc_comb_307 = pyc_extract_277;
assign pyc_comb_308 = pyc_and_278;
assign pyc_comb_309 = pyc_extract_279;
assign pyc_comb_310 = pyc_and_280;
assign pyc_comb_311 = pyc_and_282;
assign pyc_comb_312 = pyc_and_284;
assign pyc_comb_313 = pyc_mux_285;
assign pyc_comb_314 = pyc_and_286;
assign pyc_comb_315 = pyc_mux_287;
assign pyc_comb_316 = pyc_mux_288;
assign pyc_extract_318 = csr_wdata[6:0];
assign pyc_mux_319 = (pyc_comb_291 ? pyc_extract_318 : q_irq_mask_mask);
assign pyc_comb_320 = pyc_mux_319;
assign pyc_extract_322 = csr_wdata[7:0];
assign pyc_mux_323 = (pyc_comb_293 ? pyc_extract_322 : q_lmsm_tmr_scale_scale);
assign pyc_comb_324 = pyc_extract_322;
assign pyc_comb_325 = pyc_mux_323;
assign pyc_and_328 = (pyc_comb_296 & pyc_comb_297);
assign pyc_or_329 = (pyc_comb_242 | ev_fec_uncorr);
assign pyc_not_330 = (~pyc_and_328);
assign pyc_and_331 = (pyc_or_329 & pyc_not_330);
assign pyc_comb_332 = pyc_and_331;
assign pyc_and_333 = (pyc_comb_296 & pyc_comb_299);
assign pyc_or_334 = (pyc_comb_243 | ev_crc_fail);
assign pyc_not_335 = (~pyc_and_333);
assign pyc_and_336 = (pyc_or_334 & pyc_not_335);
assign pyc_comb_337 = pyc_and_336;
assign pyc_and_338 = (pyc_comb_296 & pyc_comb_301);
assign pyc_or_339 = (pyc_comb_244 | ev_retry_err);
assign pyc_not_340 = (~pyc_and_338);
assign pyc_and_341 = (pyc_or_339 & pyc_not_340);
assign pyc_comb_342 = pyc_and_341;
assign pyc_and_343 = (pyc_comb_296 & pyc_comb_303);
assign pyc_or_344 = (pyc_comb_245 | ev_crd_proto);
assign pyc_not_345 = (~pyc_and_343);
assign pyc_and_346 = (pyc_or_344 & pyc_not_345);
assign pyc_comb_347 = pyc_and_346;
assign pyc_and_348 = (pyc_comb_296 & pyc_comb_305);
assign pyc_or_349 = (pyc_comb_246 | ev_train_fail);
assign pyc_not_350 = (~pyc_and_348);
assign pyc_and_351 = (pyc_or_349 & pyc_not_350);
assign pyc_comb_352 = pyc_and_351;
assign pyc_and_353 = (pyc_comb_296 & pyc_comb_307);
assign pyc_or_354 = (pyc_comb_247 | ev_bad_vl);
assign pyc_not_355 = (~pyc_and_353);
assign pyc_and_356 = (pyc_or_354 & pyc_not_355);
assign pyc_comb_357 = pyc_and_356;
assign pyc_and_358 = (pyc_comb_296 & pyc_comb_309);
assign pyc_or_359 = (pyc_comb_248 | ev_crd_uf);
assign pyc_not_360 = (~pyc_and_358);
assign pyc_and_361 = (pyc_or_359 & pyc_not_360);
assign pyc_comb_362 = pyc_and_361;
assign pyc_eq_363 = (q_cnt_fec_uncorr_count == pyc_comb_167);
assign pyc_not_364 = (~pyc_eq_363);
assign pyc_and_365 = (inc_fec_uncorr & pyc_not_364);
assign pyc_add_366 = (q_cnt_fec_uncorr_count + pyc_comb_168);
assign pyc_mux_367 = (pyc_and_365 ? pyc_add_366 : q_cnt_fec_uncorr_count);
assign pyc_mux_368 = (pyc_comb_298 ? pyc_comb_164 : pyc_mux_367);
assign pyc_comb_369 = pyc_mux_368;
assign pyc_eq_370 = (q_cnt_crc_fail_count == pyc_comb_167);
assign pyc_not_371 = (~pyc_eq_370);
assign pyc_and_372 = (inc_crc_fail & pyc_not_371);
assign pyc_add_373 = (q_cnt_crc_fail_count + pyc_comb_168);
assign pyc_mux_374 = (pyc_and_372 ? pyc_add_373 : q_cnt_crc_fail_count);
assign pyc_mux_375 = (pyc_comb_300 ? pyc_comb_164 : pyc_mux_374);
assign pyc_comb_376 = pyc_mux_375;
assign pyc_eq_377 = (q_cnt_retry_req_count == pyc_comb_167);
assign pyc_not_378 = (~pyc_eq_377);
assign pyc_and_379 = (inc_retry_req & pyc_not_378);
assign pyc_add_380 = (q_cnt_retry_req_count + pyc_comb_168);
assign pyc_mux_381 = (pyc_and_379 ? pyc_add_380 : q_cnt_retry_req_count);
assign pyc_mux_382 = (pyc_comb_302 ? pyc_comb_164 : pyc_mux_381);
assign pyc_comb_383 = pyc_mux_382;
assign pyc_eq_384 = (q_cnt_retry_to_count == pyc_comb_167);
assign pyc_not_385 = (~pyc_eq_384);
assign pyc_and_386 = (inc_retry_to & pyc_not_385);
assign pyc_add_387 = (q_cnt_retry_to_count + pyc_comb_168);
assign pyc_mux_388 = (pyc_and_386 ? pyc_add_387 : q_cnt_retry_to_count);
assign pyc_mux_389 = (pyc_comb_304 ? pyc_comb_164 : pyc_mux_388);
assign pyc_comb_390 = pyc_mux_389;
assign pyc_eq_391 = (q_cnt_crd_of_count == pyc_comb_167);
assign pyc_not_392 = (~pyc_eq_391);
assign pyc_and_393 = (inc_crd_of & pyc_not_392);
assign pyc_add_394 = (q_cnt_crd_of_count + pyc_comb_168);
assign pyc_mux_395 = (pyc_and_393 ? pyc_add_394 : q_cnt_crd_of_count);
assign pyc_mux_396 = (pyc_comb_306 ? pyc_comb_164 : pyc_mux_395);
assign pyc_comb_397 = pyc_mux_396;
assign pyc_not_398 = (~pyc_comb_314);
assign pyc_and_399 = (inc_crd_to & pyc_not_398);
assign pyc_eq_400 = (q_cnt_crd_to_count == pyc_comb_167);
assign pyc_not_401 = (~pyc_eq_400);
assign pyc_and_402 = (pyc_and_399 & pyc_not_401);
assign pyc_add_403 = (q_cnt_crd_to_count + pyc_comb_168);
assign pyc_mux_404 = (pyc_and_402 ? pyc_add_403 : q_cnt_crd_to_count);
assign pyc_mux_405 = (pyc_comb_308 ? pyc_comb_164 : pyc_mux_404);
assign pyc_comb_406 = pyc_mux_405;
assign pyc_eq_407 = (q_cnt_train_to_count == pyc_comb_167);
assign pyc_not_408 = (~pyc_eq_407);
assign pyc_and_409 = (inc_train_to & pyc_not_408);
assign pyc_add_410 = (q_cnt_train_to_count + pyc_comb_168);
assign pyc_mux_411 = (pyc_and_409 ? pyc_add_410 : q_cnt_train_to_count);
assign pyc_mux_412 = (pyc_comb_310 ? pyc_comb_164 : pyc_mux_411);
assign pyc_comb_413 = pyc_mux_412;
assign pyc_eq_414 = (q_cnt_bad_vl_count == pyc_comb_167);
assign pyc_not_415 = (~pyc_eq_414);
assign pyc_and_416 = (inc_bad_vl & pyc_not_415);
assign pyc_add_417 = (q_cnt_bad_vl_count + pyc_comb_168);
assign pyc_mux_418 = (pyc_and_416 ? pyc_add_417 : q_cnt_bad_vl_count);
assign pyc_mux_419 = (pyc_comb_311 ? pyc_comb_164 : pyc_mux_418);
assign pyc_comb_420 = pyc_mux_419;
assign pyc_eq_421 = (q_cnt_crd_uf_count == pyc_comb_167);
assign pyc_not_422 = (~pyc_eq_421);
assign pyc_and_423 = (inc_crd_uf & pyc_not_422);
assign pyc_add_424 = (q_cnt_crd_uf_count + pyc_comb_168);
assign pyc_mux_425 = (pyc_and_423 ? pyc_add_424 : q_cnt_crd_uf_count);
assign pyc_mux_426 = (pyc_comb_312 ? pyc_comb_164 : pyc_mux_425);
assign pyc_comb_427 = pyc_mux_426;
assign pyc_and_428 = (pyc_comb_290 & pyc_comb_297);
assign pyc_eq_429 = (pyc_comb_289 == pyc_comb_166);
assign pyc_not_430 = (~pyc_eq_429);
assign pyc_sub_431 = (pyc_comb_289 - pyc_comb_170);
assign pyc_mux_432 = (pyc_eq_429 ? pyc_comb_289 : pyc_sub_431);
assign pyc_mux_433 = (pyc_and_428 ? pyc_comb_169 : pyc_mux_432);
assign pyc_comb_434 = pyc_not_430;
assign pyc_comb_435 = pyc_mux_433;
assign cnt_ctrl_port_rst__next = pyc_comb_435;
assign pyc_mux_317 = (pyc_comb_290 ? pyc_comb_301 : pyc_comb_224);
assign pyc_mux_326 = (pyc_comb_294 ? pyc_comb_297 : q_crd_to_dis_dis);
assign pyc_mux_327 = (pyc_comb_295 ? pyc_comb_324 : q_pcs_tx_test_am_ivl_scale);
assign q_cnt_bad_vl_count__next = pyc_comb_420;
assign q_cnt_crc_fail_count__next = pyc_comb_376;
assign q_cnt_crd_of_count__next = pyc_comb_397;
assign q_cnt_crd_to_count__next = pyc_comb_406;
assign q_cnt_crd_uf_count__next = pyc_comb_427;
assign q_cnt_fec_uncorr_count__next = pyc_comb_369;
assign q_cnt_retry_req_count__next = pyc_comb_383;
assign q_cnt_retry_to_count__next = pyc_comb_390;
assign q_cnt_train_to_count__next = pyc_comb_413;
assign q_crd_to_dis_dis__next = pyc_mux_326;
assign q_ctrl_irq_en__next = pyc_mux_317;
assign q_ctrl_lmsm_start__next = pyc_comb_316;
assign pyc_concat_216 = {q_ctrl_irq_en__next, q_ctrl_lmsm_start__next};
assign pyc_concat_217 = {pyc_comb_162, pyc_comb_162};
assign pyc_comb_218 = pyc_concat_216;
assign pyc_comb_219 = pyc_concat_217;
assign q_irq_mask_mask__next = pyc_comb_320;
assign q_irq_status_bad_vl__next = pyc_comb_357;
assign q_irq_status_crc_fail__next = pyc_comb_337;
assign q_irq_status_crd_proto__next = pyc_comb_347;
assign q_irq_status_crd_uf__next = pyc_comb_362;
assign q_irq_status_fec_uncorr__next = pyc_comb_332;
assign q_irq_status_retry_err__next = pyc_comb_342;
assign q_irq_status_train_fail__next = pyc_comb_352;
assign pyc_concat_230 = {q_irq_status_crd_uf__next, q_irq_status_bad_vl__next, q_irq_status_train_fail__next, q_irq_status_crd_proto__next, q_irq_status_retry_err__next, q_irq_status_crc_fail__next, q_irq_status_fec_uncorr__next};
assign pyc_concat_231 = {pyc_comb_162, pyc_comb_162, pyc_comb_162, pyc_comb_162, pyc_comb_162, pyc_comb_162, pyc_comb_162};
assign pyc_comb_232 = pyc_concat_230;
assign pyc_comb_233 = pyc_concat_231;
assign q_lmsm_tmr_scale_scale__next = pyc_comb_325;
assign q_pcs_tx_test_am_ivl_scale__next = pyc_mux_327;
assign q_port_cna_cna = pyc_reg_226;
assign pyc_concat_436 = {pyc_comb_248, pyc_comb_247, pyc_comb_246, pyc_comb_245, pyc_comb_244, pyc_comb_243, pyc_comb_242};
assign pyc_not_437 = (~q_irq_mask_mask);
assign pyc_and_438 = (pyc_concat_436 & pyc_not_437);
assign pyc_eq_439 = (pyc_and_438 == pyc_comb_171);
assign pyc_not_440 = (~pyc_eq_439);
assign pyc_and_441 = (pyc_comb_224 & pyc_not_440);
assign pyc_concat_442 = {pyc_comb_172, pyc_comb_224, pyc_comb_223, pyc_comb_162};
assign pyc_concat_443 = {pyc_comb_173, hw_retry_ack_st, hw_retry_req_st, hw_dll_sm_st, hw_lmsm_st, hw_dll_status_up, hw_link_ready, hw_link_up};
assign pyc_concat_444 = {pyc_comb_174, pyc_comb_248, pyc_comb_247, pyc_comb_246, pyc_comb_245, pyc_comb_244, pyc_comb_243, pyc_comb_242};
assign pyc_concat_445 = {pyc_comb_174, q_irq_mask_mask};
assign pyc_concat_446 = {pyc_comb_175, q_lmsm_tmr_scale_scale};
assign pyc_concat_447 = {pyc_comb_176, q_crd_to_dis_dis};
assign pyc_concat_448 = {pyc_comb_175, q_pcs_tx_test_am_ivl_scale};
assign pyc_mux_449 = (pyc_comb_187 ? pyc_concat_442 : pyc_comb_164);
assign pyc_mux_450 = (pyc_comb_188 ? pyc_concat_443 : pyc_comb_164);
assign pyc_mux_451 = (pyc_comb_189 ? pyc_concat_444 : pyc_comb_164);
assign pyc_mux_452 = (pyc_comb_190 ? pyc_concat_445 : pyc_comb_164);
assign pyc_mux_453 = (pyc_comb_191 ? q_port_cna_cna : pyc_comb_164);
assign pyc_mux_454 = (pyc_comb_192 ? pyc_comb_177 : pyc_comb_164);
assign pyc_mux_455 = (pyc_comb_193 ? pyc_comb_178 : pyc_comb_164);
assign pyc_mux_456 = (pyc_comb_194 ? pyc_comb_179 : pyc_comb_164);
assign pyc_mux_457 = (pyc_comb_195 ? pyc_comb_180 : pyc_comb_164);
assign pyc_mux_458 = (pyc_comb_196 ? pyc_comb_181 : pyc_comb_164);
assign pyc_mux_459 = (pyc_comb_197 ? pyc_comb_182 : pyc_comb_164);
assign pyc_mux_460 = (pyc_comb_198 ? pyc_comb_183 : pyc_comb_164);
assign pyc_mux_461 = (pyc_comb_199 ? pyc_comb_184 : pyc_comb_164);
assign pyc_mux_462 = (pyc_comb_200 ? q_cnt_fec_uncorr_count : pyc_comb_164);
assign pyc_mux_463 = (pyc_comb_201 ? q_cnt_crc_fail_count : pyc_comb_164);
assign pyc_mux_464 = (pyc_comb_202 ? q_cnt_retry_req_count : pyc_comb_164);
assign pyc_mux_465 = (pyc_comb_203 ? q_cnt_retry_to_count : pyc_comb_164);
assign pyc_mux_466 = (pyc_comb_204 ? q_cnt_crd_of_count : pyc_comb_164);
assign pyc_mux_467 = (pyc_comb_205 ? q_cnt_crd_to_count : pyc_comb_164);
assign pyc_mux_468 = (pyc_comb_206 ? q_cnt_train_to_count : pyc_comb_164);
assign pyc_mux_469 = (pyc_comb_207 ? q_cnt_bad_vl_count : pyc_comb_164);
assign pyc_mux_470 = (pyc_comb_208 ? q_cnt_crd_uf_count : pyc_comb_164);
assign pyc_and_471 = (pyc_comb_210 & tb_test_mode);
assign pyc_mux_472 = (pyc_and_471 ? pyc_concat_446 : pyc_comb_164);
assign pyc_and_473 = (pyc_comb_211 & tb_test_mode);
assign pyc_mux_474 = (pyc_and_473 ? pyc_concat_447 : pyc_comb_164);
assign pyc_and_475 = (pyc_comb_212 & tb_test_mode);
assign pyc_mux_476 = (pyc_and_475 ? pyc_concat_448 : pyc_comb_164);
assign pyc_or_477 = (pyc_mux_449 | pyc_mux_450);
assign pyc_or_478 = (pyc_mux_451 | pyc_mux_452);
assign pyc_or_479 = (pyc_mux_453 | pyc_mux_454);
assign pyc_or_480 = (pyc_mux_455 | pyc_mux_456);
assign pyc_or_481 = (pyc_mux_457 | pyc_mux_458);
assign pyc_or_482 = (pyc_mux_459 | pyc_mux_460);
assign pyc_or_483 = (pyc_mux_461 | pyc_mux_462);
assign pyc_or_484 = (pyc_mux_463 | pyc_mux_464);
assign pyc_or_485 = (pyc_mux_465 | pyc_mux_466);
assign pyc_or_486 = (pyc_mux_467 | pyc_mux_468);
assign pyc_or_487 = (pyc_mux_469 | pyc_mux_470);
assign pyc_or_488 = (pyc_mux_474 | pyc_mux_476);
assign pyc_or_489 = (pyc_or_477 | pyc_or_478);
assign pyc_or_490 = (pyc_or_479 | pyc_or_480);
assign pyc_or_491 = (pyc_or_481 | pyc_or_482);
assign pyc_or_492 = (pyc_or_483 | pyc_or_484);
assign pyc_or_493 = (pyc_or_485 | pyc_or_486);
assign pyc_or_494 = (pyc_or_487 | pyc_mux_472);
assign pyc_or_495 = (pyc_or_489 | pyc_or_490);
assign pyc_or_496 = (pyc_or_491 | pyc_or_492);
assign pyc_or_497 = (pyc_or_493 | pyc_or_494);
assign pyc_or_498 = (pyc_or_495 | pyc_or_496);
assign pyc_or_499 = (pyc_or_497 | pyc_or_488);
assign pyc_or_500 = (pyc_or_498 | pyc_or_499);
assign csr_rdata_q__next = pyc_or_500;
assign pyc_not_501 = (~pyc_comb_185);
assign pyc_not_502 = (~pyc_comb_213);
assign pyc_not_503 = (~pyc_comb_186);
assign pyc_and_504 = (pyc_not_502 & pyc_not_503);
assign pyc_or_505 = (pyc_not_501 | pyc_and_504);
assign pyc_comb_506 = pyc_and_441;
assign pyc_comb_507 = csr_rdata_q__next;
assign pyc_comb_508 = pyc_or_505;
assign csr_err_q = pyc_reg_515;
assign pyc_and_516 = (csr_req & pyc_comb_508);
assign pyc_comb_517 = csr_err_q;
assign pyc_comb_518 = pyc_and_516;
assign csr_err_q__next = pyc_comb_518;
assign pyc_mux_321 = (pyc_comb_292 ? csr_wdata : q_port_cna_cna);
assign q_port_cna_cna__next = pyc_mux_321;

// --- Sequential primitives
pyc_reg #(.WIDTH(2)) pyc_reg_220_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(pyc_comb_218),
  .init(pyc_comb_219),
  .q(pyc_reg_220)
);
pyc_reg #(.WIDTH(7)) pyc_reg_225_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(q_irq_mask_mask__next),
  .init(pyc_comb_163),
  .q(pyc_reg_225)
);
pyc_reg #(.WIDTH(32)) pyc_reg_226_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(q_port_cna_cna__next),
  .init(pyc_comb_164),
  .q(pyc_reg_226)
);
pyc_reg #(.WIDTH(8)) pyc_reg_227_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(q_lmsm_tmr_scale_scale__next),
  .init(pyc_comb_165),
  .q(pyc_reg_227)
);
pyc_reg #(.WIDTH(1)) pyc_reg_228_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(q_crd_to_dis_dis__next),
  .init(pyc_comb_162),
  .q(pyc_reg_228)
);
pyc_reg #(.WIDTH(8)) pyc_reg_229_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(q_pcs_tx_test_am_ivl_scale__next),
  .init(pyc_comb_165),
  .q(pyc_reg_229)
);
pyc_reg #(.WIDTH(7)) pyc_reg_234_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(pyc_comb_232),
  .init(pyc_comb_233),
  .q(pyc_reg_234)
);
pyc_reg #(.WIDTH(32)) pyc_reg_249_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(q_cnt_fec_uncorr_count__next),
  .init(pyc_comb_164),
  .q(pyc_reg_249)
);
pyc_reg #(.WIDTH(32)) pyc_reg_250_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(q_cnt_crc_fail_count__next),
  .init(pyc_comb_164),
  .q(pyc_reg_250)
);
pyc_reg #(.WIDTH(32)) pyc_reg_251_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(q_cnt_retry_req_count__next),
  .init(pyc_comb_164),
  .q(pyc_reg_251)
);
pyc_reg #(.WIDTH(32)) pyc_reg_252_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(q_cnt_retry_to_count__next),
  .init(pyc_comb_164),
  .q(pyc_reg_252)
);
pyc_reg #(.WIDTH(32)) pyc_reg_253_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(q_cnt_crd_of_count__next),
  .init(pyc_comb_164),
  .q(pyc_reg_253)
);
pyc_reg #(.WIDTH(32)) pyc_reg_254_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(q_cnt_crd_to_count__next),
  .init(pyc_comb_164),
  .q(pyc_reg_254)
);
pyc_reg #(.WIDTH(32)) pyc_reg_255_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(q_cnt_train_to_count__next),
  .init(pyc_comb_164),
  .q(pyc_reg_255)
);
pyc_reg #(.WIDTH(32)) pyc_reg_256_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(q_cnt_bad_vl_count__next),
  .init(pyc_comb_164),
  .q(pyc_reg_256)
);
pyc_reg #(.WIDTH(32)) pyc_reg_257_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(q_cnt_crd_uf_count__next),
  .init(pyc_comb_164),
  .q(pyc_reg_257)
);
pyc_reg #(.WIDTH(5)) pyc_reg_258_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(cnt_ctrl_port_rst__next),
  .init(pyc_comb_166),
  .q(pyc_reg_258)
);
pyc_reg #(.WIDTH(1)) pyc_reg_509_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(csr_rvalid_q__next),
  .init(pyc_comb_162),
  .q(pyc_reg_509)
);
pyc_reg #(.WIDTH(32)) pyc_reg_514_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(pyc_comb_507),
  .init(pyc_comb_164),
  .q(pyc_reg_514)
);
pyc_reg #(.WIDTH(1)) pyc_reg_515_inst (
  .clk(core_clk),
  .rst(rst_pyc),
  .en(pyc_comb_161),
  .d(csr_err_q__next),
  .init(pyc_comb_162),
  .q(pyc_reg_515)
);

assign csr_ready = pyc_comb_161;
assign port_rst_pulse = pyc_comb_434;
assign csr_lmsm_start = pyc_comb_223;
assign csr_irq_en = pyc_comb_224;
assign csr_irq_mask = q_irq_mask_mask;
assign csr_port_cna = q_port_cna_cna;
assign csr_tmr_scale = pyc_comb_313;
assign csr_crd_to_dis = pyc_comb_314;
assign csr_am_ivl_scale = pyc_comb_315;
assign irq = pyc_comb_506;
assign csr_rvalid = pyc_comb_512;
assign csr_rdata = csr_rdata_q;
assign csr_err = pyc_comb_517;

endmodule

