"""ub_dll_retry_req_sm — DLL RETRY_REQ_SM (pyc4.0 leaf).

Source of truth for this leaf. Business registers are ``pyc_reg``
(synchronous, active-high ``rst_pyc``; sensitive to ``core_clk`` only).
``TEST_HOOKS`` is expanded here at Python generation time (SPEC §11);
SPEC §10 lists **no** test hooks for this leaf, so only PRODUCT is
emitted (no ``rtl/dll/hooks/`` file, no ``tb_*`` ports).

Regenerate:

    python3 rtl/dll/ub_dll_retry_req_sm.py

SPEC §2.2 / CODING_STYLE §5:

    PRODUCT (TEST_HOOKS=0) → ``rtl/dll/ub_dll_retry_req_sm.v``

Module name ``ub_dll_retry_req_sm`` = ``ub_<层>_<功能>``
(CODING_STYLE §5). SPEC §2.6 names the parent ``ub_dll_retry``
(buffer + both SMs) and the block ``RETRY_REQ_SM``; this leaf is
that SM only (buffer is out of scope).

Mapped to SPEC §6.3 / UB-DL §4.7.3.3 (transfers closed in docs PR #9
@ 1277cce0), REGMAP ``STATUS.RETRY_REQ_ST[12:10]``, SPEC §3.3.3
``dll_retrain_req`` / ``lmsm_retrain_ack``, SPEC §4.2 / §3.2.3
``PORT_RST``.

Does not generate the 16-cycle PORT_RST pulse (``ub_csr`` does);
``port_rst`` is a sync clear of retry state (SPEC §6.3 / §3.2.3).
Does not own Retry_Idle / Retry_Req serialization (parent pulses
``retry_req_set_done`` when 1 Idle + 32 Req have been accepted).
"""

from __future__ import annotations

from pathlib import Path

# ---------------------------------------------------------------------------
# Parameters (SPEC §9 / §6.3 / §13). Identifiers match the spec table.
# ---------------------------------------------------------------------------

# SPEC §9 / §4.7.3.3 recommendation; draft pending Luke (SPEC §13 @ PR #9).
NUM_RETRY_THRESHOLD = 15
NUM_PHY_REINIT_THRESHOLD = 4

# SPEC §13 RETRY WAIT timeout: recommended >2× link delay, range 1 µs–10 s.
# M1 RTT assumption 2 µs (SPEC §9) → implement ≥4 µs. F_CORE ≈80.57 MHz
# (SPEC §4.1 / §9): 4e-6 * (2.578125e9/32) = 322.3125 → 323 cycles.
# OPEN: not a single closed SPEC number (PR #9 §13).
RETRY_WAIT_CYC = 323

CNT_W = 8
TMR_W = 32

# STATUS.RETRY_REQ_ST[12:10] (SPEC §6.3 / REGMAP). 5–7 reserved; never produced.
ST_NORMAL = 0
ST_REQ = 1
ST_WAIT = 2
ST_RETRAIN = 3
ST_ERROR = 4

HERE = Path(__file__).resolve().parent
PRODUCT_V = HERE / "ub_dll_retry_req_sm.v"


def _header(test_hooks: int) -> str:
    return f"""\
// Generated by rtl/dll/ub_dll_retry_req_sm.py — do not hand-edit.
// pyc4.0 leaf ub_dll_retry_req_sm. TEST_HOOKS={test_hooks} (Python generation-time).
// Registers: pyc_reg semantics (sync, rst_pyc active-high, core_clk).
// SPEC: §2.6, §3.2.3, §3.3.3, §4.2, §6.3, §7, §9, §11, §13.
// PORT_RST 16-cycle pulse: ub_csr; this leaf sees port_rst as sync clear.
// SPEC §10 lists no tb_* hooks for this leaf — PRODUCT only.
"""


def emit_verilog(test_hooks: bool) -> str:
    """Emit one netlist. ``test_hooks`` is the Python-level TEST_HOOKS flag."""
    th = 1 if test_hooks else 0
    lines: list[str] = [_header(th)]

    def w(s: str = "") -> None:
        lines.append(s)

    w("module ub_dll_retry_req_sm #(")
    w(f"  parameter integer NUM_RETRY_THRESHOLD       = {NUM_RETRY_THRESHOLD},   // SPEC §9 / §4.7.3.3 rec.; draft §13")
    w(f"  parameter integer NUM_PHY_REINIT_THRESHOLD  = {NUM_PHY_REINIT_THRESHOLD},    // SPEC §9 / §4.7.3.3 rec.; draft §13")
    w(f"  parameter integer RETRY_WAIT_CYC            = {RETRY_WAIT_CYC},  // OPEN stub cycles; SPEC §13 / §6.3 WAIT timeout")
    w(f"  parameter integer CNT_W                     = {CNT_W},    // NUM_RETRY / NUM_PHY_REINIT width")
    w(f"  parameter integer TMR_W                     = {TMR_W}     // WAIT timer width; F_CORE SPEC §4.1 / §9")
    w(") (")
    w("  input  wire                    core_clk,")
    w("  input  wire                    rst_pyc,")
    w("  input  wire                    port_rst,")
    w()
    w("  // SPEC §3.3.3 LMSM↔DLL. lmsm_retrain_ack = PHY started retrain (level).")
    w("  input  wire                    lmsm_retrain_ack,")
    w("  output wire                    dll_retrain_req,")
    w()
    w("  // OPEN leaf events: SPEC §6.3 names the condition, not a pin.")
    w("  // Parent forms start_retry = CRC-mode BCRC fail OR non-CRC FEC uncorr")
    w("  // (SPEC §6.3 / §3.3.2 / UB-DL §4.7.1). Level; sampled each core_clk.")
    w("  input  wire                    start_retry,")
    w("  input  wire                    retry_req_set_done,")
    w("  input  wire                    retry_ack_set_rx,")
    w("  input  wire                    phy_retrain_ok,")
    w()
    w("  // REGMAP STATUS.RETRY_REQ_ST[12:10] (SPEC §6.3). Never 5–7.")
    w("  output wire [2:0]              retry_req_st,")
    w()
    w("  // REGMAP / SPEC §7 sideband to ub_csr (1-cycle pulses / ERROR level).")
    w("  output wire                    retry_req_inc,")
    w("  output wire                    retry_to_inc,")
    w("  output wire                    retry_err")
    w(");")
    w()
    w("  // ------------------------------------------------------------------")
    w("  // STATUS.RETRY_REQ_ST encoding (SPEC §6.3). 5–7 reserved — never driven.")
    w("  // ------------------------------------------------------------------")
    w(f"  localparam [2:0] ST_NORMAL  = 3'd{ST_NORMAL};")
    w(f"  localparam [2:0] ST_REQ     = 3'd{ST_REQ};")
    w(f"  localparam [2:0] ST_WAIT    = 3'd{ST_WAIT};")
    w(f"  localparam [2:0] ST_RETRAIN = 3'd{ST_RETRAIN};")
    w(f"  localparam [2:0] ST_ERROR   = 3'd{ST_ERROR};")
    w()
    w("  // Combined sync reset: rst_pyc (entity) or port_rst (CSR PORT_RST).")
    w("  // SPEC §6.3: reset → NORMAL; clear NUM_RETRY and NUM_PHY_REINIT.")
    w("  wire rst_eff = rst_pyc | port_rst;")
    w()
    if test_hooks:
        w("  // SPEC §10 lists no hooks for RETRY_REQ_SM. This branch is unused.")
        w("  // Kept so TEST_HOOKS is a Python generation-time if, not `ifdef.")
        w()
    w("  // pyc_reg: st, num_retry, num_phy, tmr, inc pulses.")
    w("  reg [2:0]        st;")
    w("  reg [CNT_W-1:0]  num_retry;")
    w("  reg [CNT_W-1:0]  num_phy;")
    w("  reg [TMR_W-1:0]  tmr;")
    w("  reg              retry_req_inc_q;")
    w("  reg              retry_to_inc_q;")
    w()
    w("  wire [CNT_W-1:0] num_retry_inc =")
    w("      (&num_retry) ? num_retry : (num_retry + {{(CNT_W-1){1'b0}}, 1'b1});")
    w("  wire [CNT_W-1:0] num_phy_inc =")
    w("      (&num_phy) ? num_phy : (num_phy + {{(CNT_W-1){1'b0}}, 1'b1});")
    w("  wire             retry_hits_th =")
    w("      (num_retry_inc == NUM_RETRY_THRESHOLD[CNT_W-1:0]);")
    w("  wire             phy_hits_th =")
    w("      (num_phy_inc == NUM_PHY_REINIT_THRESHOLD[CNT_W-1:0]);")
    w("  wire             tmr_sat = &tmr;")
    w("  wire [TMR_W-1:0] tmr_inc = tmr_sat ? tmr : (tmr + {{(TMR_W-1){1'b0}}, 1'b1});")
    w("  wire             tmr_to  = (tmr >= RETRY_WAIT_CYC[TMR_W-1:0]);")
    w()
    w("  // ------------------------------------------------------------------")
    w("  // Next-state (SPEC §6.3 table). Priority when several fire (OPEN §6.3):")
    w("  //   rst_eff > ERROR hold > PHY retrain (lmsm_retrain_ack)")
    w("  //   > start_retry / set_done / ack / timeout / phy_retrain_ok.")
    w("  // REQ entry increments NUM_RETRY; if == TH, redirect to RETRAIN and")
    w("  // clear NUM_RETRY (SPEC §6.3 REQ→RETRAIN).")
    w("  // RETRAIN entry increments NUM_PHY_REINIT; if == TH, redirect to")
    w("  // ERROR and clear NUM_PHY_REINIT (SPEC §6.3 RETRAIN→ERROR).")
    w("  // WAIVER_RETRY_REQ_FSM_DEFAULT: illegal st → NORMAL.")
    w("  // ------------------------------------------------------------------")
    w("  reg [2:0]       st_n;")
    w("  reg [CNT_W-1:0] num_retry_n;")
    w("  reg [CNT_W-1:0] num_phy_n;")
    w("  reg [TMR_W-1:0] tmr_n;")
    w("  reg             try_enter_req;")
    w("  reg             enter_retrain;")
    w("  reg             wait_timeout;")
    w()
    w("  always @* begin")
    w("    st_n          = st;")
    w("    num_retry_n   = num_retry;")
    w("    num_phy_n     = num_phy;")
    w("    tmr_n         = tmr;")
    w("    try_enter_req = 1'b0;")
    w("    enter_retrain = 1'b0;")
    w("    wait_timeout  = 1'b0;")
    w("    case (st)")
    w("      ST_NORMAL: begin")
    w("        tmr_n = {TMR_W{1'b0}};")
    w("        if (lmsm_retrain_ack)")
    w("          enter_retrain = 1'b1;")
    w("        else if (start_retry)")
    w("          try_enter_req = 1'b1;")
    w("      end")
    w()
    w("      ST_REQ: begin")
    w("        tmr_n = {TMR_W{1'b0}};")
    w("        if (lmsm_retrain_ack) begin")
    w("          enter_retrain = 1'b1;")
    w("          num_retry_n   = {CNT_W{1'b0}}; // SPEC §6.3: REQ→RETRAIN clears NUM_RETRY")
    w("        end else if (retry_req_set_done) begin")
    w("          st_n  = ST_WAIT;")
    w("          tmr_n = {TMR_W{1'b0}};")
    w("        end")
    w("      end")
    w()
    w("      ST_WAIT: begin")
    w("        tmr_n = tmr_inc;")
    w("        if (lmsm_retrain_ack) begin")
    w("          enter_retrain = 1'b1;")
    w("        end else if (retry_ack_set_rx) begin")
    w("          st_n = ST_NORMAL;")
    w("        end else if (tmr_to) begin")
    w("          wait_timeout  = 1'b1;")
    w("          try_enter_req = 1'b1;")
    w("        end")
    w("      end")
    w()
    w("      ST_RETRAIN: begin")
    w("        tmr_n = {TMR_W{1'b0}};")
    w("        // SPEC §6.3 RETRAIN→REQ: PHY retrain succeeded.")
    w("        // Do not leave while lmsm_retrain_ack is still high.")
    w("        if (phy_retrain_ok && !lmsm_retrain_ack)")
    w("          try_enter_req = 1'b1;")
    w("      end")
    w()
    w("      ST_ERROR: begin")
    w("        tmr_n = {TMR_W{1'b0}};")
    w("        st_n  = ST_ERROR; // SPEC §6.3: only PORT_RST / entity rst → NORMAL")
    w("      end")
    w()
    w("      default: begin")
    w("        st_n        = ST_NORMAL; // WAIVER_RETRY_REQ_FSM_DEFAULT")
    w("        num_retry_n = {CNT_W{1'b0}};")
    w("        num_phy_n   = {CNT_W{1'b0}};")
    w("        tmr_n       = {TMR_W{1'b0}};")
    w("      end")
    w("    endcase")
    w()
    w("    // SPEC §6.3: increment NUM_RETRY on entry to REQ; if == TH → RETRAIN.")
    w("    if (try_enter_req) begin")
    w("      if (retry_hits_th) begin")
    w("        num_retry_n   = {CNT_W{1'b0}};")
    w("        enter_retrain = 1'b1;")
    w("      end else begin")
    w("        st_n        = ST_REQ;")
    w("        num_retry_n = num_retry_inc;")
    w("      end")
    w("    end")
    w()
    w("    // SPEC §6.3: increment NUM_PHY_REINIT on entry to RETRAIN; if == TH → ERROR.")
    w("    if (enter_retrain) begin")
    w("      if (phy_hits_th) begin")
    w("        st_n      = ST_ERROR;")
    w("        num_phy_n = {CNT_W{1'b0}};")
    w("      end else begin")
    w("        st_n      = ST_RETRAIN;")
    w("        num_phy_n = num_phy_inc;")
    w("      end")
    w("    end")
    w("  end")
    w()
    w("  wire enter_req = (st_n == ST_REQ) && (st != ST_REQ);")
    w()
    w("  // pyc_reg bank (sync; rst_eff = rst_pyc | port_rst).")
    w("  always @(posedge core_clk) begin")
    w("    if (rst_eff) begin")
    w("      st              <= ST_NORMAL;")
    w("      num_retry       <= {CNT_W{1'b0}};")
    w("      num_phy         <= {CNT_W{1'b0}};")
    w("      tmr             <= {TMR_W{1'b0}};")
    w("      retry_req_inc_q <= 1'b0;")
    w("      retry_to_inc_q  <= 1'b0;")
    w("    end else begin")
    w("      st              <= st_n;")
    w("      num_retry       <= num_retry_n;")
    w("      num_phy         <= num_phy_n;")
    w("      tmr             <= tmr_n;")
    w("      retry_req_inc_q <= enter_req;")
    w("      retry_to_inc_q  <= wait_timeout;")
    w("    end")
    w("  end")
    w()
    w("  assign retry_req_st   = st;")
    w("  assign dll_retrain_req = (st == ST_RETRAIN); // SPEC §3.3.3; level, not a pulse")
    w("  assign retry_req_inc  = retry_req_inc_q;     // REGMAP CNT_RETRY_REQ")
    w("  assign retry_to_inc   = retry_to_inc_q;      // REGMAP CNT_RETRY_TO")
    w("  assign retry_err      = (st == ST_ERROR);    // REGMAP IRQ_STATUS.RETRY_ERR")
    w()
    w("endmodule")
    w()
    return "\n".join(lines) + "\n"


def generate() -> Path:
    product = emit_verilog(False)
    if "`ifdef" in product:
        raise RuntimeError("generated Verilog must not use ifdef TEST_HOOKS")
    for token in ("tb_test_mode", "tb_inj_", "tb_obs_"):
        if token in product:
            raise RuntimeError(f"PRODUCT netlist must not contain {token}")
    # Reserved encodings 5–7 must never be assigned.
    for line in product.splitlines():
        if "st_n" in line and ("3'd5" in line or "3'd6" in line or "3'd7" in line
                               or "3'b101" in line or "3'b110" in line or "3'b111" in line):
            raise RuntimeError(f"RETRY_REQ_ST reserved encoding: {line}")
    PRODUCT_V.parent.mkdir(parents=True, exist_ok=True)
    PRODUCT_V.write_text(product)
    return PRODUCT_V


# Optional pyc4.0 frontend entry (port/clock/reset declaration).
# Full FSM is emitted as Verilog above; pycc/LLVM 19 is not required to regenerate.
try:
    from pycircuit import Circuit, module, u  # type: ignore

    @module(name="ub_dll_retry_req_sm")
    def build(m: Circuit) -> None:
        """pyc4.0 module boundary for ub_dll_retry_req_sm."""
        clk = m.clock("core_clk")
        rst = m.reset("rst")
        _ = (clk, rst)
        st = m.out("st", clk=clk, rst=rst, width=3, init=u(3, ST_NORMAL))
        st.set(st.out())
        m.output("retry_req_st", st.out())
        m.output("dll_retrain_req", u(1, 0))
        m.output("retry_err", u(1, 0))

    build.__pycircuit_name__ = "ub_dll_retry_req_sm"
except ImportError:
    build = None  # type: ignore


if __name__ == "__main__":
    p = generate()
    print(f"wrote {p}")
