// Generated by rtl/dll/ub_dll_retry_ack_sm.py — do not hand-edit.
// pyc4.0 leaf ub_dll_retry_ack_sm. TEST_HOOKS=0 (Python generation-time).
// Registers: pyc_reg semantics (sync, rst_pyc active-high, core_clk).
// SPEC: §2.6, §3.2.3, §4.2, §6.4, §9, §11.
// PORT_RST 16-cycle pulse: ub_csr; this leaf sees port_rst as sync clear.
// SPEC §10 lists no tb_* hooks for this leaf — PRODUCT only.

module ub_dll_retry_ack_sm (
  input  wire                    core_clk,
  input  wire                    rst_pyc,
  input  wire                    port_rst,

  // OPEN leaf events: SPEC §6.4 names the condition, not a pin.
  // Level; sampled each core_clk. Parent owns 1 Idle + 32 Ack and replay.
  input  wire                    retry_req_set_rx,
  input  wire                    retry_ack_set_done,
  input  wire                    replay_done,

  // REGMAP STATUS.RETRY_ACK_ST[14:13] (SPEC §6.4). Never 2–3.
  output wire [1:0]              retry_ack_st
);

  // ------------------------------------------------------------------
  // STATUS.RETRY_ACK_ST encoding (SPEC §6.4). 2–3 reserved — never driven.
  // ------------------------------------------------------------------
  localparam [1:0] ST_NORMAL = 2'd0;
  localparam [1:0] ST_ACK    = 2'd1;

  // Internal substate of ACK. Not exported (SPEC has two CSR states).
  localparam        SUB_SET    = 1'b0;
  localparam        SUB_REPLAY = 1'b1;

  // Combined sync reset: rst_pyc (entity) or port_rst (CSR PORT_RST).
  // SPEC §6.4: reset → NORMAL.
  wire rst_eff = rst_pyc | port_rst;

  // pyc_reg: st, sub.
  reg [1:0] st;
  reg       sub;

  // ------------------------------------------------------------------
  // Next-state (SPEC §6.4 table).
  //   NORMAL → ACK : received peer Retry_Req_Set
  //   ACK → NORMAL : Retry_Ack_Set done AND this-round replay done
  //   ACK stay ACK : Retry_Req_Set while sending marked replay (restart)
  // WAIVER_RETRY_ACK_FSM_DEFAULT: illegal st (2–3) → NORMAL.
  // ------------------------------------------------------------------
  reg [1:0] st_n;
  reg       sub_n;

  always @* begin
    st_n  = st;
    sub_n = sub;
    case (st)
      ST_NORMAL: begin
        sub_n = SUB_SET;
        if (retry_req_set_rx)
          st_n = ST_ACK;
      end

      ST_ACK: begin
        // SPEC §6.4: while sending replay, a new Retry_Req_Set restarts.
        if ((sub == SUB_REPLAY) && retry_req_set_rx) begin
          sub_n = SUB_SET;
        end else if ((sub == SUB_SET) && retry_ack_set_done && replay_done) begin
          st_n  = ST_NORMAL;
          sub_n = SUB_SET;
        end else if ((sub == SUB_SET) && retry_ack_set_done) begin
          sub_n = SUB_REPLAY;
        end else if ((sub == SUB_REPLAY) && replay_done) begin
          st_n  = ST_NORMAL;
          sub_n = SUB_SET;
        end
      end

      default: begin
        st_n  = ST_NORMAL; // WAIVER_RETRY_ACK_FSM_DEFAULT
        sub_n = SUB_SET;
      end
    endcase
  end

  // pyc_reg bank (sync; rst_eff = rst_pyc | port_rst).
  always @(posedge core_clk) begin
    if (rst_eff) begin
      st  <= ST_NORMAL;
      sub <= SUB_SET;
    end else begin
      st  <= st_n;
      sub <= sub_n;
    end
  end

  assign retry_ack_st = st;

endmodule

