"""Shared helpers for the tool-gate scripts.

Kept stdlib-first. PyYAML is optional but used when present (scripts/gate/requirements.txt).
"""

from __future__ import annotations

import ast
import fnmatch
import json
import os
import re
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Iterable

GATE_DIR = Path(__file__).resolve().parent
REPO_ROOT = GATE_DIR.parent.parent
# All machine-readable lists live next to the scripts (scripts/gate/).
LISTS_DIR = GATE_DIR
LEGACY_LIST = LISTS_DIR / "legacy.txt"
HANDWRITTEN_LIST = LISTS_DIR / "handwritten.yml"
BLACKBOX_LIST = LISTS_DIR / "blackbox.yml"
HOOKS_PORTS_LIST = LISTS_DIR / "hooks_ports.yml"
MIGRATE_LIST = LISTS_DIR / "pycircuit_migrate.txt"
LEAK_ALLOW_LIST = LISTS_DIR / "leak_allow.yml"
PLACEHOLDER_MARK = "PLACEHOLDER_SOURCE"
CMN_MEM_CELL = "ub_cmn_mem_1r1w"
DEFAULT_CMN_MEM_THRESH_BITS = 4096
IMPL_QUICK_SYNTH_MD = REPO_ROOT / "docs" / "rules" / "impl_quick_synth.md"
INVENTORY_CANDIDATES = (
    REPO_ROOT / "docs" / "arch" / "MODULE_INVENTORY.yml",
    REPO_ROOT / "docs" / "arch" / "MODULE_INVENTORY.yaml",
    REPO_ROOT / "docs" / "MODULE_INVENTORY.yml",
    REPO_ROOT / "docs" / "MODULE_INVENTORY.yaml",
    LISTS_DIR / "MODULE_INVENTORY.yml",
)
WAIVERS_DIR = REPO_ROOT / "waivers"
APPROVERS_FILE = WAIVERS_DIR / "approvers.yml"
TOOLCHAIN_LOCK = REPO_ROOT / "TOOLCHAIN.lock"
CDC_RULES = GATE_DIR / "cdc_rules.yml"
OUT_DIR = GATE_DIR / "out"

RTL_SOURCE_SUFFIXES = {".v", ".sv"}
RTL_INCLUDE_SUFFIXES = {".vh", ".svh"}
FILELIST_SUFFIXES = {".f", ".vf"}

# Layer names are discovered from the tree. Do not hard-code pcs/dll/lmsm/csr.
# Xia: cmn is a real layer (ub_cmn_mem_1r1w) and must always be enumerated.
LAYER_SKIP = {
    "hooks",
    "gen",
    "include",
    "__pycache__",
    "lib",
    "tests",
    "out",
    "filelists",
}
ALWAYS_LAYERS = ("cmn",)

# Layer discovery only. Do not scan rtl/gen (that tree is not used).

# Fallback only if scripts/gate/handwritten.yml is absent. Prefer the YAML list.
WHITELIST_CELLS = {"ub_rst_sync"}

GENERATED_BANNER = re.compile(
    r"(GENERATED from pycircuit|Generated by .+pyCircuit|Generated by .+\.py|"
    r"do not (hand-)?edit)",
    re.IGNORECASE,
)

PLACEHOLDER_APPROVERS = {
    "",
    "todo",
    "tbd",
    "pending",
    "n/a",
    "na",
    "-",
}


@dataclass
class RtlUnit:
    module: str
    file: Path
    kind: str  # top | leaf | include
    sources: list[Path] = field(default_factory=list)


@dataclass
class Finding:
    check: str
    module: str
    file: str
    rule: str
    message: str
    severity: str = "error"
    bucket: str = "new"  # new | legacy | migrate | report
    waived_by: str = ""

    def key(self) -> tuple[str, str, str, str]:
        return (self.check, self.module, self.file, self.rule)


def die(msg: str, code: int = 1) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    raise SystemExit(code)


def rel(path: Path | str) -> str:
    p = Path(path)
    try:
        return p.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return p.as_posix()


def load_yaml(path: Path) -> Any:
    text = path.read_text(encoding="utf-8")
    try:
        import yaml  # type: ignore
    except ImportError:
        die(
            f"PyYAML is required to read {rel(path)}. "
            f"Install: pip install -r scripts/gate/requirements.txt"
        )
    data = yaml.safe_load(text)
    return data if data is not None else {}


LOCK_SCAN_SKIP_DIRS = {
    ".git",
    ".venv",
    "venv",
    ".pycircuit-venv",
    ".pycircuit-src",
    ".pycircuit_out",
    "node_modules",
    "__pycache__",
    "out",
}


def find_extra_toolchain_locks() -> list[Path]:
    """Any TOOLCHAIN.lock other than the repo-root copy is a conflict."""
    extras: list[Path] = []
    root = TOOLCHAIN_LOCK.resolve() if TOOLCHAIN_LOCK.is_file() else TOOLCHAIN_LOCK
    stack = [REPO_ROOT]
    while stack:
        d = stack.pop()
        try:
            kids = list(d.iterdir())
        except OSError:
            continue
        for child in kids:
            if child.is_dir():
                if child.name in LOCK_SCAN_SKIP_DIRS:
                    continue
                stack.append(child)
            elif child.name == "TOOLCHAIN.lock":
                try:
                    if child.resolve() != root:
                        extras.append(child)
                except OSError:
                    extras.append(child)
    return extras


def collect_toolchain_lock_findings(check: str) -> list[Finding]:
    extras = find_extra_toolchain_locks()
    if not extras:
        return []
    return [
        Finding(
            check=check,
            module="*",
            file="TOOLCHAIN.lock",
            rule="TOOLCHAIN_LOCK_CONFLICT",
            message=(
                "tool versions must come from the repo-root TOOLCHAIN.lock only; "
                f"extra copies: {[rel(p) for p in extras]}"
            ),
        )
    ]


def parse_lock(path: Path = TOOLCHAIN_LOCK) -> dict[str, str]:
    """Read the repo-root TOOLCHAIN.lock only. A second copy is a conflict."""
    if path.resolve() != TOOLCHAIN_LOCK.resolve():
        print(
            f"NOTE: ignoring non-root lock {rel(path)}; "
            f"versions from {rel(TOOLCHAIN_LOCK)} only"
        )
        path = TOOLCHAIN_LOCK
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or line.startswith("[") or "=" not in line:
            continue
        key, _, rest = line.partition("=")
        val = rest.strip().strip('"').strip("'")
        out[key.strip()] = val
    return out


def run_cmd(
    argv: list[str],
    cwd: Path | None = None,
    timeout: int | None = None,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        argv,
        cwd=cwd or REPO_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=timeout,
        check=False,
    )


def tool_version_line(cmd: list[str], fallback: str = "not-on-PATH") -> str:
    if not shutil_which(cmd[0]):
        return fallback
    proc = run_cmd(cmd)
    text = (proc.stdout or "").strip().splitlines()
    return text[0] if text else fallback


def shutil_which(name: str) -> str | None:
    from shutil import which

    return which(name)


def print_tool_versions(needed: Iterable[str]) -> None:
    lock = parse_lock()
    mapping = {
        "verilator": ("verilator_lock", ["verilator", "--version"]),
        "icarus": ("icarus_lock", ["iverilog", "-V"]),
        "yosys": ("yosys_lock", ["yosys", "-V"]),
        "eqy": ("eqy_lock", ["eqy", "--version"]),
        "sby": ("sby_lock", ["sby", "--version"]),
        "pycc": ("llvm_lock", ["pycc", "--version"]),
        "python": ("python_lock", [sys.executable, "--version"]),
        "llvm": ("llvm_lock", ["llvm-config-19", "--version"]),
        "cmake": ("cmake_lock", ["cmake", "--version"]),
        "ninja": ("ninja_lock", ["ninja", "--version"]),
    }
    extras = find_extra_toolchain_locks()
    print("=== tool versions (repo-root TOOLCHAIN.lock vs actual) ===")
    if extras:
        print(
            "TOOLCHAIN.lock CONFLICT: extra copies "
            f"{[rel(p) for p in extras]} (root is the only allowed source)"
        )
    for name in needed:
        lock_key, argv = mapping[name]
        locked = lock.get(lock_key, "")
        actual = tool_version_line(argv)
        on_path = shutil_which(argv[0]) is not None
        if locked:
            matched = locked in actual
            status = "MATCH" if matched else "MISMATCH — locked version not installed; using actual (not silent)"
            print(f"TOOL {name}: locked={locked} actual={actual} {status}")
        else:
            extra = "locked=(not in TOOLCHAIN.lock)"
            print(f"TOOL {name}: {extra} actual={actual}")
        if name in {"verilator", "icarus", "yosys", "eqy"} and not on_path:
            print(f"TOOL {name}: MISSING on PATH")
    print("=== end tool versions ===")


def read_list_patterns(path: Path) -> list[str]:
    pats: list[str] = []
    if not path.is_file():
        return pats
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if line:
            pats.append(line.replace("\\", "/"))
    return pats


def read_legacy_patterns(path: Path = LEGACY_LIST) -> list[str]:
    return read_list_patterns(path)


def read_migrate_patterns(path: Path = MIGRATE_LIST) -> list[str]:
    return read_list_patterns(path)


def is_migrate_path(path: Path, patterns: list[str] | None = None) -> bool:
    """Existing pyCircuit leaves from main / PR #5 / #7 / #11 / #12 (迁移待办)."""
    rel_path = rel(path)
    pats = patterns if patterns is not None else read_migrate_patterns()
    for pat in pats:
        if rel_path == pat or fnmatch.fnmatch(rel_path, pat):
            return True
        p = Path(pat)
        if len(p.parts) >= 3 and p.parts[0] == "pycircuit":
            layer, stem = p.parts[1], p.stem
            if rel_path in {
                f"rtl/{layer}/{stem}.v",
                f"rtl/{layer}/hooks/{stem}.v",
            }:
                return True
    return False


def looks_generated(path: Path) -> bool:
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:4000]
    except OSError:
        return False
    return bool(GENERATED_BANNER.search(head))


def is_legacy_path(path: Path, patterns: list[str] | None = None) -> bool:
    """D10 leftover: listed in legacy.txt and not a pyCircuit rewrite."""
    if looks_generated(path):
        return False
    if is_handwritten_path(path):
        return False
    rel_path = rel(path)
    pats = patterns if patterns is not None else read_legacy_patterns()
    for pat in pats:
        if rel_path == pat or rel_path.startswith(pat.rstrip("/") + "/"):
            return True
        if fnmatch.fnmatch(rel_path, pat):
            return True
    return False


def _file_for_class(path_text: str) -> str:
    # Verilator prints file:line[:col]; classify on the path only.
    cleaned = path_text.split(":")[0] if path_text else ""
    return cleaned


def classify_finding(finding: Finding) -> Finding:
    if finding.bucket == "report":
        return finding
    if finding.check == "spec_leak" or finding.rule in {
        "PLACEHOLDER_INSTANTIATED",
        "PLACEHOLDER_SOURCE_MISSING",
    }:
        finding.bucket = "new"
        return finding
    path = Path(REPO_ROOT / _file_for_class(finding.file))
    if is_handwritten_path(path):
        finding.bucket = "new"
    elif is_migrate_path(path):
        finding.bucket = "migrate"
    elif is_legacy_path(path):
        finding.bucket = "legacy"
    else:
        finding.bucket = "new"
    return finding


def load_approvers() -> set[str]:
    if not APPROVERS_FILE.is_file():
        return set()
    data = load_yaml(APPROVERS_FILE)
    names: set[str] = set()
    for row in data.get("gatekeepers") or []:
        login = str(row.get("login") or "").strip()
        role = str(row.get("role") or "").strip().lower()
        if login and role in {"verification", "verif", "gatekeeper", "工具守门"}:
            names.add(login)
        if login:
            # login is accepted only when marked as the verification gatekeeper
            if row.get("gatekeeper") is True or role:
                names.add(login)
    return names


def _entry_approved(entry: dict[str, Any], approvers: set[str], kind: str) -> bool:
    ident = entry.get("id") or entry.get("file")
    approver = str(entry.get("approver") or "").strip()
    status = str(entry.get("status") or "approved").strip().lower()
    if approver.lower() in PLACEHOLDER_APPROVERS:
        print(f"{kind} ignore {ident}: no approver (待守门人批准)")
        return False
    if approver not in approvers:
        print(f"{kind} ignore {ident}: approver {approver!r} is not a verification gatekeeper")
        return False
    if status in {"draft", "pending", "todo"}:
        print(f"{kind} ignore {ident}: status={status}")
        return False
    return True


_LIST_CACHE: dict[str, list[dict[str, Any]]] = {}


def _load_approved_list(path: Path, key: str, kind: str) -> list[dict[str, Any]]:
    cache_key = str(path)
    if cache_key in _LIST_CACHE:
        return _LIST_CACHE[cache_key]
    if not path.is_file():
        _LIST_CACHE[cache_key] = []
        return []
    data = load_yaml(path)
    approvers = load_approvers()
    accepted: list[dict[str, Any]] = []
    for entry in data.get(key) or []:
        if _entry_approved(entry, approvers, kind):
            accepted.append(dict(entry))
    _LIST_CACHE[cache_key] = accepted
    return accepted


def load_handwritten() -> list[dict[str, Any]]:
    """Approved handwritten SV entries from scripts/gate/handwritten.yml."""
    return _load_approved_list(HANDWRITTEN_LIST, "entries", "HANDWRITTEN")


def is_handwritten_path(path: Path) -> bool:
    rel_path = rel(path)
    for entry in load_handwritten():
        pat = str(entry.get("file") or "").replace("\\", "/")
        if not pat:
            continue
        if rel_path == pat or fnmatch.fnmatch(rel_path, pat):
            return True
    return False


def handwritten_modules() -> set[str]:
    """Module names (file stems) of approved handwritten cells."""
    names: set[str] = set()
    for entry in load_handwritten():
        pat = str(entry.get("file") or "")
        if pat:
            names.add(Path(pat).stem)
        mod = str(entry.get("module") or "")
        if mod:
            names.add(mod)
    return names or set(WHITELIST_CELLS)


BLACKBOX_KINDS = {"stub", "macro"}
BLACKBOX_PORTS = {"1RW", "1R1W"}
BLACKBOX_CONFLICT = {"old", "new"}
BLACKBOX_REQUIRED = (
    "module",
    "file",
    "kind",
    "replaces",
    "depth",
    "width",
    "ports",
    "read_latency",
    "rw_conflict",
    "reset",
    "macro",
    "reason",
    "registrant",
    "approver",
)


def load_blackbox_raw() -> list[dict[str, Any]]:
    if not BLACKBOX_LIST.is_file():
        return []
    data = load_yaml(BLACKBOX_LIST)
    rows = data.get("entries") if isinstance(data, dict) else None
    return [dict(e) for e in (rows or []) if isinstance(e, dict)]


def load_blackboxes() -> list[dict[str, Any]]:
    """Approved stub/macro entries from scripts/gate/blackbox.yml."""
    return _load_approved_list(BLACKBOX_LIST, "entries", "BLACKBOX")


def load_stubs() -> list[dict[str, Any]]:
    """Alias: approved blackbox.yml entries (kind stub|macro)."""
    return load_blackboxes()


def is_stub_listed(path: Path) -> bool:
    rel_path = rel(path)
    if path.stem in stub_modules():
        return True
    for entry in load_blackboxes():
        pat = str(entry.get("file") or "").replace("\\", "/")
        if not pat:
            continue
        if rel_path == pat or fnmatch.fnmatch(rel_path, pat):
            return True
    return False


def stub_modules() -> set[str]:
    names: set[str] = set()
    for entry in load_blackboxes():
        pat = str(entry.get("file") or "")
        if pat:
            names.add(Path(pat).stem)
        for key in ("module", "name"):
            mod = str(entry.get(key) or "")
            if mod:
                names.add(mod)
    return names


def blackbox_lib_files() -> list[Path]:
    """Files synth-check must read with `read_verilog -lib`."""
    files: list[Path] = []
    for entry in load_blackboxes():
        pat = str(entry.get("file") or "")
        if not pat:
            continue
        path = REPO_ROOT / pat
        if path.is_file():
            files.append(path)
    return files


def blackbox_by_module() -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for entry in load_blackboxes():
        name = str(entry.get("module") or Path(str(entry.get("file") or "")).stem)
        if name:
            out[name] = entry
    return out


def validate_blackbox_schema() -> list[Finding]:
    """Fail the job if blackbox.yml is missing fields or uses kind=primitive."""
    findings: list[Finding] = []
    if not BLACKBOX_LIST.is_file():
        return [
            Finding(
                check="lint",
                module="*",
                file=rel(BLACKBOX_LIST),
                rule="BLACKBOX_LIST_MISSING",
                message="scripts/gate/blackbox.yml is required",
            )
        ]
    for idx, entry in enumerate(load_blackbox_raw()):
        ident = str(entry.get("id") or entry.get("module") or f"entry[{idx}]")
        missing = [k for k in BLACKBOX_REQUIRED if str(entry.get(k) or "").strip() == ""]
        if missing:
            findings.append(
                Finding(
                    check="lint",
                    module=str(entry.get("module") or "*"),
                    file=rel(BLACKBOX_LIST),
                    rule="BLACKBOX_SCHEMA",
                    message=f"{ident}: missing/empty fields {missing}",
                )
            )
        kind = str(entry.get("kind") or "").strip().lower()
        if kind and kind not in BLACKBOX_KINDS:
            findings.append(
                Finding(
                    check="lint",
                    module=str(entry.get("module") or "*"),
                    file=rel(BLACKBOX_LIST),
                    rule="BLACKBOX_KIND",
                    message=(
                        f"{ident}: kind={kind!r} is not allowed; "
                        f"use stub|macro (Xia: ub_cmn_mem_1r1w is a normal "
                        f"pycircuit/cmn leaf, not kind=primitive)"
                    ),
                )
            )
        ports = str(entry.get("ports") or "").strip()
        if ports and ports not in BLACKBOX_PORTS:
            findings.append(
                Finding(
                    check="lint",
                    module=str(entry.get("module") or "*"),
                    file=rel(BLACKBOX_LIST),
                    rule="BLACKBOX_SCHEMA",
                    message=f"{ident}: ports={ports!r} must be 1RW or 1R1W",
                )
            )
        conflict = str(entry.get("rw_conflict") or "").strip().lower()
        if conflict and conflict not in BLACKBOX_CONFLICT:
            findings.append(
                Finding(
                    check="lint",
                    module=str(entry.get("module") or "*"),
                    file=rel(BLACKBOX_LIST),
                    rule="BLACKBOX_SCHEMA",
                    message=f"{ident}: rw_conflict={conflict!r} must be old or new",
                )
            )
        reset = str(entry.get("reset") or "")
        valid_outside = entry.get("valid_outside")
        if re.search(r"不复位|unreset|no.?reset", reset, re.I) and valid_outside is not True:
            findings.append(
                Finding(
                    check="lint",
                    module=str(entry.get("module") or "*"),
                    file=rel(BLACKBOX_LIST),
                    rule="BLACKBOX_VALID_OUTSIDE",
                    message=(
                        f"{ident}: reset says the array is not reset; "
                        f"set valid_outside: true or RDC will fail"
                    ),
                )
            )
    return findings


STUB_ATTR_RE = re.compile(r"\(\*\s*(?:blackbox|stub)\s*\*\)", re.I)
STUB_NAME_RE = re.compile(r"_(?:stub|blackbox|bb)$", re.I)
STUB_COMMENT_RE = re.compile(
    r"\b(?:blackbox|behavioral stub|sram stub|SRAM stub)\b",
    re.I,
)


def looks_like_stub_or_blackbox(path: Path) -> bool:
    """Heuristic: attribute, name, directory, or comment marks a stub/blackbox."""
    if STUB_NAME_RE.search(path.stem):
        return True
    parts = {p.lower() for p in path.parts}
    if parts & {"stubs", "blackbox", "blackboxes"}:
        return True
    try:
        text = path.read_text(encoding="utf-8", errors="replace")[:8000]
    except OSError:
        return False
    return bool(STUB_ATTR_RE.search(text) or STUB_COMMENT_RE.search(text))


def iter_rtl_sources() -> list[Path]:
    rtl = REPO_ROOT / "rtl"
    if not rtl.is_dir():
        return []
    out: list[Path] = []
    for path in sorted(rtl.rglob("*")):
        if path.is_file() and path.suffix.lower() in RTL_SOURCE_SUFFIXES:
            out.append(path)
    return out


def load_hooks_ports() -> dict[str, list[str]]:
    """module → allowed extra HOOKS port names (approved entries only)."""
    extra: dict[str, list[str]] = {}
    for entry in _load_approved_list(HOOKS_PORTS_LIST, "entries", "HOOKS_PORTS"):
        module = str(entry.get("module") or "").strip()
        if not module:
            continue
        ports: list[str] = []
        for item in entry.get("extra_ports") or []:
            if isinstance(item, str):
                ports.append(item)
            elif isinstance(item, dict) and item.get("name"):
                ports.append(str(item["name"]))
        extra[module] = ports
    return extra


# Xia: HOOKS-only backdoors. tb_<inst>_bd_* and companion tb_<inst>_bd_vld_*.
# Gated by tb_test_mode; must be on the SPEC §10 list (hooks_ports.yml).
_TB_BD_VLD_RE = re.compile(r"^tb_[A-Za-z_][A-Za-z0-9_]*_bd_vld_")
_TB_BD_RE = re.compile(r"^tb_[A-Za-z_][A-Za-z0-9_]*_bd_")


def is_tb_port(name: str) -> bool:
    return name == "tb_test_mode" or name.startswith("tb_")


def is_tb_bd_vld_port(name: str) -> bool:
    return bool(_TB_BD_VLD_RE.match(name))


def is_tb_bd_port(name: str) -> bool:
    return bool(_TB_BD_RE.match(name)) and not is_tb_bd_vld_port(name)


def is_listed_hook_style(name: str) -> bool:
    """Allowed tb_* shapes on the §10 / hooks_ports.yml list."""
    return (
        name == "tb_test_mode"
        or name.startswith("tb_inj_")
        or name.startswith("tb_obs_")
        or is_tb_bd_port(name)
        or is_tb_bd_vld_port(name)
    )


def is_eqy_tie_low_port(name: str) -> bool:
    """HOOKS extra inputs tied to 0 for PRODUCT≡HOOKS (SPEC §11 (d)(f))."""
    return (
        name == "tb_test_mode"
        or name.startswith("tb_inj_")
        or is_tb_bd_port(name)
        or is_tb_bd_vld_port(name)
    )


def hooks_extra_for(module: str, leaf: str | None = None) -> list[str] | None:
    """Look up extra ports by variant module, then by untagged leaf."""
    table = load_hooks_ports()
    if module in table:
        return table[module]
    if leaf and leaf in table:
        return table[leaf]
    cmn_tag = cmn_mem_tag_of(module)
    if cmn_tag and CMN_MEM_CELL in table:
        return table[CMN_MEM_CELL]
    # ub_lmsm_x4 → ub_lmsm
    if "_" in module:
        stem = module.rsplit("_", 1)[0]
        if stem in table:
            return table[stem]
    return None


def find_module_inventory() -> Path | None:
    for path in INVENTORY_CANDIDATES:
        if path.is_file():
            return path
    return None


def load_module_inventory() -> dict[str, Any]:
    path = find_module_inventory()
    if path is None:
        return {}
    data = load_yaml(path)
    return data if isinstance(data, dict) else {}


def load_waivers(check: str | None = None) -> list[dict[str, Any]]:
    approvers = load_approvers()
    accepted: list[dict[str, Any]] = []
    if not WAIVERS_DIR.is_dir():
        return accepted
    for path in sorted(WAIVERS_DIR.glob("*.yml")):
        if path.name == "approvers.yml":
            continue
        data = load_yaml(path)
        for entry in data.get("waivers") or []:
            if check and entry.get("check") != check:
                continue
            approver = str(entry.get("approver") or "").strip()
            status = str(entry.get("status") or "approved").strip().lower()
            if approver.lower() in PLACEHOLDER_APPROVERS:
                print(
                    f"WAIVER ignore {entry.get('id')}: no approver "
                    f"(待守门人批准)"
                )
                continue
            if approver not in approvers:
                print(
                    f"WAIVER ignore {entry.get('id')}: approver {approver!r} "
                    f"is not a verification gatekeeper"
                )
                continue
            if status in {"draft", "pending", "todo"}:
                print(f"WAIVER ignore {entry.get('id')}: status={status}")
                continue
            accepted.append(dict(entry))
    return accepted


def waiver_matches(finding: Finding, entry: dict[str, Any]) -> bool:
    if entry.get("check") and entry["check"] != finding.check:
        return False
    module = entry.get("module") or entry.get("模块")
    if module and str(module) not in {finding.module, "*"}:
        return False
    fpat = entry.get("file") or entry.get("文件")
    if fpat and not fnmatch.fnmatch(finding.file, str(fpat)):
        return False
    rule = entry.get("rule") or entry.get("规则")
    if rule and str(rule) not in {finding.rule, "*"}:
        return False
    msg = entry.get("message") or entry.get("消息匹配")
    if msg and not re.search(str(msg), finding.message):
        return False
    return True


def apply_waivers(findings: list[Finding], check: str) -> list[Finding]:
    waivers = load_waivers(check)
    for finding in findings:
        classify_finding(finding)
        for entry in waivers:
            if waiver_matches(finding, entry):
                finding.waived_by = str(entry.get("id") or entry.get("approver"))
                break
    return findings


def split_findings(
    findings: list[Finding],
) -> tuple[list[Finding], list[Finding], list[Finding], list[Finding], list[Finding]]:
    blocking: list[Finding] = []
    legacy: list[Finding] = []
    migrate: list[Finding] = []
    report: list[Finding] = []
    waived: list[Finding] = []
    for f in findings:
        if f.waived_by:
            waived.append(f)
        elif f.bucket == "legacy":
            legacy.append(f)
        elif f.bucket == "migrate":
            migrate.append(f)
        elif f.bucket == "report":
            report.append(f)
        else:
            blocking.append(f)
    return blocking, legacy, migrate, report, waived


def emit_report(check: str, findings: list[Finding]) -> int:
    """Print the multi-column report. Return process exit code."""
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    merged = list(findings) + collect_toolchain_lock_findings(check)
    apply_waivers(merged, check)
    findings = merged
    blocking, legacy, migrate, report, waived = split_findings(findings)
    print(f"=== {check} findings ===")
    print(
        f"total={len(findings)} blocking={len(blocking)} "
        f"legacy_report_only={len(legacy)} migrate_backlog={len(migrate)} "
        f"report_only={len(report)} waived={len(waived)}"
    )
    print()
    print("## New leaves (blocking)")
    if not blocking:
        print("(none)")
    else:
        _print_table(blocking)
    print()
    print("## D10 legacy (report-only; 待 legacy 迁移 PR 处理、守门人批准)")
    if not legacy:
        print("(none)")
    else:
        _print_table(legacy)
    print()
    print("## pyCircuit migrate (main / PR #5 / #7 / #11 / #12; 迁移待办)")
    roster = read_migrate_roster()
    if roster:
        print("| path | group | status |")
        print("| --- | --- | --- |")
        for row in roster:
            print(f"| {row['path']} | {row['group']} | {row['status'] or ''} |")
    if migrate:
        _print_table(migrate)
    elif not roster:
        print("(none)")
    pending = list_pending_waivers()
    placeholders = [
        leaf
        for leaf in discover_pycircuit_leaves() + discover_product_leaves()
        if leaf.get("placeholder")
    ]
    if placeholders:
        print()
        print("## SPEC §2.2 _placeholder (lint/TB only; not PRODUCT; not synth)")
        print("| module | layer | file |")
        print("| --- | --- | --- |")
        seen_ph: set[str] = set()
        for leaf in placeholders:
            key = str(leaf.get("module"))
            if key in seen_ph:
                continue
            seen_ph.add(key)
            print(
                f"| {leaf.get('module')} | {leaf.get('layer')} | "
                f"{leaf.get('product') or leaf.get('source') or ''} |"
            )
    if report:
        print()
        print("## Report-only (non-blocking; inventory / timing / pycc emit / combo depth)")
        _print_table(report)
    if waived:
        print()
        print("## Waived (approved gatekeeper entries only)")
        _print_table(waived)
    if pending:
        print()
        print("## Pending waiver drafts (waivers/pending/; inactive until approved)")
        print("| id | check | file | status |")
        print("| --- | --- | --- | --- |")
        for row in pending:
            print(
                f"| {row.get('id') or ''} | {row.get('check') or ''} | "
                f"{row.get('file') or ''} | {row.get('status') or 'pending'} |"
            )
    payload = {
        "check": check,
        "blocking": [asdict(f) for f in blocking],
        "legacy": [asdict(f) for f in legacy],
        "migrate": [asdict(f) for f in migrate],
        "report": [asdict(f) for f in report],
        "waived": [asdict(f) for f in waived],
    }
    (OUT_DIR / f"{check}.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    if blocking:
        print(f"\n{check}: FAIL ({len(blocking)} blocking finding(s) on new leaves)")
        return 1
    print(f"\n{check}: PASS (no blocking findings on new leaves)")
    return 0


def read_migrate_roster() -> list[dict[str, str]]:
    """Parse scripts/gate/pycircuit_migrate.txt including group comments."""
    rows: list[dict[str, str]] = []
    if not MIGRATE_LIST.is_file():
        return rows
    group = "main"
    status = ""
    seen: set[tuple[str, str]] = set()
    for raw in MIGRATE_LIST.read_text(encoding="utf-8").splitlines():
        stripped = raw.strip()
        if stripped.startswith("#"):
            body = stripped[1:].strip()
            low = body.lower()
            if low.startswith("main"):
                group, status = "main", ""
            elif "pr #11" in low:
                group = "PR #11"
                status = "已迁" if "已迁" in body else "待 Xia 核实"
            elif body.upper().startswith("PR #"):
                group = body.split("—")[0].split("-")[0].strip()
                status = ""
            continue
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        key = (line, group)
        if key in seen:
            continue
        seen.add(key)
        rows.append({"path": line, "group": group, "status": status})
    return rows


def list_pending_waivers() -> list[dict[str, str]]:
    pending_dir = WAIVERS_DIR / "pending"
    out: list[dict[str, str]] = []
    if not pending_dir.is_dir():
        return out
    for path in sorted(pending_dir.glob("*.yml")):
        if path.name.lower() == "readme.yml":
            continue
        try:
            data = load_yaml(path)
        except SystemExit:
            continue
        entries = data.get("waivers") if isinstance(data, dict) else None
        if not entries:
            continue
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            out.append(
                {
                    "id": str(entry.get("id") or ""),
                    "check": str(entry.get("check") or ""),
                    "file": rel(path),
                    "status": str(entry.get("status") or "pending"),
                }
            )
    return out


def _print_table(rows: list[Finding]) -> None:
    print("| module | check | rule | file | message |")
    print("| --- | --- | --- | --- | --- |")
    for f in rows:
        msg = f.message.replace("\n", " ").replace("|", "/")
        if len(msg) > 160:
            msg = msg[:157] + "..."
        print(f"| {f.module} | {f.check} | {f.rule} | {f.file} | {msg} |")


def _is_rtl_file(path: Path) -> bool:
    return path.suffix.lower() in RTL_SOURCE_SUFFIXES | RTL_INCLUDE_SUFFIXES


def _excluded(path: Path) -> bool:
    rel_path = rel(path)
    parts = rel_path.split("/")
    if any(p in {"tb", "legacy", "sim_build"} for p in parts):
        return True
    name = path.name
    if name.endswith("_tb.v") or name.endswith("_tb.sv"):
        return True
    return False


def parse_filelist(path: Path) -> tuple[list[Path], list[Path]]:
    files: list[Path] = []
    incdirs: list[Path] = []
    base = path.parent
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("+incdir+"):
            incdirs.append((base / line[len("+incdir+") :]).resolve())
            continue
        if line.startswith("-I"):
            incdirs.append((base / line[2:].strip()).resolve())
            continue
        files.append((base / line).resolve())
    return files, incdirs


def discover_layers(root: Path) -> list[str]:
    """Directory names under root that count as hierarchy layers / ifaces.

    Always includes `cmn` (Xia: ub_cmn_mem_1r1w lives in pycircuit/cmn,
    rtl/cmn, formal/cmn) even if the directory is still empty.
    """
    names: set[str] = set()
    if root.is_dir():
        for path in sorted(root.iterdir()):
            if not path.is_dir():
                continue
            if path.name in LAYER_SKIP or path.name.startswith("."):
                continue
            names.add(path.name)
    if root.name in {"pycircuit", "rtl", "formal", "tb"}:
        names.update(ALWAYS_LAYERS)
    return sorted(names)


def is_hooks_path(path: Path) -> bool:
    return "hooks" in {p.lower() for p in path.parts}


def discover_rtl() -> dict[str, Any]:
    """Layer-based discovery. Never scans rtl/gen.

    PRODUCT = rtl/<layer>/*.{v,sv}
    HOOKS   = rtl/<layer>/hooks/*.{v,sv}
    <layer> is auto-enumerated (pcs, dll, common, cmn, tp, ta, mem, ...).
    Layers correspond 1:1 with pycircuit/<layer>/.
    Files sitting directly under rtl/ are D10 leftovers only.
    """
    sources: list[Path] = []
    incdirs: list[Path] = []
    used_filelists = False
    filelists: list[Path] = []
    rtl_root = REPO_ROOT / "rtl"
    pyc_root = REPO_ROOT / "pycircuit"
    layers = discover_layers(rtl_root)
    pyc_layers = discover_layers(pyc_root)
    seen: set[Path] = set()

    def _add(path: Path) -> None:
        if not path.is_file() or not _is_rtl_file(path) or _excluded(path):
            return
        if "gen" in {p.lower() for p in path.parts}:
            return
        rp = path.resolve()
        if rp in seen:
            return
        seen.add(rp)
        sources.append(rp)

    if rtl_root.is_dir():
        for path in sorted(rtl_root.iterdir()):
            if path.is_file():
                _add(path)  # D10 leftovers at rtl/*.v
        for layer in layers:
            if layer == "gen":
                continue
            layer_dir = rtl_root / layer
            if not layer_dir.is_dir():
                continue
            for path in sorted(layer_dir.iterdir()):
                if path.is_file():
                    _add(path)
            hooks = layer_dir / "hooks"
            if hooks.is_dir():
                for path in sorted(hooks.iterdir()):
                    if path.is_file():
                        _add(path)
            incdirs.append(layer_dir.resolve())
        incdirs.append(rtl_root.resolve())

    print(
        "RTL discovery: PRODUCT=rtl/<layer>/*.{v,sv} "
        "HOOKS=rtl/<layer>/hooks/*.{v,sv} "
        f"(no rtl/gen). rtl_layers={layers or []} "
        f"pycircuit_layers={pyc_layers or []}"
    )
    missing_rtl = [ly for ly in pyc_layers if ly not in layers]
    extra_rtl = [ly for ly in layers if ly not in pyc_layers and ly != "common"]
    if missing_rtl:
        print(f"NOTE: pycircuit layers with no rtl/<layer>/: {missing_rtl}")
    if extra_rtl:
        print(f"NOTE: rtl layers with no pycircuit/<layer>/: {extra_rtl}")

    sources = [p for p in sources if p.is_file()]
    modules: list[RtlUnit] = []
    inst_re = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]*)\s+#\s*\(|\b([A-Za-z_][A-Za-z0-9_]*)\s+[A-Za-z_][A-Za-z0-9_]*\s*\(")
    mod_re = re.compile(r"^\s*module\s+([A-Za-z_][A-Za-z0-9_]*)\b", re.MULTILINE)
    defined: dict[str, RtlUnit] = {}
    instantiations: dict[str, set[str]] = {}
    for path in sources:
        if path.suffix.lower() not in RTL_SOURCE_SUFFIXES:
            continue
        text = strip_verilog_comments(path.read_text(encoding="utf-8", errors="replace"))
        names = mod_re.findall(text)
        if not names:
            continue
        insts: set[str] = set()
        # Drop the module's own name from instantiation matches.
        for m in re.finditer(
            r"\b([A-Za-z_][A-Za-z0-9_]*)\s+(?:#\s*\([^;]*\)\s*)?([A-Za-z_][A-Za-z0-9_]*)\s*\(",
            text,
        ):
            cell, inst = m.group(1), m.group(2)
            if cell in {"module", "function", "task", "if", "for", "while", "case"}:
                continue
            if inst in {"begin", "end"}:
                continue
            insts.add(cell)
        for name in names:
            unit = RtlUnit(module=name, file=path, kind="leaf", sources=sources)
            defined[name] = unit
            instantiations[name] = insts - {name}

    kids: set[str] = set()
    for insts in instantiations.values():
        kids.update(insts)
    for name, unit in defined.items():
        unit.kind = "leaf" if name not in instantiations or not (instantiations[name] & set(defined)) else "top"
        # A module that instantiates another discovered module is a top (or mid).
        if instantiations.get(name, set()) & set(defined):
            unit.kind = "top"
        else:
            unit.kind = "leaf"
        modules.append(unit)

    # Unique include dirs
    uniq_inc: list[Path] = []
    for d in incdirs:
        if d not in uniq_inc and d.is_dir():
            uniq_inc.append(d)
    # Always add rtl/ and rtl/common when present
    for extra in (REPO_ROOT / "rtl", REPO_ROOT / "rtl" / "common"):
        if extra.is_dir() and extra.resolve() not in uniq_inc:
            uniq_inc.append(extra.resolve())

    return {
        "sources": sources,
        "incdirs": uniq_inc,
        "modules": modules,
        "used_filelists": used_filelists,
        "filelists": filelists,
        "instantiations": instantiations,
        "defined": defined,
        "layers": layers,
        "pycircuit_layers": pyc_layers,
    }


VARIANT_TABLE_NAMES = {
    "VARIANTS",
    "TAGS",
    "PARAM_SETS",
    "EMIT_TAGS",
    "PARAM_VARIANTS",
    "VARIANT_TABLE",
    "EMIT_VARIANTS",
}


def is_placeholder_module(name: str) -> bool:
    return name.endswith("_placeholder") or "_placeholder_" in name


def is_placeholder_path(path: Path) -> bool:
    return is_placeholder_module(Path(path).stem)


def variant_module_name(leaf: str, tag: str | None) -> str:
    """SPEC §2.2: <leaf>_<tag>; single parameter set has no tag."""
    if tag is None:
        return leaf
    t = str(tag).strip()
    if t in {"", "default", "-", "none"}:
        return leaf
    t = t.lstrip("_")
    return f"{leaf}_{t}"


def _const_to_py(node: ast.AST) -> Any:
    if isinstance(node, ast.Constant):
        return node.value
    if isinstance(node, ast.Dict):
        out: dict[Any, Any] = {}
        for k, v in zip(node.keys, node.values):
            if k is None:
                continue
            out[_const_to_py(k)] = _const_to_py(v)
        return out
    if isinstance(node, ast.List):
        return [_const_to_py(x) for x in node.elts]
    if isinstance(node, ast.Tuple):
        return tuple(_const_to_py(x) for x in node.elts)
    return None


def parse_variant_table(path: Path) -> list[dict[str, Any]]:
    """Read the tag → params table from a leaf source (SPEC §2.2).

    Missing table → one untagged variant. Tag `placeholder` / `_placeholder`
    becomes module `<leaf>_placeholder`.
    """
    if not path.is_file():
        return [{"tag": None, "params": {}, "placeholder": False}]
    try:
        tree = ast.parse(path.read_text(encoding="utf-8", errors="replace"))
    except SyntaxError:
        return [{"tag": None, "params": {}, "placeholder": False}]
    table: Any = None
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        for tgt in node.targets:
            if isinstance(tgt, ast.Name) and tgt.id in VARIANT_TABLE_NAMES:
                table = _const_to_py(node.value)
                break
        if table is not None:
            break
    if not table:
        return [{"tag": None, "params": {}, "placeholder": False}]
    rows: list[dict[str, Any]] = []
    if isinstance(table, dict):
        items = list(table.items())
    elif isinstance(table, (list, tuple)):
        items = []
        for item in table:
            if isinstance(item, dict) and "tag" in item:
                items.append((item.get("tag"), item.get("params") or {}))
            elif isinstance(item, str):
                items.append((item, {}))
    else:
        return [{"tag": None, "params": {}, "placeholder": False}]
    if len(items) == 1 and (items[0][0] in {None, "", "default"}):
        return [{"tag": None, "params": items[0][1] or {}, "placeholder": False}]
    for tag, params in items:
        tag_s = None if tag in {None, ""} else str(tag)
        ph = bool(tag_s and "placeholder" in tag_s)
        rows.append({"tag": tag_s, "params": params if isinstance(params, dict) else {}, "placeholder": ph})
    return rows or [{"tag": None, "params": {}, "placeholder": False}]


def discover_rtl_variants(layer: str, leaf: str) -> list[str]:
    """Committed PRODUCT modules for a leaf: <leaf>.v and <leaf>_*.v."""
    layer_dir = REPO_ROOT / "rtl" / layer
    if not layer_dir.is_dir():
        return []
    names: list[str] = []
    for path in sorted(layer_dir.iterdir()):
        if not path.is_file() or path.suffix.lower() not in RTL_SOURCE_SUFFIXES:
            continue
        if path.stem == leaf or path.stem.startswith(f"{leaf}_"):
            names.append(path.stem)
    return names


def discover_pycircuit_leaves() -> list[dict[str, Any]]:
    """Leaves from pycircuit/<layer>/*.py, expanded per SPEC §2.2 variant."""
    root = REPO_ROOT / "pycircuit"
    skip_py = {"__init__.py", "emit.py", "selfcheck.py"}
    leaves: list[dict[str, Any]] = []
    for layer in discover_layers(root):
        for path in sorted((root / layer).glob("*.py")):
            if path.name in skip_py:
                continue
            table = parse_variant_table(path)
            rtl_names = discover_rtl_variants(layer, path.stem)
            planned = [variant_module_name(path.stem, row["tag"]) for row in table]
            modules = list(dict.fromkeys(planned + rtl_names))
            if not modules:
                modules = [path.stem]
            for module in modules:
                tag = None
                params: dict[str, Any] = {}
                placeholder = is_placeholder_module(module)
                for row in table:
                    if variant_module_name(path.stem, row["tag"]) == module:
                        tag = row["tag"]
                        params = row["params"]
                        placeholder = placeholder or bool(row["placeholder"])
                        break
                if module != path.stem and tag is None and module.startswith(f"{path.stem}_"):
                    tag = module[len(path.stem) + 1 :]
                parsed = parse_cmn_mem_tag(tag) if is_cmn_mem_module(module) else None
                if parsed and not params:
                    params = parsed
                leaves.append(
                    {
                        "layer": layer,
                        "leaf": path.stem,
                        "module": module,
                        "tag": tag,
                        "params": params,
                        "placeholder": placeholder,
                        "source": rel(path),
                        "product": f"rtl/{layer}/{module}.v",
                        "hooks": f"rtl/{layer}/hooks/{module}.v",
                    }
                )
    return leaves


def load_leak_allow() -> list[dict[str, Any]]:
    return _load_approved_list(LEAK_ALLOW_LIST, "entries", "LEAK_ALLOW")


def is_leak_allowed(path: Path) -> bool:
    rel_path = rel(path)
    for entry in load_leak_allow():
        pat = str(entry.get("file") or entry.get("path") or "").replace("\\", "/")
        if not pat:
            continue
        if rel_path == pat or fnmatch.fnmatch(rel_path, pat):
            return True
    return False


def is_cmn_mem_module(name: str) -> bool:
    return name == CMN_MEM_CELL or name.startswith(CMN_MEM_CELL + "_")


# Xia: ub_cmn_mem_1r1w_<tag> with tag d<DEPTH>w<WIDTH>[m<WMASK_W>]
# e.g. d512w512m64, d64w64m16. Bits for the blackbox test are DEPTH*WIDTH.
_CMN_MEM_TAG_RE = re.compile(r"^d(\d+)w(\d+)(?:m(\d+))?$", re.I)


def parse_cmn_mem_tag(tag: str | None) -> dict[str, int] | None:
    if not tag:
        return None
    m = _CMN_MEM_TAG_RE.fullmatch(str(tag).strip().lstrip("_"))
    if not m:
        return None
    out = {"DEPTH": int(m.group(1)), "WIDTH": int(m.group(2))}
    if m.group(3):
        out["WMASK_W"] = int(m.group(3))
    return out


def cmn_mem_tag_of(name: str) -> str | None:
    """Return the d<DEPTH>w<WIDTH>[m<WMASK_W>] tag, or None."""
    if name == CMN_MEM_CELL:
        return None
    prefix = CMN_MEM_CELL + "_"
    if name.startswith(prefix):
        tag = name[len(prefix) :]
        if parse_cmn_mem_tag(tag):
            return tag
    return None


_CMN_THRESH_CACHE: int | None = None


def read_cmn_mem_threshold_bits() -> int:
    """Threshold in bits. Read impl_quick_synth.md; default 4096 (4 kbit)."""
    global _CMN_THRESH_CACHE
    if _CMN_THRESH_CACHE is not None:
        return _CMN_THRESH_CACHE
    path = IMPL_QUICK_SYNTH_MD
    if not path.is_file():
        print(
            f"NOTE: {rel(path)} missing; "
            f"ub_cmn_mem_1r1w blackbox threshold={DEFAULT_CMN_MEM_THRESH_BITS} bits"
        )
        _CMN_THRESH_CACHE = DEFAULT_CMN_MEM_THRESH_BITS
        return _CMN_THRESH_CACHE
    text = path.read_text(encoding="utf-8", errors="replace")
    m = re.search(
        r"(?:threshold|blackbox|cmn_mem)[^\n]{0,60}?(\d+)\s*bits?",
        text,
        re.I,
    )
    if m:
        _CMN_THRESH_CACHE = int(m.group(1))
        return _CMN_THRESH_CACHE
    m = re.search(r"(\d+(?:\.\d+)?)\s*kbit", text, re.I)
    if m:
        _CMN_THRESH_CACHE = int(float(m.group(1)) * 1024)
        return _CMN_THRESH_CACHE
    m = re.search(r"\b(2048|4096|8192|16384)\b", text)
    if m:
        _CMN_THRESH_CACHE = int(m.group(1))
        return _CMN_THRESH_CACHE
    print(
        f"NOTE: {rel(path)} has no kbit/bits threshold; "
        f"using {DEFAULT_CMN_MEM_THRESH_BITS}"
    )
    _CMN_THRESH_CACHE = DEFAULT_CMN_MEM_THRESH_BITS
    return _CMN_THRESH_CACHE


def _parse_int_lit(text: str) -> int | None:
    text = text.strip().replace("_", "")
    if re.fullmatch(r"\d+", text):
        return int(text)
    m = re.fullmatch(r"(\d+)'[dD](\d+)", text)
    if m:
        return int(m.group(2))
    m = re.fullmatch(r"(\d+)'[hH]([0-9a-fA-F]+)", text)
    if m:
        return int(m.group(2), 16)
    return None


def parse_cmn_mem_dims(path: Path | None, extra: dict[str, Any] | None = None) -> tuple[int | None, int | None]:
    """Return (depth, width) from tag / params / file. Bits = DEPTH*WIDTH."""
    depth = width = None
    extra = extra or {}
    for key in (
        extra.get("tag"),
        extra.get("module"),
        path.stem if path is not None else None,
    ):
        if not key:
            continue
        tag = cmn_mem_tag_of(str(key)) or (
            str(key) if parse_cmn_mem_tag(str(key)) else None
        )
        parsed = parse_cmn_mem_tag(tag)
        if parsed:
            depth = depth or parsed["DEPTH"]
            width = width or parsed["WIDTH"]
            break
    for key, val in extra.items():
        lk = str(key).lower()
        if lk in {"depth", "words", "entries"} and isinstance(val, (int, str)):
            parsed = _parse_int_lit(str(val))
            if parsed is not None:
                depth = parsed
        if lk in {"width", "dw", "data_w"} and isinstance(val, (int, str)):
            parsed = _parse_int_lit(str(val))
            if parsed is not None:
                width = parsed
    if path and path.is_file():
        text = strip_verilog_comments(path.read_text(encoding="utf-8", errors="replace"))
        for name, dest in (("depth", "depth"), ("width", "width"), ("dw", "width")):
            m = re.search(
                rf"\b(?:parameter|localparam)\s+(?:integer\s+)?{name}\s*=\s*([^,;]+)",
                text,
                re.I,
            )
            if m:
                parsed = _parse_int_lit(m.group(1))
                if parsed is not None:
                    if dest == "depth" and depth is None:
                        depth = parsed
                    if dest == "width" and width is None:
                        width = parsed
        # array:  reg [W-1:0] mem [0:D-1]
        m = re.search(
            r"\b(?:reg|logic)\s*\[\s*(\d+)\s*[-:]",
            text,
            re.I,
        )
        m2 = re.search(
            r"\]\s*[A-Za-z_][A-Za-z0-9_]*\s*\[\s*(?:0\s*:\s*)?(\d+)",
            text,
        )
        if width is None and m:
            width = int(m.group(1)) + 1
        if depth is None and m2:
            depth = int(m2.group(1)) + (0 if "0:" in (m2.group(0) or "") else 0)
            if "0:" in m2.group(0):
                depth = int(m2.group(1)) + 1
        # filename / module: official d<DEPTH>w<WIDTH>[m<WMASK_W>]; legacy _NxN / _dN_wN
        stem = path.stem
        parsed = parse_cmn_mem_tag(cmn_mem_tag_of(stem) or "")
        if parsed:
            depth = depth or parsed["DEPTH"]
            width = width or parsed["WIDTH"]
        m = re.search(r"_(\d+)x(\d+)$", stem, re.I)
        if m:
            depth = depth or int(m.group(1))
            width = width or int(m.group(2))
        m = re.search(r"_d(\d+)_w(\d+)", stem, re.I)
        if m:
            depth = depth or int(m.group(1))
            width = width or int(m.group(2))
    return depth, width


def cmn_mem_bits(path: Path | None, extra: dict[str, Any] | None = None) -> int | None:
    depth, width = parse_cmn_mem_dims(path, extra)
    if depth is None or width is None:
        return None
    return depth * width


def cmn_mem_is_large(path: Path | None, extra: dict[str, Any] | None = None, thresh: int | None = None) -> bool:
    bits = cmn_mem_bits(path, extra)
    if bits is None:
        return False
    return bits > (thresh if thresh is not None else read_cmn_mem_threshold_bits())


def large_cmn_mem_lib_files(top: str, disc: dict[str, Any] | None = None) -> list[Path]:
    """Mem files that parent synth/equiv must read with -lib (same copy both sides)."""
    thresh = read_cmn_mem_threshold_bits()
    disc = disc or discover_rtl()
    defined: dict = disc.get("defined") or {}
    files: list[Path] = []
    seen: set[Path] = set()
    # Walk the instance closure.
    stack = [top]
    visited: set[str] = set()
    inst_map: dict[str, set[str]] = disc.get("instantiations") or {}
    while stack:
        name = stack.pop()
        if name in visited:
            continue
        visited.add(name)
        unit = defined.get(name)
        if unit is None:
            continue
        if is_cmn_mem_module(name) and cmn_mem_is_large(unit.file, thresh=thresh):
            rp = unit.file.resolve()
            if rp not in seen:
                seen.add(rp)
                files.append(unit.file)
            continue
        # Instance-level overrides on this parent.
        if unit.file.is_file() and not is_cmn_mem_module(name):
            text = strip_verilog_comments(
                unit.file.read_text(encoding="utf-8", errors="replace")
            )
            for m in re.finditer(
                rf"\b({re.escape(CMN_MEM_CELL)}\w*)\s+(?:#\s*\((.*?)\)\s*)?"
                rf"([A-Za-z_][A-Za-z0-9_]*)\s*\(",
                text,
                re.S,
            ):
                cell, plist, _inst = m.group(1), m.group(2) or "", m.group(3)
                params: dict[str, Any] = {}
                tagged = parse_cmn_mem_tag(cmn_mem_tag_of(cell) or "")
                if tagged:
                    params.update(tagged)
                for pm in re.finditer(
                    r"\.(DEPTH|WIDTH|WMASK_W|depth|width|wmask_w)\s*\(\s*([^)]+)\)",
                    plist,
                    re.I,
                ):
                    params[pm.group(1)] = pm.group(2).strip()
                cell_unit = defined.get(cell)
                cell_path = cell_unit.file if cell_unit is not None else None
                if cmn_mem_is_large(cell_path, params, thresh=thresh) and cell_path:
                    rp = cell_path.resolve()
                    if rp not in seen:
                        seen.add(rp)
                        files.append(cell_path)
        for child in inst_map.get(name, set()):
            stack.append(child)
    return files


def placeholder_mark_present(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    return PLACEHOLDER_MARK in text


def collect_placeholder_policy_findings(check: str = "emit") -> list[Finding]:
    """_placeholder must not be instantiated by PRODUCT; source needs a mark."""
    findings: list[Finding] = []
    disc = discover_rtl()
    inst_map: dict[str, set[str]] = disc.get("instantiations") or {}
    defined: dict[str, RtlUnit] = disc.get("defined") or {}
    for parent, children in inst_map.items():
        unit = defined.get(parent)
        if unit is None:
            continue
        if is_placeholder_path(unit.file) or is_hooks_path(unit.file):
            continue
        for child in sorted(children):
            if not is_placeholder_module(child):
                continue
            findings.append(
                Finding(
                    check=check,
                    module=parent,
                    file=rel(unit.file),
                    rule="PLACEHOLDER_INSTANTIATED",
                    message=(
                        f"PRODUCT netlist instantiates placeholder cell {child}; "
                        f"_placeholder is lint/TB only (SPEC §2.2)"
                    ),
                )
            )
    seen_src: set[str] = set()
    for leaf in discover_pycircuit_leaves():
        if not leaf.get("placeholder"):
            continue
        src = REPO_ROOT / leaf["source"]
        key = rel(src)
        if key in seen_src:
            continue
        seen_src.add(key)
        if src.is_file() and not placeholder_mark_present(src):
            findings.append(
                Finding(
                    check=check,
                    module=leaf["module"],
                    file=key,
                    rule="PLACEHOLDER_SOURCE_MISSING",
                    message=(
                        "placeholder source must name its origin "
                        f"(constant or comment {PLACEHOLDER_MARK})"
                    ),
                )
            )
    for leaf in discover_product_leaves():
        if not leaf.get("placeholder"):
            continue
        prod = REPO_ROOT / leaf["product"]
        src = None
        for pyc in discover_pycircuit_leaves():
            if pyc.get("module") == leaf["module"] or pyc.get("leaf") == leaf.get("leaf"):
                if pyc.get("placeholder"):
                    src = REPO_ROOT / pyc["source"]
                    break
        if src and src.is_file():
            continue
        if prod.is_file() and not placeholder_mark_present(prod):
            findings.append(
                Finding(
                    check=check,
                    module=leaf["module"],
                    file=rel(prod),
                    rule="PLACEHOLDER_SOURCE_MISSING",
                    message=(
                        "placeholder netlist has no pycircuit source mark; "
                        f"add {PLACEHOLDER_MARK} in the source (or this file)"
                    ),
                )
            )
    return findings


def discover_leaf_pairs() -> list[dict[str, str]]:
    """Unique (layer, module) PRODUCT/HOOKS pairs. Layer names are discovered."""
    seen: set[str] = set()
    pairs: list[dict[str, str]] = []
    for leaf in discover_pycircuit_leaves() + discover_product_leaves():
        key = f"{leaf['layer']}/{leaf['module']}"
        if key in seen:
            continue
        seen.add(key)
        pairs.append(leaf)
    return pairs


PORT_CHUNK_RE = re.compile(
    r"\b(input|output|inout)\b((?:\s+(?:wire|reg|logic|signed))*"
    r"(?:\s+\[[^\]]+\])?\s*"
    r"[A-Za-z_][A-Za-z0-9_]*(?:\s*,\s*[A-Za-z_][A-Za-z0-9_]*)*)",
    re.I,
)
PORT_IDENT_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


_MODULE_DECL_RE = re.compile(r"^\s*module\s+([A-Za-z_][A-Za-z0-9_]*)\b", re.M)


def declared_module_name(text: str) -> str | None:
    m = _MODULE_DECL_RE.search(text)
    return m.group(1) if m else None


def verilog_equal_except_module_name(left: Path, right: Path) -> bool:
    """True if the two netlists match after substituting the declared module name."""
    ta = left.read_text(encoding="utf-8", errors="replace")
    tb = right.read_text(encoding="utf-8", errors="replace")
    na, nb = declared_module_name(ta), declared_module_name(tb)
    if not na or not nb:
        return ta == tb
    token = "__GATE_MOD__"

    def norm(text: str, name: str) -> str:
        return re.sub(rf"\b{re.escape(name)}\b", token, text)

    return norm(ta, na) == norm(tb, nb)


def collect_layer_netlists(rtl_root: Path) -> dict[str, Path]:
    """rtl/<layer>/*.v and rtl/<layer>/hooks/*.v, keyed by layer-relative path."""
    out: dict[str, Path] = {}
    if not rtl_root.is_dir():
        return out
    for layer_dir in sorted(rtl_root.iterdir()):
        if not layer_dir.is_dir():
            continue
        if layer_dir.name in LAYER_SKIP or layer_dir.name == "gen":
            continue
        for path in sorted(layer_dir.iterdir()):
            if path.is_file() and path.suffix.lower() in RTL_SOURCE_SUFFIXES:
                out[f"{layer_dir.name}/{path.name}"] = path
        hooks = layer_dir / "hooks"
        if hooks.is_dir():
            for path in sorted(hooks.iterdir()):
                if path.is_file() and path.suffix.lower() in RTL_SOURCE_SUFFIXES:
                    out[f"{layer_dir.name}/hooks/{path.name}"] = path
    return out


def parse_ports(path: Path) -> list[tuple[str, str]]:
    """Return (direction, name) in declaration order."""
    text = strip_verilog_comments(path.read_text(encoding="utf-8", errors="replace"))
    skip = {"input", "output", "inout", "wire", "reg", "logic", "signed"}
    ports: list[tuple[str, str]] = []
    for kind, blob in PORT_CHUNK_RE.findall(text):
        for name in PORT_IDENT_RE.findall(blob):
            if name.lower() in skip:
                continue
            ports.append((kind.lower(), name))
    return ports


def collect_blackbox_findings(check: str = "lint") -> list[Finding]:
    """Unlisted stub/macro is blocking. Timing vs MODULE_INVENTORY is report-only."""
    findings: list[Finding] = validate_blackbox_schema()
    for f in findings:
        f.check = check
    inventory = load_module_inventory()
    inv_path = find_module_inventory()
    storage_rows: list[dict[str, Any]] = []
    if inventory:
        raw = inventory.get("storage") or inventory.get("memories") or []
        if isinstance(raw, list):
            storage_rows = [r for r in raw if isinstance(r, dict)]
    if inv_path is None:
        print(
            "NOTE: MODULE_INVENTORY not found "
            "(docs/arch/MODULE_INVENTORY.yml); blackbox timing auto-check skipped"
        )
    listed = load_blackboxes()
    print(
        f"blackbox registry: {len(listed)} approved stub|macro entries "
        f"(ub_cmn_mem_1r1w is a normal cmn leaf, not listed here)"
    )
    for path in iter_rtl_sources():
        if is_handwritten_path(path):
            continue
        # Generated cmn storage leaf is a normal PRODUCT, not a stub.
        if path.stem == "ub_cmn_mem_1r1w" and "cmn" in path.parts:
            continue
        detected = looks_like_stub_or_blackbox(path)
        listed_here = is_stub_listed(path)
        if detected and not listed_here:
            findings.append(
                Finding(
                    check=check,
                    module=path.stem,
                    file=rel(path),
                    rule="STUB_UNLISTED",
                    message=(
                        "stub/blackbox under rtl/ is not on "
                        "scripts/gate/blackbox.yml "
                        "(or the entry has no gatekeeper approver)"
                    ),
                )
            )
            continue
        if not listed_here:
            continue
        entry = next(
            (
                e
                for e in listed
                if str(e.get("file") or "").replace("\\", "/") == rel(path)
                or fnmatch.fnmatch(rel(path), str(e.get("file") or ""))
                or str(e.get("module") or "") == path.stem
            ),
            {},
        )
        if not storage_rows:
            continue
        match = None
        for row in storage_rows:
            rid = str(row.get("id") or row.get("replaces") or row.get("macro") or "")
            rmod = str(row.get("module") or "")
            if rid and rid == str(entry.get("replaces") or entry.get("macro") or entry.get("id") or ""):
                match = row
                break
            if rmod and rmod in {path.stem, entry.get("module")}:
                match = row
                break
        if match is None:
            findings.append(
                Finding(
                    check=check,
                    module=path.stem,
                    file=rel(path),
                    rule="STUB_TIMING_NO_INVENTORY_ROW",
                    message=(
                        "registered stub/macro has no MODULE_INVENTORY storage row "
                        "to check read latency / 1RW/1R1W / conflict"
                    ),
                    bucket="report",
                )
            )
            continue
        want = {
            "read_latency": match.get("read_latency", match.get("read_lat")),
            "ports": match.get("ports") or match.get("port_kind"),
            "conflict": match.get("conflict")
            or match.get("rw_conflict")
            or match.get("same_addr"),
        }
        got = {
            "read_latency": entry.get("read_latency", entry.get("read_lat")),
            "ports": entry.get("ports") or entry.get("port_kind"),
            "conflict": entry.get("rw_conflict") or entry.get("conflict"),
        }
        mismatches = [
            f"{k}: inventory={want[k]!r} list={got[k]!r}"
            for k in want
            if want[k] is not None and got[k] is not None and str(want[k]) != str(got[k])
        ]
        missing = [k for k in want if want[k] is not None and got[k] is None]
        if mismatches or missing:
            findings.append(
                Finding(
                    check=check,
                    module=path.stem,
                    file=rel(path),
                    rule="STUB_TIMING",
                    message=(
                        "blackbox timing vs MODULE_INVENTORY (report-only): "
                        + "; ".join(mismatches + [f"{k} missing on list" for k in missing])
                    ),
                    bucket="report",
                )
            )
    return findings


def collect_stub_findings(check: str = "lint") -> list[Finding]:
    return collect_blackbox_findings(check)


def discover_product_leaves() -> list[dict[str, Any]]:
    """PRODUCT files at rtl/<layer>/<module>.v (not hooks/, not whitelist cells)."""
    rtl_root = REPO_ROOT / "rtl"
    leaves: list[dict[str, Any]] = []
    for layer in discover_layers(rtl_root):
        layer_dir = rtl_root / layer
        if not layer_dir.is_dir():
            continue
        for path in sorted(layer_dir.iterdir()):
            if not path.is_file() or path.suffix.lower() not in RTL_SOURCE_SUFFIXES:
                continue
            if is_handwritten_path(path) or path.stem in handwritten_modules():
                continue
            tag = None
            leaf_name = path.stem
            params: dict[str, Any] = {}
            cmn_tag = cmn_mem_tag_of(path.stem)
            if cmn_tag:
                leaf_name = CMN_MEM_CELL
                tag = cmn_tag
                params = parse_cmn_mem_tag(cmn_tag) or {}
            leaves.append(
                {
                    "layer": layer,
                    "leaf": leaf_name,
                    "module": path.stem,
                    "tag": tag,
                    "params": params,
                    "placeholder": is_placeholder_path(path),
                    "product": rel(path),
                    "hooks": f"rtl/{layer}/hooks/{path.stem}.v",
                }
            )
    return leaves


def module_closure(module: str, disc: dict) -> list[Path]:
    """Files needed to lint/synth `module` (itself + discovered children)."""
    defined: dict[str, RtlUnit] = disc.get("defined") or {}
    inst_map: dict[str, set[str]] = disc.get("instantiations") or {}
    seen: set[str] = set()
    stack = [module]
    files: list[Path] = []
    while stack:
        name = stack.pop()
        if name in seen:
            continue
        seen.add(name)
        unit = defined.get(name)
        if unit is None:
            continue
        files.append(unit.file)
        for child in inst_map.get(name, set()):
            if child in defined:
                stack.append(child)
    return files


def strip_verilog_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    out: list[str] = []
    for line in text.splitlines():
        if "//" in line:
            line = line.split("//", 1)[0]
        out.append(line)
    return "\n".join(out)


def verilator_inc_args(incdirs: list[Path]) -> list[str]:
    # Verilator treats a bare "-I" plus a following path as another source file.
    return [f"-I{d}" for d in incdirs]


def yosys_inc_prefix(incdirs: list[Path]) -> str:
    return " ".join(f"-I{d}" for d in incdirs)
