"""Shared helpers for the tool-gate scripts.

Kept stdlib-first. PyYAML is optional but used when present (scripts/gate/requirements.txt).
"""

from __future__ import annotations

import fnmatch
import json
import os
import re
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Iterable

GATE_DIR = Path(__file__).resolve().parent
REPO_ROOT = GATE_DIR.parent.parent
LEGACY_LIST = GATE_DIR / "legacy.txt"
WAIVERS_DIR = REPO_ROOT / "waivers"
APPROVERS_FILE = WAIVERS_DIR / "approvers.yml"
TOOLCHAIN_LOCK = REPO_ROOT / "TOOLCHAIN.lock"
CDC_RULES = GATE_DIR / "cdc_rules.yml"
OUT_DIR = GATE_DIR / "out"

RTL_SOURCE_SUFFIXES = {".v", ".sv"}
RTL_INCLUDE_SUFFIXES = {".vh", ".svh"}
FILELIST_SUFFIXES = {".f", ".vf"}

# Directories searched for product RTL (first existing wins for "gen" trees).
RTL_SCAN_DIRS = (
    "rtl/gen/product",
    "rtl/gen/hooks",
    "rtl/gen",
    "rtl",
)
FILELIST_GLOBS = (
    "rtl/**/*.f",
    "rtl/**/*.vf",
    "scripts/gate/filelists/*.f",
)

GENERATED_BANNER = re.compile(
    r"(GENERATED from pycircuit|Generated by .+pyCircuit|Generated by .+\.py|"
    r"do not (hand-)?edit)",
    re.IGNORECASE,
)

PLACEHOLDER_APPROVERS = {
    "",
    "todo",
    "tbd",
    "pending",
    "n/a",
    "na",
    "-",
}


@dataclass
class RtlUnit:
    module: str
    file: Path
    kind: str  # top | leaf | include
    sources: list[Path] = field(default_factory=list)


@dataclass
class Finding:
    check: str
    module: str
    file: str
    rule: str
    message: str
    severity: str = "error"
    bucket: str = "new"  # new | legacy
    waived_by: str = ""

    def key(self) -> tuple[str, str, str, str]:
        return (self.check, self.module, self.file, self.rule)


def die(msg: str, code: int = 1) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    raise SystemExit(code)


def rel(path: Path | str) -> str:
    p = Path(path)
    try:
        return p.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return p.as_posix()


def load_yaml(path: Path) -> Any:
    text = path.read_text(encoding="utf-8")
    try:
        import yaml  # type: ignore
    except ImportError:
        die(
            f"PyYAML is required to read {rel(path)}. "
            f"Install: pip install -r scripts/gate/requirements.txt"
        )
    data = yaml.safe_load(text)
    return data if data is not None else {}


def parse_lock(path: Path = TOOLCHAIN_LOCK) -> dict[str, str]:
    """Read TOOLCHAIN.lock key = \"value\" pairs (comment-tolerant, not full TOML)."""
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or line.startswith("[") or "=" not in line:
            continue
        key, _, rest = line.partition("=")
        val = rest.strip().strip('"').strip("'")
        out[key.strip()] = val
    return out


def run_cmd(
    argv: list[str],
    cwd: Path | None = None,
    timeout: int | None = None,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        argv,
        cwd=cwd or REPO_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=timeout,
        check=False,
    )


def tool_version_line(cmd: list[str], fallback: str = "not-on-PATH") -> str:
    if not shutil_which(cmd[0]):
        return fallback
    proc = run_cmd(cmd)
    text = (proc.stdout or "").strip().splitlines()
    return text[0] if text else fallback


def shutil_which(name: str) -> str | None:
    from shutil import which

    return which(name)


def print_tool_versions(needed: Iterable[str]) -> None:
    lock = parse_lock()
    mapping = {
        "verilator": ("verilator_lock", ["verilator", "--version"]),
        "icarus": ("icarus_lock", ["iverilog", "-V"]),
        "yosys": ("yosys_lock", ["yosys", "-V"]),
        "sby": ("sby_lock", ["sby", "--version"]),
        "python": ("", [sys.executable, "--version"]),
    }
    print("=== tool versions (TOOLCHAIN.lock vs actual) ===")
    for name in needed:
        lock_key, argv = mapping[name]
        locked = lock.get(lock_key, "")
        actual = tool_version_line(argv)
        on_path = shutil_which(argv[0]) is not None
        if locked:
            matched = locked in actual
            status = "MATCH" if matched else "MISMATCH — locked version not installed; using actual (not silent)"
            print(f"TOOL {name}: locked={locked} actual={actual} {status}")
        else:
            extra = "locked=(not in TOOLCHAIN.lock)"
            print(f"TOOL {name}: {extra} actual={actual}")
        if name in {"verilator", "icarus", "yosys"} and not on_path:
            print(f"TOOL {name}: MISSING on PATH")
    print("=== end tool versions ===")


def read_legacy_patterns(path: Path = LEGACY_LIST) -> list[str]:
    pats: list[str] = []
    if not path.is_file():
        return pats
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if line:
            pats.append(line.replace("\\", "/"))
    return pats


def looks_generated(path: Path) -> bool:
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:4000]
    except OSError:
        return False
    return bool(GENERATED_BANNER.search(head))


def is_legacy_path(path: Path, patterns: list[str] | None = None) -> bool:
    """D10 leftover: listed in legacy.txt and not a pyCircuit rewrite."""
    if looks_generated(path):
        return False
    rel_path = rel(path)
    pats = patterns if patterns is not None else read_legacy_patterns()
    for pat in pats:
        if rel_path == pat or rel_path.startswith(pat.rstrip("/") + "/"):
            return True
        if fnmatch.fnmatch(rel_path, pat):
            return True
    return False


def classify_finding(finding: Finding) -> Finding:
    finding.bucket = "legacy" if is_legacy_path(Path(REPO_ROOT / finding.file)) else "new"
    return finding


def load_approvers() -> set[str]:
    if not APPROVERS_FILE.is_file():
        return set()
    data = load_yaml(APPROVERS_FILE)
    names: set[str] = set()
    for row in data.get("gatekeepers") or []:
        login = str(row.get("login") or "").strip()
        role = str(row.get("role") or "").strip().lower()
        if login and role in {"verification", "verif", "gatekeeper", "工具守门"}:
            names.add(login)
        if login:
            # login is accepted only when marked as the verification gatekeeper
            if row.get("gatekeeper") is True or role:
                names.add(login)
    return names


def load_waivers(check: str | None = None) -> list[dict[str, Any]]:
    approvers = load_approvers()
    accepted: list[dict[str, Any]] = []
    if not WAIVERS_DIR.is_dir():
        return accepted
    for path in sorted(WAIVERS_DIR.glob("*.yml")):
        if path.name == "approvers.yml":
            continue
        data = load_yaml(path)
        for entry in data.get("waivers") or []:
            if check and entry.get("check") != check:
                continue
            approver = str(entry.get("approver") or "").strip()
            status = str(entry.get("status") or "approved").strip().lower()
            if approver.lower() in PLACEHOLDER_APPROVERS:
                print(
                    f"WAIVER ignore {entry.get('id')}: no approver "
                    f"(待守门人批准)"
                )
                continue
            if approver not in approvers:
                print(
                    f"WAIVER ignore {entry.get('id')}: approver {approver!r} "
                    f"is not a verification gatekeeper"
                )
                continue
            if status in {"draft", "pending", "todo"}:
                print(f"WAIVER ignore {entry.get('id')}: status={status}")
                continue
            accepted.append(dict(entry))
    return accepted


def waiver_matches(finding: Finding, entry: dict[str, Any]) -> bool:
    if entry.get("check") and entry["check"] != finding.check:
        return False
    module = entry.get("module") or entry.get("模块")
    if module and str(module) not in {finding.module, "*"}:
        return False
    fpat = entry.get("file") or entry.get("文件")
    if fpat and not fnmatch.fnmatch(finding.file, str(fpat)):
        return False
    rule = entry.get("rule") or entry.get("规则")
    if rule and str(rule) not in {finding.rule, "*"}:
        return False
    msg = entry.get("message") or entry.get("消息匹配")
    if msg and not re.search(str(msg), finding.message):
        return False
    return True


def apply_waivers(findings: list[Finding], check: str) -> list[Finding]:
    waivers = load_waivers(check)
    for finding in findings:
        classify_finding(finding)
        for entry in waivers:
            if waiver_matches(finding, entry):
                finding.waived_by = str(entry.get("id") or entry.get("approver"))
                break
    return findings


def split_findings(findings: list[Finding]) -> tuple[list[Finding], list[Finding], list[Finding]]:
    blocking: list[Finding] = []
    legacy: list[Finding] = []
    waived: list[Finding] = []
    for f in findings:
        if f.waived_by:
            waived.append(f)
        elif f.bucket == "legacy":
            legacy.append(f)
        else:
            blocking.append(f)
    return blocking, legacy, waived


def emit_report(check: str, findings: list[Finding]) -> int:
    """Print the two-column report. Return process exit code."""
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    apply_waivers(findings, check)
    blocking, legacy, waived = split_findings(findings)
    print(f"=== {check} findings ===")
    print(f"total={len(findings)} blocking={len(blocking)} "
          f"legacy_report_only={len(legacy)} waived={len(waived)}")
    print()
    print("## New leaves (blocking)")
    if not blocking:
        print("(none)")
    else:
        _print_table(blocking)
    print()
    print("## D10 legacy (report-only; 待 legacy 迁移 PR 处理、守门人批准)")
    if not legacy:
        print("(none)")
    else:
        _print_table(legacy)
    if waived:
        print()
        print("## Waived (approved gatekeeper entries only)")
        _print_table(waived)
    payload = {
        "check": check,
        "blocking": [asdict(f) for f in blocking],
        "legacy": [asdict(f) for f in legacy],
        "waived": [asdict(f) for f in waived],
    }
    (OUT_DIR / f"{check}.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    if blocking:
        print(f"\n{check}: FAIL ({len(blocking)} blocking finding(s) on new leaves)")
        return 1
    print(f"\n{check}: PASS (no blocking findings on new leaves)")
    return 0


def _print_table(rows: list[Finding]) -> None:
    print("| module | check | rule | file | message |")
    print("| --- | --- | --- | --- | --- |")
    for f in rows:
        msg = f.message.replace("\n", " ").replace("|", "/")
        if len(msg) > 160:
            msg = msg[:157] + "..."
        print(f"| {f.module} | {f.check} | {f.rule} | {f.file} | {msg} |")


def _is_rtl_file(path: Path) -> bool:
    return path.suffix.lower() in RTL_SOURCE_SUFFIXES | RTL_INCLUDE_SUFFIXES


def _excluded(path: Path) -> bool:
    rel_path = rel(path)
    parts = rel_path.split("/")
    if any(p in {"tb", "legacy", "sim_build"} for p in parts):
        return True
    name = path.name
    if name.endswith("_tb.v") or name.endswith("_tb.sv"):
        return True
    return False


def parse_filelist(path: Path) -> tuple[list[Path], list[Path]]:
    files: list[Path] = []
    incdirs: list[Path] = []
    base = path.parent
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("+incdir+"):
            incdirs.append((base / line[len("+incdir+") :]).resolve())
            continue
        if line.startswith("-I"):
            incdirs.append((base / line[2:].strip()).resolve())
            continue
        files.append((base / line).resolve())
    return files, incdirs


def discover_rtl() -> dict[str, Any]:
    """Auto-discover RTL from filelists (preferred) or directories."""
    filelists: list[Path] = []
    for glob in FILELIST_GLOBS:
        filelists.extend(sorted(REPO_ROOT.glob(glob)))
    sources: list[Path] = []
    incdirs: list[Path] = []
    used_filelists = False
    if filelists:
        used_filelists = True
        for fl in filelists:
            files, incs = parse_filelist(fl)
            sources.extend(files)
            incdirs.extend(incs)
    else:
        seen: set[Path] = set()
        for dname in RTL_SCAN_DIRS:
            dpath = REPO_ROOT / dname
            if not dpath.is_dir():
                continue
            for path in sorted(dpath.rglob("*")):
                if not path.is_file() or not _is_rtl_file(path) or _excluded(path):
                    continue
                if path.resolve() in seen:
                    continue
                seen.add(path.resolve())
                sources.append(path.resolve())
            incdirs.append(dpath.resolve())
            common = dpath / "common"
            if common.is_dir():
                incdirs.append(common.resolve())

    sources = [p for p in sources if p.is_file()]
    modules: list[RtlUnit] = []
    inst_re = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]*)\s+#\s*\(|\b([A-Za-z_][A-Za-z0-9_]*)\s+[A-Za-z_][A-Za-z0-9_]*\s*\(")
    mod_re = re.compile(r"^\s*module\s+([A-Za-z_][A-Za-z0-9_]*)\b", re.MULTILINE)
    defined: dict[str, RtlUnit] = {}
    instantiations: dict[str, set[str]] = {}
    for path in sources:
        if path.suffix.lower() not in RTL_SOURCE_SUFFIXES:
            continue
        text = strip_verilog_comments(path.read_text(encoding="utf-8", errors="replace"))
        names = mod_re.findall(text)
        if not names:
            continue
        insts: set[str] = set()
        # Drop the module's own name from instantiation matches.
        for m in re.finditer(
            r"\b([A-Za-z_][A-Za-z0-9_]*)\s+(?:#\s*\([^;]*\)\s*)?([A-Za-z_][A-Za-z0-9_]*)\s*\(",
            text,
        ):
            cell, inst = m.group(1), m.group(2)
            if cell in {"module", "function", "task", "if", "for", "while", "case"}:
                continue
            if inst in {"begin", "end"}:
                continue
            insts.add(cell)
        for name in names:
            unit = RtlUnit(module=name, file=path, kind="leaf", sources=sources)
            defined[name] = unit
            instantiations[name] = insts - {name}

    kids: set[str] = set()
    for insts in instantiations.values():
        kids.update(insts)
    for name, unit in defined.items():
        unit.kind = "leaf" if name not in instantiations or not (instantiations[name] & set(defined)) else "top"
        # A module that instantiates another discovered module is a top (or mid).
        if instantiations.get(name, set()) & set(defined):
            unit.kind = "top"
        else:
            unit.kind = "leaf"
        modules.append(unit)

    # Unique include dirs
    uniq_inc: list[Path] = []
    for d in incdirs:
        if d not in uniq_inc and d.is_dir():
            uniq_inc.append(d)
    # Always add rtl/ and rtl/common when present
    for extra in (REPO_ROOT / "rtl", REPO_ROOT / "rtl" / "common"):
        if extra.is_dir() and extra.resolve() not in uniq_inc:
            uniq_inc.append(extra.resolve())

    return {
        "sources": sources,
        "incdirs": uniq_inc,
        "modules": modules,
        "used_filelists": used_filelists,
        "filelists": filelists,
        "instantiations": instantiations,
    }


def strip_verilog_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    out: list[str] = []
    for line in text.splitlines():
        if "//" in line:
            line = line.split("//", 1)[0]
        out.append(line)
    return "\n".join(out)


def verilator_inc_args(incdirs: list[Path]) -> list[str]:
    args: list[str] = []
    for d in incdirs:
        args.extend(["-I", str(d)])
    return args


def yosys_inc_prefix(incdirs: list[Path]) -> str:
    return " ".join(f"-I{d}" for d in incdirs)
