"""Shared helpers for the tool-gate scripts.

Kept stdlib-first. PyYAML is optional but used when present (scripts/gate/requirements.txt).
"""

from __future__ import annotations

import fnmatch
import json
import os
import re
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Iterable

GATE_DIR = Path(__file__).resolve().parent
REPO_ROOT = GATE_DIR.parent.parent
# All machine-readable lists live next to the scripts (scripts/gate/).
LISTS_DIR = GATE_DIR
LEGACY_LIST = LISTS_DIR / "legacy.txt"
HANDWRITTEN_LIST = LISTS_DIR / "handwritten.yml"
BLACKBOX_LIST = LISTS_DIR / "blackbox.yml"
HOOKS_PORTS_LIST = LISTS_DIR / "hooks_ports.yml"
MIGRATE_LIST = LISTS_DIR / "pycircuit_migrate.txt"
INVENTORY_CANDIDATES = (
    REPO_ROOT / "docs" / "arch" / "MODULE_INVENTORY.yml",
    REPO_ROOT / "docs" / "arch" / "MODULE_INVENTORY.yaml",
    REPO_ROOT / "docs" / "MODULE_INVENTORY.yml",
    REPO_ROOT / "docs" / "MODULE_INVENTORY.yaml",
    LISTS_DIR / "MODULE_INVENTORY.yml",
)
WAIVERS_DIR = REPO_ROOT / "waivers"
APPROVERS_FILE = WAIVERS_DIR / "approvers.yml"
TOOLCHAIN_LOCK = REPO_ROOT / "TOOLCHAIN.lock"
CDC_RULES = GATE_DIR / "cdc_rules.yml"
OUT_DIR = GATE_DIR / "out"

RTL_SOURCE_SUFFIXES = {".v", ".sv"}
RTL_INCLUDE_SUFFIXES = {".vh", ".svh"}
FILELIST_SUFFIXES = {".f", ".vf"}

# Layer names are discovered from the tree. Do not hard-code pcs/dll/lmsm/csr.
# Xia: cmn is a real layer (ub_cmn_mem_1r1w) and must always be enumerated.
LAYER_SKIP = {
    "hooks",
    "gen",
    "include",
    "__pycache__",
    "lib",
    "tests",
    "out",
    "filelists",
}
ALWAYS_LAYERS = ("cmn",)

# Layer discovery only. Do not scan rtl/gen (that tree is not used).

# Fallback only if scripts/gate/handwritten.yml is absent. Prefer the YAML list.
WHITELIST_CELLS = {"ub_rst_sync"}

GENERATED_BANNER = re.compile(
    r"(GENERATED from pycircuit|Generated by .+pyCircuit|Generated by .+\.py|"
    r"do not (hand-)?edit)",
    re.IGNORECASE,
)

PLACEHOLDER_APPROVERS = {
    "",
    "todo",
    "tbd",
    "pending",
    "n/a",
    "na",
    "-",
}


@dataclass
class RtlUnit:
    module: str
    file: Path
    kind: str  # top | leaf | include
    sources: list[Path] = field(default_factory=list)


@dataclass
class Finding:
    check: str
    module: str
    file: str
    rule: str
    message: str
    severity: str = "error"
    bucket: str = "new"  # new | legacy | migrate | report
    waived_by: str = ""

    def key(self) -> tuple[str, str, str, str]:
        return (self.check, self.module, self.file, self.rule)


def die(msg: str, code: int = 1) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    raise SystemExit(code)


def rel(path: Path | str) -> str:
    p = Path(path)
    try:
        return p.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return p.as_posix()


def load_yaml(path: Path) -> Any:
    text = path.read_text(encoding="utf-8")
    try:
        import yaml  # type: ignore
    except ImportError:
        die(
            f"PyYAML is required to read {rel(path)}. "
            f"Install: pip install -r scripts/gate/requirements.txt"
        )
    data = yaml.safe_load(text)
    return data if data is not None else {}


def parse_lock(path: Path = TOOLCHAIN_LOCK) -> dict[str, str]:
    """Read TOOLCHAIN.lock key = \"value\" pairs (comment-tolerant, not full TOML)."""
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or line.startswith("[") or "=" not in line:
            continue
        key, _, rest = line.partition("=")
        val = rest.strip().strip('"').strip("'")
        out[key.strip()] = val
    return out


def run_cmd(
    argv: list[str],
    cwd: Path | None = None,
    timeout: int | None = None,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        argv,
        cwd=cwd or REPO_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=timeout,
        check=False,
    )


def tool_version_line(cmd: list[str], fallback: str = "not-on-PATH") -> str:
    if not shutil_which(cmd[0]):
        return fallback
    proc = run_cmd(cmd)
    text = (proc.stdout or "").strip().splitlines()
    return text[0] if text else fallback


def shutil_which(name: str) -> str | None:
    from shutil import which

    return which(name)


def print_tool_versions(needed: Iterable[str]) -> None:
    lock = parse_lock()
    mapping = {
        "verilator": ("verilator_lock", ["verilator", "--version"]),
        "icarus": ("icarus_lock", ["iverilog", "-V"]),
        "yosys": ("yosys_lock", ["yosys", "-V"]),
        "eqy": ("eqy_lock", ["eqy", "--version"]),
        "sby": ("sby_lock", ["sby", "--version"]),
        "pycc": ("pycc_lock", ["pycc", "--version"]),
        "python": ("", [sys.executable, "--version"]),
    }
    print("=== tool versions (TOOLCHAIN.lock vs actual) ===")
    for name in needed:
        lock_key, argv = mapping[name]
        locked = lock.get(lock_key, "")
        actual = tool_version_line(argv)
        on_path = shutil_which(argv[0]) is not None
        if locked:
            matched = locked in actual
            status = "MATCH" if matched else "MISMATCH — locked version not installed; using actual (not silent)"
            print(f"TOOL {name}: locked={locked} actual={actual} {status}")
        else:
            extra = "locked=(not in TOOLCHAIN.lock)"
            print(f"TOOL {name}: {extra} actual={actual}")
        if name in {"verilator", "icarus", "yosys", "eqy"} and not on_path:
            print(f"TOOL {name}: MISSING on PATH")
    print("=== end tool versions ===")


def read_list_patterns(path: Path) -> list[str]:
    pats: list[str] = []
    if not path.is_file():
        return pats
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if line:
            pats.append(line.replace("\\", "/"))
    return pats


def read_legacy_patterns(path: Path = LEGACY_LIST) -> list[str]:
    return read_list_patterns(path)


def read_migrate_patterns(path: Path = MIGRATE_LIST) -> list[str]:
    return read_list_patterns(path)


def is_migrate_path(path: Path, patterns: list[str] | None = None) -> bool:
    """Existing pyCircuit leaves from main / PR #5 / #7 / #11 / #12 (迁移待办)."""
    rel_path = rel(path)
    pats = patterns if patterns is not None else read_migrate_patterns()
    for pat in pats:
        if rel_path == pat or fnmatch.fnmatch(rel_path, pat):
            return True
        p = Path(pat)
        if len(p.parts) >= 3 and p.parts[0] == "pycircuit":
            layer, stem = p.parts[1], p.stem
            if rel_path in {
                f"rtl/{layer}/{stem}.v",
                f"rtl/{layer}/hooks/{stem}.v",
            }:
                return True
    return False


def looks_generated(path: Path) -> bool:
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:4000]
    except OSError:
        return False
    return bool(GENERATED_BANNER.search(head))


def is_legacy_path(path: Path, patterns: list[str] | None = None) -> bool:
    """D10 leftover: listed in legacy.txt and not a pyCircuit rewrite."""
    if looks_generated(path):
        return False
    if is_handwritten_path(path):
        return False
    rel_path = rel(path)
    pats = patterns if patterns is not None else read_legacy_patterns()
    for pat in pats:
        if rel_path == pat or rel_path.startswith(pat.rstrip("/") + "/"):
            return True
        if fnmatch.fnmatch(rel_path, pat):
            return True
    return False


def _file_for_class(path_text: str) -> str:
    # Verilator prints file:line[:col]; classify on the path only.
    cleaned = path_text.split(":")[0] if path_text else ""
    return cleaned


def classify_finding(finding: Finding) -> Finding:
    if finding.bucket == "report":
        return finding
    path = Path(REPO_ROOT / _file_for_class(finding.file))
    if is_handwritten_path(path):
        finding.bucket = "new"
    elif is_migrate_path(path):
        finding.bucket = "migrate"
    elif is_legacy_path(path):
        finding.bucket = "legacy"
    else:
        finding.bucket = "new"
    return finding


def load_approvers() -> set[str]:
    if not APPROVERS_FILE.is_file():
        return set()
    data = load_yaml(APPROVERS_FILE)
    names: set[str] = set()
    for row in data.get("gatekeepers") or []:
        login = str(row.get("login") or "").strip()
        role = str(row.get("role") or "").strip().lower()
        if login and role in {"verification", "verif", "gatekeeper", "工具守门"}:
            names.add(login)
        if login:
            # login is accepted only when marked as the verification gatekeeper
            if row.get("gatekeeper") is True or role:
                names.add(login)
    return names


def _entry_approved(entry: dict[str, Any], approvers: set[str], kind: str) -> bool:
    ident = entry.get("id") or entry.get("file")
    approver = str(entry.get("approver") or "").strip()
    status = str(entry.get("status") or "approved").strip().lower()
    if approver.lower() in PLACEHOLDER_APPROVERS:
        print(f"{kind} ignore {ident}: no approver (待守门人批准)")
        return False
    if approver not in approvers:
        print(f"{kind} ignore {ident}: approver {approver!r} is not a verification gatekeeper")
        return False
    if status in {"draft", "pending", "todo"}:
        print(f"{kind} ignore {ident}: status={status}")
        return False
    return True


_LIST_CACHE: dict[str, list[dict[str, Any]]] = {}


def _load_approved_list(path: Path, key: str, kind: str) -> list[dict[str, Any]]:
    cache_key = str(path)
    if cache_key in _LIST_CACHE:
        return _LIST_CACHE[cache_key]
    if not path.is_file():
        _LIST_CACHE[cache_key] = []
        return []
    data = load_yaml(path)
    approvers = load_approvers()
    accepted: list[dict[str, Any]] = []
    for entry in data.get(key) or []:
        if _entry_approved(entry, approvers, kind):
            accepted.append(dict(entry))
    _LIST_CACHE[cache_key] = accepted
    return accepted


def load_handwritten() -> list[dict[str, Any]]:
    """Approved handwritten SV entries from scripts/gate/handwritten.yml."""
    return _load_approved_list(HANDWRITTEN_LIST, "entries", "HANDWRITTEN")


def is_handwritten_path(path: Path) -> bool:
    rel_path = rel(path)
    for entry in load_handwritten():
        pat = str(entry.get("file") or "").replace("\\", "/")
        if not pat:
            continue
        if rel_path == pat or fnmatch.fnmatch(rel_path, pat):
            return True
    return False


def handwritten_modules() -> set[str]:
    """Module names (file stems) of approved handwritten cells."""
    names: set[str] = set()
    for entry in load_handwritten():
        pat = str(entry.get("file") or "")
        if pat:
            names.add(Path(pat).stem)
        mod = str(entry.get("module") or "")
        if mod:
            names.add(mod)
    return names or set(WHITELIST_CELLS)


BLACKBOX_KINDS = {"stub", "macro"}
BLACKBOX_PORTS = {"1RW", "1R1W"}
BLACKBOX_CONFLICT = {"old", "new"}
BLACKBOX_REQUIRED = (
    "module",
    "file",
    "kind",
    "replaces",
    "depth",
    "width",
    "ports",
    "read_latency",
    "rw_conflict",
    "reset",
    "macro",
    "reason",
    "registrant",
    "approver",
)


def load_blackbox_raw() -> list[dict[str, Any]]:
    if not BLACKBOX_LIST.is_file():
        return []
    data = load_yaml(BLACKBOX_LIST)
    rows = data.get("entries") if isinstance(data, dict) else None
    return [dict(e) for e in (rows or []) if isinstance(e, dict)]


def load_blackboxes() -> list[dict[str, Any]]:
    """Approved stub/macro entries from scripts/gate/blackbox.yml."""
    return _load_approved_list(BLACKBOX_LIST, "entries", "BLACKBOX")


def load_stubs() -> list[dict[str, Any]]:
    """Alias: approved blackbox.yml entries (kind stub|macro)."""
    return load_blackboxes()


def is_stub_listed(path: Path) -> bool:
    rel_path = rel(path)
    if path.stem in stub_modules():
        return True
    for entry in load_blackboxes():
        pat = str(entry.get("file") or "").replace("\\", "/")
        if not pat:
            continue
        if rel_path == pat or fnmatch.fnmatch(rel_path, pat):
            return True
    return False


def stub_modules() -> set[str]:
    names: set[str] = set()
    for entry in load_blackboxes():
        pat = str(entry.get("file") or "")
        if pat:
            names.add(Path(pat).stem)
        for key in ("module", "name"):
            mod = str(entry.get(key) or "")
            if mod:
                names.add(mod)
    return names


def blackbox_lib_files() -> list[Path]:
    """Files synth-check must read with `read_verilog -lib`."""
    files: list[Path] = []
    for entry in load_blackboxes():
        pat = str(entry.get("file") or "")
        if not pat:
            continue
        path = REPO_ROOT / pat
        if path.is_file():
            files.append(path)
    return files


def blackbox_by_module() -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for entry in load_blackboxes():
        name = str(entry.get("module") or Path(str(entry.get("file") or "")).stem)
        if name:
            out[name] = entry
    return out


def validate_blackbox_schema() -> list[Finding]:
    """Fail the job if blackbox.yml is missing fields or uses kind=primitive."""
    findings: list[Finding] = []
    if not BLACKBOX_LIST.is_file():
        return [
            Finding(
                check="lint",
                module="*",
                file=rel(BLACKBOX_LIST),
                rule="BLACKBOX_LIST_MISSING",
                message="scripts/gate/blackbox.yml is required",
            )
        ]
    for idx, entry in enumerate(load_blackbox_raw()):
        ident = str(entry.get("id") or entry.get("module") or f"entry[{idx}]")
        missing = [k for k in BLACKBOX_REQUIRED if str(entry.get(k) or "").strip() == ""]
        if missing:
            findings.append(
                Finding(
                    check="lint",
                    module=str(entry.get("module") or "*"),
                    file=rel(BLACKBOX_LIST),
                    rule="BLACKBOX_SCHEMA",
                    message=f"{ident}: missing/empty fields {missing}",
                )
            )
        kind = str(entry.get("kind") or "").strip().lower()
        if kind and kind not in BLACKBOX_KINDS:
            findings.append(
                Finding(
                    check="lint",
                    module=str(entry.get("module") or "*"),
                    file=rel(BLACKBOX_LIST),
                    rule="BLACKBOX_KIND",
                    message=(
                        f"{ident}: kind={kind!r} is not allowed; "
                        f"use stub|macro (Xia: ub_cmn_mem_1r1w is a normal "
                        f"pycircuit/cmn leaf, not kind=primitive)"
                    ),
                )
            )
        ports = str(entry.get("ports") or "").strip()
        if ports and ports not in BLACKBOX_PORTS:
            findings.append(
                Finding(
                    check="lint",
                    module=str(entry.get("module") or "*"),
                    file=rel(BLACKBOX_LIST),
                    rule="BLACKBOX_SCHEMA",
                    message=f"{ident}: ports={ports!r} must be 1RW or 1R1W",
                )
            )
        conflict = str(entry.get("rw_conflict") or "").strip().lower()
        if conflict and conflict not in BLACKBOX_CONFLICT:
            findings.append(
                Finding(
                    check="lint",
                    module=str(entry.get("module") or "*"),
                    file=rel(BLACKBOX_LIST),
                    rule="BLACKBOX_SCHEMA",
                    message=f"{ident}: rw_conflict={conflict!r} must be old or new",
                )
            )
        reset = str(entry.get("reset") or "")
        valid_outside = entry.get("valid_outside")
        if re.search(r"不复位|unreset|no.?reset", reset, re.I) and valid_outside is not True:
            findings.append(
                Finding(
                    check="lint",
                    module=str(entry.get("module") or "*"),
                    file=rel(BLACKBOX_LIST),
                    rule="BLACKBOX_VALID_OUTSIDE",
                    message=(
                        f"{ident}: reset says the array is not reset; "
                        f"set valid_outside: true or RDC will fail"
                    ),
                )
            )
    return findings


STUB_ATTR_RE = re.compile(r"\(\*\s*(?:blackbox|stub)\s*\*\)", re.I)
STUB_NAME_RE = re.compile(r"_(?:stub|blackbox|bb)$", re.I)
STUB_COMMENT_RE = re.compile(
    r"\b(?:blackbox|behavioral stub|sram stub|SRAM stub)\b",
    re.I,
)


def looks_like_stub_or_blackbox(path: Path) -> bool:
    """Heuristic: attribute, name, directory, or comment marks a stub/blackbox."""
    if STUB_NAME_RE.search(path.stem):
        return True
    parts = {p.lower() for p in path.parts}
    if parts & {"stubs", "blackbox", "blackboxes"}:
        return True
    try:
        text = path.read_text(encoding="utf-8", errors="replace")[:8000]
    except OSError:
        return False
    return bool(STUB_ATTR_RE.search(text) or STUB_COMMENT_RE.search(text))


def iter_rtl_sources() -> list[Path]:
    rtl = REPO_ROOT / "rtl"
    if not rtl.is_dir():
        return []
    out: list[Path] = []
    for path in sorted(rtl.rglob("*")):
        if path.is_file() and path.suffix.lower() in RTL_SOURCE_SUFFIXES:
            out.append(path)
    return out


def load_hooks_ports() -> dict[str, list[str]]:
    """module → allowed extra HOOKS port names (approved entries only)."""
    extra: dict[str, list[str]] = {}
    for entry in _load_approved_list(HOOKS_PORTS_LIST, "entries", "HOOKS_PORTS"):
        module = str(entry.get("module") or "").strip()
        if not module:
            continue
        ports: list[str] = []
        for item in entry.get("extra_ports") or []:
            if isinstance(item, str):
                ports.append(item)
            elif isinstance(item, dict) and item.get("name"):
                ports.append(str(item["name"]))
        extra[module] = ports
    return extra


def find_module_inventory() -> Path | None:
    for path in INVENTORY_CANDIDATES:
        if path.is_file():
            return path
    return None


def load_module_inventory() -> dict[str, Any]:
    path = find_module_inventory()
    if path is None:
        return {}
    data = load_yaml(path)
    return data if isinstance(data, dict) else {}


def load_waivers(check: str | None = None) -> list[dict[str, Any]]:
    approvers = load_approvers()
    accepted: list[dict[str, Any]] = []
    if not WAIVERS_DIR.is_dir():
        return accepted
    for path in sorted(WAIVERS_DIR.glob("*.yml")):
        if path.name == "approvers.yml":
            continue
        data = load_yaml(path)
        for entry in data.get("waivers") or []:
            if check and entry.get("check") != check:
                continue
            approver = str(entry.get("approver") or "").strip()
            status = str(entry.get("status") or "approved").strip().lower()
            if approver.lower() in PLACEHOLDER_APPROVERS:
                print(
                    f"WAIVER ignore {entry.get('id')}: no approver "
                    f"(待守门人批准)"
                )
                continue
            if approver not in approvers:
                print(
                    f"WAIVER ignore {entry.get('id')}: approver {approver!r} "
                    f"is not a verification gatekeeper"
                )
                continue
            if status in {"draft", "pending", "todo"}:
                print(f"WAIVER ignore {entry.get('id')}: status={status}")
                continue
            accepted.append(dict(entry))
    return accepted


def waiver_matches(finding: Finding, entry: dict[str, Any]) -> bool:
    if entry.get("check") and entry["check"] != finding.check:
        return False
    module = entry.get("module") or entry.get("模块")
    if module and str(module) not in {finding.module, "*"}:
        return False
    fpat = entry.get("file") or entry.get("文件")
    if fpat and not fnmatch.fnmatch(finding.file, str(fpat)):
        return False
    rule = entry.get("rule") or entry.get("规则")
    if rule and str(rule) not in {finding.rule, "*"}:
        return False
    msg = entry.get("message") or entry.get("消息匹配")
    if msg and not re.search(str(msg), finding.message):
        return False
    return True


def apply_waivers(findings: list[Finding], check: str) -> list[Finding]:
    waivers = load_waivers(check)
    for finding in findings:
        classify_finding(finding)
        for entry in waivers:
            if waiver_matches(finding, entry):
                finding.waived_by = str(entry.get("id") or entry.get("approver"))
                break
    return findings


def split_findings(
    findings: list[Finding],
) -> tuple[list[Finding], list[Finding], list[Finding], list[Finding], list[Finding]]:
    blocking: list[Finding] = []
    legacy: list[Finding] = []
    migrate: list[Finding] = []
    report: list[Finding] = []
    waived: list[Finding] = []
    for f in findings:
        if f.waived_by:
            waived.append(f)
        elif f.bucket == "legacy":
            legacy.append(f)
        elif f.bucket == "migrate":
            migrate.append(f)
        elif f.bucket == "report":
            report.append(f)
        else:
            blocking.append(f)
    return blocking, legacy, migrate, report, waived


def emit_report(check: str, findings: list[Finding]) -> int:
    """Print the multi-column report. Return process exit code."""
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    apply_waivers(findings, check)
    blocking, legacy, migrate, report, waived = split_findings(findings)
    print(f"=== {check} findings ===")
    print(
        f"total={len(findings)} blocking={len(blocking)} "
        f"legacy_report_only={len(legacy)} migrate_backlog={len(migrate)} "
        f"report_only={len(report)} waived={len(waived)}"
    )
    print()
    print("## New leaves (blocking)")
    if not blocking:
        print("(none)")
    else:
        _print_table(blocking)
    print()
    print("## D10 legacy (report-only; 待 legacy 迁移 PR 处理、守门人批准)")
    if not legacy:
        print("(none)")
    else:
        _print_table(legacy)
    print()
    print("## pyCircuit migrate (main / PR #5 / #7 / #11 / #12; 迁移待办)")
    roster = read_migrate_roster()
    if roster:
        print("| path | group | status |")
        print("| --- | --- | --- |")
        for row in roster:
            print(f"| {row['path']} | {row['group']} | {row['status'] or ''} |")
    if migrate:
        _print_table(migrate)
    elif not roster:
        print("(none)")
    pending = list_pending_waivers()
    if report:
        print()
        print("## Report-only (non-blocking; inventory / timing / pycc emit / combo depth)")
        _print_table(report)
    if waived:
        print()
        print("## Waived (approved gatekeeper entries only)")
        _print_table(waived)
    if pending:
        print()
        print("## Pending waiver drafts (waivers/pending/; inactive until approved)")
        print("| id | check | file | status |")
        print("| --- | --- | --- | --- |")
        for row in pending:
            print(
                f"| {row.get('id') or ''} | {row.get('check') or ''} | "
                f"{row.get('file') or ''} | {row.get('status') or 'pending'} |"
            )
    payload = {
        "check": check,
        "blocking": [asdict(f) for f in blocking],
        "legacy": [asdict(f) for f in legacy],
        "migrate": [asdict(f) for f in migrate],
        "report": [asdict(f) for f in report],
        "waived": [asdict(f) for f in waived],
    }
    (OUT_DIR / f"{check}.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    if blocking:
        print(f"\n{check}: FAIL ({len(blocking)} blocking finding(s) on new leaves)")
        return 1
    print(f"\n{check}: PASS (no blocking findings on new leaves)")
    return 0


def read_migrate_roster() -> list[dict[str, str]]:
    """Parse scripts/gate/pycircuit_migrate.txt including group comments."""
    rows: list[dict[str, str]] = []
    if not MIGRATE_LIST.is_file():
        return rows
    group = "main"
    status = ""
    seen: set[tuple[str, str]] = set()
    for raw in MIGRATE_LIST.read_text(encoding="utf-8").splitlines():
        stripped = raw.strip()
        if stripped.startswith("#"):
            body = stripped[1:].strip()
            low = body.lower()
            if low.startswith("main"):
                group, status = "main", ""
            elif "pr #11" in low:
                group, status = "PR #11", "待 Xia 核实"
            elif body.upper().startswith("PR #"):
                group = body.split("—")[0].split("-")[0].strip()
                status = ""
            continue
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        key = (line, group)
        if key in seen:
            continue
        seen.add(key)
        rows.append({"path": line, "group": group, "status": status})
    return rows


def list_pending_waivers() -> list[dict[str, str]]:
    pending_dir = WAIVERS_DIR / "pending"
    out: list[dict[str, str]] = []
    if not pending_dir.is_dir():
        return out
    for path in sorted(pending_dir.glob("*.yml")):
        if path.name.lower() == "readme.yml":
            continue
        try:
            data = load_yaml(path)
        except SystemExit:
            continue
        entries = data.get("waivers") if isinstance(data, dict) else None
        if not entries:
            continue
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            out.append(
                {
                    "id": str(entry.get("id") or ""),
                    "check": str(entry.get("check") or ""),
                    "file": rel(path),
                    "status": str(entry.get("status") or "pending"),
                }
            )
    return out


def _print_table(rows: list[Finding]) -> None:
    print("| module | check | rule | file | message |")
    print("| --- | --- | --- | --- | --- |")
    for f in rows:
        msg = f.message.replace("\n", " ").replace("|", "/")
        if len(msg) > 160:
            msg = msg[:157] + "..."
        print(f"| {f.module} | {f.check} | {f.rule} | {f.file} | {msg} |")


def _is_rtl_file(path: Path) -> bool:
    return path.suffix.lower() in RTL_SOURCE_SUFFIXES | RTL_INCLUDE_SUFFIXES


def _excluded(path: Path) -> bool:
    rel_path = rel(path)
    parts = rel_path.split("/")
    if any(p in {"tb", "legacy", "sim_build"} for p in parts):
        return True
    name = path.name
    if name.endswith("_tb.v") or name.endswith("_tb.sv"):
        return True
    return False


def parse_filelist(path: Path) -> tuple[list[Path], list[Path]]:
    files: list[Path] = []
    incdirs: list[Path] = []
    base = path.parent
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("+incdir+"):
            incdirs.append((base / line[len("+incdir+") :]).resolve())
            continue
        if line.startswith("-I"):
            incdirs.append((base / line[2:].strip()).resolve())
            continue
        files.append((base / line).resolve())
    return files, incdirs


def discover_layers(root: Path) -> list[str]:
    """Directory names under root that count as hierarchy layers / ifaces.

    Always includes `cmn` (Xia: ub_cmn_mem_1r1w lives in pycircuit/cmn,
    rtl/cmn, formal/cmn) even if the directory is still empty.
    """
    names: set[str] = set()
    if root.is_dir():
        for path in sorted(root.iterdir()):
            if not path.is_dir():
                continue
            if path.name in LAYER_SKIP or path.name.startswith("."):
                continue
            names.add(path.name)
    if root.name in {"pycircuit", "rtl", "formal", "tb"}:
        names.update(ALWAYS_LAYERS)
    return sorted(names)


def is_hooks_path(path: Path) -> bool:
    return "hooks" in {p.lower() for p in path.parts}


def discover_rtl() -> dict[str, Any]:
    """Layer-based discovery. Never scans rtl/gen.

    PRODUCT = rtl/<layer>/*.{v,sv}
    HOOKS   = rtl/<layer>/hooks/*.{v,sv}
    <layer> is auto-enumerated (pcs, dll, common, cmn, tp, ta, mem, ...).
    Layers correspond 1:1 with pycircuit/<layer>/.
    Files sitting directly under rtl/ are D10 leftovers only.
    """
    sources: list[Path] = []
    incdirs: list[Path] = []
    used_filelists = False
    filelists: list[Path] = []
    rtl_root = REPO_ROOT / "rtl"
    pyc_root = REPO_ROOT / "pycircuit"
    layers = discover_layers(rtl_root)
    pyc_layers = discover_layers(pyc_root)
    seen: set[Path] = set()

    def _add(path: Path) -> None:
        if not path.is_file() or not _is_rtl_file(path) or _excluded(path):
            return
        if "gen" in {p.lower() for p in path.parts}:
            return
        rp = path.resolve()
        if rp in seen:
            return
        seen.add(rp)
        sources.append(rp)

    if rtl_root.is_dir():
        for path in sorted(rtl_root.iterdir()):
            if path.is_file():
                _add(path)  # D10 leftovers at rtl/*.v
        for layer in layers:
            if layer == "gen":
                continue
            layer_dir = rtl_root / layer
            if not layer_dir.is_dir():
                continue
            for path in sorted(layer_dir.iterdir()):
                if path.is_file():
                    _add(path)
            hooks = layer_dir / "hooks"
            if hooks.is_dir():
                for path in sorted(hooks.iterdir()):
                    if path.is_file():
                        _add(path)
            incdirs.append(layer_dir.resolve())
        incdirs.append(rtl_root.resolve())

    print(
        "RTL discovery: PRODUCT=rtl/<layer>/*.{v,sv} "
        "HOOKS=rtl/<layer>/hooks/*.{v,sv} "
        f"(no rtl/gen). rtl_layers={layers or []} "
        f"pycircuit_layers={pyc_layers or []}"
    )
    missing_rtl = [ly for ly in pyc_layers if ly not in layers]
    extra_rtl = [ly for ly in layers if ly not in pyc_layers and ly != "common"]
    if missing_rtl:
        print(f"NOTE: pycircuit layers with no rtl/<layer>/: {missing_rtl}")
    if extra_rtl:
        print(f"NOTE: rtl layers with no pycircuit/<layer>/: {extra_rtl}")

    sources = [p for p in sources if p.is_file()]
    modules: list[RtlUnit] = []
    inst_re = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]*)\s+#\s*\(|\b([A-Za-z_][A-Za-z0-9_]*)\s+[A-Za-z_][A-Za-z0-9_]*\s*\(")
    mod_re = re.compile(r"^\s*module\s+([A-Za-z_][A-Za-z0-9_]*)\b", re.MULTILINE)
    defined: dict[str, RtlUnit] = {}
    instantiations: dict[str, set[str]] = {}
    for path in sources:
        if path.suffix.lower() not in RTL_SOURCE_SUFFIXES:
            continue
        text = strip_verilog_comments(path.read_text(encoding="utf-8", errors="replace"))
        names = mod_re.findall(text)
        if not names:
            continue
        insts: set[str] = set()
        # Drop the module's own name from instantiation matches.
        for m in re.finditer(
            r"\b([A-Za-z_][A-Za-z0-9_]*)\s+(?:#\s*\([^;]*\)\s*)?([A-Za-z_][A-Za-z0-9_]*)\s*\(",
            text,
        ):
            cell, inst = m.group(1), m.group(2)
            if cell in {"module", "function", "task", "if", "for", "while", "case"}:
                continue
            if inst in {"begin", "end"}:
                continue
            insts.add(cell)
        for name in names:
            unit = RtlUnit(module=name, file=path, kind="leaf", sources=sources)
            defined[name] = unit
            instantiations[name] = insts - {name}

    kids: set[str] = set()
    for insts in instantiations.values():
        kids.update(insts)
    for name, unit in defined.items():
        unit.kind = "leaf" if name not in instantiations or not (instantiations[name] & set(defined)) else "top"
        # A module that instantiates another discovered module is a top (or mid).
        if instantiations.get(name, set()) & set(defined):
            unit.kind = "top"
        else:
            unit.kind = "leaf"
        modules.append(unit)

    # Unique include dirs
    uniq_inc: list[Path] = []
    for d in incdirs:
        if d not in uniq_inc and d.is_dir():
            uniq_inc.append(d)
    # Always add rtl/ and rtl/common when present
    for extra in (REPO_ROOT / "rtl", REPO_ROOT / "rtl" / "common"):
        if extra.is_dir() and extra.resolve() not in uniq_inc:
            uniq_inc.append(extra.resolve())

    return {
        "sources": sources,
        "incdirs": uniq_inc,
        "modules": modules,
        "used_filelists": used_filelists,
        "filelists": filelists,
        "instantiations": instantiations,
        "defined": defined,
        "layers": layers,
        "pycircuit_layers": pyc_layers,
    }


def discover_pycircuit_leaves() -> list[dict[str, str]]:
    """Leaves from pycircuit/<layer>/*.py (layer names not hard-coded)."""
    root = REPO_ROOT / "pycircuit"
    skip_py = {"__init__.py", "emit.py", "selfcheck.py"}
    leaves: list[dict[str, str]] = []
    for layer in discover_layers(root):
        for path in sorted((root / layer).glob("*.py")):
            if path.name in skip_py:
                continue
            leaves.append(
                {
                    "layer": layer,
                    "module": path.stem,
                    "source": rel(path),
                    "product": f"rtl/{layer}/{path.stem}.v",
                    "hooks": f"rtl/{layer}/hooks/{path.stem}.v",
                }
            )
    return leaves


def discover_leaf_pairs() -> list[dict[str, str]]:
    """Unique (layer, module) PRODUCT/HOOKS pairs. Layer names are discovered."""
    seen: set[str] = set()
    pairs: list[dict[str, str]] = []
    for leaf in discover_pycircuit_leaves() + discover_product_leaves():
        key = f"{leaf['layer']}/{leaf['module']}"
        if key in seen:
            continue
        seen.add(key)
        pairs.append(leaf)
    return pairs


PORT_CHUNK_RE = re.compile(
    r"\b(input|output|inout)\b((?:\s+(?:wire|reg|logic|signed))*"
    r"(?:\s+\[[^\]]+\])?\s*"
    r"[A-Za-z_][A-Za-z0-9_]*(?:\s*,\s*[A-Za-z_][A-Za-z0-9_]*)*)",
    re.I,
)
PORT_IDENT_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


def parse_ports(path: Path) -> list[tuple[str, str]]:
    """Return (direction, name) in declaration order."""
    text = strip_verilog_comments(path.read_text(encoding="utf-8", errors="replace"))
    skip = {"input", "output", "inout", "wire", "reg", "logic", "signed"}
    ports: list[tuple[str, str]] = []
    for kind, blob in PORT_CHUNK_RE.findall(text):
        for name in PORT_IDENT_RE.findall(blob):
            if name.lower() in skip:
                continue
            ports.append((kind.lower(), name))
    return ports


def collect_blackbox_findings(check: str = "lint") -> list[Finding]:
    """Unlisted stub/macro is blocking. Timing vs MODULE_INVENTORY is report-only."""
    findings: list[Finding] = validate_blackbox_schema()
    for f in findings:
        f.check = check
    inventory = load_module_inventory()
    inv_path = find_module_inventory()
    storage_rows: list[dict[str, Any]] = []
    if inventory:
        raw = inventory.get("storage") or inventory.get("memories") or []
        if isinstance(raw, list):
            storage_rows = [r for r in raw if isinstance(r, dict)]
    if inv_path is None:
        print(
            "NOTE: MODULE_INVENTORY not found "
            "(docs/arch/MODULE_INVENTORY.yml); blackbox timing auto-check skipped"
        )
    listed = load_blackboxes()
    print(
        f"blackbox registry: {len(listed)} approved stub|macro entries "
        f"(ub_cmn_mem_1r1w is a normal cmn leaf, not listed here)"
    )
    for path in iter_rtl_sources():
        if is_handwritten_path(path):
            continue
        # Generated cmn storage leaf is a normal PRODUCT, not a stub.
        if path.stem == "ub_cmn_mem_1r1w" and "cmn" in path.parts:
            continue
        detected = looks_like_stub_or_blackbox(path)
        listed_here = is_stub_listed(path)
        if detected and not listed_here:
            findings.append(
                Finding(
                    check=check,
                    module=path.stem,
                    file=rel(path),
                    rule="STUB_UNLISTED",
                    message=(
                        "stub/blackbox under rtl/ is not on "
                        "scripts/gate/blackbox.yml "
                        "(or the entry has no gatekeeper approver)"
                    ),
                )
            )
            continue
        if not listed_here:
            continue
        entry = next(
            (
                e
                for e in listed
                if str(e.get("file") or "").replace("\\", "/") == rel(path)
                or fnmatch.fnmatch(rel(path), str(e.get("file") or ""))
                or str(e.get("module") or "") == path.stem
            ),
            {},
        )
        if not storage_rows:
            continue
        match = None
        for row in storage_rows:
            rid = str(row.get("id") or row.get("replaces") or row.get("macro") or "")
            rmod = str(row.get("module") or "")
            if rid and rid == str(entry.get("replaces") or entry.get("macro") or entry.get("id") or ""):
                match = row
                break
            if rmod and rmod in {path.stem, entry.get("module")}:
                match = row
                break
        if match is None:
            findings.append(
                Finding(
                    check=check,
                    module=path.stem,
                    file=rel(path),
                    rule="STUB_TIMING_NO_INVENTORY_ROW",
                    message=(
                        "registered stub/macro has no MODULE_INVENTORY storage row "
                        "to check read latency / 1RW/1R1W / conflict"
                    ),
                    bucket="report",
                )
            )
            continue
        want = {
            "read_latency": match.get("read_latency", match.get("read_lat")),
            "ports": match.get("ports") or match.get("port_kind"),
            "conflict": match.get("conflict")
            or match.get("rw_conflict")
            or match.get("same_addr"),
        }
        got = {
            "read_latency": entry.get("read_latency", entry.get("read_lat")),
            "ports": entry.get("ports") or entry.get("port_kind"),
            "conflict": entry.get("rw_conflict") or entry.get("conflict"),
        }
        mismatches = [
            f"{k}: inventory={want[k]!r} list={got[k]!r}"
            for k in want
            if want[k] is not None and got[k] is not None and str(want[k]) != str(got[k])
        ]
        missing = [k for k in want if want[k] is not None and got[k] is None]
        if mismatches or missing:
            findings.append(
                Finding(
                    check=check,
                    module=path.stem,
                    file=rel(path),
                    rule="STUB_TIMING",
                    message=(
                        "blackbox timing vs MODULE_INVENTORY (report-only): "
                        + "; ".join(mismatches + [f"{k} missing on list" for k in missing])
                    ),
                    bucket="report",
                )
            )
    return findings


def collect_stub_findings(check: str = "lint") -> list[Finding]:
    return collect_blackbox_findings(check)


def discover_product_leaves() -> list[dict[str, str]]:
    """PRODUCT files at rtl/<layer>/<module>.v (not hooks/, not whitelist cells)."""
    rtl_root = REPO_ROOT / "rtl"
    leaves: list[dict[str, str]] = []
    for layer in discover_layers(rtl_root):
        layer_dir = rtl_root / layer
        for path in sorted(layer_dir.iterdir()):
            if not path.is_file() or path.suffix.lower() not in RTL_SOURCE_SUFFIXES:
                continue
            if is_handwritten_path(path) or path.stem in handwritten_modules():
                continue
            leaves.append(
                {
                    "layer": layer,
                    "module": path.stem,
                    "product": rel(path),
                    "hooks": f"rtl/{layer}/hooks/{path.stem}.v",
                }
            )
    return leaves


def module_closure(module: str, disc: dict) -> list[Path]:
    """Files needed to lint/synth `module` (itself + discovered children)."""
    defined: dict[str, RtlUnit] = disc.get("defined") or {}
    inst_map: dict[str, set[str]] = disc.get("instantiations") or {}
    seen: set[str] = set()
    stack = [module]
    files: list[Path] = []
    while stack:
        name = stack.pop()
        if name in seen:
            continue
        seen.add(name)
        unit = defined.get(name)
        if unit is None:
            continue
        files.append(unit.file)
        for child in inst_map.get(name, set()):
            if child in defined:
                stack.append(child)
    return files


def strip_verilog_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    out: list[str] = []
    for line in text.splitlines():
        if "//" in line:
            line = line.split("//", 1)[0]
        out.append(line)
    return "\n".join(out)


def verilator_inc_args(incdirs: list[Path]) -> list[str]:
    # Verilator treats a bare "-I" plus a following path as another source file.
    return [f"-I{d}" for d in incdirs]


def yosys_inc_prefix(incdirs: list[Path]) -> str:
    return " ".join(f"-I{d}" for d in incdirs)
